### ISSUE TITLE
¿Dónde se ecuentra el cuestionario de recolección de cuentas?

### ISSUE THREAD

**Issue by bmurtagh01** [Exploratorio-DCC-PUC/Syllabus#1]
Hola, quería saber donde puedo encontrar el link del cuestionario Google donde uno envía su usuario de GitHub.
Muchas gracias

**Comment by IchottMano** [comment]
@bmurtagh01 Hola!
El cuestionario es a través del Siding, en la seccion de cuestionarios.
Saludos!

**Comment by perezpefaur** [comment]
Hola! No sabia que habia que llenar el formulario y ahora me sale que estoy fuera de plazo )=
