### ISSUE TITLE
Clase Anterior?

### ISSUE THREAD

**Issue by naquiroz** [Exploratorio-DCC-PUC/Syllabus#1]
Hola, me gustaría saber si se va  a subir el material de la clase anterior? 
Y lo otro, donde puedo encontrar las fechas de las evaluaciones?

**Comment by aaossa** [comment]
Hola! Agregué la tercera clase. Si falta otro material comenta de nuevo y lo agregamos 😁 Las fechas de las evaluaciones aparecen en dicha presentación
