### ISSUE TITLE
piso 4

### ISSUE THREAD

**Issue by totichi** [Exploratorio-DCC-PUC/Syllabus#10]
tenia una pequeña duda...
cuando dice que se debe hacer toda la acción de encontrar las cosas con "xx" en un solo comando, se refiere a eso solamente o tambien a crear un archivo txt y modificarlo desde la terminal?

**Comment by aaossa** [comment]
Se refiere a que debes encontrar las lineas y guardar solo esas en el archivo, en un solo comando
