### ISSUE TITLE
Perfil codecademy

### ISSUE THREAD

**Issue by sebastianferrer** [Exploratorio-DCC-PUC/Syllabus#10]
Para poner el link del perfil codecademy se debe realizar el cambio desde el computador(local) y subirlo a github o se puede cambiar directamente en el archivo README.md que aparece en el repositorio?

**Comment by diflores** [comment]
Hola:
Ambas son alternativas correctas. Si lo haces vía web, recuerda hacer `git pull` antes de hacer más cambios en tu local, para evitar _merge conflicts_.

¡Saludos!

EDIT: ¡Ojo! Cuando haces _push_ vía web, el mensaje por defecto del _commit_ es "add files via upload". Para el equipo docente ese no es un mensaje descriptivo, por lo que te recomiendo cambiarlo para no tener descuento en la nota de la tarea.

**Comment by TiareM** [comment]
Hola, cómo puedo cambiar el mensaje descriptivo de un commit ya enviado?
