### ISSUE TITLE
Guardar el BPMN

### ISSUE THREAD

**Issue by ncasassus** [Exploratorio-DCC-PUC/Syllabus#100]
Alguien que esté haciendo la tarea en el link https://demo.bpmn.io/s/start, ¿Cómo están guardando su tarea? Yo no lo he logrado hacer. Traté con screenshot pero la resolución no da para leer las acciones. Cualquier sugerencia se agradece.

**Comment by gatochico** [comment]
Para guardar como BPMN hay un boton directo, y para guardar como pdf utiliza el botón para descargar como SVG y después busca en internet un conversor de SVG a PDF... Eso es lo que me funciono a mi, por lo menos!

**Comment by ncasassus** [comment]
Buenísima, gracias! Intentaré de hacer eso
