### ISSUE TITLE
TC3 

### ISSUE THREAD

**Issue by Crespy98** [Exploratorio-DCC-PUC/Syllabus#100]
se suponía que ayer en la noche se iba a subir la tarea chica, como aun no la suben el plazo de entrega también se va a correr?

**Comment by estefaniiaaa** [comment]
Y la ayudantía que está programada para la próxima semana también se correría si suben la tarea ???

**Comment by Mdelaf** [comment]
La TC3 se subió ayer, y por lo tanto el plazo de entrega es hasta el próximo martes 22 de octubre a las 23:59. La ayudantía del día de hoy será para esta ayudarlos con esta tarea. La próxima semana no hay ayudantía.

Saludos.
