### ISSUE TITLE
Lenguaje de https://turingmachinesimulator.com/

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#101]
Hola vi en el primer ejemplo de la página (binary numbers divisable by 3), que ocupa el commando mod. Al buscar en internet pude averiguar lo que significaba, pero me entro la duda, que al igual que el comando mod deben haber otros comandos más para este lenguaje que no salen especificados en el tutorial.pdf ni en programing_languaje.pdf y busque en internet y tampoco encontré ninguna documentación del programa. En el caso que no exista documentación, hay algun lugar donde podriamos aprender mas sobre como escribir en la pagina? como se podria escribir la parte entera de un numero?

**Comment by Pyralspite** [comment]
Hola!
Las Máquinas de Turing no utilizan comandos como mod, únicamente estados y símbolos. Si te fijas, la línea `// q0 - mod3 == 0  ` comienza con //. Esto significa que es un comentario, por lo que la máquina lo ignora. 
Esa parte del código explica que la máquina pasará al estado q0 si al hacer mod3 al input hasta ese punto, el resto de la división es 0 (osea que hasta ese punto es divisible por 3). Sin embargo, estas anotaciones son para que nosotros entendamos los cambios de estado, no para la máquina. El código que la máquina interpretará empieza en la línea 16, y la función de transición que implementa la lógica definida en los comentarios, en la línea 20.
Hoy en la ayudantía repasaremos como funcionan las Máquinas de Turing y la sintaxis del simulador. Te recomiendo asistir c:
Saludos!
