### ISSUE TITLE
TC4 Notificacion aprovacion o rechazo

### ISSUE THREAD

**Issue by danustilovsky** [Exploratorio-DCC-PUC/Syllabus#101]
Hola, cuando se termina la etapa de analisis de riesgo e impacto, suponiendo que se aprueba o rechaza el RFC se debe enviar una notificacion, mi duda es a quien se le debe hacer llegar la notificacion?

gracias

**Comment by Dalal15** [comment]
Se debe notificar al solicitante, que es quien creó el RFC.
