### ISSUE TITLE
Informe

### ISSUE THREAD

**Issue by clementesepulveda** [Exploratorio-DCC-PUC/Syllabus#103]
Hola, como que no entiendo cual es la diferencia entre la 1 y la 3 de la parte del informe de la tc3, porque si explico mi codigo lo voy hacer con los estados de la maquina. Y para la definicion formal, ya aparecen en el enunciado, entonces seria solo poner eso en informe?
muchas gracias

**Comment by Pyralspite** [comment]
Hola!

La diferencia entre la pregunta 1 y 3 es que la primera está más orientada en explicar como fue implementada tu máquina (pasos que sigue, decisiones que tomaste, casos borde que consideraste, etc). En esta descripción obviamente puede que menciones algunos de los estados de tu máquina, sin embargo no es necesario que te explayes en ellos, solo que los utilices como respaldos para entender el funcionamiento.
En cambio, en la pregunta 3 si queremos que se enfoquen en **todos** los estados que componen su máquina y como interactúan entre ellos, poniendo especial atención en explicar los tres puntos que les pedimos.
Para la definición formal, deben completar con la información de su máquina, de forma similar a como se hace en el ejemplo de la página 3.

Saludos!
