### ISSUE TITLE
Etapa autorización

### ISSUE THREAD

**Issue by cotefon** [Exploratorio-DCC-PUC/Syllabus#104]
Hola! en la parte de la autorización existe el RFC, ¿cual es la diferencia en que sea normal y estándar?

**Comment by Dalal15** [comment]
Hola,
 
Si es normal, se tiene que ver su nivel de impacto y según eso se autorizan los cambios. En el caso de que sea estándar, no hay actividades de autorización y se autoriza el cambio automáticamente, finalizando el proceso.
