### ISSUE TITLE
Parte 2 del informe

### ISSUE THREAD

**Issue by sebaelsaca** [Exploratorio-DCC-PUC/Syllabus#105]
En la parte 2 del informe a que se refieren con definición formal? Y definición de esos elementos en general o de la máquina creada.

**Comment by Pyralspite** [comment]
Hola, la definición formal que les pedimos es similar a la del ejemplo, pero en este caso para la máquina que ustedes crearon. 
Por ejemplo, para Q deben incluir todos los estados de su máquina, usando notación de conjuntos.

**Comment by TriniVial** [comment]
Hay que poner todas las funciones de traslación que tiene nuestra maquina??

**Comment by Pyralspite** [comment]
Hola, no es necesario poner la función de transición en la definición formal, solo las cosas que les pedimos c:

**Comment by gachondoj** [comment]
Hola
Como seria una definicion formal para q0?

**Comment by absoto4** [comment]
Hola! tengo la misma duda, cómo sería una definición formal de q0? no sale en el ejemplo 😞

**Comment by Pyralspite** [comment]
Hola, bastaría con algo del tipo

q0 = _suEstadoInicial_
