### ISSUE TITLE
No está presentación prog. lógica para control

### ISSUE THREAD

**Issue by Fenho** [Exploratorio-DCC-PUC/Syllabus#107]
En el siding y en syllabus esta la presentación de HCI (Alessio Bellino) en vez de la de programación lógica. El pdf tiene el nombre de programación lógica pero en realidad es el de HCI.

**Comment by aaossa** [comment]
Toda la razón, conseguiremos la clase 🙌

**Comment by aaossa** [comment]
Arreglado 👌
