### ISSUE TITLE
Nota T4

### ISSUE THREAD

**Issue by clementesepulveda** [Exploratorio-DCC-PUC/Syllabus#108]
Tengo una duda sobre la nota de la tarea 4. Si es que no la alcanzo a terminar o me baja el promedio, igual se toma en cuenta?

**Comment by diflores** [comment]
Hola:

Si la nota que obtengas en la TC4 no te sirve para aumentar o mantener el promedio, rellenaremos ese espacio con la mejor nota de tus tareas chicas entre TC1, TC2 y TC3.
