### ISSUE TITLE
PDF en TC4

### ISSUE THREAD

**Issue by StroveLight** [Exploratorio-DCC-PUC/Syllabus#109]
Hola!

¿Se debe usar PDF para la entrega si las dos cosas pedidas son codigos de prolog y no se pide explicacion explicitamente?

![image](https://user-images.githubusercontent.com/48263952/69484752-c7f44d00-0e15-11ea-9e3e-d576f80ab3c2.png)

**Comment by diflores** [comment]
¡Hola!

Se nos pasó eso de una versión anterior del enunciado. Basta con archivos .pl

¡Saludos!

**Comment by StroveLight** [comment]
Gracias~ (*‘ω‘ *)
