### ISSUE TITLE
edicion de texto

### ISSUE THREAD

**Issue by tcamposc** [Exploratorio-DCC-PUC/Syllabus#11]
despues de editar los textos por comandos, el programa los lee por distintas lineas pero al abrirlo como texto, me aparece todo en una sola linea.

**Comment by ValentinaAlvarezG** [comment]
Lo estás abriendo con editor de texto? o a través de consola?

**Comment by tcamposc** [comment]
Al abrirlo por consola se ve bien, pero al abrirlo por texto me aparece todo en una linea

**Comment by ValentinaAlvarezG** [comment]
Entones está bien
