### ISSUE TITLE
Piso4

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [Exploratorio-DCC-PUC/Syllabus#11]
Hola! no entiendo que es lo que hay que hacer en un solo comando. Desde lo de crear la carpeta con mi usuario hasta el final? o solo la parte de filtrar?

Saludos! :(

**Comment by aaossa** [comment]
Solo filtrar y generar el archivo

**Comment by ValentinaAlvarezG** [comment]
Gracias!!!
