### ISSUE TITLE
Control

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#110]
Hola, se puede subir un word con las respuestas al control o tiene que estar hecho a mano?

**Comment by NevadaStreets** [comment]
Se debe subir un archivo .pdf 

Puede ser resuelto a mano o en word, como prefieran. Siempre y cuando el archivo que suban sea uno en formato .pdf y sus respuestas sean inteligibles.

Saludos!

**Comment by perezpefaur** [comment]
Gracias!
