### ISSUE TITLE
Git para Mac

### ISSUE THREAD

**Issue by Natydlb** [Exploratorio-DCC-PUC/Syllabus#113]
![WhatsApp Image 2020-03-18 at 18 25 43](https://user-images.githubusercontent.com/62019255/77009028-00c8ac80-6946-11ea-8d2d-28a877cdb30c.jpeg)
Hola, en el video sale que Mac tiene Git, pero no lo encontré por lo que descargue git pero al momento de ejecutarlo sale ese mensaje

**Comment by denisparra** [comment]
Podrias revisar lo que sale acá: https://support.apple.com/es-us/HT202491

**Comment by denisparra** [comment]
@Natydlb Te sirvió la respuesta para poder instalar git ?

**Comment by Natydlb** [comment]
Hola sii! @denisparra Gracias !
