### ISSUE TITLE
Duda del enunciado de primer paso

### ISSUE THREAD

**Issue by fbesoainp** [Exploratorio-DCC-PUC/Syllabus#114]
En el enunciado del primer paso dice "Esto se debe lograr mostrando todos los archivos al mismo tiempo y sin colocarlos manualmente." quiere decir que todo tiene que ser logrado con una solo linea de comando y no puedo ingresar manualmente los nombres de los archivos de texto?

otra duda: se puede hacer cat de una lista de paths de archivos o se puede lograr algo parecido con algun otro comando?

**Comment by ValentinaAlvarezG** [comment]
Hola!

Sobre lo primero: Sí, es un comando en particular el que necesitas para lograr mostrarlo todo.
Sobre lo segundo: no entiendo muy bien a que te refieres con lista de paths o que es lo que quieres hacer.

**Comment by fbesoainp** [comment]
ok muchas gracias!
