### ISSUE TITLE
Duda primer paso

### ISSUE THREAD

**Issue by josecaceresb** [Exploratorio-DCC-PUC/Syllabus#115]
Hola, no entendí como mover todos los archivos "tareaChica".bla sin tener que moverlo uno por uno al archivo creado.

**Comment by ValentinaAlvarezG** [comment]
Hola! Eso es parte de la tarea, la gracia es que se te tiene que ocurrir como. El amigo google puede ayudarte un poco si no se te ocurre como moverlos. Además ten en consideración el hint de ese paso (estos archivos se encuentran en las carpetas más profundas 👀 )

**Comment by josecaceresb** [comment]
Ya gracias !
