### ISSUE TITLE
Problema al ejecutar comandos

### ISSUE THREAD

**Issue by Natydlb** [Exploratorio-DCC-PUC/Syllabus#116]
![WhatsApp Image 2020-03-18 at 22 03 59](https://user-images.githubusercontent.com/62019255/77021066-83f8fb00-6964-11ea-9ba1-a4b37b5d5f28.jpeg)
Abrí la carpeta y todo pero no me deja ejecutar los comandos para configurarlo con el repositorio privado ayuda :(((

**Comment by ValentinaAlvarezG** [comment]
Hola!
Antes de ejecutar el .pyc puedes hacer ls (listar los archivos de la carpeta) y mostrarme lo que te aparece porfis

**Comment by Natydlb** [comment]
![WhatsApp Image 2020-03-18 at 22 23 20](https://user-images.githubusercontent.com/62019255/77022009-303be100-6967-11ea-9433-1284c2f84e50.jpeg)

**Comment by ValentinaAlvarezG** [comment]
Ah ya, lo que pasa es que no estas corriendo el .pyc en el lugar correcto. Si usas ls, y listas los archivos y carpetas que tienes donde estás parado, no tienes el archivo .pyc ahí y por eso no lo encuentra. 
Tienes que moverte hacia la carpeta donde tengas guardado el .pyc para ejecutar el comando de python.
Avísame si pudiste solucionarlo :)

**Comment by Natydlb** [comment]
Creo que no tengo en ninguna carpeta guardado el .pyc o el .pyc es el programa de phyton? y tengo que buscar la carpeta de phyton? no entiendo :(

**Comment by ValentinaAlvarezG** [comment]
Mmmmm, a ver, por lo que veo, ya creaste tu repo. Necesito saber si instalaste git en tu computador.

**Comment by Natydlb** [comment]
si y no, porque me meti a la terminal puse git y me salía quiere ejecutar git y puse aceptar, pero así como descargarlo e instalarlo yo no

**Comment by ValentinaAlvarezG** [comment]
Puedes desde la consola ejecutar el siguiente comando:
`which git`

**Comment by Natydlb** [comment]
![WhatsApp Image 2020-03-18 at 23 03 21](https://user-images.githubusercontent.com/62019255/77024219-ba3a7880-696c-11ea-8253-c3d601dfb0c0.jpeg)

**Comment by ValentinaAlvarezG** [comment]
Ya entonces tienes git. Lo que tienes que hacer es:

- En tu repo, hay un boton verde que dice Clone or Download, le haces click y te va a aparecer lo que sale en la foto: 

![image](https://user-images.githubusercontent.com/26123660/77024524-8d3a9580-696d-11ea-9d51-1641528599bb.png)

- Copias ese link que aparece en esa cajita, que en tu caso https://github.com/Exploratorio-DCC-PUC/tc1-2020-1-Natydlb.git

- Abre una terminal donde quieras que esté tu repo, por ejemplo en el escritorio, documentos, no sé, donde quieras. En la terminal escribes git clone y pegas el link, es decir, debería verse así:
`git clone https://github.com/Exploratorio-DCC-PUC/tc1-2020-1-Natydlb.git `
Apretas enter, y debería empezar a clonarse el repo,, te va decir algo así como Cloning into... y cuando termine, en la carpeta donde corriste este comando va a estar tu repo donde adentro va a estar el .pyc y ahí si te ubicas en la carpeta donde esté el pyc y corres el comando con python.

Avísame si te resulta o si tienes dudas
