### ISSUE TITLE
Tercer paso TC1

### ISSUE THREAD

**Issue by sopadeoliva** [Exploratorio-DCC-PUC/Syllabus#117]
Para el tercer paso, obtuve el número de archivos de la carpeta TareaChica1 (número de 5 dígitos). Entre al directorio que indica las instrucciones, usando los últimos tres dígitos del número, pero aquí no llego a nada ("sabrás cual es el archivo a mostrar").

Probé con distintas formas de contar archivos, que me tiraban números iguales o similares (dependiendo de lo que voy a preguntar abajo), pero ninguno me llevó a nada, solo a más SubSub...Carpetas y archivos random.

¿Las carpetas cuentan como archivos? ¿O solo debemos contar los archivos de texto?
Igualmente, probé de las dos formas, obtuve números, pero no llegué a nada. ¿Cómo voy a saber que tengo el número correcto?

**Comment by ValentinaAlvarezG** [comment]
Hola! Debes contar **sólo los archivos**. Si es que hiciste bien todos los pasos anteriores, te mueves a la carpeta indicada por el número y listas lo que hay en esa carpeta, te prometo que vas a saber cuál archivo de esos tienes que mostrar. Si sientes que de verdad no sabes qué archivo es, mándame un correo a vjalvarez@uc.cl con el pantallazo del ls de la carpeta que te da que tienes que mostrar según los dígitos y puedo guiarte mejor.

**Comment by sopadeoliva** [comment]
Gracias!

Acabo de conseguirlo, pero ya caché porqué no me funcionaba. De ahí otra duda (pa que le sirva al resto también):
En el Segundo paso, cuando pide crear la carpeta "NombreApellido" sale "en el directorio padre de esta tarea", varios de nosotrxs entendimos que era el repo clonado (la carpeta tc1-2020...) y no la carpeta TareaChica1.
¿No es así, supongo? 😅 

(Si cuento los archivos dentro de NombreApellido sí me calza, así que asumo q ese era el problema jajaj)

**Comment by ValentinaAlvarezG** [comment]
Aaaaah no, **la carpeta padre de esta tarea es TareaChica1**
