### ISSUE TITLE
Abrir PrimerPaso.md en Mac

### ISSUE THREAD

**Issue by nicolascamhi** [Exploratorio-DCC-PUC/Syllabus#118]
No me deja abrir el archivo PrimerPaso.md. Me sale el siguiente mensaje: 

<img width="1440" alt="Screen Shot 2020-03-19 at 00 28 42" src="https://user-images.githubusercontent.com/62315390/77028823-b7de1b80-6978-11ea-8939-5e5fa5976fef.png">

**Comment by ValentinaAlvarezG** [comment]
Hola!

Puedes usar:
`cat PrimerosPasos.md`
en la consola

**Comment by nicolascamhi** [comment]
No me deja!
<img width="1440" alt="Screen Shot 2020-03-19 at 13 30 14" src="https://user-images.githubusercontent.com/62315390/77090367-cc0c3200-69e5-11ea-9b5f-5d47b94d9c51.png">
