### ISSUE TITLE
Duda de entrega de PDF

### ISSUE THREAD

**Issue by fbesoainp** [Exploratorio-DCC-PUC/Syllabus#119]
El pdf tiene que estar en la carpeta TareaChica1?
o se entrega de otro modo?
tiene que tener algun nombre en especifico?

**Comment by gatochico** [comment]
Hola! El PDF debe estar dentro de tu repositorio privado, al mismo nivel de la carpeta TareaChica1 (donde inicialmente estaba el archivo README.mc y el .pyc). No tiene que tener un nombre específico, mientras sea apropiado para una entrega formal (:

**Comment by fbesoainp** [comment]
ok gracias
