### ISSUE TITLE
Aprobación de un curso

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#12]
Para aprobar un curso hay que agregar la sigla del curso al info.txt del jugador. Para eso habría que abrir por ejemplo el c01.txt y leer su texto dentro para saber la sigla. Ahora bien si ese curso fue asignado a un persona como ayudantia, c01.txt no se encontraria dentro de la carpeta cursos sino en la carpeta personal de un jugador. Como podriamos encontrar c01.txt en ese caso? Esta bien lo que explico? hay que asumir algo mas?

**Comment by perezpefaur** [comment]
Se que se puede ocupar el comando find, pero mi duda es que si es que la idea de la pregunta 5 es la que describi arriba o esta mal

**Comment by ValentinaAlvarezG** [comment]
Hola!

Para aprobar un curso se supone que debes haber caído en esa casilla primero y en el tablero se pueden ver las siglas de los cursos.

Para los comandos que debes poner en el informe, no es necesario que pongas algún curso en específico, basta con que lo dejes expresado con la variable correspondiente al curso.
