### ISSUE TITLE
Problema con Comandos

### ISSUE THREAD

**Issue by Mamunoz42** [Exploratorio-DCC-PUC/Syllabus#120]
Hola! 
Saben que tengo una duda en la parte dos de las instrucciones del pdf que nos entregaron, en donde sale que hay que ingresar unos comandos, yo estoy en windows y no entiendo bien como hacer esta parte. 
Lo otro es que yo tengo instalada la versión de python 3.7.7, esta sirve verdad?

**Comment by gatochico** [comment]
Hola! 

Primero, 3.7.7 debería servirte para ejecutar el archivo así que no hay problema con eso. Con respecto a los comandos del enunciado, debes hacer lo siguiente:

1) Abrir git bash y clonar tu repositorio personal en tu computadora. 
![image](https://user-images.githubusercontent.com/37161120/77069996-36ae7500-69c8-11ea-9e40-8920ea1ea3ad.png)

2) Ubicarte dentro de la carpeta de tu repositorio personal.
![image](https://user-images.githubusercontent.com/37161120/77070092-5e054200-69c8-11ea-8140-2b42feb2674a.png)

3) Ejecutar los comandos indicados para windows en el enunciado. Debería aparecer lo siguiente:
![image](https://user-images.githubusercontent.com/37161120/77070469-087d6500-69c9-11ea-8cfb-ceea642a4a2b.png)

Una vez que termine de ejecutar el último comando, debería aparecer una carpeta llamada TareaChica1 dentro de la carpeta de tu repositorio personal, donde están las instrucciones para la tarea.

Espero haberte ayudado!

**Comment by Mamunoz42** [comment]
Muchisimas gracias :)
