### ISSUE TITLE
error: cannot start 'python.exe': Not found in PATH

### ISSUE THREAD

**Issue by tomasdempster** [Exploratorio-DCC-PUC/Syllabus#121]
hola!! Al poner en la terminal "python TChica1.pyc" no me genera la carpeta y me sale error: cannot start 'python.exe': Not found in PATH. (tengo python descargado)

**Comment by gatochico** [comment]
Hola! ¿Estás usando windows? Esto probablemente se deba a que python no fue agregado al PATH. Podrias intentar [seguir este tutorial para agregar python al PATH de windows](https://geek-university.com/python/add-python-to-the-windows-path/) . 

La otra alternativa, si se te hace más facil, es que 1) Desinstales python de tu computadora y 2) Lo instales nuevamente (recuerda que debe ser una version 3.7) y **asegurarte de clickear la siguiente casilla durante la instalación**:

![image](https://user-images.githubusercontent.com/37161120/77090515-05dd3880-69e6-11ea-84bc-ef45fdf0841f.png)
Avísanos cómo te va! Si sigues con problemas, trata de adjuntar algun pantallazo del error que te salga.

**Comment by tomasdempster** [comment]
Ahi me funciono, muchas gracias! solo que ahora no se me creo la carpeta 

![foto 1 ](https://user-images.githubusercontent.com/62022227/77111700-8d3aa400-6a06-11ea-8fd0-5f061a7decaf.png)

**Comment by railira** [comment]
Hola! creo tener un problema parecido, al poner "alias python=’winpty python.exe’" me dice "bash: alias: python.exe’: not found". El tema es que ya probé agregando python al path y sigue tirando lo mismo
