### ISSUE TITLE
Error al ejecutar alias python=’winpty python.exe’

### ISSUE THREAD

**Issue by Benjamin-Pedraza** [Exploratorio-DCC-PUC/Syllabus#122]
Hola, 
Cuando ejecuto en git bash "alias python=’winpty python.exe’" me aparece esto. ¯\_(ツ)_/¯

![2020-03-19 (3)](https://user-images.githubusercontent.com/62078034/77105168-f7018080-69fb-11ea-901e-be21547faf3b.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! Puede ser pq copiaste el comando del pdf y las  comillas no son las mismas parece. Trata escribiéndolas directamente tu con las comillas simples. Avísame si te resulta

**Comment by Benjamin-Pedraza** [comment]
Funcionó :) gracias

**Comment by DiegoPollack** [comment]
Hola! tengo un problema similar, sin embargo cuando cambio las comillas, en vez de aparecer un error, no ocurre nada. Cuál podría ser el problema 
![0](https://user-images.githubusercontent.com/62223393/77109490-c2dd8e00-6a02-11ea-89cc-289dd08d547a.png)

**Comment by gatochico** [comment]
Hola, ¿Qué ocurre si ejecutas solo `python` en la consola de bash tras ejecutar el alias?
Otra alternativa es ejecutar `python TChica.pyc 2` en la carpeta de tu repositorio a traves de la **cmd de windows**(Tecla win + R, escribir cmd en el cuadro de texto, y presionar aceptar) (en este caso no es necesario correr `alias python="winpty python.exe"` antes).

**Comment by DiegoPollack** [comment]
Hola, cuando ejecuto sólo `Python` en la consola (después de haber ejecutado el alias), esta abre la tienda de Microsoft donde me dá la opción para descargar Python 3.8 (yo tengo descargada la versión 3.7.2). Por otro lado, al ejecutar el comando desde la cmd aparece el mensaje "Bad magic number in .pyc file".  Qué puedo hacer al respecto?
![1](https://user-images.githubusercontent.com/62223393/77113809-36cf6480-6a0a-11ea-960a-0e1ec713d808.png)

**Comment by gatochico** [comment]
Ese error aparece cuando corres el programa con otra versión de python no 3.7
Corre en la cmd `python --version` y dime que versión te da.

**Comment by DiegoPollack** [comment]
La versión que aparece ahora es 3.8.2 
![2](https://user-images.githubusercontent.com/62223393/77115011-4c458e00-6a0c-11ea-8f88-ca6bf446f1f4.png)

**Comment by gatochico** [comment]
Es debido a eso, desinstala python de tu computadora completamente y asegura descargar alguna de las versiones 3.7. Con eso podrás ejecutar el programa.

**Comment by DiegoPollack** [comment]
Una vez que desinstalé Python y lo instalé de nuevo fucnionó. Muchas gracias por la ayda!

**Comment by Francisco-Morales-R** [comment]
Holaa, yo tengo el mismo, problema pero cuando usar el segundo comando después de haber hecho lo del cmd, me sale un error, que dice que no se encuentra una cosa y que se solucionaría reinstalando el programa. Ese mismo error me sale en pantalla al intentar ver que versión de python tengo.
Supongo que tengo que descargar python de nuevo, pero antes tengo que borrar solo la aplicacion, o algo mas? o nada?

**Comment by maarcee** [comment]
hola :D tengo un problema parecido pero cuando ejecuto alias python=’winpty python.exe’ me sale un error gigante. La versión de python que tengo es la 3.7.4 y cuando la instalé le puse el "agregar al PATH". ¿Qué puedo hacer? :(
![Captura powershell](https://user-images.githubusercontent.com/62041665/77375398-1ece4c80-6d4c-11ea-89c4-bf6074dca61d.PNG)

**Comment by gatochico** [comment]
@maarcee Debes ejecutar los comandos del enunciado desde la consola de git bash, no la powershell de windows, el cual no posee el comando alias.

**Comment by maarcee** [comment]
ohhhhh de verdad no me había dado cuenta!! muchas gracias!!! :D eres un sol <3
