### ISSUE TITLE
no se me crea la carpeta TChica1

### ISSUE THREAD

**Issue by angelescox** [Exploratorio-DCC-PUC/Syllabus#123]
luego de poner los comandos sugeridos en git bash, no me sale error en ninguno de los dos, pero no me crea ni sale nada. Que podria ser?
![image](https://user-images.githubusercontent.com/62268739/77113058-e1468800-6a08-11ea-9f10-809f4cdd1b7a.png)

**Comment by gatochico** [comment]
Hola, ¿Qué ocurre si ejecutas solo python en la consola de bash tras ejecutar el alias?

Otra alternativa es abrir con el navegador la carpeta de la tchica, escribe cmd donde muestra la imagen, y aprieta enter:
![image](https://user-images.githubusercontent.com/37161120/77114144-c70da980-6a0a-11ea-882d-04d195236b34.png)
 Y te aparecerá la cmd de Windows. Ahí ejecuta `python TChica1.py 9` y debería correr (en este caso no es necesario correr `alias python="winpty python.exe"` antes).

Avísanos como te va!

**Comment by angelescox** [comment]
Así? No me corrió

**Comment by jorgemouat** [comment]
Yo también tengo el mismo problema y no pude solucionarlo con las recomendaciones

**Comment by gatochico** [comment]
Hola! A todos quienes tienen el problema, ¿Qué version de python están utilizando? pueden verlo corriendo en la cmd de windows `python --version` o en git bash corriendo primero la línea del alias del enunciado y luego `python --version`.

**Comment by jorgemouat** [comment]
A mi se me soluciono abriendo git bash como administrador. Quizas a alguien mas le sirva. Gracias.

**Comment by railira** [comment]
Hola! creo tener un problema parecido, al poner "alias python=’winpty python.exe’" me dice "bash: alias: python.exe’: not found". El tema es que ya probé agregando python al path y sigue tirando lo mismo
![Captura223](https://user-images.githubusercontent.com/62022050/77174667-31245e00-6aa0-11ea-8028-e40f994b46c5.PNG)

**Comment by gatochico** [comment]
@railira Es por las comillas del comando. Reemplazalas con comillas simples (')

**Comment by railira** [comment]
graciaas!
