### ISSUE TITLE
Primer paso.md

### ISSUE THREAD

**Issue by nnovoag** [Exploratorio-DCC-PUC/Syllabus#124]
hola no me deja abrir el primerpaso.md en mi mac
![Captura de pantalla 2020-03-19 a las 17 37 31](https://user-images.githubusercontent.com/62225957/77113007-c83dd700-6a08-11ea-8765-ecb4b1176671.png)

**Comment by gatochico** [comment]
Hola! Puedes abrir esos archivos, abriendo la terminal en la carpeta y ejecutando `cat PrimerPaso.md` (:

**Comment by nnovoag** [comment]
mentira no me resulto, me dice "no such file or directory"

**Comment by nnovoag** [comment]
no me resulto eso pero ya pude, gracias igual
