### ISSUE TITLE
Devolverse a carpetas padre?

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#127]
Hola, quiero devolverme a una carpeta padre, para luego devolverme nuevamente a la siguiente carpeta padre. hago lo que hacen en el video como con los paths pero no me funciona :(

![Captura de Pantalla 2020-03-19 a la(s) 8 09 44 p  m](https://user-images.githubusercontent.com/62023649/77122994-badf1780-6a1d-11ea-87a2-e305b3d18f2c.png)

**Comment by ValentinaAlvarezG** [comment]
Hola, como quieres cambiar de directorio, tienes utilizar cd. Te puedes devolver a la carpeta Padre con: 

`cd ..`

**Comment by ghost** [comment]
gracias!
