### ISSUE TITLE
Como almacenar los archivos encontrados

### ISSUE THREAD

**Issue by Natydlb** [Exploratorio-DCC-PUC/Syllabus#128]
Hola! Tal como sale en el video 2 intente ocupar dos acciones juntas mediante un >, en este caso intente ocupar un find(así encontre los archivos que necesitaba) y ocupe la carpeta que había creado pero no me funciono y nunca cargo ocupe el find solo y el "find . -name "tareaChica*.bla""
nose que ocupar más, ayuda :(
![WhatsApp Image 2020-03-19 at 20 38 15](https://user-images.githubusercontent.com/62019255/77125201-dd742f00-6a23-11ea-81fc-00ce072f6914.jpeg)

**Comment by gatochico** [comment]
Hola! Lo que ocurre es que el operador `>` redirige el output del comando de la izquierda a **un archivo de texto**. Lo que estaría haciendo en verdad es tomar el resultado de tu comando find, y escribirlo a un **archivo** que se llame NataliaDelaBarra, pero eso no hará nada con los archivos originales (Además, creo que no puedes tener una carpeta y un archivo con el mismo nombre y sin extensión, por lo que quizás ni se cree el archivo de texto en este caso en específico, por eso aparentemente no pasa nada).  

Recuerda que tu quieres mover los archivos encontrados, por lo que debería estar involucrado en algún lugar el comando para mover archivos explicado en el video 1. También te recomiendo buscar en internet ejemplos similares. Éxito! 💪
