### ISSUE TITLE
Duda Bonus Final

### ISSUE THREAD

**Issue by josemquinta** [Exploratorio-DCC-PUC/Syllabus#129]
En la parte final de la tarea sale un bonus, en el cual hay que crear una función que cuente los bytes de los archivos de una carpeta. Pero no entiendo que es lo que hay que entregar... hay que añadir el proceso en git al pdf? o simplemente poner el total de bytes o la funcion en alguna parte?

**Comment by ValentinaAlvarezG** [comment]
Hola! Al igual que el resto de la tarea, debes agregar al pdf el comando utilizado con el pantallazo correspondiente de su ejecución.
