### ISSUE TITLE
Pregunta 6 Variables

### ISSUE THREAD

**Issue by juanpacl111** [Exploratorio-DCC-PUC/Syllabus#13]
En este ejercicio  se mencionan ciertas variables como Precio ayudantía: p

La pregunta es, debo utilizar bash para encontrar el precio y luego restárselo manualmente al jugador o es necesario hacer una variable que registre este PATH y un código que sea capás de leer este path y operarlo con el jugador específico? 

En otras palabras,
Para cada ejercicio es necesario tener un código que lo resuelva en su totalidad?

**Comment by StroveLight** [comment]
Como se parece un poco a la idea de esta pregunta, lo preguntaré aquí:

¿Cuál es la profundidad de la tarea? es decir, en el enunciado dice (En "Tu mision", 12) que si el jugador cae en uno de los casilleros de destino pasa algo, por lo que:

[1] ¿debemos de guardar los casilleros del mapa para ver si el jugador cae o no en una de estas casillas o podemos asumir que el usuario escogerá casi con un dado cual destino sale, además de saber cuando cae en la casilla apropiada, y que este usuario usará el comando necesario para hacer que ese destino realice la acción?

[2] Además, la parte de mostrar los comandos correspondientes, ¿Se refiere a los que el programa ejecuta para esa situación o los que el usuario debería ejecutar para que se cumpla la situación?

**Comment by ValentinaAlvarezG** [comment]
Hola!

@juanpacl111 la idea es que el precio está dado y su valor es p, por lo que en tu comando debes restarlo manualmente.

@StroveLight  si te fijas bien en el enunciado, para los puntos 11 y 12 se especifica cual es la carta de destino que debes leer y por lo tanto, seguir sus intrucciones. Para cada una de ellas están las suposiciones correspondientes. 

Tu debes escribir el comando que corresponde a cada situación. Si tu carta de destino o de evento indica que devuelvas una ayudantía, esto por ejemplo significa que la carta del curso que estaba en jugador debe volver al dcc, entonces debes moverla con comandos bash. Es todo más o menos manual, no hay programa que esté revisando los casos, tu debes escribir los comandos que deberían correrse en caso de que ocurran las situaciones descritas en el enunciado, de acuerdo a las reglas del juego.

**Comment by Coolgatty** [comment]
En la 6 me puedes explicar por que se menciona a un jugador 3? El enunciado esta un poco confuso pero asumo que debia ser jugador 2 pues en este caso solo puede estar el jugador que tiene que pagar la ayudantia y el jugador que es ayudante.

**Comment by ValentinaAlvarezG** [comment]
@Coolgatty  hola, es un error de tipeo. Tanto de la 6 como de la 7, donde dice jugador 3, debería decir jugador i_2
