### ISSUE TITLE
Como detener un comando 

### ISSUE THREAD

**Issue by allisonaguilar** [Exploratorio-DCC-PUC/Syllabus#131]
hola!  ingrese el siguiente comando pero por error lo puse a buscar en la dirección equivocada y como resultado quedo eternamente buscando . Qué puedo hacer para pararlo?

MacBook-Air-de-allison: SubCarpeta_4 allison$ grep -r ´tc1-2020-1-allisonaguilar´
grep: warning: recursive search of stdin

**Comment by ValentinaAlvarezG** [comment]
Hola!

Puedes apretar control+c para pararlo

**Comment by allisonaguilar** [comment]
Muchas gracias!!
