### ISSUE TITLE
paso 2

### ISSUE THREAD

**Issue by nnovoag** [Exploratorio-DCC-PUC/Syllabus#132]
![Captura de pantalla 2020-03-21 a las 13 42 11](https://user-images.githubusercontent.com/62225957/77231481-fabb1180-6b79-11ea-991a-0cf5d62917ea.png)
hola estoy tratando de hacer el paso dos y me aparece eso, me gustaria saber que significa para poder arreglarlo :/ gracias

**Comment by ValentinaAlvarezG** [comment]
Hola! no estás usando de manera correcta el comando mv, la opción -t no es válida.

**Comment by nnovoag** [comment]
es que hartos lo hicieron asi y les resultó..... donde puedo ver como usarla entonces? porque no tengo ide de como mover todas las cosas de una sola vez osino

**Comment by nicolascamhi** [comment]
¿Por qué estás haciendo esto en el paso 2? A mi me sale que el paso dos es este:

<img width="1440" alt="Screen Shot 2020-03-21 at 18 08 51" src="https://user-images.githubusercontent.com/62315390/77236634-2c929f00-6b9f-11ea-8a1f-098bf50d7fa4.png">
