### ISSUE TITLE
No deja hacer commit

### ISSUE THREAD

**Issue by nicolascamhi** [Exploratorio-DCC-PUC/Syllabus#133]
No me está dejando hacer un commit, me sale un error

<img width="1440" alt="Screen Shot 2020-03-21 at 19 14 25" src="https://user-images.githubusercontent.com/62315390/77237589-5b614300-6ba8-11ea-9812-49ebdaeb1cba.png">

**Comment by gatochico** [comment]
Hola! Debes seguir las instrucciones que te indica el error y ejecutar los comandos
`git config --global user.email "tu correo que usaste para la cuenta de github"`
`git config --global user.email "tu usuario de github"`

Y luego trata de hacer el commit de nuevo.

**Comment by nicolascamhi** [comment]
Gracias!
