### ISSUE TITLE
Proceso de git sin terminar, ¿Como lo arreglo?

### ISSUE THREAD

**Issue by Francisco-Morales-R** [Exploratorio-DCC-PUC/Syllabus#134]
Hola, estaba intentando hacer un git add -A para guardar lo primero que era el crear la carpeta TareaChica1  y me sale un error que dice que hay otro preceso que no ha finalizado, y creo que es por que anteriormente ya habia intentado hacer in git add -A, pero parece que no lo dejé terminar y cerré la terminal, ¿Cómo lo soluciono?
![MINGW64__c_Users_Lenovo_desktop_Exploratorio_tc1-2020-1-Francisco-Morales-R 21-03-2020 19_38_09 (2)](https://user-images.githubusercontent.com/62259502/77238051-06bfc700-6bac-11ea-9745-959873c500b8.png)

**Comment by gatochico** [comment]
Hay dos opciones:

1) Podrias intentar manualmente borrar el archivo vía consola. Estando en la carpeta tc1-2020-1-... , con un `cd .git` y después `rm index.lock` debería arreglarse.

2) Si no resulta, guarda todos los archivos de la carpeta en un respaldo en tu computadora, clona nuevamente el repositorio (tienes que borrar el antiguo de tu escritorio primero) y luego subes todo de nuevo.

Avisa cómo te va!

**Comment by Francisco-Morales-R** [comment]
borré el index.lock manualmente desde la carpeta .git que estaba oculta y se solucionó, graciaaas
