### ISSUE TITLE
Cuenta mal el número de archivos

### ISSUE THREAD

**Issue by railira** [Exploratorio-DCC-PUC/Syllabus#135]
Conté todos los archivos dentro de la carpeta padre y seguí la ruta que indican los últimos tres dígitos pero no llegué al siguiente paso

**Comment by gatochico** [comment]
Hola! Recuerda que ese paso pide contar **todos los archivos presentes** en la carpeta, no sólo los con extensión .txt 
(PD: borré tu imagen ya que tiene parte del comando adjunta)

**Comment by airiquelme** [comment]
> Hola! Recuerda que ese paso pide contar **todos los archivos presentes** en la carpeta, no sólo los con extensión .txt
> (PD: borré tu imagen ya que tiene parte del comando adjunta)

ese es exactamente mi problema, no se si railira arreglo su problema, pero yo quiero contar todos los archivos, pero no las carpetas. No se como se hace, y google me da cualquier cosa
onda, hago
> find . | wc
que me da archivos y carpetas, pero no encuentro en google como tomar *todo, pero exceptuar carpetas
PD, usando "propiedades" de la carpeta desde el navegador, se cual es el numero que me deberia dar, y simplemente no puedo llegar a el :(
