### ISSUE TITLE
Problema con el conteo de archivos

### ISSUE THREAD

**Issue by ian-fell** [Exploratorio-DCC-PUC/Syllabus#137]
Al momento de tener que contar los archivos he tomado en consideración todos los casos posibles, y no logro llegar al numero indicado. He tenido en consideración los archivos ocultos, los con y sin extensión, y probando todas las combinaciones, y no logro llegar al numero. Algún consejo para encontrar lo solicitado? 
Sería de mucha utilidad :)

**Comment by gatochico** [comment]
Hola! Algunas recomendaciones podrían ser: 

1) El conteo de archivos incluye solo archivos (con cualquier extensión), y no carpetas.
2) Puede que durante la realización de los pasos anteriores creaste archivos demás, o borraste archivos sin querer. Para comprobar esto puedes ejecutar nuevamente el archivo TareaChica1.pyc y generar de nuevo la carpeta TareaChica (puedes generarlo en otro directorio, o trasladas la actual a otra parte de tu computador), y ejecutar los comandos de los pasos anteriores de nuevo (ahora que sabes cuales son los correctos hasta ese paso).
3) El archivo que creaste en el paso anterior (el de la película) debe estar dentro de TareaChica1 (por si lo pusiste fuera de la carpeta).

Espero haberte ayudado y si no es así, comenta de nuevo!
