### ISSUE TITLE
Problema para mover archivos encontrados

### ISSUE THREAD

**Issue by aboehmg** [Exploratorio-DCC-PUC/Syllabus#138]
Hola. Estoy intentando mover los archivos para el final del Primer paso, pero no logró unir las funciones find y mv. Encontré una forma en google de hacerlo, pero no la entiendo completamente, por lo que prefiero no usarla de primeras.
Mi idea es primero encontrar los archivos por medio de find, para luego mover los escogidos con mv. Me dice que me falta una destinación, aunque creo haber puesto la información necesaria (la carpeta con mi nombre).

**Comment by gatochico** [comment]
Hola! El problema que te lanza es debido que el comando `mv` necesita dos argumentos: `mv x y` donde `x `es el archivo a mover e `y `es el destino. De momento tu comando solo le entrega 1 argumento a mv.

No hay problema si usas comandos encontrados en internet, sin embargo queremos que entiendas porqué estos funcionan, y es por ello que se pide una breve explicación de cada comando en el informe. Si deseas usar alguno, también deberás hacer una breve investigación sobre cómo este funciona.

Eso dicho, hay formas de hacer ese paso con la info dada en los videos: toma en cuenta la pista dada en ese paso de que todos los archivos están en las carpetas más profundas, y que la profundidad máxima es la misma en todos los caminos (No hay carpetas más profundas que subsubsubcarpeta).

Éxito con la tarea!

**Comment by aboehmg** [comment]
Hola de nuevo. 
Pensé que lo había logrado, pero resulta que solo logré borrar todos los archivos que parten con "tareaChica" jajaja. 
¿Supongo que debo partir de nuevo? (Aún así no entiendo por qué me borró los archivos y no me los movió)
Intenté usar el tip que me diste de la profundidad.
![Duda2](https://user-images.githubusercontent.com/62244385/77334726-f3c00a80-6d03-11ea-86dc-6714a8585d36.JPG)
