### ISSUE TITLE
Problema commit y pushear

### ISSUE THREAD

**Issue by hasanchezuc** [Exploratorio-DCC-PUC/Syllabus#139]
![image](https://user-images.githubusercontent.com/61988958/77318590-12b2a280-6cec-11ea-9892-875fdf942c7e.png)

Hola, me sale el error de la imagen. Que podría hacer?.

Saludos

**Comment by gatochico** [comment]
Hola! Eso se debe a que hay cambios en el repositorio remoto (en github) que no están en el repositorio en tu computadora. Intenta primero ejecutar el comando `git pull`, y si no te deja, haz un respaldo de tu repo local en tu computadora y clona el repositorio de nuevo.

Avísanos como te va!

**Comment by hasanchezuc** [comment]
![image](https://user-images.githubusercontent.com/61988958/77339843-2b7e8080-6d0b-11ea-82f3-ac22f85b9634.png)

Lo que hice fue:
1. borrar todo (excepto la carpeta de TareaChica1 que la copie en otra parte). 
2. volver a clonar
3. copiar la carpeta de tareachica en la carpeta que se me creo de clonacion
4. hacer lo que sale en la foto.

se me queda ahí  :(

**Comment by hasanchezuc** [comment]
ahí me corrió, al parecer se demora mucho en mi pc.
