### ISSUE TITLE
Prueba gratis - tarjeta de crédito

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#14]
Hola, 
Quería saber cuál fue la decisión que se tomó al final respecto a si se deberán realizar las actividades para usuarios pro en el curso de codecademy (es decir, si las actividades se van a considerar o no para la nota de la tarea), ya que para hacerse pro la página pide los datos de la tarjeta de crédito (como habíamos mencionado algunos en la ayudantía del día miércoles).

**Comment by Pyralspite** [comment]
Hola,
Lamento la demora en responder este asunto. Con el resto de los ayudantes estuvimos buscando una solución que no perjudicara a nadie (ni a quienes no podían acceder a la parte PRO, ni a quienes ya la habían completado). Finalmente, hemos decidido que deben realizar tanto las lecciones PRO como gratuitas del curso.
La única forma de acceder a la prueba gratuita sin registrar la tarjeta de crédito es al aceptar la oferta inmediatamente después de registrarse en la página. Por lo tanto, quienes no aceptaron en su momento deben crearse una nueva cuenta y realizar las partes PRO en ella. Si ya hicieron las partes gratuitas en otra cuenta, deben explicar su caso en el README y poner el link de ambas cuentas. Nosotros revisaremos su avance para corroborar que completaron ambas partes del curso.
Reitero mis disculpas por las dificultades que causó esta situación. Si siguen teniendo problemas para completar el curso nos escriben para ver como lo arreglamos.
Saludos
