### ISSUE TITLE
Como Hacer todo de nuevo

### ISSUE THREAD

**Issue by Mamunoz42** [Exploratorio-DCC-PUC/Syllabus#140]
Hola
Ya terminé la tarea, pero me gustaría probar hacer el paso de buscar y mover los archivos de otra forma y ver si así me funciona, pero no se si debo clonar nuevamente mi repositorio o como podría hacer esto, ya que si esta forma me funciona se me haría mas fácil explicarlo en el pdf.

**Comment by gatochico** [comment]
Hola! Para probar todo de nuevo no es necesario clonar el repositorio nuevamente. Copia el archivo `TChica1.pyc` en otra carpeta y ejecutalo de nuevo como indica el enunciado. Este archivo es el que genera la carpeta TareaChica1, por lo que tendrás otra carpeta para probar tus comandos desde 0.

Al final cuando subas tu tarea, sube la carpeta TareaChica1 que corresponda con el set de comandos que usaste en el informe, ya que las carpetas donde se ocultan ciertos archivos se eligen aleatoriamente.

**Comment by Mamunoz42** [comment]
Muchas Gracias
