### ISSUE TITLE
Error en el nombre de los commits 

### ISSUE THREAD

**Issue by rodrigopg908** [Exploratorio-DCC-PUC/Syllabus#141]
busque ayuda en internet para cambiar el nombre de un commit anterior, dado que hice un commit al finalizar el paso 2 , y al terminar la tarea no se le hicieron mas cambios a la carpeta TareaChica1, entonces no me agregaba con gitt add la carpeta.
segui los pasos , pero se agregaron muchos commits y se cambio tambien el nombre del commit con el pdf. Sin embargo los archivos estan bien . 
Quisiera saber como quitar los commits que se crearon con el nuevo nombre.
si esto afectara en la nota, como puedo hacer todo denuevo para tener solo los 2 commits necesarios?

![ayuda](https://user-images.githubusercontent.com/62294082/77348026-7e5e3500-6d17-11ea-877d-bcb861bbe3d7.jpg)

**Comment by gatochico** [comment]
Hola! Si ya terminaste la tarea, deja los commit tal como están y no habra problema.
