### ISSUE TITLE
Problema con git push

### ISSUE THREAD

**Issue by camigonzalezp** [Exploratorio-DCC-PUC/Syllabus#142]
![Captura de Pantalla 2020-03-23 a la(s) 18 47 07](https://user-images.githubusercontent.com/62308052/77366643-2e8f6600-6d37-11ea-8b6c-026ff0cd7910.png)
Hola! Al hacer git commit me apareció una lista infinita como la que sale en la parte inferior de la imagen, está bien? por qué pasa esto?

**Comment by gatochico** [comment]
Hola! Por lo que veo hasta ahí hiciste solo `git commit`, ¿Pudiste hacer luego push, o te lanzó algun error?

La lista infinita está bien, ya que cuando haces un commit la consola muestra todos los archivos que fueron editados/agregados/quitados en dicho commit. Como es la primera vez que subes la carpeta TareaChica1, te saldrá el listado de todos los elementos de la carpeta ya que son archivos nuevos que vas a subir.

**Comment by camigonzalezp** [comment]
Ah ya comprendo. Sí, después pude hacer push y subir la carpeta, gracias! Lo último, no importa desde que parte del directorio se haga push cierto?

**Comment by gatochico** [comment]
No importa, con tal que estes dentro del repositorio al hacer push!
