### ISSUE TITLE
es normal que me salgan tantos simbolos? creo que deberia ser mas bien texto

### ISSUE THREAD

**Issue by andrius6789** [Exploratorio-DCC-PUC/Syllabus#143]
![image](https://user-images.githubusercontent.com/62076980/77370819-74046100-6d40-11ea-8491-44348555549d.png)

**Comment by gatochico** [comment]
Hola! Esto se debe a que el archivo `TChica1.pyc` no debe ejecutarse con `cat`, sino que con `python` con el comando que se da en el enunciado. Luego de eso, el resto la tarea se realiza con la carpeta `TareaChica1` que se creó tras ejecutar las líneas del enunciado.

**Comment by andrius6789** [comment]
El problema es que al ejecutar las 2 lineas de comando que nos dan en el enunciado no se crea esta carpeta TareaChica1 entonces ya no se que hacer

**Comment by gatochico** [comment]
¿Qué te indica la consola cuando corres los comandos?

**Comment by andrius6789** [comment]
nada, los "acepta" pero no me da ninguna respuesta

**Comment by andrius6789** [comment]
![image](https://user-images.githubusercontent.com/62076980/77379916-a752ea00-6d58-11ea-8494-39956af991bc.png)

**Comment by gatochico** [comment]
Podrías probar con dos cosas:

1) A alguien más en la issue #123 le resultó abriendo git bash como administrador.
2) Si no funciona, revisa que tu versión de python sea una 3.7.x corriendo `python --version` después del comando alias.

**Comment by andrius6789** [comment]
hice ambas y no paso nada, al usar "python --version" me lo recepciona bash pero no me entrega ningun resultado

**Comment by gatochico** [comment]
¿Y qué pasa si tratas de correr el comando del enunciado o `python --version` con la cmd de windows? (En este caso no es necesario poner el comando alias primero)

**Comment by andrius6789** [comment]
nada tampoco, solo me pide otro comando sin darme ninguna respuesta
hoy instale el python que recomienda la tarea entonces no entiendo cual es el problema

**Comment by gatochico** [comment]
¿Podrías mostrarme lo que muestra la cmd si corres `where python`?

**Comment by andrius6789** [comment]
![image](https://user-images.githubusercontent.com/62076980/77454669-9e552d80-6dd7-11ea-8405-474f1c7735a0.png)

**Comment by gatochico** [comment]
Ah ya, [leyendo en internet](https://stackoverflow.com/questions/58940519/cmd-doesnt-return-any-output-after-running-my-python-script) dicen que el problemas es por bajar python mediante la microsoft store. Lo que hacen en el link anterior es:
- Desinstalar python de tu computadora. 
- Instalarlo de nuevo, pero desde [este link](https://www.python.org/downloads/release/python-377/) (clickea en alguno de los windows executables que aparecen abajo)
-Asegurate de tickear la caja que dice `Add python to PATH`:
![image](https://user-images.githubusercontent.com/37161120/77472176-47108680-6df2-11ea-9ab3-94db35234253.png)
-Intenta nuevamente correr el comando python (debería haberse solucionado) desde la cmd (o git bash si quieres, pero ahí debes si o si correr el comando `alias python=...` primero)

Avisanos como te va!
