### ISSUE TITLE
abrir Tchica

### ISSUE THREAD

**Issue by angelescox** [Exploratorio-DCC-PUC/Syllabus#144]
![image](https://user-images.githubusercontent.com/62268739/77450428-fc7f1200-6dd1-11ea-8812-73ac5f516675.png)
ya desinstale python y volvi a bajarmelo, que puedo hacer?

**Comment by gatochico** [comment]
Hola! Debes ejecutar el comando estando en la carpeta de tu repositorio personal en el computados (que es donde está el archivo .pyc). Si no lo tienes, recuerda que debes clonar el repositorio primero!
