### ISSUE TITLE
Problema git commit

### ISSUE THREAD

**Issue by camigonzalezp** [Exploratorio-DCC-PUC/Syllabus#145]
![Captura de Pantalla 2020-03-24 a la(s) 17 52 46](https://user-images.githubusercontent.com/62308052/77475953-64485380-6df8-11ea-9aee-cb1bb2653e9c.png)
Hola, cuando hago git add . y luego git commit -m me aparece este mensaje, pero no entiendo por qué si ya le hice git add

**Comment by gatochico** [comment]
Hola! Puede que anteriormente hayas hecho un commit que todavía no pusheas al repositorio remoto. Prueba haciendo `git status` y ve si te dice algo similar a esto:
![image](https://user-images.githubusercontent.com/37161120/77493045-cf0d8500-6e20-11ea-8963-cab3826a6096.png)
Si es así, es porque tienes un commit que todavía no se sube al repo remoto. Puedes ver que mensaje tiene dicho commit haciendo `git log` y si apruebas el mensaje, haz solo git push. Si quieres cambiar el mensaje de dicho commit, haz `git reset HEAD~`, y puedes hacer git add, commit y push de nuevo (para este caso trata primero hacer una copia de respaldo de tu tarea en el escritorio :eyes:).

**Comment by camigonzalezp** [comment]
![Captura de Pantalla 2020-03-24 a la(s) 22 59 05](https://user-images.githubusercontent.com/62308052/77493909-21e83c00-6e23-11ea-9538-bcb1eed0f620.png)
Me aparece esto haciendo git status, pero no entiendo por qué si ya le hice git add .

**Comment by gatochico** [comment]
Y además de esos archivos, hay algun cambio en tu repositorio local con respecto al remoto? Los archivos .DS_Store los generan los mac automáticamente y no es necesario que se suban cuando subas tu tarea. Por ende, no es necesario que los añadas al commit.

**Comment by camigonzalezp** [comment]
No, en GitHub solo aparece el primer commit que hice (este es el segundo)

**Comment by gatochico** [comment]
A lo que me refiero es si has hecho algún cambio en los archivos del repositorio entre el primer commit y el segundo que quieres subir?

Si en este momento el repositorio local y el remoto son exactamente iguales (exceptuando los .DS_Store), no te dejará hacer un commit nuevo por que no hay ningún cambio a subir. En cuanto hagas algún cambio en el repositorio, como añadir, mover o borrar un archivo/carpeta (cosas que tendrás que hacer durante la tarea), podrás hacer un commit.
