### ISSUE TITLE
Tengo un problema cuando utilizo git add (me di cuenta cuando intento commitear que no tengo nada que subir)

### ISSUE THREAD

**Issue by andrius6789** [Exploratorio-DCC-PUC/Syllabus#146]
![image](https://user-images.githubusercontent.com/62076980/77480403-6c0bf600-6e00-11ea-8c89-81084d00a05e.png)

**Comment by gatochico** [comment]
Hola! Estando dentro de TareaChica1 ejecuta ` ls -a` y sube lo que retorna la consola, por favor
