### ISSUE TITLE
Duda Bonus Final Tamaño

### ISSUE THREAD

**Issue by Jimnora** [Exploratorio-DCC-PUC/Syllabus#147]
El tamaño que se entrega debe ser el tamaño aparente de los archivos, es decir, lo que sale si uno pone propiedades en el buscador? o es el espacio ocupado en el disco duro?

**Comment by gatochico** [comment]
Hola! El tamaño que se pide es el aparente de los archivos en bytes. No el ocupado en disco, ya que te dará un tamaño mayor al pedido.

**Comment by Jimnora** [comment]
Muchas gracias 👍 
Lo otro, con crear una función de consola se refiere a crear desde cero? o utilizar comandos ya existentes para hacerlo?
