### ISSUE TITLE
Duda sobre git add

### ISSUE THREAD

**Issue by Bea2000** [Exploratorio-DCC-PUC/Syllabus#148]
Hola! Al ejecutar git add --all me retorna esto. ¿Significa algo o lo ignoro?
![MINGW64__c_Users_beatr_tc1-2020-1-Bea2000 25-03-2020 18_47_41](https://user-images.githubusercontent.com/62019058/77588864-6f1ee900-6ec9-11ea-9b15-1e56b5a908da.png)

**Comment by gatochico** [comment]
Hola! Puedes ignorar ese mensaje, ya que no afecta en nada tus archivos ni tu tarea.

Por si quieres saber la explicación: LF y CRLF son formas que tienen los distintos sistemas operativos para indicar un salto de línea en un archivo de texto. El mensaje indica que tu archivo usaba LF, y se reemplazará por CRLF por un tema de mantener un mismo formato en todos los archivos.

**Comment by Bea2000** [comment]
Super, gracias!!
