### ISSUE TITLE
Cometí un error al ejecutar commit

### ISSUE THREAD

**Issue by Bea2000** [Exploratorio-DCC-PUC/Syllabus#149]
Hola!
Ingresé el código mal sin querer. No se si hice algo o simplemente lo ejecuto de nuevo.
![MINGW64__c_Users_beatr_tc1-2020-1-Bea2000 25-03-2020 19_17_53](https://user-images.githubusercontent.com/62019058/77590957-b4ddb080-6ecd-11ea-96f4-2db7f7f1863f.png)

**Comment by malopez16** [comment]
Hola,
Puedes ejecutarlo nuevamente. No se ejecutó ningún comando.
Tuviste un error en `git -commit`. En realidad, es `git commit`, sin ese "-".
Saludos :)
