### ISSUE TITLE
confusión con carpeta padre

### ISSUE THREAD

**Issue by SofiaP419** [Exploratorio-DCC-PUC/Syllabus#150]
En el primer paso, al crear la carpeta NombreApellido, no la puse en la carpeta TareaChica1 porque pensé que la carpeta padre era tc1-2020.  ¿Tengo que hacer la tarea toda de nuevo o puedo simplemente mover la carpeta después a donde corresponde? (Para realizar el paso 3).

**Comment by gatochico** [comment]
Hola! No hay problema con que muevas manualmente la carpeta a su ubicación correcta (recuerda indicarlo en el informe, eso sí),
