### ISSUE TITLE
problema al contar los archivos que hay en TareaChica1

### ISSUE THREAD

**Issue by sbmirandap** [Exploratorio-DCC-PUC/Syllabus#151]
me da un numero pero al buscar en las carpetas y subcarpetas no encuentro nada, no se que podría hacer :(

**Comment by gatochico** [comment]
Hola! Puedes tratar haciendo que el conteo de archivos ignore los archivos ocultos (puedes investigar en internet como lograr esto). Otras cosas a tomar en cuenta:
- La carpeta NombreApellido debe estar dentro de TareaChica1
- Debes contar el nº de archivos (archivos totales, no incluir carpetas en el conteo, e ignorando los archivos ocultos).
- Debes hacer realizado ya todos los pasos anteriores de la tarea.
- Debes contar todos los archivos que se encuentran en la carpeta TareaChica1. (el .pyc, por ejemplo, no cuenta, ya que está fuera de la carpeta)

Avísanos como te va!

**Comment by sbmirandap** [comment]
no me sigue resultando ya intente los dos numeres distintos que me dieron :(

**Comment by gatochico** [comment]
En qué sistema operativo estás trabajando?

**Comment by sbmirandap** [comment]
estoy desde mac

**Comment by gatochico** [comment]
Con los mac ocurre que a veces crean unas carpetas ocultas llamadas [DS_Store](https://sistemas.com/archivos-ds-store.php). Por ende, no se verán en el navegador de archivos, pero al momento de ejecutar el conteo de archivos sí se incluirán en este y puede que debido a eso no estés llegando a la rpta.

Una idea es hacer que el comando que cuenta archivos **no cuente archivos ocultos** (puedes investigar eso en internet). Otra opción sería investigar el como sacar esta carpeta DS_Store de tu carpeta TareaChica1.

De todas formas, como este problema no es culpa tuya, si en tu informe incluyes el comando original (es decir, un comando que cuente todos los archivos de una carpeta, y funcione correctamente) para resolver ese paso, tendrás el puntaje correcto allí aunque el número de archivos no calze con la ubicación del archivo final. (posee extensión .md, por si deseas buscarlo con el explorador de archivos para seguir con el bonus)
