### ISSUE TITLE
Saber si se subió la actualización que le hice a la tarea

### ISSUE THREAD

**Issue by sbvillalobosm** [Exploratorio-DCC-PUC/Syllabus#152]
Hola
No estoy segura si se subieron los últimos cambios que le hice a la tarea. Le añadí el pdf a mi repositorio y eso sí aparece en github, pero en la carpeta de TareaChica1 aparece que la última actualización fue la que hice anoche y no la de hoy en la tarde, ¿igual se actualizó o no?

![image](https://user-images.githubusercontent.com/62085874/77806845-b2fa2580-7064-11ea-91ae-60ebde1b24da.png)

**Comment by gatochico** [comment]
Hola! Los diferentes tiempos de actualización ocurren ya que un archivo se vuelve a subir al repositorio remoto **solo si fue modificado**.

En ese ultimo push, probablemente solo subiste el .pdf y no cambiaste nada a los otros archivos con respecto al push anterior a ese (que sería el penúltimo, por ejemplo). Por lo tanto, esos archivos quedan con la fecha de modificación del push donde sí hubo cambios, y el pdf queda con la nueva fecha, ya que ese sí cambio en la última actualización del repositorio.

En resumen, no tienes que preocuparte que las fechas sean distintas 🤓
