### ISSUE TITLE
pregunta del git add

### ISSUE THREAD

**Issue by magdalenanario** [Exploratorio-DCC-PUC/Syllabus#155]
Que hago si es que me siguen apareciendo en rojo ciertos archivos a pesar de ya haber hecho git add a los archivos y carpetas que me salieron en rojo tras haber hecho git status?
![image](https://user-images.githubusercontent.com/62227994/77859363-4eafa100-71df-11ea-82a9-1456c9aaf922.png)

**Comment by gatochico** [comment]
Hola! Cómo estás haciendo el add? Con `git add .`? Si no es así, prueba con ese comando y luego revisa el git status.

**Comment by magdalenanario** [comment]
![image](https://user-images.githubusercontent.com/62227994/77941244-3fd4f700-7290-11ea-938f-f16c447b67fc.png)
asi hice el git add a la carpeta creada con nombre y apellido y al archivo progreso.txt. Pero nose que significan esos archivos en rojo que sale "deleted" en la primera foto que mande y nose si tengo que agregarlos para el commit o no

**Comment by gatochico** [comment]
Lo que ocurre es que en ese paso mueves archivos de varias ubicaciones en la carpeta TareaChica1 a la carpeta MagdalenaNario. Luego, haces add solo de la carpeta MagdalenaNario (que es la que tiene archivos nuevos) sin embargo, cuando moviste archivos los **sacaste de su ubicación original** (lo que está bien, así funciona mover). 

El mensaje rojo de arriba te indica que git encontró un cambio (del tipo deleted, que serían los archivos que moviste de su ubicación original) y no fue incluido con git add al commit (ya que hiciste el git add de carpetas en específico).

Para incluir todos esos cambios (ya sean add, modify o delete) al commit, la forma más facil es hacer `git add .`, lo que te incluye **todos los cambios hechos en el repositorio** de forma inmediata. Así, no tienes que hacer add por cada item que quieres agregar.  Haciendo ese comando te dejará de salir la notificación en rojo, y el repositorio remoto será igual al local cuando hagas el push.

Espero se haya entendido!

**Comment by magdalenanario** [comment]
sisi perfecto! pero acabo de poner git add . y me sigue apareciendo lo mismo en rojo. No sera mejor que ponga git add -A ?

**Comment by gatochico** [comment]
En teoría deberían ambos funcionar. De todas formas, intenta con git add -A y nos dices como te va.
