### ISSUE TITLE
Como eliminar commits?

### ISSUE THREAD

**Issue by airiquelme** [Exploratorio-DCC-PUC/Syllabus#156]
Acabo de leer que por poner commits con "mala descripción" te baja puntos. Mi problema es que hice un commit para ver si me resultaba, pero ahora se que me baj puntos... que hago?

**Comment by ValentinaAlvarezG** [comment]
Hola! Mientras cumplas con que tienes dos o más commits descriptivos, está bien. Así que puedes agregar otro que sea descriptivo y entenderemos que si hay otro no descriptivo estabas probando.
