### ISSUE TITLE
Duda comando Bonus

### ISSUE THREAD

**Issue by airiquelme** [Exploratorio-DCC-PUC/Syllabus#157]
estoy probando el comando "du", pero es extraño porque si hago "du -s *" me da todos los bytes (supuestamente 97k) pero si hago "du -sh *" me da cada archivo y sus bytes respectivos.
PERO, probe sumar cada uno de los archivos y me dio 69k...
cual de los dos es el que se pide? que estoy haciendo mal? segun el navegador la carpeta pesa 447k y estoy más confundido todavía :,(

**Comment by gatochico** [comment]
Hola! Cuando usas du con la opción h, te retorna el tamaño de las cosas en kilobytes (unidades de 1024 bytes). Quizá por eso no te calzan los valores.

Recuerda 2 cosas: lo que se pide es retornar la suma del tamaño de todos los archivos (!= a el espacio en disco que usa una carpeta, ya que una carpeta siempre usa un poco más de tamaño en disco que el que muestra el navegador de archivos, que sería el tamaño que quieres mostrar) y que el resultado retornado esté en bytes.

Espero eso te ayude!
