### ISSUE TITLE
2 PDF en el repositorio de Github  

### ISSUE THREAD

**Issue by Gustav2000** [Exploratorio-DCC-PUC/Syllabus#158]
Hola, subi 2 versiones de mis Comandos de Git en PDF pero no se sobreescribieron como pensé que pasaría. Importa si quedan las 2 versiones subidas en Github? 
![Pantallazo Github](https://user-images.githubusercontent.com/62355739/77961782-c699cc00-72b0-11ea-9751-c54d64c41e84.jpeg)

**Comment by ValentinaAlvarezG** [comment]
Hola!
Puedes borrar el archivo que no quieras que te revisemos. Usa:

`git rm nombrearchivo.extension`

`git commit -m "eliminando archivo"`

`git push`

Avísame si te funciona!

**Comment by Gustav2000** [comment]
Sí me funcionó, gracias!!!
