### ISSUE TITLE
No puedo contar bien los archivos que nos piden

### ISSUE THREAD

**Issue by andrius6789** [Exploratorio-DCC-PUC/Syllabus#159]
Para la ultima parte de la tarea, estoy intentando encontrar la SubSubcarpeta_x que sea la correcta pero no llego a dar con ella
utilizo el comando 
y me arroja 28994 pero al dirigirme a la Carpeta_9/SubCarpeta_4/SubSubCarpeta_4/ con el comando
cd Carpeta_9/SubCarpeta_4/SubSubCarpeta_4/ no encuentro nada util al utilizar "ls"

**Comment by gatochico** [comment]
Hola! Primero, dices que arroja 28**994** archivos, pero vas al indice **9/4/4**. ¿Será eso o es un error de escritura? 

Por otro lado, algunas cosas a revisar:
1) ¿La carpeta Nombre Apellido está dentro de la carpeta TareaChica1? Si la creaste fuera de dicha carpeta, ponla dentro ya que debe ser incluida en el conteo de archivos.
2) Estas contando todos los archivos de TareaChica1? Todo lo que esté fuera, como generador.py o README.md no deben ser incluidos.
3) Quizá durante la realización de los otros pasos creaste o borraste archivos demás. Podrías generar nuevamente la carpeta TareaChica1 (los comandos de los pasos anteriores se mantendrán, solo cambiarán algunas rutas de carpetas)
4) Usas mac? Ya que mac genera algunos archivos ocultos que harán que tu conteo sea mayor al que se pide. Podrías tratar haciendo que tu comando ignore archivos ocultos.

Finalmente, si ninguna recomendación te sirve y sabes que tu comando está bien, escribe dicho comando en el .pdf y explica la situación. (con pantallazos)

El archivo que deberías encontrar al final de ese paso se llama `elFin.md`, por si deseas buscarlo manualmente para comprobar tu comando.
