### ISSUE TITLE
Cmd, bash o PowerShell

### ISSUE THREAD

**Issue by Baelfire18** [Exploratorio-DCC-PUC/Syllabus#160]
Da lo mismo si hago la tarea 1, con git bash, la cmd o la windows powershell? Todas son consolas, deberia dar lo mismo cierto?

**Comment by ValentinaAlvarezG** [comment]
Hola!
No da lo mismo para la tarea, por que algunos comandos de windows son diferentes a los de linux y nosotros evaluaremos con comandos de linux. Así que si tienes windows deberías hacerlo con git bash para asegurarte de que los comandos son los que evaluaremos.

**Comment by Baelfire18** [comment]
F. Todo otra vez
