### ISSUE TITLE
Tengo un problema con git add, commit y push

### ISSUE THREAD

**Issue by andrius6789** [Exploratorio-DCC-PUC/Syllabus#161]
![image](https://user-images.githubusercontent.com/62076980/77978747-39b73880-72d9-11ea-9f63-3be2569ea30a.png)

**Comment by gatochico** [comment]
Hola! Puede que git esté tomando la carpeta TareaChica1 en sí como un repositorio por sí solo, y por ende no te deja agregarla. 

Puedes intentar con estas dos opciones:
1) Busca si dentro de la carpeta TareaChica1 (no dentro de tc1-2020-1-..., sino de TareaChica1) hay una carpeta llamada `.git` . Si hay una, borrala e intenta hacer el push de nuevo. Ojo que al ser una carpeta oculta (parte con un "."), tendrás que activar en tu explorador de archivos la opción "ver archivos ocultos" si es que la buscas por ese medio. También podrías buscarla con el siguiente comando de bash estando dentro de TareaChica1: `find -type d -name ".git"`.
2) Genera la carpeta TareaChica1 de nuevo (los comandos a usar en cada paso se mantienen, solo tendrás que ejecutarlos de nuevo y sacar los pantallazos de nuevo para el informe.)

**Comment by andrius6789** [comment]
![image](https://user-images.githubusercontent.com/62076980/78048907-c51fe080-7350-11ea-9dc9-8d9687e5a744.png)
Ahora me dice que no hay un .git
