### ISSUE TITLE
Duda de encoding

### ISSUE THREAD

**Issue by BMarink512** [Exploratorio-DCC-PUC/Syllabus#163]
Al momento de subir el archivo csv a google colab, y tratar de leerlo con *df=pd.read_csv(url)* me tira el error:
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte**

Es suficiente para arreglarlo con encoding ISO-8859-1 o van a ver partes que no cambiaran?

**Comment by malopez16** [comment]
Hola! 
Te recomiendo utilizar encoding latin-1. 
Saludos!

**Comment by pablobaldazzi** [comment]
Hola! Tengo el mismo error, como puedo cambiar el encoding de utf-8 a latin-1?

**Comment by Jiruiz2** [comment]
Hola,

Al leer el csv con la función read_csv debes especificarle el encoding de la siguiente manera:
pandas.read_csv(nombre.csv, encoding="latin-1")

Saludos

**Comment by pablobaldazzi** [comment]
Muchas gracias! Ultima pregunta, solamente tengo que especificar el tipo de encoding para el comando read?

**Comment by malopez16** [comment]
Hola,
Sí, sólo para la lectura está bien.
Saludos!
