### ISSUE TITLE
Practico II JavaScript

### ISSUE THREAD

**Issue by Baelfire18** [Exploratorio-DCC-PUC/Syllabus#164]
Hola tengo una pregunta del practico ii. Como se pude hacer para que todos los cambios hecho al momento de interatuar con  la pagina creada por el HTML queden guardados en código. Tal como queda guardado el ejemplo. Como "dejar guardadas esas nuevas constantes y funciones. 
Gracias

**Comment by LuisFros** [comment]
Hola @Baelfire18 !
Es una muy buena duda. 
En pocas palabras, podrias usar una de las siguientes alternativas:
- Cookies
- LocalStorage
- Base de Datos externa

Si buscas profunidizar en estos temas, te recomiendo leer esto: 
[JS - Persistence](https://www.oreilly.com/library/view/javascript-cookbook/9781449390211/ch20.html
) y buscar en google como funcionan estas alternativas.
