### ISSUE TITLE
Redondeo de Datos

### ISSUE THREAD

**Issue by ian-fell** [Exploratorio-DCC-PUC/Syllabus#165]
Para la primera parte de la tarea piden redondear datos, especificando que aquellos datos con decimal .5, por ejemplo 5.5, sean redondeados para arriba. El único método para pandas, por más que busco, es .round(), el cual redondea los datos .5 hacia abajo. Lógicamente todo el resto de los redondeos está bien, pero difiere en el .5, esto será un problema?

**Comment by Jiruiz2** [comment]
Hola,
No hay ningún problema que aproximes hacia abajo o hacia arriba. De todas maneras te dejo esta página por si quieres probar otras opciones https://stackoverflow.com/questions/27592456/floor-or-ceiling-of-a-pandas-series-in-python
Saludos
