### ISSUE TITLE
Expresión fecha de lanzamiento

### ISSUE THREAD

**Issue by fedezang** [Exploratorio-DCC-PUC/Syllabus#167]
Para la pregunta 4 de la parte 1 se pide realizar un gráfico en base a los meses de lanzamiento de las películas, pero sin considerar las películas que no tengan mes de lanzamiento. ¿Cómo se expresa la fecha en esas películas? Para poder diferenciarlas de las que sí tienen mes de lanzamiento.

**Comment by malopez16** [comment]
Hola!
Las que no llevan mes, simplemente no van en el gráfico.
Saludos!

**Comment by fedezang** [comment]
Sisi, pero para diferenciarlas antes de hacer el gráfico. Porque las películas con fecha vienen en el formato YYYY-MM-DD, mi duda es en que formato se encuentran las películas sin mes de lanzamiento

**Comment by malopez16** [comment]
Hola nuevamente!
Descubrir eso es parte del desafío del procesamiento de datos :)
Saludos!
