### ISSUE TITLE
Peliculas sin mes

### ISSUE THREAD

**Issue by vWing7** [Exploratorio-DCC-PUC/Syllabus#168]
En la pregunta 4 de la parte 1, ¿que tiene que salir en las peliculas sin mes?¿mes = 00? Pregunto porque al menos al transformar a datetime no me tira error ni pierdo filas, pero al buscar por mes == 0 no obtengo resultados.

**Comment by Jiruiz2** [comment]
Hola,

Si una película no tiene mes puedes ignorarla.

Saludos
