### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by OrregoSilva** [Exploratorio-DCC-PUC/Syllabus#170]
Hola!
Queria saber si el server de discord se va a seguir usando, ya que me pasa que tengo dudas que no se como redactarlas sin mostrar la solución a una gran parte de la tarea.

**Comment by Jiruiz2** [comment]
Hola,
El server si se seguirá usando pero solo cuando hayan horario de consultas. De todas maneras si tienes problemas y debes mostrar código puedes enviar un correo a alguno de los ayudantes y veremos como ayudarte.
Saludos
