### ISSUE TITLE
Ejemplo Repositorio Base TG1

### ISSUE THREAD

**Issue by Jimnora** [Exploratorio-DCC-PUC/Syllabus#171]
En el documento de la tarea dice "En el repositorio base de la tarea, encontrarás una estructura
propuesta que te ayudará a cumplir con el formato esperado."
Cuando cree mi repositorio con git-hub classroom, no me apareció esta estructura propuesta. Donde se encuentra? Como puedo saber si tienen acceso a mi repositorio privado?

**Comment by malopez16** [comment]
Hola!


- Si trabajas en el repo. de github classroom, no deberían haber problemas.
- En cuanto a la estructura del repo, se sugiere que todos los archivos, parte 1,2 y 3, se guarden en la raíz, y que las imágenes queden guardadas dentro de una carpeta.
Ejemplo:
![image](https://user-images.githubusercontent.com/26126519/78840743-985f6f00-79c9-11ea-91b9-0e2f0c4eeeb9.png)
