### ISSUE TITLE
Hardcodear en TG1

### ISSUE THREAD

**Issue by Baelfire18** [Exploratorio-DCC-PUC/Syllabus#172]
Hola escribo para preguntar si se puede instanciar lo que se pide o hay que hacerlo para casos generales.
Por ejemplo: que el grafico 2 se deba poner de otro color para la primera pelicula sea cual fuese, o yo sabiendo cual es la primera, hago que esa sea de otro color.
Tambien se puede aplicar para la parte2, los resumenes de las peliculas. Si hay que sacar para los primeros 5, sean cuales fuesen estos. O yo ya habiendo sacado los primeros 5. Con la libreria de wikipedia busco de la forma adecuada, el resumen de cada una de ellas por su nombre ya conocido y las agrego al dataframe

**Comment by malopez16** [comment]
Hola!
Se busca que se realice siempre para casos generales, vale decir, no hacer [hardcoding](https://stackoverflow.com/questions/1895789/what-does-hard-coded-mean). 
En este caso, hardcoding significaría dibujar el gráfico, obtener los datos, y luego escribir exáctamente el dato que quieres que se pinte. Lo correcto es programar el gráfico cosa de que sólo alterando la data de input todo esto ocurra y se marque automáticamente la barra que corresponde (sin cambiar nada más que la data de input!!).
Esto es importante no sólo para esta tarea sino siempre! (y por el resto de su carrera y años programando jeje).

Saludos

**Comment by Baelfire18** [comment]
Para la parte 2. Intente hacerlo en caso general pero los comandos de wikipedia me fallaban alintentar hacerlo con un dataframe, luego el miercoles por discort un ayudante me dijo que efectivamnte no se podia usar dataframe con wiki. En estos caso que prima? No harcoderalo o no usar FORs en la tarea para sacar todos los resumenes de las paginas

**Comment by malopez16** [comment]
Hola!
El ayudante cuando respondió tu pregunta se estaba refiriendo a que no le puedes meter un dataframe completo a la función de wikipedia, porque la función de wikipedia acepta un string, y no un dataframe.  

Eso no implica que sí puedes aplicar funciones sobre columnas o filas (o sea, sobre los datos/strings que están dentro del dataframe), lo cuál no es lo mismo que aplicar la función metiendo directamente el objeto del tipo dataframe. Para más info: [Aplicar función a datos en dataframe](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html) . También se puede buscar en google como hacer apply a filas o columnas de un dataframe.  

En cuanto a la consulta del comentario anterior, la respuesta es ninguno: **No** hay que hardcodear, y **tampoco hay que utilizar ciclos (while, for, etc)**, sino que hay que utilizar las funciones propias de pandas (selección de filas, columnas y/o elementos, y aplicación de funciones a esas filas, columnas y/o elementos).   

Saludos!
