### ISSUE TITLE
Problema con Wikipedia

### ISSUE THREAD

**Issue by furzuadr** [Exploratorio-DCC-PUC/Syllabus#173]
Hola! Estoy haciendo la parte 2 y me funciona perfecto para 4 de las películas, pero en esta obtengo esto:
`PageError: Page id "the dark night" does not match any pages. Try another id!`
Lo raro es que está entrando "The Dark Knight", incluso si hago
`print(wiki.summary('The Dark Knight'))
`
Me pasa lo mismo.
Qué podrá ser?

**Comment by camigervasoni** [comment]
me pasa lo mismoo, no cacho porquee

**Comment by furzuadr** [comment]
Descubrí que el problema es porque en Wikipedia se llama `The Dark Knight (film)`, por lo que cambié la línea 4842 por esta:
`185000000.0,Warner Bros.,USA,Christopher Nolan,Action,534858444.0,The Dark Knight (film),PG-13,2008-07-18,152,9.0,Christian Bale,1839571,Jonathan Nolan,2008`
y me funciona, es posible que se actualice el csv a esto? Sino qué otra solución puede haber?

**Comment by malopez16** [comment]
Estimados,
Lamentablemente solucionar este problema sería darles parte de la tarea resuelta. Recuerden que los datos no pueden cambiar, sino que deben solucionarlo sólo utilizando herramientas de la librería.
Por lo mismo, no se permite poner soluciones o posibles snippets de código para esta problemática.

Saludos.
