### ISSUE TITLE
Adjuntar imágenes en archivo html

### ISSUE THREAD

**Issue by railira** [Exploratorio-DCC-PUC/Syllabus#174]
Hola, escribo porque no logro hacer que aparezcan las imágenes en mi página web. Estas están guardadas dentro de la misma carpeta que el archivo html y dentro de este archivo hago el llamado correspondiente, sin embargo solo logro que me aparezca un pequeño icono en la página.
![Captura](https://user-images.githubusercontent.com/62022050/78932214-217fb000-7a75-11ea-9b4f-c5c3c1e6ee27.PNG)

**Comment by LuisFros** [comment]
Hola @railira,
Parte de los desafios de la tarea es lograr mostrar las imagenes en la pagina. 
Sin embargo, pueden haber razones particulares por las cuales no te esta funcionando esto.
Para poder ayudarte necesito que me digas que navegador estas utilizando (Chrome, Firefox, etc) y informacion sobre tu sistema operativo (Windows, Mac y otros).

Ademas, te recomiendo que revises que las direccion o "path" que estes utilizando sea correcta. Puedes revisar la materia sobre como hacer referencias a carpetas y archivos, en el modulo de git shell del curso. Alternativamente, como siempre, puedes buscar ejemplos en google y tratar de guiarte por ellos. 

Si llega a ser el caso que no logras solucionar el problema con los pasos que mencione, entonces deberias probar montando el servidor de Python que sale en el enunciado. 
![imagen](https://user-images.githubusercontent.com/21247721/78934371-cea7f780-7a78-11ea-934f-2e769b288f5d.png)

Espero que logres resolverlo y suerte con la tarea!

**Comment by railira** [comment]
Estoy utilizando Chrome y el sistema es windows 10. Ya intenté con la nota y no me dio resultado

**Comment by railira** [comment]
Ya lo logré, gracias.

**Comment by LuisFros** [comment]
Que bueno!
