### ISSUE TITLE
Grafico 3 distinto del enunciado

### ISSUE THREAD

**Issue by Gustav2000** [Exploratorio-DCC-PUC/Syllabus#175]
En el gráfico 3 (dispersión) de Puntaje vs Presupuesto, el enunciado no menciona nada sobre el 'rating', sin embargo en la imagen del gráfico se ven los puntos de colores según el rating. Seguimos el enunciado y en ese caso no colocamos el Ranting?

**Comment by Jiruiz2** [comment]
Hola,
El enunciado manda, es decir, no es necesario que le pongas colores según el rating, aunque esto puede ayudar a ver como se distribuye el presupuesto y el score de mejor manera.
Saludos
