### ISSUE TITLE
Error al crear Data Frame

### ISSUE THREAD

**Issue by Natydlb** [Exploratorio-DCC-PUC/Syllabus#176]
Hola! Al momento de querer crear el Dataframe, me sale el siguiente mensaje
![0960AE00-0B58-45E6-A9CB-1E73313B6379](https://user-images.githubusercontent.com/62019255/78957834-6c6ce800-7ab4-11ea-9aa3-f384095b9967.jpeg)
Arriba igual lo tengo ordenado pero no está como una tabla :(

**Comment by malopez16** [comment]
Hola!
Lo que muestras no es al crear el dataframe, sino al aplicar una operación al dataframe. Tampoco aparece el error completo en el pantallazo que subiste, entonces con esa información no podemos ayudarte mucho :(
