### ISSUE TITLE
No se ven los gráficos en el archivo ipynb

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#177]
Hola, cuando subo al repositorio el archivo ipynb y entro a él por medio de github no se pueden apreciar los gráficos. ¿Hay alguna forma de hacer que se vean?

**Comment by Jiruiz2** [comment]
Hola,
Lo ves directo desde github?

**Comment by AlfreMK** [comment]
Sí, también me pasa con el archivo de la ayudantía de altair. Hay alguna forma de verlo desde otra prte?

**Comment by Jiruiz2** [comment]
Hola, 
No es necesario que se vea desde github, de hecho es probable que no tenga soporte para ese caso. Solo es necesario que se vean los gráficos al correr directamente el programa .ipynb
