### ISSUE TITLE
Sobre el código javascript para la tarea

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#179]
Para implementar el dark mode, ¿Cómo se tiene que subir el código de javascript? Hay que crear una archivo externo de javascript y referenciarlo en html con <script src="codigojava.js"> o hay que escribirlo en el mismo código de html con el sintaxis <script>? O ambas formas son válidas para la tarea?

**Comment by LuisFros** [comment]
Hola! 
Como hemos trabajado durante el curso, la idea es tenerlo en un archivo separado. 
No es un requisito del enunciado, pero seria más ordenado y fácil de corregir para los ayudantes. 
En general es considerado una “buena práctica” tener el código modularizado.
