### ISSUE TITLE
[TG1]  Gráfico de torta

### ISSUE THREAD

**Issue by dlcartagena** [Exploratorio-DCC-PUC/Syllabus#18]
Cuando dice que hay que generar un gráfico de torta con los géneros "más escuchados por el usuario" hay alguna cantidad específica (Top 5, top 10, etc...)?

**Comment by diflores** [comment]
¡Hola!

Como no fue especificado en el enunciado, queda a criterio de ustedes. Recomiendo Top 10.

¡Saludos!
