### ISSUE TITLE
Agregar JS

### ISSUE THREAD

**Issue by fedezang** [Exploratorio-DCC-PUC/Syllabus#180]
Hola, para agregar javascript se pide correr el comando ’python -m http.server’ en la consola, sin embargo el comando no me retorna nada. De igual manera pude agregar javascript a la página. ¿Habría algún problema en no poder ocupar el comando?

**Comment by LuisFros** [comment]
No hay problema @fedezang, 
Si te funciona sin usar el comando de python, es valido tambien.
