### ISSUE TITLE
Error Wikipedia Top 5

### ISSUE THREAD

**Issue by Pablo-Carrasco** [Exploratorio-DCC-PUC/Syllabus#181]
Al aplicar una función a cada elemento del Dataframe del top 5 me arrojaba error  una película en específico, y al aplicar la función 'summery' a esa película, me arroja este error, no sé si es un problema mío, de la API o de otro tipo,  'summery' funciona con las otras 4. Además, noto que se cambia el id respecto del título ingresado a 'summery', es muy raro, no sé qué pasa.
![error-top5](https://user-images.githubusercontent.com/62043814/79054400-7147ae00-7c12-11ea-8795-9993340b1a85.PNG)

**Comment by malopez16** [comment]
Hola!

No podemos darles mucha más información, dado que este problema está considerado como parte de la dificultad de la pregunta, y como algo que uds. deberían resolver. Se puede hacer de varias formas! (#173).
Recuerda también #172 ! En el pantallazo que pusiste hay hardcoding y eso no es lo que se busca.

Saludos!
