### ISSUE TITLE
Error wikipedia 'Forrest Gump'

### ISSUE THREAD

**Issue by jasilvamc** [Exploratorio-DCC-PUC/Syllabus#184]
![ErrorForrestGump](https://user-images.githubusercontent.com/62022671/79055245-8116c080-7c19-11ea-96da-1a4b0641feab.png)
Me aparece este error al buscar el summry de Forrest Gump, pero estoy seguro de que estoy buscando el summary con el nombre correcto de la página de wikipedia (lo busqué a través de la API y usé el resultado que me entregaba como argumento). Pareciera que deja de reconocer que existe una pagina con ese nombre, y transforma la búsqueda de 'Forrest Gump' a 'forest hump'. Esto me pasa cuando el argumento de summary es una variable con el nombre correcto o el nombre directamente como string.

**Comment by Jiruiz2** [comment]
Hola,
Me puedes mostrar de una forma genérica (sin mostrar tu código real) como haces la busqueda?
Saludos

**Comment by jasilvamc** [comment]
Primero uso la función search de wikipedia con el nombre de la pelicula (sacado de movies.csv). Con eso consigo el id de una página de wikipedia, y eso es lo que uso de argumento para summary. Se supone que siempre debiera conseguir un resultado valido con eso, y revisé directamente en la página de wikipedia que el string que usé para summary estuviese correcto. Te puedo enviar el código por interno si es que es necesario

**Comment by malopez16** [comment]
Toda la razón con respecto a este problema! Aclaración en #187 :)
