### ISSUE TITLE
Mes 0, gráfico 4

### ISSUE THREAD

**Issue by Gustav2000** [Exploratorio-DCC-PUC/Syllabus#185]
En el gráfico de la pregunta 4 aparece un 0 en el eje X (supongo que está considerando a las que no tienen mes), pero como dice en el enunciado, no hay que colocar a los que no tienen mes de lanzamiento. Entonces, no tenemos que colocar en el eje X el mes 0, o si?

**Comment by Jiruiz2** [comment]
Hola,
Como dices el mes 0 se le asignó a todas aquellas fechas que no cumplían el formato AAAA/MM/DD, sin embargo como manejar estos datos queda a su criterio.
Saludos
