### ISSUE TITLE
Jupyter problema: permission denied

### ISSUE THREAD

**Issue by pilarjimenez** [Exploratorio-DCC-PUC/Syllabus#186]
Hola, cuando intento crear una notebook nueva en jupyter me sale: "permission denied untitled.ipynb¨. No logra abrir una libreta y las soluciones que encontre son por medio de Anaconda y yo instale Jupyter por un pip.

**Comment by malopez16** [comment]
Hola!,
Debido a esto, como se mencionó en ambas ayudantías anteriores, recomendamos utilizar [Google Colab](https://colab.research.google.com) :)
Saludos!
