### ISSUE TITLE
Tamaño de las imágenes 

### ISSUE THREAD

**Issue by aboehmg** [Exploratorio-DCC-PUC/Syllabus#189]
Hola, 

¿Las imágenes de la página web deben preservar su relación de aspecto? ¿O es suficiente si llenan los 400px de altura **o** de ancho? Tengo problemas para romper la relación de aspecto, ya que haga lo que haga siempre se mantiene igual.

**Comment by LuisFros** [comment]
Hola @aboehmg, 
No estoy seguro si te refieres a que la imagen "se vea bien", eso no un es requisito de la tarea. 
Lo importante para la tarea es que tengan **todas el mismo tamaño**, independiente de que los graficos se vean distorsionados al tenerlos todos del mismo tamaño.

**Comment by aboehmg** [comment]
¡Gracias! Logré solucionar mi duda anterior, pero me surgió otro problema. 
Las dimensiones del gráfico 3 me aparecen distintas. Los gráficos 1, 2 y 4 tienen dimensiones 378x400, mientras que el gráfico 3 tiene dimensiones 400x400, no entiendo por qué pasa esto si el código es el mismo para todos los gráficos. Pareciera ser un problema de mi imagen, pero no entiendo como solucionarlo. (Puedo adjuntar foto si es necesario)

**Comment by LuisFros** [comment]
Hola, 
Usando las reglas de CSS deberias hacer que las imagenes tengan el mismo tamaño. Tu imagen no puede ser el problema dado que con las reglas correctas en CSS, se puede hacer que tengan el mismo tamaño.
![imagen](https://user-images.githubusercontent.com/21247721/79123854-11afe680-7d69-11ea-82b9-0b49a2d020dc.png)

**Comment by aboehmg** [comment]
Adjunto fotos del problema. No mando fotos del código porque asumo que no se puede, pero puedo decir que todas las imágenes están en una misma clase que define el tamaño de las imágenes, el margen y el borde. Al reemplazar el gráfico 3 por otra imagen se soluciona el problema.
De hecho, es aún más raro ahora que estoy intentando sacar la foto. La imagen parte del tamaño correcto (foto 1), pero cuando inspecciono el elemento cambia su tamaño (foto 2).
![Foto 1](https://user-images.githubusercontent.com/62244385/79130155-7a509080-7d74-11ea-8f68-310a00cc3223.JPG)
![Foto 2](https://user-images.githubusercontent.com/62244385/79130170-80467180-7d74-11ea-95cd-fd31c1ff4198.JPG)

**Comment by LuisFros** [comment]
Hola de nuevo,
Cuando inspeccionas el código, el tamaño de la pantalla cambia y por eso el tamaño de la imagen es distinta. (Están dentro de un contenedor flex).
Debes revisar tus propiedades CSS para que el tamaño de las imágenes sean iguales **sin importar el tamaño de la pantalla**

**Comment by aboehmg** [comment]
Hola Luis,
Una aclaración. El tamaño de las imágenes se mantuvo para todas, menos para el gráfico 3. Las dos imágenes que saqué fueron en pantalla completa. Es como si el tamaño de la imagen del gráfico 3 se hubiera cambiado al inspeccionar un elemento de la página porque está se actualizó. De cualquier manera intentaré ver si no hago que sean flex los contenedores de las imágenes y si así soluciona mi problema. Sería más fácil mostrar en vídeo lo que pasa, pero no puedo hacerlo rápidamente ahora. 
En el peor de los casos si no lo he solucionado hasta el miércoles pregunto por discord.
¡Gracias por tus rápidas respuestas!

**Comment by aboehmg** [comment]
Update: Logré solucionar el problema sacando el contenedor flex donde había puesto las imágenes. Aún así me parece muy raro lo que pasaba antes (que solo haya pasado con una imagen), así que si averiguas por qué pasaba eso igual me gustaría saberlo.

**Comment by LuisFros** [comment]
Ok. Ojo que debe ser un contenedor flex como dice en el enunciado.
La razón de lo que te esta pasando es parte de la dificultad de resolver el problema. Responderte eso seria darte parte de la solución de la tarea.
