### ISSUE TITLE
Ubicacion dataset?

### ISSUE THREAD

**Issue by naquiroz** [Exploratorio-DCC-PUC/Syllabus#19]
Hola! La carpeta con los datos para la primera parte se encuentra en el directorio padre de la `parte 1` y por ello mi pregunta es.
Como accedemos a el? Usando la libreria os para cambiar el path? O la movemos a parte1? O alguna otra solucion?
Saludos.

**Comment by figarrido** [comment]
Hola, con la librería pandas puedes ingresar el path donde se encuentra el dataset (puedes usar lo aprendido en la tarea pasada :wink: para entregar un path relativo).
