### ISSUE TITLE
No logro centrar el texto

### ISSUE THREAD

**Issue by Bea2000** [Exploratorio-DCC-PUC/Syllabus#190]
Hola! Me pasa que el anunciado pide que el body sea un contenedor flex pero al hacer eso no logro centrar mi texto, he tratado con más de una función y no pasa nada. En cambio cuando le quito el "display: flex" al body me funciona fácilmente.

**Comment by LuisFros** [comment]
Hola! 
Es posible hacerlo solo con las propiedades de flexbox que se revisan en el video de ayuda y revisando la pagina de FlexBox que esta en el enunciado (https://css-tricks.com/snippets/css/a-guide-to-flexbox/) .
