### ISSUE TITLE
Nota final en la parte del bonus

### ISSUE THREAD

**Issue by nnovoag** [Exploratorio-DCC-PUC/Syllabus#191]
hola queria saber si era muy importante lo de "python -m http.server"porque lo hice sin querer en la carpeta indebida y ya cuando lo hice en la carpeta correcta me aparecia "OSError: [Errno 48] Address already in use"

**Comment by LuisFros** [comment]
Hola!
Primero te recomiendo revisar esta issue que ya fue respondida: #180 
El proposito de ese comando es poder usar JavaScript cuando no les funciona directamente en el buscador.
![imagen](https://user-images.githubusercontent.com/21247721/79124012-6bb0ac00-7d69-11ea-8f45-44fae5855981.png)
