### ISSUE TITLE
sacar películas sin mes

### ISSUE THREAD

**Issue by sbmirandap** [Exploratorio-DCC-PUC/Syllabus#192]
estoy un poco confundida, en la pregunta 4 transforme las fechas a to_datetime y hice otro df con los meses de ese, no se cuales son las películas que no tienen mes de lanzamiento, en el nuevo df estarían las películas sin meses también? que quizás por no tener mes se convierten automáticamente en enero (01)? no se si están o no :(

**Comment by malopez16** [comment]
Hola!
Lo que podrías hacer es aplicar esas operaciones sobre un rango de películas, y también imprimir lo que pasa en ese mismo rango.
También podrías analizar la data para ver si tiene basura entremedio, y para ver cuál sería a tu juicio el mejor filtro a implementar.
Recuerda también que al imprimir un dataframe, te dice la cantidad de elementos en él. Ese también es un buen indicador.

Saludos,
Mauricio
