### ISSUE TITLE
[Parte 1] [Pregunta 3] Aclaración enunciado

### ISSUE THREAD

**Issue by malopez16** [Exploratorio-DCC-PUC/Syllabus#194]
Hola,
Para la pregunta 3 de la tarea, se busca que den una breve respuesta a la pregunta propuesta, simplemente analizando el gráfico solicitado.
Saludos!

**Comment by fbesoainp** [comment]
a que se refiere con "un texto alternativo que sea igual al titulo de cada grafico"?
y donde se debe responder la pregunta?

**Comment by malopez16** [comment]
@fbesoainp esta Issue es acerca de la pregunta 3 de la parte 1. Si tienes una consulta acerca de otra pregunta, por favor abre otra issue para que tus compañeros puedan encontrarla de manera más fácil.  

En cuanto a la pregunta a responder en la parte 3, pueden responderla como un comentario de código (con los # ), o también pueden poner una caja de texto en la pregunta 3, y dar una breve explicación.  

Se espera una explicación **breve, de no más de 2 líneas.**
