### ISSUE TITLE
Contenedores de imágenes

### ISSUE THREAD

**Issue by Gustav2000** [Exploratorio-DCC-PUC/Syllabus#196]
![image](https://user-images.githubusercontent.com/62355739/79400358-ffde6700-7f53-11ea-9116-12ec92975daa.png)

A que se refiere con los contenedores de imágenes? Tienen que ser tipo item o se refiere a la imagen en si misma?

**Comment by malopez16** [comment]
Hola!
Puedes encontrar la respuesta en el material del curso: 
https://cursos.canvas.uc.cl/courses/5501/modules/items/183735

Saludos!
