### ISSUE TITLE
Bonus: como obtener puerto del servidor

### ISSUE THREAD

**Issue by allisonaguilar** [Exploratorio-DCC-PUC/Syllabus#197]
hola! el comando pyhon -m http.server no me retorna nada, ya leí las issues anteriores pero mi duda es como completar el siguiente paso:

 Luego, en tu navegador debes colocar la URL ’localhost:XXXX/YYYYY.html’, don- de ’XXXX’ es el puerto del servidor y ’YYYYY’ es el nombre del archivo HTML.

si no logro que retorne el puerto del servidor?

**Comment by Jiruiz2** [comment]
Hola,

Me puedes mandar un pantallazo de lo que ocurre en tu consola al momento de correr el código?

Saludos
