### ISSUE TITLE
Problemas Pregunta Bonus

### ISSUE THREAD

**Issue by pascual1** [Exploratorio-DCC-PUC/Syllabus#198]
El código js no me funciona cuando viene del documento que escribí pero al escribirlo en la consola del navegador si. Estoy trabajando desde el local host con el código del cmd y nada.

**Comment by LuisFros** [comment]
Hola, podrías probar si te funciona la solución del practico II? Eso te ayudará a identificar si el problema esta con tu código o si es algo particular de tu computador.

[https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Ayudant%C3%ADas/Solucion%20Practico%20Web%20II](https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Ayudant%C3%ADas/Solucion%20Practico%20Web%20II)

**Comment by pascual1** [comment]
Ya encontré una solución, gracias
