### ISSUE TITLE
Cantidad de commit 

### ISSUE THREAD

**Issue by Bea2000** [Exploratorio-DCC-PUC/Syllabus#199]
Hola! Quería saber si tenía que subir toda la tarea como un commit o subir un commit por cada parte.
Muchas gracias de antemano!

**Comment by Jiruiz2** [comment]
Hola,

Para esta tarea no hay mínimo ni máximo de commits. De todas maneras se recomienda siempre que vayas subiendo commits apenas terminas alguna parte con el fin de evitar errores futuros. 

Saludos
