### ISSUE TITLE
TC1 - nano

### ISSUE THREAD

**Issue by colorostrobl** [Exploratorio-DCC-PUC/Syllabus#2]
¿Está permitido, para hacer cambios en archivos, utilizar el text editor nano?

**Comment by Pyralspite** [comment]
Hola!
No está permitido utilizar ningún editor de texto para modificar los archivos, deben hacerlo todo mediante comandos.

Saludos c:

**Comment by TriniVial** [comment]
cuando copio el link de mi perfil de Codecademy y despues me meto me dice que esta terminado pero si reviso lo que escribí, está todo en blanco. Lo tendría que hacer denuevo?
el tutorial se hace hasta el paso nueve?

**Comment by perezpefaur** [comment]
Entonces lo que aprendimos con nano del tutorial no sirve para la tarea?
Es que nano se puede abrir mediante comandos y como estaba en el tutorial, pensé que se podía ocupar.
(perdon si suena repetitiva la pregunta)

**Comment by dvaldesl** [comment]
Concuerdo contigo perezpefaur, tambien tenia entendido que se podia usar nano. ¿pueden especificar mejor eso?

**Comment by StroveLight** [comment]
Entonces se puede usar un editor de texto para hacer los comandos los cuales modifiquen los archivos?

**Comment by Pyralspite** [comment]
Hola,
Pueden usar un editor de texto para hacer el informe. No pueden usar un editor de texto (ni siquiera nano) para modificar los archivos de texto.
