### ISSUE TITLE
Ejecutar start.py

### ISSUE THREAD

**Issue by valeeeriquelme** [Exploratorio-DCC-PUC/Syllabus#2]
Al tratar de ejecutar start.py me aparece "bash: python: command not found", que puede estar fallando?

**Comment by aaossa** [comment]
Hola, tienes Windows? Si es así, seguramente no tienes Python 3 en el PATH. Para confirmar esa teoría necesito que revises si puedes usar el comando python en la consola (cmd) 🤔 Si no puedes avanzar hoy con esto, mañana en la ayudantía podemos ayudarte!

**Comment by valeeeriquelme** [comment]
Ya lo pude resolver, muchas gracias :)
