### ISSUE TITLE
Cual es la diferencia, pregunta 8

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#20]
El enunciado dice:
![image](https://user-images.githubusercontent.com/48262438/63228718-fc2bf200-c1c4-11e9-8831-e241e97dbbda.png)
Cual es la diferencia entre:
1) Muestra el comando con el cual puedes visualizar lo que dice la tarjeta
2) Además muestra los comandos de las instrucciones correspondientes
a la tarjeta
La verdad que lo encuentro un poco redundante

Ya entendi! En dos hay que escribir los comandos para cambiar los creditos. Lo dejo aca por si alguien tiene la misma duda.

**Comment by ValentinaAlvarezG** [comment]
Para la primera parte, debes mostrar en la consola lo que dice la tarjeta y eso es un comando.
Para la segunda parte, debes seguir la instrucciones de la tarjeta (no recuerdo que era) pero por ejemplo aprobar un curso, devolver una ayudantia, etc... Estos pueden ser mas de un comando.

Exactamente lo que dices abajo
