### ISSUE TITLE
[Manejo de datos] - ¿Cómo puedo optimizar el uso de estos?

### ISSUE THREAD

**Issue by VicenteVicenteVicenteVicenteVicente** [Exploratorio-DCC-PUC/Syllabus#20]
Para efectuar los gráficos, se pide obtener los "X" más frecuentes, pero el código que nos sirve para efectuar esto, entrega un output el cual no sé como insertarlo directamente en una función de matplotlib. Hasta ahora lo he hecho manualmente (Obtener los datos, copiarlos y pegarlos uno por uno). ¿Es este método el esperado, o hay uno más eficaz? 🤔 😨

**Comment by diflores** [comment]
Hola, Vicente (qué buen *username*),

Copiar los datos uno por uno definitivamente no es lo que se espera. Investiga sobre cómo entregar columnas de un ```DataFrame``` a un *plot* en ```matplotlib```. Hay varios ejemplos en internet.

¡Saludos!

**Comment by VicenteVicenteVicenteVicenteVicente** [comment]
¡Muchas gracias Dani! 😸
