### ISSUE TITLE
[Git shell] Como eliminar un archivo de github

### ISSUE THREAD

**Issue by magdalenanario** [Exploratorio-DCC-PUC/Syllabus#200]
Hola! Queria saber como eliminar un archivo de mi repositorio de github, ya que le queria hacer un par de cambios

**Comment by Jiruiz2** [comment]
Hola,

Solo debes eliminarlo en tu repositorio local (carpeta) y subir los cambios con git add, commit y push.

Saludos

**Comment by magdalenanario** [comment]
Ayer al intentar borrarlo, apreté el signo de un basurero que salia al lado del archivo que queria borrar y se guardo un commit en el que salia 'deleted'. ¿Importa que ese commit quede guardado?
y ahora hice lo que tu me dijiste y me aparece esto
![image](https://user-images.githubusercontent.com/62227994/79576463-51d8d700-8091-11ea-9382-36c74d048c7f.png)

**Comment by LuisFros** [comment]
Hola @magdalenanario ,
**Explicacion:**
Lo que te esta diciendo el mensaje en consola es que los archivos que estan en Github son distintos a los que tienes localmente en tu computador.

Dado que borraste el archivo apretando el icono de la "basura", lo que hiciste fue borrar el archivo en Github.
Al borrarlo el github, los archivos que tienes en tu local estan distintos a los que estan en github. Por eso dice "**the remote contains work that you do not have locally**"

**Solucion:**
Existen muchas maneras de solucionarlo, existe una manera facil de solucionarlo y ojala sea tu caso.

---

_Solucion facil_:
1. Traer los cambios de Github a tu local:
```
git pull
```





(Si no te funciona la solucion facil, seguimos a una no tan facil)

----

_Solucion menos facil_:

Para solucionarlo, tienes que hacer 2 cosas:
1. Guardar los cambias que tengas localmente, ese commit que hiciste.
2. Traer los cambios que hiciste en github (el archivo que borraste al apretar el boton)


Antes de empezar, te recomiendo hacer una copia local de tu carpeta. Copy+Paste de tu carpeta en otro lugar (como tu escritorio) para estar seguros de que no pierdas tus datos.


1. Asegurate que no tienes mas cambios locales sin "commitear". Debes responder: todos mis cambios estan dentro del commit que hice?
2. Ahora tienes que guardar los cambios que hiciste para poder traer los cambios de github, por lo que debes sacar los cambios del commit corriend el siguiente comando: 
```
git reset --soft HEAD~1
```
(Lo que hace este comando es borrar el mensaje de tu commit, pero manteniendo los cambios en tu local. No vas a perder tus datos al correr este comando). 
3. Ahora debes correr el siguiente comando:
```
git stash
```
(Este comando guarda todos los cambios que estaban en tu commit en un lugar)
4. Ahora puedes traer los cambios que hiciste en github.
```
git pull
```
(Esto va a traer los cambios que estan en Github a tu local, que en este caso va a ser el archivo que borraste).
5. Ahora vamos a aplicar los cambios que tenias antes,
``` 
git stash pop

```
6. Ahora si puedes hacer lo tipico de siempre (`add` `commit` y `push`) y no deberias tener mas problemas.

**Comment by magdalenanario** [comment]
ya perfecto
En la manera facil hay que hacer git pull y despues de nuevo git add, commit y push cierto?
![image](https://user-images.githubusercontent.com/62227994/79580751-7a63cf80-8097-11ea-9861-ce130edc1ec5.png)

**Comment by LuisFros** [comment]
(La imagen no se puede ver bien) Pero si debes hacer add, commit y push despues.

**Comment by magdalenanario** [comment]
![image](https://user-images.githubusercontent.com/62227994/79582113-543f2f00-8099-11ea-81aa-a3e09cdec1f0.png)
Esa era la imagen
Eso significa que el git pull funcione bien cierto?

**Comment by LuisFros** [comment]
No. No funciono bien, justo modificaste el archivo que borraste en github. Entonces tienes que decidir que hacer ahora, ese archivo lo puedes borrar ("Parte1y2.ipynb")?

**Comment by magdalenanario** [comment]
si si puedo
intento la solucion menos facil entonces?

**Comment by LuisFros** [comment]
Antes de pasar a la menos facil,creo que ahora pudes hacer `add` `commit` `push` y deberia resolver el problema.

**Comment by magdalenanario** [comment]
![image](https://user-images.githubusercontent.com/62227994/79584042-d597c100-809b-11ea-8769-ff70bc6a7482.png)
en el git commit que mensaje pongo? Para que quien corrija mi tarea entienda lo que paso

**Comment by LuisFros** [comment]
Un mensaje que diga de manera **concisa** lo que te explique detalladamente en mi primera respuesta.

**Comment by LuisFros** [comment]
@magdalenanario Parece que si funciono. Una manera de asegurarse que no tengas mas cambios locales es con el comando :
```
git status
```
https://git-scm.com/book/es/v2/Fundamentos-de-Git-Guardando-cambios-en-el-Repositorio#r_checking_status

**Comment by magdalenanario** [comment]
Muchas graciass!
