### ISSUE TITLE
Que es eso de margin responsive 5%?

### ISSUE THREAD

**Issue by airiquelme** [Exploratorio-DCC-PUC/Syllabus#201]
He buscado por internet y francamente no parezco encontrar nada que use porcentajes... cual es el atributo o parametro o cuestión flex para eso? si me dicen "busca flex-responsive en google" me sirve, porque solo buscando "responsive" no encuentro nada. gracias

**Comment by LuisFros** [comment]
Hola @airiquelme , la idea de usar porcentajes se usa en paginas responsive. La explicacion y aplicacion de paginas responsive va mas alla de esta tarea, si quieres saber mas sobre ese tema: https://en.wikipedia.org/wiki/Responsive_web_design

La razon de la palabra "responsive" es para guiar que el margen debe ser 5% para todos los tamaños de las pantallas. 
Para que quede claro y no cause confusiones: 
- Para responder esa instruccion, **solo deben agregar un valor adecuado a la propiedad de margen**.
-  No es necesario modificar nada de flexbox o nada mas complejo que eso
