### ISSUE TITLE
Git add de .ipynb

### ISSUE THREAD

**Issue by pilarjimenez** [Exploratorio-DCC-PUC/Syllabus#202]
Cuando hago git add me dice:
LF will be replaced by CRLF in .ipynb

Debo cambiar algo?

**Comment by malopez16** [comment]
Hola,
No te preocupes por eso.
De todas formas, puedes recrear lo que hará el ayudante para revisar tu tarea, para estar tranquila:
1) Sube tu .ipynb a tu repo
2) Crea una carpeta en tu pc
3) Clona tu repo en esa carpeta
4) Abre google collab, y sube el archivo .ipynb ahí.
5) Si se ve todo bien, no hay ningún problema. El ayudante segirá este procedimiento, así que debería ver lo mismo que tú estás viendo.

Saludos!
