### ISSUE TITLE
Duda E/R TC2

### ISSUE THREAD

**Issue by furzuadr** [Exploratorio-DCC-PUC/Syllabus#203]
Hola! 
Para la TC2, puedo agregar atributos extras? Que considero que podrían ser buenos PK, o sólo se puede trabajar con los que dan en el enunciado?
Gracias!

**Comment by gatochico** [comment]
Hola! 

Puedes agregar atributos extra a las entidades si así lo deseas (recuerda agregarlo en supuestos!). Si haces que tu PK sea un atributo que no esté en el enunciado, eso si, indica en el README una justificación de porqué ninguno de los otros atributos sería un buen candidato a llave. Finalmente, recomiendo leer con detalle el enunciado y ver si realmente necesitas un atributo extra como primary key para alguna entidad, o si es posible obtener una de los datos ya entregados.

Éxito!
