### ISSUE TITLE
Selección de columnas en parte II TC2

### ISSUE THREAD

**Issue by boltibolti** [Exploratorio-DCC-PUC/Syllabus#206]
hola, pasa que intento seleccionar varias columnas de distintas tablas y me aparecen errores 
![2020-04-18 (5)](https://user-images.githubusercontent.com/62029353/79676468-9610c800-81b4-11ea-8c95-9e5b9d690633.png)
![2020-04-18 (3)](https://user-images.githubusercontent.com/62029353/79676469-990bb880-81b4-11ea-8960-f4dc5f6837bd.png)
busqué en google pero salía que lo hacían con tabla.atributo ¿Como se hace?

**Comment by ValentinaAlvarezG** [comment]
Hola!, no entiendo por qué pones COLUMN. Para hacer la consulta haces 
SELECT tabla.atributo FROM tabla;
