### ISSUE TITLE
Sobre las cardinalidades del diagrama E/R

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#207]
Hola, con respecto a las cardinalidades, estas no aparecen en la clase de base de datos, así que no sé de que forma de todas las que tiene tendría que usar para representarlas. ¿Con un paréntesis al lado de la relación (ej: (1:N))?, ¿Que la cardinalidad esté en cada línea que conecte las relaciones y entidades, si es en ese caso, que tipo de línea? ¿O cualquiera está bien?

**Comment by gatochico** [comment]
Hola! 
Para anotar las cardinalidades puedes usar cualquier tipo de notacion de las que existen para los diagramas E/R. Si utilizas las notaciones con números/letras como las que indicaste anteriormente, debes utilizar una línea simple como a continuación:
![image](https://user-images.githubusercontent.com/37161120/79680282-05e67900-81dc-11ea-8a3b-be95ea0bd4d1.png)

Las lineas con símbolos en sus extremos son otro tipo de notación, cuyo significado sería:
![image](https://user-images.githubusercontent.com/37161120/79680349-bf454e80-81dc-11ea-8d42-69831caf1735.png)

Puedes usar la que más te acomode en tu diagrama!

**Comment by Francisco-Morales-R** [comment]
En este caso, si ocupamos lineas con símbolos ¿Es necesario darle un nombre a la relación?. En el caso de que sí, ¿Se lo agregamos en un texto simple?

**Comment by gatochico** [comment]
Hola! (disculpa la demora)

Si se ocupan las líneas con simbolos, también se deben usar los rombos para denominar la relación. La unica diferencia es que ahora en vez de números en los extremos que unen a cada entidad irán los simbolos.
