### ISSUE TITLE
Pregunta sobre el enunciado (parte 1)

### ISSUE THREAD

**Issue by Bea2000** [Exploratorio-DCC-PUC/Syllabus#208]
En la parte 1 el enunciado menciona que las obras pueden ser representadas por varias compañías teatrales pero no nos da a entender si las obras pueden no ser representadas por alguna compañía y si pueden ser representadas por solo una.

**Comment by gatochico** [comment]
Hola! Una obra puede ser representada por ninguna, una o más compañías.

**Comment by Bea2000** [comment]
Muchas gracias!
