### ISSUE TITLE
Cardinalidad en relación múltiple

### ISSUE THREAD

**Issue by fedezang** [Exploratorio-DCC-PUC/Syllabus#209]
Hola, quería saber cómo expresar la cardinalidad en una relación múltiple, en el caso de que la cardinalidad fuera distinta para cada par de entidades en la relación.

**Comment by ValentinaAlvarezG** [comment]
Hola! A que te refieres con una relación múltiple? Las relaciones, por lo que menos las que nosotros les pedimos, son relaciones entre dos entidades por lo que puedes usar la notación 1:1, 1:N, N:N como se muestran en el material de apoyo.

**Comment by fedezang** [comment]
![Captura de Pantalla 2020-04-19 a la(s) 18 10 55](https://user-images.githubusercontent.com/62078222/79701212-27da0d00-8269-11ea-8010-63fe8a1e7301.png)
En el caso de tener algo así

**Comment by ValentinaAlvarezG** [comment]
No deberías tener algo así. La tarea está pensada para relaciones entre dos entidades solamente. Te recomendaría darle otra vuelta a lo que estás tratando de modelar. Y si no, puedes preguntarlo por acá.

**Comment by fedezang** [comment]
Muchas gracias!
