### ISSUE TITLE
Prueba gratis tarjeta de crédito en cuenta nueva

### ISSUE THREAD

**Issue by jitorralba** [Exploratorio-DCC-PUC/Syllabus#21]
Hola! Pasa y resulta que me acabo de crear otra cuenta de codecademy con distinto mail y todo, y acepte los 7 días de prueba justo cuando cree la cuenta, pero aún así me pide registrar una tarjeta de crédito. Así que no se que hacer.

**Comment by Pyralspite** [comment]
Hola, revisa tu correo c:
