### ISSUE TITLE
Relaciones en el diagrama E/R

### ISSUE THREAD

**Issue by gecoli** [Exploratorio-DCC-PUC/Syllabus#210]
¿Es necesario poner nombres descriptivos a las relaciones? ¿o podemos colocar cualquiera para identificarlos? algo así como, ¿cómo saber si los nombres son los que se esperan?

**Comment by ValentinaAlvarezG** [comment]
Hola! Si, la idea es que sean descriptivos.

**Comment by gecoli** [comment]
¡Muchas gracias! Aparte, ¿deben tener sus propios atributos (como la figura 1 en el Material de Apoyo)?

**Comment by ValentinaAlvarezG** [comment]
Eso depende de la relación, si es que tiene atributos extra. Pues, se entiende que la relación "hereda" los atributos que son primary key de las entidades que relaciona, por lo que no es necesario ponerlas. 

En el caso de la figura 1, la relación participa tiene como atributos tid (ID del trabajador), pid (ID del proyecto), inició_participación y fin_participación. Pero los primeros dos no se ponen como atributos, en cambio si los otros dos que son como propios de la relación.

Entonces una relación puede perfectamente no tener más atributos, pero si los tiene, deben ponerse.

**Comment by gecoli** [comment]
¡Okay, muchas gracias!
