### ISSUE TITLE
TC2 Parte II

### ISSUE THREAD

**Issue by gecoli** [Exploratorio-DCC-PUC/Syllabus#211]
En la consulta 2, ¿hay que sacarle pantallazo a toda la tabla, independiente de que las obras se repitan y/o los lugares se repitan?

**Comment by ValentinaAlvarezG** [comment]
Hola! Si no me equivoco, no deberían repetirse. Lo que sí puede pasar es que hay muchas obras que se llaman igual, por ejemplo, la anunciación tiene varios autores, entonces son diferentes anunciaciones, así que deberían verse todas.
Si mal no recuerdo, los resultados de las tablas no son tan largos por lo que debería caber en pantalla toda la respuesta. Puede que en alguna haya que agrandar la parte de la tabla si no quieres sacar dos pantallazos.
No se si respondi tu duda jajaja

**Comment by gecoli** [comment]
¡Sí, lo hiciste! Muchas gracias
