### ISSUE TITLE
Parte II: Consulta 5

### ISSUE THREAD

**Issue by Baelfire18** [Exploratorio-DCC-PUC/Syllabus#212]
Hola, me salen multiples autores para las diferentes obras en en la 5 de la parte ii.
Es esto posible con la base de datos dada? O estoy cometiendo un error?
Lo curioso es que me calzan los aid y oid (⊙＿⊙')
Gracias

**Comment by ValentinaAlvarezG** [comment]
Hola, whaaat, me puedes mandar un pantallazo de lo que te sale como resultado?

**Comment by Baelfire18** [comment]
![borrar](https://user-images.githubusercontent.com/50716449/79715495-d69a3f80-82a1-11ea-9adf-b9efb5b52b2e.png)

Le puse en la tabla el aid y el oid de cada tabla respectiva, por si acaso y me dan igual. Estoy haciendo algo mal? O los datos son asi?

**Comment by ValentinaAlvarezG** [comment]
A ver la idea de la consulta es que agrupes la información de los artistas por el artista, entonces por ejemplo para Rafaello deberías juntar todas sus obras y contarlas. Entonces el resultado debería ser por ejemplo 1 Rafaello Sanzio 4, porque su id es 1 y tiene 4 obras. Y esto tienes que hacer para todos los artistas que tengan 3 o más obras. Entonces a tu consulta le faltan más cosas para que te de el resultado. 

Si sigues con dudas, mándame un mail (vjalvarez@uc.cl) con la consulta que estás intentando ahora y te puedo guiar un poco más sobre lo que te falta.

**Comment by Baelfire18** [comment]
Si, si lo sé que el resultado me pide el número de obras por artista. Pero lo estaba haciendo “por partes”, primero agrupó los artistas y sus obras, luego sacó el número y luego ordenó.
Pero como me tiro esta respuesta, no quiero seguir porque creo que puede persistir este error más adelante y se cuenten obras 2 o más veces para diferentes artistas.
Se debería corregir este error más adelante o yo estoy haciendo algo mal?

**Comment by ValentinaAlvarezG** [comment]
Aaaah espera, te refieres a que hay más de un artista que participa en la obra? onda que por ejemplo Da vinci y Verrocchio hacen la anunciación? y lo mismo con el Bautismo de Cristo?

**Comment by Baelfire18** [comment]
Si

**Comment by ValentinaAlvarezG** [comment]
Aaaaaah, sisisi, está bien. Por que en una obra puede haber participado más de un artista.

**Comment by Baelfire18** [comment]
Ya buena grax
