### ISSUE TITLE
Duda sobre cómo descargar postgreeSQL

### ISSUE THREAD

**Issue by Natydlb** [Exploratorio-DCC-PUC/Syllabus#213]
Hola! Descargue PostgreSQL pero nose como abrirlo puesto que me sale así 
![0D5464AE-12F9-44C4-8434-6CCB536E07D7](https://user-images.githubusercontent.com/62019255/79773289-45f24c80-82ff-11ea-8a5e-3ba69eededed.jpeg)
Y dentro de la carpeta Documentation me sale esto 
![image](https://user-images.githubusercontent.com/62019255/79773378-65897500-82ff-11ea-97a6-48925933c1c9.jpg)
La aplicación la descargue de postgresql.org, como me podría meter a Postgree?

**Comment by ValentinaAlvarezG** [comment]
Hola! c: para la tarea deberías usar sqliteonline, no es necesario que instales nada.
