### ISSUE TITLE
Otra duda de enunciado TC2

### ISSUE THREAD

**Issue by ian-fell** [Exploratorio-DCC-PUC/Syllabus#214]
En el enunciado se menciona que una compañía puede estar representando 1 o más obras a la vez en un momento. También se menciona que cada compañía es dueña única de su teatro en donde se representan las obras. Lo que no me queda claro es; si una compañía esta representando más obras a la vez, es porque es dueña de múltiples teatros en donde se representa solo una obra? O la compañía es dueña de un único teatro en donde se puede representar más de una obra a la vez?

**Comment by ValentinaAlvarezG** [comment]
Hola! Existe algo que se llama Relax Relational Algebra Calculator. Pero tampoco lo conozco mucho y tendría que averiguar como podrían cargar el .db que les subimos a esa plataforma. Pero si quieres puedes buscar y probar ahí con los dataset de la página para ver si entiendes bien como se usan los operadores. 

En todo caso, si entiendes bien como se usan los operadores, no debería costarte mucho hacer las consultas. Cualquier cosa pregunta por las issues :)

**Comment by ian-fell** [comment]
Hola, creo que esta respuesta es para el issue de arriba :)

**Comment by ValentinaAlvarezG** [comment]
Ay si, perdón! Con respecto a tu duda, la compañía es dueña de un único teatro. Por otro lado, la compañía puede representar más de una obra a la vez. No se si te aclara la duda.

**Comment by ian-fell** [comment]
Eso quiere decir que aquel teatro puede representar más de una obra a la vez?

**Comment by ValentinaAlvarezG** [comment]
Claro, si lo quieres ver así. Pero ojo que no es el teatro el que representa la obra sino que es la compañía.
