### ISSUE TITLE
Consultas en álgebra relacional

### ISSUE THREAD

**Issue by aboehmg** [Exploratorio-DCC-PUC/Syllabus#215]
Hola,

¿Hay alguna manera de hacer las consultas en SQL Online usando álgebra relacional? ¿O tenemos que escribir la consulta sin poder probarla para el bónus?

**Comment by ValentinaAlvarezG** [comment]
Hola! Existe algo que se llama Relax Relational Algebra Calculator. Pero tampoco lo conozco mucho y tendría que averiguar como podrían cargar el .db que les subimos a esa plataforma. Pero si quieres puedes buscar y probar ahí con los dataset de la página para ver si entiendes bien como se usan los operadores.

En todo caso, si entiendes bien como se usan los operadores, no debería costarte mucho hacer las consultas. Cualquier cosa pregunta por las issues :)

**Comment by aboehmg** [comment]
¡Muchas gracias! Veré que logro hacer.
