### ISSUE TITLE
Obras con el mismo nombre

### ISSUE THREAD

**Issue by franciscogazitua** [Exploratorio-DCC-PUC/Syllabus#217]
Hola, existen dos obras que tienen el mismo nombre y ocurren en el mismo lugar, pero tienen distintos años de inicio y termino y distintos periodos ¿Estas obras se deben considerar como dos obras distintas o deben ser agrupadas la una con la otra?
![La anunciación](https://user-images.githubusercontent.com/62035562/79809986-ea947e80-833f-11ea-974e-4b8068593051.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! Son obras distintas

**Comment by franciscogazitua** [comment]
Muchas Gracias
