### ISSUE TITLE
Duda parte 2: código utilizable

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#218]
Hola , tengo una duda.

En la parte 2 de la tarea, ¿solo se puede hacer uso de los códigos que están en el material de apoyo, o se puede utilizar código extraído de Internet?

**Comment by ghost** [comment]
``

**Comment by ValentinaAlvarezG** [comment]
Hola! Puedes usar material externo. Es una buena práctica igual poner el link de donde sacaste la información extra.
