### ISSUE TITLE
Duda Conversión a pdf Parte 1

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#219]
Hola.

Resulta que al exportar mi diagrama a pdf, este me queda divido en varias paginas por su extensión horizontal. ¿Está bien así, o tiene que quedar todo el diagrama en una sola pagina de pdf?

**Comment by gatochico** [comment]
Hola! Por temas de corrección lo ideal es que quede en una sola página. Lo que puedes hacer es al momento de exportar ir a **File > Export as > Advanced** y te aparecerá un cuadro así:

![image](https://user-images.githubusercontent.com/37161120/79887636-33444a00-83c9-11ea-9b28-219c506d53e7.png)


Cambias el formato para que sea PDF, y vas modificando el valor del recuadro zoom hasta que tu diagrama quepa todo en 1 página.

**Comment by rmena0203** [comment]
Hola, yo tengo el mismo problema. Estoy trabajando desde un mac y no me sale la opción "advanced" cuando pongo "exportar como". La solución que encontré fue exportarlo como png, donde si me permitía editar el zoom, y luego exportar esa imagen .png en formato .pdf. El problema es que al pasar la imagen a pdf se baja mucho la calidad del diagrama, a tal punto que hay algunas palabras que no se leen con total facilidad (aunque igual se pueden leer). Quisiera saber si está bien y lo dejo así, o hay alguna otra solución para poder exportar el diagrama en formato .pdf directamente. Muchas gracias!
