### ISSUE TITLE
problema starter code

### ISSUE THREAD

**Issue by AgustinZalaquett** [Exploratorio-DCC-PUC/Syllabus#22]
cuando pongo el link de la tarea se empiezan a cargar dos archivos, uno que crea el repositorio y otro que importa el starter code, lo que pasa es que ese segundo nunca termina de cargar por lo que no puedo empezar a hacer la tarea. Lo he dejado dias cargando  y no pasa nada

**Comment by IchottMano** [comment]
Hola!
Esto se habló en la issue #5 
Saludos!
