### ISSUE TITLE
tc2, pregunta 5 sql

### ISSUE THREAD

**Issue by PipeOlivares** [Exploratorio-DCC-PUC/Syllabus#220]
Buenas, 
Cuando cuento el numero de obras que tiene cada artista, me entrega un numero que es el numero real multiplicado por 105. Eso significa que para poner la segunda condicion que es que el conteo sea mayor que 3, me funciona pero solo si divido por 105...
![Captura de pantalla (33)](https://user-images.githubusercontent.com/62343412/79939670-b1d2d300-842d-11ea-8fd6-3942a9a120e7.png)
Tienen alguna idea de porque me esta ocurriendo esto (y tan especificamente con el numero 105) y quizas como poder solucionarlo?

-F

**Comment by ValentinaAlvarezG** [comment]
Hola! Que raro jajaja mándame un mail a vjalvarez@uc.cl con la consulta que estás intentando para ver que onda
