### ISSUE TITLE
Pregunta cardinalidad parte 1 tc2

### ISSUE THREAD

**Issue by camigervasoni** [Exploratorio-DCC-PUC/Syllabus#221]
Hola!, tengo una pegunta, como podria representar, en la representación con letras y numeros, una cardinalidad que en un extremo puede ser 1, o más? como una letra nomas, o despues tendria que definir la letra o algo así. Adjunto foto de como habrian dicho que se podia representar con lineas.
![Captura de Pantalla 2020-04-23 a la(s) 17 19 45](https://user-images.githubusercontent.com/62357375/80150854-1e151a00-8587-11ea-8888-aac1b1e3a055.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! Puedes usar 1..N en ese lado.

**Comment by camigervasoni** [comment]
muchas gracias!, pero tengo que ponerle parentesis o algo?

**Comment by ValentinaAlvarezG** [comment]
No! no necesitas paréntesis. Sólo pones 1..N
