### ISSUE TITLE
Duda sobre entrega parte dos

### ISSUE THREAD

**Issue by Natydlb** [Exploratorio-DCC-PUC/Syllabus#222]
Hola! Lei en el correo que la parte dos se entregaba en el pdf con arriba el texto y bajo ello la captura de pantalla con las tablas, mi pregunta es si en vez de escribir el texto arriba puedo subir el pantallazo  del texto y de la tabla ya que lo había guardado en ese formato en un pdf y después borre las fotos:( En la foto del pantallazo alcanza a salir bien el input(texto) y la tabla entera

**Comment by ValentinaAlvarezG** [comment]
Si alcanza a salir todo bien, no te preocupes, puedes dejarlo así. Lo importante es que se ve todo clarito
