### ISSUE TITLE
TC2 Parte uno, ¿Uso de flechas?

### ISSUE THREAD

**Issue by MagnaThyrsus** [Exploratorio-DCC-PUC/Syllabus#223]
![image](https://user-images.githubusercontent.com/62019527/80238884-3b9cbf00-862d-11ea-961b-f93e9cd0f0b8.png)
Tengo una relacion distribuida asi. Si justifico, puedo usar flechas para determinar que es "el cliente compra el producto" y no "el producto compra al cliente"? (el ejemplo es un poco obvio pero en la tarea hay una situacion mas gris)

**Comment by ValentinaAlvarezG** [comment]
Hola! No es necesario utilizar flechas en estos casos. Los nombres de las relaciones son para entender un poco mejor la relación pero no es estricto. No se si se entiende. La notación de flechas es para indicar cardinalidad, no dirección. El rombo representa que dos entidades se relacionan y es para ambos lados, porque un cliente compra producto pero eso también significa que un producto es comprado por un cliente, entonces por eso el nombre uno lo elige para que se entienda, pero uno cuando lee diagramas es capaz de entender la relación para el otro lado también. Espero haya quedado claro, sino, me dices :)
