### ISSUE TITLE
Duda sobre relaciones entre entidades

### ISSUE THREAD

**Issue by OrregoSilva** [Exploratorio-DCC-PUC/Syllabus#224]
Hola!
Tenia una duda acerca de si es que 2 entidades pueden tener mas de una relacion, ya que hay cardinalidades que no se bien como representarlas con solo una relacion, pero con 2 si se hacerlo.
Se puede hacer eso?

**Comment by ValentinaAlvarezG** [comment]
Hola! para términos de esta entrega, solo necesitas una relación entre dos entidades.

 En la vida, se puede tener, pero suele ser redundante, aunque a veces es necesario para la modelación del problema. Pero como te digo, para la entrega, no te debería pasar que necesites dos. Quizás puedes preguntar sobre la duda que te está generando la cardinalidad.

**Comment by OrregoSilva** [comment]
Muchas gracias!
