### ISSUE TITLE
Compañía no hace ninguna obra

### ISSUE THREAD

**Issue by Gustav2000** [Exploratorio-DCC-PUC/Syllabus#225]
Hola, en el enunciado dice: "Cada compañía puede estar representando múltiples obras en un momento dado, aunque también puede estar trabajando en una sola obra". Mi duda es si también podría estar trabajando en 0 obras (ninguna obra). Es para ver la cardinalidad.

**Comment by gatochico** [comment]
Hola! Como ese caso no queda definido de forma explícita en el enunciado, puedes dejarlo a tu libre elección como un supuesto (recuerda escribirlo en el archivo README.md).

Éxito!

**Comment by Gustav2000** [comment]
Gracias, y la escritura correcta podría partir desde el 0?, es decir, 0..N

**Comment by gatochico** [comment]
sip!
