### ISSUE TITLE
Condicion de sql DATE no funciona

### ISSUE THREAD

**Issue by airiquelme** [Exploratorio-DCC-PUC/Syllabus#227]
estoy intentando usar en el WHERE fechanacimiento >= 1400
pero igual me retorna uno con 1386
intenté con >= 1400-01-01 y tampoco, tengo q hacer algo en especial para que me recoga el dato como fecha?

**Comment by ValentinaAlvarezG** [comment]
Hola! Debes poner la fecha con comillas. Algo como fechanacimiento >= '1400-01-0-1', dime si te funciona!

**Comment by airiquelme** [comment]
siiiiii si me funcionó!
muchas gracias :)
