### ISSUE TITLE
duda parte 1

### ISSUE THREAD

**Issue by BMarink512** [Exploratorio-DCC-PUC/Syllabus#228]
hola, a que se refiere que hayan dos vectores de distinta clase y a que se refiere con clase, ¿es lo mismo que solo poner una columna?

**Comment by IchottMano** [comment]
Hola!

Cuanod nos referimos a vectores de clase, nos referimos, como dice el nombre, a un **vector** de datos, es decir, a un arreglo o "lista" (no es lo mismo, pero parecido) de dimensión 1, como una columna.

Cuando te pedimos dos vectores de clase distintos, nos referimos a que debes realizar la separación del dataset 2 veces distintas. Esto se puede hacer a través de la librería pandas, asumiendo que estás trabajando con un DataFrame (si no estas seguro que significa esto ultimo, te sugiero que leas la documentación de pandas).

Saludos!
