### ISSUE TITLE
Comentarios app Perusall "anónimos"

### ISSUE THREAD

**Issue by andres-tamm** [Exploratorio-DCC-PUC/Syllabus#229]
Hola! Quería saber como puedo comentar en el texto de forma no anónima, dado que al comentar no me deja desactivar el cuadrito que dice anónimo y cuando hago hover sobre mi comentario dice: "This comment was posted anonymusly ... " quería saber si esto afecta a la hora de recaudar los comentarios que hice y si hay alguna forma de cambiar este ajuste.
Gracias!

**Comment by mimadri** [comment]
Hola!
No hay problema con que comentes de forma anónima, ya que solo tus compañeros verán esa etiqueta. Para el profe si aparecerá quién realizó cada comentario, por lo que esto no afectará en tu calificación.
Saludos!!

**Comment by andres-tamm** [comment]
Gracias!

**Comment by andres-tamm** [comment]
SOLUCIÓN

Lo que tienes que hacer es abrir el documento desde la barra de la izquierda de la siguiente manera:

Readings > Documents > Lecturas IIC1005 > Lectura-Control-1

Cuando hagas esto debería aparecer un circulito con tus iniciales en el lado izquierdo del texto.



Por alguna razón no funciona de la otra forma, como que si no entras asi, obligatoriamente quedas anónimo.
![Captura de Pantalla 2020-04-30 a la(s) 11 05 36](https://user-images.githubusercontent.com/62019639/80726642-ad17ba00-8ad2-11ea-81f8-5efb1837f16b.png)
