### ISSUE TITLE
Scripts 

### ISSUE THREAD

**Issue by sebaelsaca** [Exploratorio-DCC-PUC/Syllabus#23]
Creo que hay que poner if/else en más de una parte de la tarea. Eso no se puede hacer en un terminal sino en un script. Los scripts dónde los escribo??? Y lo subo después aparte del pdf? Estoy confudido.

**Comment by StroveLight** [comment]
Como va al tema,
Si es que se pudiesen usar, ¿Se pueden definir funciones en el script?

**Comment by Pyralspite** [comment]
Hola,
Para escribir los comandos en el informe pueden usar como supuesto que se cumplen todas las condiciones necesarias (a menos que esa instrucción explícitamente diga que algo no se cumple). Por lo tanto, no es necesario que usen if/else para manejar varios casos, solo el caso general.
Por otro lado, les recuerdo que en esta tarea no deben programar el juego, solo los comandos necesarios para cumplir con las instrucciones, los cuales deben ser plasmados en el informe. Por lo tanto, no es necesario subir scripts.
Saludos
