### ISSUE TITLE
Gráfico de evolución por meses

### ISSUE THREAD

**Issue by jncaceres** [Exploratorio-DCC-PUC/Syllabus#23]
Al momento de hacer el grafico lineal para ver como progresa la reproduccion de canciones por cada mes, me ocurre que si hago el grafico lineal no me muestra las fechas abajo, pero si es que lo hago en cualquier otro tipo de grafico si aparecen las fechas y no entiendo por que ocurre.

**Comment by benjastraub** [comment]
¿Cuando lo haces lineal no te muestra ninguna fecha o sólo te muestra algunas?

**Comment by jncaceres** [comment]
No me mostraba ninguna pero ya lo solucione con xticks, muchas gracias
