### ISSUE TITLE
Sobre la parte 1

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#230]
Hola!, la verdad no entiendo la parte 1, en el análisis de características, mencionan que hay que excluir las columnas innecesarias o que no aporten información, pero después se menciona que solo dos columnas son las que sirven (la de los editores y la de ventas del resto del mundo). O sea que hay que excluir todas menos esas dos y quedarme con un dataframe de dos columnas? O me tengo que quedar con dos dataframes de 1 columna cada una? O cómo es? Lo más probable es que estoy confundiendo hartos conceptos. Favor de definir lo que es clase, etiqueta, asignación de clase, característica, vector de clase :(.

Y otra duda muy corta, es que cuando se refieren a “ventas del resto del mundo” están siendo explícitos con ello cierto? No es que se refieran a la suma de las ventas de todo el mundo (Japón+ NA+Europa+ Resto del mundo) cierto? 
Sorry por el texto tan largo pero es que de verdad no entiendo nada el análisis de características de la parte 1 :((.
De antemano gracias por su respuesta!

**Comment by AstridESMJ** [comment]
Hola @AlfreMK,

Si lees bien el enunciado dice : "considerando dos vectores de clase distintos: editora del juego y ventas en el resto del mundo", esto quiere decir que deberás considerar en un experimento que la clase ó etiqueta es la editora del juego y en un segundo experimento deberás considerar las ventas en el resto del mundo como la clase.
Tomando en cuenta esos dos experimentos debes limpiar la base de dato viendo qué atributos/columnas no te serán útiles en la tarea de clasificar/regresión.
Si, para cuando se dice "ventas en el resto del mundo" se hace referencia a esa columna solamente.

Saludos,

Astrid
