### ISSUE TITLE
Duda I1 Pregunta 1.3

### ISSUE THREAD

**Issue by apinif** [Exploratorio-DCC-PUC/Syllabus#232]
En la pregunta 3 de la parte 1 "¿Qué aplicacion de iPhone o Android usan los usuarios para participar en el proyecto?" Se refiere al proyecto _Sidewalk_ o al ejemplo que dí en la pregunta 1.2?

**Comment by denisparra** [comment]
se refiere al proyecto Sidewalk.

**Comment by IchottMano** [comment]
Hola! 

No cierres la issue! Le podría servir a tus compañeros, nosotros la cerraremos por ti después 😄 

Saludos!
