### ISSUE TITLE
Duda pregunta 2.3

### ISSUE THREAD

**Issue by maggiemunoz** [Exploratorio-DCC-PUC/Syllabus#233]
puedo preguntar que es un turker? o la traduccion? google no me dice nada, por contexto creo que son los pagados pero no estoy segura

**Comment by Dnpoblete** [comment]
Hola @maggiemunoz, lo puedes buscar en internet y en los comentarios de perusall, la idea es que ustedes busquen la información, y preguntar a algún compañero sera considerado como copia.

Éxito con la I1 :smile:
