### ISSUE TITLE
Duda Enunciado TG2

### ISSUE THREAD

**Issue by Hanfud4** [Exploratorio-DCC-PUC/Syllabus#236]
Hola, leyendo el enunciado de la Tarea Grande 2 nos surgieron las siguientes dudas:
-  ¿Qué es exactamente el dato Rank? ¿Están ordenados por calidad, por ventas, gusto personal u otro? ¿O es homólogo al id?
-  Hay entradas que figuran con ventas en cero en todas las ubicaciones, ¿Esto significa que efectivamente no se vendió el juego, que vendieron menos de 0.01M USD o que no hay datos? 
Agradeciendo su tiempo,
Salu2

**Comment by IchottMano** [comment]
Hola!
El dato rank se refiere al ranking de las ventas del videojuego. El id solo es un indicador de orden.
Si aparece como 0 ventas, es porque no vendió suficiente para aparecer.

Saludos!
