### ISSUE TITLE
Cantidad de Publisher y accuracy [TG2]

### ISSUE THREAD

**Issue by sopadeoliva** [Exploratorio-DCC-PUC/Syllabus#237]
Hola!

Me surgió una duda viendo los datos. Segun tengo entendido hay +500 publishers distintos, muchos que tienen muy pocos juegos (más de la mitad tiene menos de 5, más o menos, y muchas con solo 1). Me esperaría que un clasificador que solo tiene una muestra para poner una etiqueta no va a ser muy certero.
Mi duda es si se pueden agrupar Publisher en una etiqueta nueva (p.ej. "Otras") y considerar como hiperparámetro la cantidad de juegos que tiene la editora (no sé, por ejemplo, si tiene menos de X juegos, cae en "Otras").
Obviamente esto tiene sus fallas también, pero tampoco entiendo muy bien el orden de magnitud por el cual debería moverse el accuracy... :(

Muchas gracias, saludos <3

**Comment by IchottMano** [comment]
Hola!

Efectivamente, al existir muchos publishers, de los cuales tienen algunos muy pocos datos para trabajar, se espera que su accuracy no sea muy buena.
Puedes hacerlo como dices, agrupando, sin embargo esto podría afectar tus resultados, pero es completamente válido.

Saludos!
