### ISSUE TITLE
One-Hot Encoding en TG2

### ISSUE THREAD

**Issue by vWing7** [Exploratorio-DCC-PUC/Syllabus#238]
Tengo un problema al intentar hacer One-Hot-Encoding con la función de scikit-learn, y pasarla a pandas para tener completa la matriz de features. Me da la impresión de que es por el formato del output al transformar. Lo que quería preguntar es si se puede usar get_dummies() de pandas para el encoding.

Gracias

**Comment by IchottMano** [comment]
Hola!

Si, pueden usarlo.

Saludos!
