### ISSUE TITLE
Normalización de datos

### ISSUE THREAD

**Issue by franciscojpcc** [Exploratorio-DCC-PUC/Syllabus#239]
Hola, tengo una duda respecto a la parte de normalizar los datos. Dado que el objetivo de esta parte es reducir la dispersión de los datos, ¿Es necesario usar la librería sklearn, en específico el comando Normalizer? ¿O puedo crear otra función que cumpla con el mismo objetivo?

**Comment by IchottMano** [comment]
Hola!

Pueden usar una función ya sea de sklearn o también a través de pandas.

Saludos!
