### ISSUE TITLE
Al crear un dataframe del csv con las imágenes, el link de las imágenes no sale completo

### ISSUE THREAD

**Issue by FloValdes** [Exploratorio-DCC-PUC/Syllabus#24]
![screenshot_1](https://user-images.githubusercontent.com/37163115/38165012-9c7c9ae0-34e3-11e8-84f1-e00e912968b6.png)

En la columna de Image_Link no salen los links completos, si no que se cortan con "...". Cuando quiero ocupar merge para sacar las fotos de los 5 artistas más escuchados también salen con "...". ¿Cómo puedo hacer que lo importe completo?

Gracias!

**Comment by diflores** [comment]
¡Hola!

Los links en realidad no están cortados, los tres puntos son solo para indicar que ese campo del `DataFrame`continúa. Cuando exportes a `.csv`, verás que salen completos.

¡Saludos!

**Comment by FloValdes** [comment]
En csv también me salen cortados
![screenshot_2](https://user-images.githubusercontent.com/37163115/38165149-4edc986a-34e5-11e8-9a49-341e843bd4eb.png)

**Comment by diflores** [comment]
Los *links* están correctos, pero el archivo debe estar separado por comas, ¿estás usando `pandas` para exportar a `.csv`?

**Comment by FloValdes** [comment]
No, estaba usando python, con pandas se arregló!
Muchas gracias
