### ISSUE TITLE
csv TG2

### ISSUE THREAD

**Issue by gecoli** [Exploratorio-DCC-PUC/Syllabus#240]
Resulta que, por alguna razón, no puedo descargar el games.csv desde el syllabus, ¿hay alguna razón de esto? 

O sea, me abre el siguiente link cuando apreto Download https://raw.githubusercontent.com/Exploratorio-DCC-PUC/Syllabus/master/Tareas/Tarea%20Grande%202/games.csv

**Comment by IchottMano** [comment]
Hola!

Si guardas esa página deberías obtener el archivo que necesitas.

Saludos!
