### ISSUE TITLE
Duda TG2

### ISSUE THREAD

**Issue by Jimnora** [Exploratorio-DCC-PUC/Syllabus#241]
Para la tarea, se solicita que se analicen los datos con respecto a 2 vectores de clase distintos, pero quedo con la duda si se debe utilizar uno para la clasificación y otro para la regresión, o los 2 para ambos, etc...

**Comment by IchottMano** [comment]
Hola!

Son dos vectores de clase, uno para la clasificación (publisher) y otro para la regresión (other sales).

Saludos!
