### ISSUE TITLE
Tarea Grande 2. Get Dummies

### ISSUE THREAD

**Issue by railira** [Exploratorio-DCC-PUC/Syllabus#243]
Quiero convertir str en datos numéricos para esto he decidido usar .get_dummies que me genera un data frame de 0 y 1 a partir de una columna de datos seleccionada. Pero al agregar este data frame a mi data frame original muchos de los valores de 0 y 1 se convierten en "NaN". Como puedo solucionar esto?

**Comment by IchottMano** [comment]
Hola!

Intenta setear el parámetro **dummy_na** de la función get_dummies a True
```python
pandas.get_dummies(dataframe, dummy_na=True)
```


Saludos!
