### ISSUE TITLE
Error al sacar las métricas del clasificador

### ISSUE THREAD

**Issue by magdalenanario** [Exploratorio-DCC-PUC/Syllabus#244]
Hola, qué significa el error
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
que me arroja al  calcular las metricas del clasificador?

**Comment by IchottMano** [comment]
Hola!

Podría ser que en el dataset de test no tienes ejemplos de alguna clase?

Si es así podrías simplemente ignorar esa clase para testear 🤔 

Estaré atento,
Saludos!

**Comment by apinif** [comment]
Encontre en [StackOverflow](https://stackoverflow.com/questions/43162506/undefinedmetricwarning-f-score-is-ill-defined-and-being-set-to-0-0-in-labels-wi) que significa que hay etiquetas en uno de los arrays que no estan en el otro, esto yo lo arrgele utilizando numpy y poniendo el argumento labels=np.intersect1d(array1, array2) en los argumentos del classification report, no se si esta bien, que algun ayudante confirme :)

**Comment by magdalenanario** [comment]
graciaas!
