### ISSUE TITLE
Dudas sobre visualizar el TSNE y sobre el markdown del informe.

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#245]
Hola!! , para el caso de visualizar los datos de TSNE con altair, en el caso del vector de clase de ventas, hay que distinguir los datos con colores o formas también?, ¿o simplemente no hay que distintguirlos con nada? ¿En el caso de ser lo primero habría que agrupar los datos en intervalos entonces cierto?

y otra cosa: que es eso del formato markdown para el informe? lo he buscado por internet y no le encuentro diferencia con escribir en las celdas de texto de colab como en la tarea grande 1 😢 . Sería bien útil que pusieran un ejemplo para ver más o menos lo que piden sobre esto (una foto o algo).

De antemano, muchas gracias

**Comment by Dnpoblete** [comment]
Hola @AlfreMK, con respecto a tu primera duda en el enunciado dice que se espera que cada punto pueda ser identificado con su clase respectiva según color o forma, por lo que la respuesta es sí, y en el caso de que uses las clases de other sales tendrías que hacer intervalos para los colores.

![image](https://user-images.githubusercontent.com/42362982/81876739-5b9b1080-9551-11ea-87b6-52e94b46c04e.png)

Con respecto a markdown aquí encontré una guía en internet con comandos básicos que te podría servir, para que la revises https://www.markdownguide.org/basic-syntax/

En caso de seguir con dudas avisame para poder ayudarte 😄 
¡Éxito con la tarea!
