### ISSUE TITLE
Datos a utilizar en Parte 3 (t-SNE)

### ISSUE THREAD

**Issue by aboehmg** [Exploratorio-DCC-PUC/Syllabus#247]
Hola!

Mi duda es la siguiente: ¿A qué dataset/subset debemos aplicar t-SNE en la parte 3? ¿Es el mismo que el usado en la parte 2 (matriz|vector)?

**Comment by AstridESMJ** [comment]
Hola!

Deben hacer reducción de dimensionalidad al dataset completo games.csv

Saludos.

**Comment by nicolascamhi** [comment]
Necesariamente debe ser el dataset original completo (games.csv)?? No podemos sacar columnas que creemos que no aportan o preprocesar los datos?

**Comment by Dnpoblete** [comment]
Hola @nicolascamhi, puede ser con el dataset completo o sin las columnas que no son necesarias, por lo que amabas opciones serán consideradas como válidas, pero tengan mucho ojo con las columnas que eliminan.

¡Éxito con la tarea! :smile:
