### ISSUE TITLE
Dudas matriz de características parte 1

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#248]
1. Las dos matrices de características deben tener la misma cantidad de _features_? O puedo hacer una matriz con menos columnas que la otra si considero que algunas características sirven para el clasificador pero no para el regresor (o viceversa)? 

2. La matriz de características de la editora puede contener a la otra clase (ventas en el resto del mundo)?

**Comment by IchottMano** [comment]
Hola!

1.- Es su decisión, si quieren hacer individualmente la elección de features o no está bien, siempre y cuando se fundamente porqué decidieron hacerlo así.

2.- Si, no hay problema con eso.

Saludos!

**Comment by AstridESMJ** [comment]
Hola,

1. La cantidad de features a utilizar deben ser definidas por ti, no es necesario que sea para ambos casos el mismo número.
2. Si, puede contenerla.

Saludos.
