### ISSUE TITLE
Duda de visualización de cluster de densidad

### ISSUE THREAD

**Issue by fbesoainp** [Exploratorio-DCC-PUC/Syllabus#249]
En el gráfico de densidad los clusters nos aparecen como un degrade de colores y no como clusters individuales a diferencia del gráfico T-SNE. 
Estaría bien dejarlo así?

**Comment by IchottMano** [comment]
Hola! 
A modo de poder contestar bien tu pregunta, te pido que porfa envíen un pantallazo del gráfico obtenido y ojalá de el código que lo produce a mi mail (reschilling@uc.cl), esto a modo de poder ayudarlos sin comprometer su código.
Saludos!

**Comment by Francisco-Morales-R** [comment]
Holaa, creo entender la pregunta y a mi me pasó lo mismo. Creo que es por que el numero del cluster lo toma con un float, números que van de corrido, y para poder solucionarlo la idea es especificar en el gráfico que se le otorgue un color según un int, para que estén por separado.
Espero haber ayudado
