### ISSUE TITLE
error de git "fatal" 

### ISSUE THREAD

**Issue by AgustinZalaquett** [Exploratorio-DCC-PUC/Syllabus#25]
al escribir "git add ." me sale "fatal:  not a git repository (or any of the parent directories): .git"
y eso mismo con el resto de los comandos "git algo"

**Comment by Pyralspite** [comment]
Hola!
La ruta en la que estás ejecutando los comandos es la de tu repositorio local? Si no, una opción es abrir la carpeta, hacer click derecho y seleccionar "Git Bash Here" o moverte mediante comandos hasta entrar en ella. 
Si sigue sin resolverse, manda un pantallazo de tu consola.
