### ISSUE TITLE
Problemas ejemplos graficos TG1

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [Exploratorio-DCC-PUC/Syllabus#25]
Hola! tengo problemas para ver los ejemplos adjuntos en las secciones de
>Gráfico de la evolución de la cantidad de canciones escuchadas por mes.
>Gráfico de barras de la cantidad de canciones escuchadas por hora del día

Me dice que no se puede acceder a ese sitio :c

**Comment by diflores** [comment]
Hola,

Sí, parece haber un problema con el servicio en el que alojé las imágenes. Aquí van otros links:

[Ítem 5 de la parte 1](https://pasteboard.co/HetocnO.png).
[Ítem 7 de la parte 1](https://pasteboard.co/HetocnO.png).


¡Saludos!
