### ISSUE TITLE
Sobre las predicciones y el ruido en el clustering 

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#250]
Hola!, disculpe las molestias pero me inquietan algunas dudas. 
Primero, ¿qué esperan de nosotros que pongamos en las predicciones de los clusters? ¿Esperan como predicciones la visualización de los clusters en las gráficas o esperan algo más numérico como un accuracy? 

Segundo, con respecto a datos que son considerados "ruido" en el clustering, ¿Hay que tomarlos como datos de ruido a momento de elegir los parámetros para nuestros modelos de clusters?, ¿o hay que colocarlos en un cluster independiente de lo lejos que estén del mismo(i.e que no hayan datos ruidos)? 

Tercero, con respecto al número de iteraciones para la reducción de dimensiones en TSNE, hay un número que recomienden en especial? Es que si elegimos 4000 se demora como 10 minutos. Por otro lado, si elegimos 1000 (que es el default) se demora como 2 minutos. 

Cuarto, con respecto a métodos externos a la tarea (como el método "codo") que son útiles para obtener un número de clusters o el eps, ¿se le pueden meter funciones como "for", y/o librerías como numpy?

Agradecería su pronta respuesta. Gracias de antemano.

**Comment by IchottMano** [comment]
Hola! 

En primer lugar, queremos que principalmente analicen la diferencia que puedan observar entre lo que les dice el algoritmo de clustering en comparación a los datos reales que poseen. Esperamos un análisis mas visual, pero de todos modos pueden apoyarse de métricas para clustering como el **silhouette score**.

En segundo lugar, queda a su discreción como trabajar con los datos que consideren "ruidosos".

En tercer lugar, no recomiendo que jueguen con el numero de iteraciones del TSNE. Pueden dejarlo con su valor por defecto.

Por último lugar, pueden usar métodos externos para ver la cantidad optima de los parámetros, sin embargo **no pueden usar ciclos**.

Saludos!
