### ISSUE TITLE
Duda sobre el uso de ciclos

### ISSUE THREAD

**Issue by CholgaMan1** [Exploratorio-DCC-PUC/Syllabus#251]
Hola, mi duda es si podemos utilizar ciclos en la tarea para realizar cosas que no son modificar o sacar datos del dataframe, ya que en el enunciado la prohibición de ciclos está mencionada en la Parte 1, y no queda claro si se extiende también para el resto de las partes, en particular en la parte 3 para determinar el número óptimo de clusters.

**Comment by IchottMano** [comment]
Hola!

La prohibición de uso de ciclos se extiende para **toda la tarea**.

Saludos!

**Comment by nnovoag** [comment]
si no puedo hacer ciclos como puedo crear los rangos en la parte de visualizacion de t-sne para other sales?
