### ISSUE TITLE
Reducción de Dimensionalidad

### ISSUE THREAD

**Issue by fedezang** [Exploratorio-DCC-PUC/Syllabus#252]
Hola, tengo una duda respecto a la visualización de tSNE.
¿Cómo se pueden identificar las clases en un gráfico si estas son desconocidas? o ¿A qué componente de la reducción de dimensión corresponden las clases?

**Comment by IchottMano** [comment]
Hola!

No entiendo bien tu pregunta, ¿Porqué no conocerías las clases de cada punto luego de reducirles la dimensionalidad? Recuerda que los datos que tenías antes de reducir la dimensionalidad aún quedan guardados en memoria, no son eliminados luego de reducir su dimensión.

Cuando tu reduces la dimension de tus puntos terminas con 2 dimensiones que no poseen sentido físico, pero en ningun momento tu eliminas el dataframe que tenías antes.

Espero esto ayude un poco a responder tus dudas y, de lo contrario, por favor hazmelo saber.
Saludos!

**Comment by fedezang** [comment]
Entiendo, pero entonces la clase a identificar sería la editora del juego o ventas en el resto del mundo?
Gracias por tu respuesta!
