### ISSUE TITLE
clases a predecir y cantidad de centroides en el kmeans

### ISSUE THREAD

**Issue by magdalenanario** [Exploratorio-DCC-PUC/Syllabus#254]
Hola!
Tengo dos dudas en la parte tres de la tarea
1-Hay que predecir la cantidad de clusters o etiquetas de Publishers o de Other_Sales?
2-En el Kmeans, para determinar la cantidad de centroides, hay que basarse en la visualizacion del tSNE o guiarse por la cantidad de clases que vimos en la parte 2?

**Comment by IchottMano** [comment]
Hola!

Puedes hacerlo con cualquiera de las dos. Para la parte de Kmeans, pueden hacerlo de la manera que ustedes quieran pero argumentando y explicando que hicieron.

Saludos!

**Comment by magdalenanario** [comment]
graciaass!

**Comment by denisparra** [comment]
Para predecir el número de clusters no hay una solución 100% efectiva, pero como mencioné en clases lo mejor es usar las métricas extrínsecas. Además de la revisión visual, yo sugiero que usando sk-learn calculen el sillouette coefficient (https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html#sphx-glr-auto-examples-cluster-plot-kmeans-silhouette-analysis-py)
