### ISSUE TITLE
Parte 4, pregunta 5

### ISSUE THREAD

**Issue by vWing7** [Exploratorio-DCC-PUC/Syllabus#256]
No entiendo bien la pregunta 5 de la parte 4, según había visto en el nuevo enunciado, ya no se tienen que sacar las métricas para el set de entrenamiento, así que no entiendo a que se refiere con diferencia. 
Gracias

**Comment by Dnpoblete** [comment]
Hola @vWing7, con respecto a tu duda, en el caso de que lo hayas hecho como decía el enunciado anterior, también será considerado cómo válido, pero en el caso de que lo hicieras como se pide en el enunciado actualizado, la idea es que deben decir las diferencias que encuentren entre las métricas para cada clase del set de pruebas, para eso lo tienen que analizar y pensar cuales podrían ser diferencias.

¡Éxito con la tarea! :smile:
