### ISSUE TITLE
Duda a la matriz a normalizar

### ISSUE THREAD

**Issue by airiquelme** [Exploratorio-DCC-PUC/Syllabus#257]
Cuando normalizamos la matriz, debe ser la matriz solo con las características?
No hay que normalizar el vector de clase ni nada?}
Y si hay q hacerlo, el vector tiene que estar adentro de la matiz al normalizar los datos o no importa?

**Comment by IchottMano** [comment]
Hola!

No hay que normalizar el vector de clase.

Saludos!
