### ISSUE TITLE
For loops para mejor K en KNN y Silhouette

### ISSUE THREAD

**Issue by nicolascamhi** [Exploratorio-DCC-PUC/Syllabus#258]
Hola! Hicimos un algoritmo que nos encuentra el mejor K para KNN, pero tiene un for loop, eso está permitido?? La verdad es anexo al código requerido para la tarea, por eso pensé que quizás si lo permitirían. Además, en Silhouette es necesario usar for loops, se puede??

Por otra parte, cómo puedo justificar los hiperparámetros que esocogimos en el informe?? No entendemos en profundidad como funcionan y  encontramos los mejores probando.

**Comment by IchottMano** [comment]
Hola! 

Como se dijo en #251 no esta permitido el uso de ciclos. No es necesario usar loops lara sacar el silhouette score. Para explicar porqué los hiperparámetros son los mejores, deben hacerlo primero entendiendo como funciona el modelo que estan usando y con eso les podría ser mas fácil entender que son los hiperparametros e inferir porqué podrían ser los mejores.

Saludos!
