### ISSUE TITLE
Enunciado 1 Tarea

### ISSUE THREAD

**Issue by josemquinta** [Exploratorio-DCC-PUC/Syllabus#259]
Hola, 
Si es que hicimos la tarea en base al primer enunciado subido a el repo, lo podemos dejar así o hay que pasarlo obligatoria mente a lo requerido en el segundo enunciado publicado. El cual si bien pide menos cosas nos haría tener que reestructurar todo el notebook

Saludos

**Comment by IchottMano** [comment]
Hola!

Si ya lo hicieron como estaba antes, no es necesatio que lo cambien.

Saludos!
