### ISSUE TITLE
Parte 1, Item 6

### ISSUE THREAD

**Issue by mathiasvaldebenito** [Exploratorio-DCC-PUC/Syllabus#26]
En el Item 6 cuando se pide la cantidad de canciones escuchadas según día de la semana, ¿se está refiriendo a un promedio de cuántas escucha aquel día de la semana o a la sumatoria de todas las canciones escuchadas ese día de la semana?

**Comment by diflores** [comment]
¡Hola!

Se refiere a la sumatoria: cuántas canciones del total del *dataset* fueron escuchadas un lunes, cuántas un martes y así hasta el domingo.

¡Saludos!

**Comment by Gorgola22** [comment]
Y se debe usar dentro del gráfico los valores porcentuales o como enteros?
