### ISSUE TITLE
Formato de modificación de archivos

### ISSUE THREAD

**Issue by mafernandez9** [Exploratorio-DCC-PUC/Syllabus#26]
Hola! 
Cuando modifico info.txt para algún jugador, el archivo se me modifica de tal forma de que todo me queda en la misma línea, de esta forma:
Posición: 0Créditos: 50Aprobados:
¿Existe algún problema con esto?
¿O tengo que modificarlo para que me queden en lineas distintas?
Muchas gracias!

**Comment by ValentinaAlvarezG** [comment]
A veces pasa que si lo abres con el bloc de notas se ve así, pero si lo abres mediante consola se ve en líneas separadas, mientras se visualice bien al abrirlo por consola está todo bien.
