### ISSUE TITLE
Duda parte 4 pregunta 5

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#260]
En el enunciado anterior se pedía comparar las métricas del set de pruebas con las del set de entrenamiento, pero en el enunciado actualizado se pide "explicar la diferencia entre las métricas del set de pruebas para cada clase". ¿Debemos incluir el set de entrenamiento en nuestra respuesta si nos estamos guiando por el enunciado actualizado? ¿O solo debemos comparar las métricas dadas para cada etiqueta del set de pruebas?

**Comment by Dnpoblete** [comment]
Hola @sebastian-contreras-r, en el caso de que lo hayan hecho como decía el enunciado anterior será considerado válido, y en el caso de que lo hagan como dice en el nuevo es como dices tu, donde solo deben comparar las métricas dadas del set de pruebas para cada clase.

¡Éxito con la tarea! 😄

**Comment by ghost** [comment]
Ok, muchas gracias!
