### ISSUE TITLE
Duda inputs TC3

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#263]
Hola! viendo estos ejemplos 
![Captura de Pantalla 2020-06-04 a la(s) 9 45 56 a  m](https://user-images.githubusercontent.com/62023649/83765182-de8f2280-a648-11ea-80e3-cd110101fd1e.png)

Siempre el primer digito de los numeros debe ser 0? porque sino como se hace la suma sin aumentar el numero de digitos de los numeros del input? (tengo entendido que estos no varian, todos los numeros tienen el mismo largo, al menos sin contar el bonus)

Quizas también puedan venir inputs con un dígito 1 primero, pero que la máquina lo rechaze o no?

**Comment by mimadri** [comment]
Hola Pablo!
No necesariamente el primer dígito de los números será cero, por ejemplo:
Para **010101.100010.110111** (21,34,55) que sí es una secuencia que se asemeja a la sucesión de Fibonacci (de hecho, es parte de ella) la máquina debería aceptar el input, y sólo uno de los tres números binarios comienza con un 0. 
Pero también habrán casos en los que varios números en la secuencia (o tal vez todos) empezarán en 0 para que tengan la misma cantidad de dígitos, que es uno de los supuestos de la tarea.
Saludos!
