### ISSUE TITLE
Duda sobre el informe con el ejemplo de suma binaria

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#264]
Hola! para el caso de usar como código base el ejemplo de la suma binaria, ¿hay que explicar el funcionamiento de todo ese código detalladamente además de lo que agregué, o solo tengo que explicar los fragmentos de código que agregue y/o cambié?

De antemano muchas gracias.

**Comment by Pyralspite** [comment]
Hola!

Tienes que explicar todo el código base _que se mantenga_, además del código que tú agregues (puedes considerar el código modificado como código de tu autoría, para que no te compliques mencionando que cambiaste, y te concentres solo en explicar que hace ahora). 
En otras palabras, debes explicar todo el código que estás entregando, independiente de la fuente original (aunque debes citarla).

Saludos!
