### ISSUE TITLE
Duda input TC3

### ISSUE THREAD

**Issue by nicobuzeta** [Exploratorio-DCC-PUC/Syllabus#265]
Hola, tengo una duda sobre los primeros numeros del input.
Los numeros siempre son n<sub>i</sub> ≥ 0 o n<sub>i</sub> > 0?
Osea el primer numero puede ser 0 o debe ser un numero positivo?

Gracias

**Comment by Pyralspite** [comment]
Hola!

Puedes asumir que todos los números serán mayores a 0, ya que uno de los supuestos es que no habrá números repetidos a lo largo de la secuencia c:

**Comment by nicobuzeta** [comment]
Con "Todos los números de una secuencia serán distintos" se refiere a que no puede haber situaciones como un numero 0101 y otro 01010011?

**Comment by Pyralspite** [comment]
Cuando decimos que no habrá números repetidos en una secuencia, quiere decir que no habrá situaciones como 

0000.1011.1011 (TRUE según definición)
o
11010.11111.11010 (FALSE según definición, porque 11010+11111 != 11010)

Pero en el bonus (el único caso en que puedes tener números binarios de distinto largo), sí es válida una secuencia como

0101.1001110.01010011

en la que aparecen los números que tú indicas (aunque honestamente, no entendí bien a que apuntabas con tu ejemplo).

Además, ten presente que si en uno de los test aparece un número, este puede aparecer en otro test.

Espero haber resuelto tu duda, me avisas si algo no te quedó claro.

**Comment by nicobuzeta** [comment]
Ah si perfecto, no estaba pensado en el tercer numero. 
Muchas gracias
