### ISSUE TITLE
Duda sobre el supuesto n0<n1

### ISSUE THREAD

**Issue by Mamunoz42** [Exploratorio-DCC-PUC/Syllabus#266]
Holaaaa, mientras realizaba la tarea me surgió una duda, cuando ocurre que; n1<n0, mi maquina se tiene que detener en ese mismo instante o debo hacer algo en especial?, con algo en especial me refiero a que por ejemplo llegue al final de la cinta y ahí recién diga que es False siendo que mi máquina arrojaría False antes de que pudiese terminar de recorrer todo.

**Comment by Pyralspite** [comment]
Hola!

Para cualquier caso en que el input sea incorrecto, da igual si tu máquina se detiene de inmediato o hace algo más antes, mientras entregue False. Impleméntala como más te acomode.

Mucho éxito :3

**Comment by Mamunoz42** [comment]
Yaaaa, muchísimas gracias :)
