### ISSUE TITLE
Duda sobre el informe

### ISSUE THREAD

**Issue by nicobuzeta** [Exploratorio-DCC-PUC/Syllabus#267]
Hola, en las instrucciones para el informe, la primera seccion es sobre entregar una "explicacion detallada del funcionamiento de la maquina", y especifica que debemos decir que hace y tambien como lo hace. Por lo tanto para decir como lo hace, vamos a tener que explicar que hace en cada estado por donde pasa la maquina.

Por lo tanto mi duda es como diferenciar entre esa seccion y la seccion 3 que pide una explicacion para cada estado. Especialmente la parte que dice "Que acciones realiza la máquina mientras se encuentra en este estado." Ya que esto va a ser casi igual que la seccion 1.

**Comment by Pyralspite** [comment]
Hola!

Es cierto que parte de lo que se pone en la primera sección se solapa con la tercera sección, pero están orientadas a objetivos distintos.

En la primera sección al explicar como funciona tu máquina puede ser necesario que menciones ciertos estados o tipos de estados, pero esto debe ser en la medida que dé contexto a tu explicación. Enumerar estados con el fin de mencionarlos todos puede ser hasta contraproducente en esta parte. La prioridad está en que la implementación y funcionamiento de tu máquina se entienda.

En cambio, en la tercera sección si es necesario que menciones **todos** los estados. Puedes pensarlo como una versión "en palabras" de la función de transición, en que se van listando los estados o grupos de estados que componen tu máquina. Como en la primera parte ya explicaste en detalle como funciona tu máquina, en esta parte se espera que "Que acciones realiza la máquina mientras se encuentra en este estado" se explique en una o dos líneas.

Animo con el informe c:

**Comment by nicobuzeta** [comment]
Ya, gracias
