### ISSUE TITLE
Informe parte 1

### ISSUE THREAD

**Issue by OrregoSilva** [Exploratorio-DCC-PUC/Syllabus#268]
Hola!
Para la parte en donde tenemos que explicar como funciona la maquina, ¿podemos ir mostrando el desarrollo de un ejemplo para apoyar la explicacion?
Saludos!

**Comment by Pyralspite** [comment]
Claro! Lo que encuentres conveniente para apoyar tu explicación.

**Comment by OrregoSilva** [comment]
Buena muchas gracias!

**Comment by sbvillalobosm** [comment]
Sobre esta misma parte del informe, podemos añadir las partes del código que vamos a explicar? o no puede haber nada de código en el informe?
