### ISSUE TITLE
Tipo de input y extensión del informe

### ISSUE THREAD

**Issue by Mamunoz42** [Exploratorio-DCC-PUC/Syllabus#269]
Holaaa, quería hacer dos consultas;
La primera es sobre los inputs que puede recibir la máquina, por ejemplo, mi máquina podría recibir esta serie de números? -> 10000.00001.00010.00011
La segunda consulta es sobre si existe alguna extensión máxima para el informe que se debe entregar.

**Comment by Pyralspite** [comment]
Hola!

El ejemplo que das es válido como un test negativo (output False).
Respecto a tu segunda pregunta, no hay una extensión máxima, pero las ayudantes agradecerían que sean eficientes con sus palabras al momento de redactar su explicación c:

**Comment by Mamunoz42** [comment]
Entonces mi máquina para un input de largo 5 debe comprobar que el 2° término es mayor que el 1° término y que el 3° sea la suma de los dos, luego ver que el 3° sea mayor al 2° y que el 4° sea la suma de estos y así hasta comprobar que el 5° es la suma del 3° y 4°?

**Comment by Pyralspite** [comment]
Hay algo que estás pasando por alto y quizás te simplifique la vida. Si sumas dos números positivos (mayores a 0), el resultado **siempre** será mayor que estos dos.
 
Por enunciado sabes que los números de la secuencia son positivos. Por lo tanto:

Si `n1 > n0` y `n2 = n0 + n1`, entonces `n2 > n1 > n0`. Luego, si `n3 = n2 + n1`, entonces `n3 > n2` y así con el resto de los números.

Es decir, te basta con verificar que `n1 > n0` y a partir de `n2`, verificar que es la suma de los dos números anteriores.

**Comment by Mamunoz42** [comment]
Sisisi, la duda es que entonces debo ir sumando siempre verdad?

**Comment by Pyralspite** [comment]
Sip!

**Comment by Mamunoz42** [comment]
Oka, muchisimas gracias :)
