### ISSUE TITLE
Sumar/ restar créditos 

### ISSUE THREAD

**Issue by SFarfan** [Exploratorio-DCC-PUC/Syllabus#27]
Hola, tengo una duda en las preguntas donde se debe explicitar el comando para restar o sumar créditos al jugador según sea el caso. La resta tengo que hacerla con un comando en especial o simplemente poner, por ejemplo "Créditos: cri - 10" ? cri es el numero de créditos que se debe suponer que hay en ese momento.
De antemano gracias

**Comment by ValentinaAlvarezG** [comment]
Puedes hacerlo de la manera en que lo indicas, no es necesario que uses un comando especial para restarlos
