### ISSUE TITLE
.csv // javascript

### ISSUE THREAD

**Issue by topkaj** [Exploratorio-DCC-PUC/Syllabus#27]
Hola,
En la parte 2, cuando se pide cargar los datos .csv usando javascript, ¿cuál es la forma en que se espera que se carguen? Pregunto esto porque leí en internet que no es posible abrir directamente archivos locales con el path por temas de seguridad, a menos que el usuario los suba mediante un "input" y luego se use FileReader. También encontré que se podían leer usando librerías como jQuery.
Por ahora pude construir la tabla, pero copiando los datos del .csv en una variable dentro del .js

**Comment by NevadaStreets** [comment]
Es verdad que por temas de seguridad no te dejan abrir archivos locales algunos browsers como Chrome. Pero si abres tu código (HTML) en otro navegador como Mozilla Firefox debería funcionar, o abriendo tu página web como un servidor. Por ejemplo puedes correr un servidor local utilizando Python, basta con ejecutar este comando en consola:

`python -m http.server 8000`

Y luego acceder a `http://localhost:8000/`. Esto debería permitir que tu página web cargue archivos locales incluso utilizando Chrome.

Bueno, y para cargar estos archivos locales basta con leer un csv utilizando la librería jQuery tal como tu lo has dicho.

Lo que esperamos que carguen sus datos leyendo un .csv desde el código en Javascript, utilizando Javascript puro, una librería como jQuery u otra librería que te permita leer el archivo de forma fácil y pueda ser ejecutada en un navegador.

Espero que esto resuelva tus dudas!

**Comment by topkaj** [comment]
muchas gracias !! 💯

**Comment by valeeeriquelme** [comment]
Podemos utilizar el botón de carga de archivos, utilizando el tag input? Porque de ninguna forma el JavaScript puede leer un archivo directamente del equipo del usuario sin que sea seleccionado.
