### ISSUE TITLE
Comparacion Bonus 1 y 2

### ISSUE THREAD

**Issue by Jimnora** [Exploratorio-DCC-PUC/Syllabus#270]
En el caso en que al realizar la suma de el mismo numero binario que con el que se compara, pero este tiene una mayor cantidad de 0 al inicio del numero, tambien se debe considerar esto para los bonus?

**Comment by Pyralspite** [comment]
Hola!

No sé si estoy entendiendo bien tu pregunta. Recuerda que uno de los supuestos es que todos los números de una secuencia serán distintos.

**Comment by Jimnora** [comment]
por ejemplo:
1000.1.00001001
Si uno toma en cuenta que los 0 a la izquierda del tercer numero no cambiar el valor de este, este caso deberia ser aceptado por la maquina

**Comment by Pyralspite** [comment]
El caso que muestras no sería aceptado porque n0 >n1.

Pero las secuencias

1.1000.00001001
01.1000.1001
0001.01000.001001

Son todos ejemplos de entradas que tu máquina debería poder aceptar en el bonus.
