### ISSUE TITLE
Poner código en el informe

### ISSUE THREAD

**Issue by sbvillalobosm** [Exploratorio-DCC-PUC/Syllabus#271]
Hola :)
En la parte 1 del informe, podemos añadir las partes del código que vamos a explicar? o no puede haber nada de código en el informe?

Saludos

**Comment by Pyralspite** [comment]
Hola!

Es válido poner código, diagramas, pantallazos y cualquier otra cosa que creas que puede ayudar a comprender mejor tu explicación. Lo que no es válido es poner alguna de estas cosas **en vez de** tu explicación. Es decir, pegar un pedazo de código y que quede como "ejercicio para el lector" comprender que hace.

Saludos :3

**Comment by sbvillalobosm** [comment]
Muchas gracias! 
Tengo otra duda, en la parte de definición formal tengo que responder de acuerdo a mi tarea? Por ejemplo, definir conjuntos con mis propios estados?

**Comment by mimadri** [comment]
Sí, la definición formal debe ser respecto a tu máquina!
Saludos :)

**Comment by sbvillalobosm** [comment]
Comprendo, muchas gracias!! :)
