### ISSUE TITLE
Informe, Parte 2

### ISSUE THREAD

**Issue by stefanocando** [Exploratorio-DCC-PUC/Syllabus#272]
Hola,
En el informe, cuando piden la definición formal se refieren a una definición general de los conceptos para todas las máquinas de Turing o una definición en relación a la máquina que nosotros hicimos?

**Comment by mimadri** [comment]
Hola!
La definición formal debe tener todos los parámetros que se mencionan en el enunciado (conjunto de estados, alfabeto de la maquina, estados de aceptacion, etc) pero respecto a tu máquina.
Saludos :)
