### ISSUE TITLE
imagenes en latex

### ISSUE THREAD

**Issue by magdalenanario** [Exploratorio-DCC-PUC/Syllabus#273]
Holaa
Quería preguntar cómo se pueden poner pantallazos en latex?? Es que intente hacerlo sacando un pantallazo, guardandolo como imagen en mis archivo y despues escribiendo

\graphicspath{ {la carpeta donde esta mi imagen/} }
\includegraphics{el nombre de mi imagen}

, sin embargo me dice que la imagen no existe

**Comment by mimadri** [comment]
Hola Magdalena!

Al principio del documento importaste el paquete graphicx? (con: `\usepackage{graphicx}`)
Si importaste la imagen a tu template, podrías intentar lo siguiente:
Si tu imagen se llama, por ejemplo, _diagrama.PNG_, una forma de añadirla en tu documento principal es:
`\begin{figure}[h!]`
`\includegraphics[scale=0.5]{diagrama}`
`\caption{Diagrama de estados}`
`\label{fig:diagrama}`
`\end{figure}`

Con esto debería funcionar
Suerte con la tarea :)

**Comment by magdalenanario** [comment]
Lo acabo de intentar y no me funciona
¿a que te refieres con importar la imagen al template?

**Comment by mimadri** [comment]
Si estás usando Overleaf, debes agregar la imagen en esta parte 

> 
![diagrama](https://user-images.githubusercontent.com/48396891/84702897-56046200-af25-11ea-90f4-af453cf899fa.PNG)

Si no es así, qué editor estás usando?

**Comment by magdalenanario** [comment]
ahi me funciono!
graciasss!!
