### ISSUE TITLE
Duda administrativa

### ISSUE THREAD

**Issue by furzuadr** [Exploratorio-DCC-PUC/Syllabus#274]
Hola! En el programa sale que uno se puede eximir del examen si es que no tiene ninguna nota menor a 4.0.
Además, sale que se puede borrar la peor nota entre controles y tareas chicas. Si es que no hago una tarea chica y borro ese 1.0, igual puedo eximirme? O ese 1.0 cuenta como una nota menor a 4.0 que impide la eximición?
Gracias!

**Comment by mimadri** [comment]
Hola!
La nota que se borra no cuenta para el cálculo de la nota de presentación, así que si te podrías eximir
Saludos :)
