### ISSUE TITLE
Repositorio TC3

### ISSUE THREAD

**Issue by Imenend** [Exploratorio-DCC-PUC/Syllabus#275]
Hola, el link que aparece en canvas para la creación del repositorio para entregar la tarea chica 3 me lleva a una ventana de "404 not found"(no he creado el repositorio, y por ende no tengo lugar para entregar la tarea)

**Comment by Pyralspite** [comment]
Hola, sospecho que estás usando el link de la primera invitación. Ese lo tuvimos que invalidar y les mandamos una [segunda invitación](https://classroom.github.com/a/PVYtm394) en un aviso

Avisame si ese link te funciona

**Comment by Imenend** [comment]
Funciona, gracias
