### ISSUE TITLE
Subir imágenes del archivo en repo

### ISSUE THREAD

**Issue by sbvillalobosm** [Exploratorio-DCC-PUC/Syllabus#276]
Hola!

Tengo la duda si es que debemos subir las imágenes que ocupamos para el informe al repositorio, para cuando revisen el archivo .tex o no es necesario.

gracias :)

**Comment by mimadri** [comment]
Hola!
Sí, debes agregar todos los archivos adicionales que ocupaste para compilar el informe.
Saludos (:

**Comment by sbvillalobosm** [comment]
Yap, muchas gracias!!
