### ISSUE TITLE
I2, Concepto de automatizar

### ISSUE THREAD

**Issue by AlfreMK** [Exploratorio-DCC-PUC/Syllabus#277]
Hola!, tengo una duda sobre el concepto, puesto que prácticamente toda la parte 2 depende de saberlo bien. 
¿Hasta que punto llega el concepto de automatizar? ¿Por ejemplo, si yo creara una IA que piense exactamente como un humano (y hasta tenga sentimientos) y haga tareas, contaría como que se está automatizando las tareas?, ¿o la palabra automatizar llega hasta cierto punto?
De antemano gracias

**Comment by SocVis** [comment]
Hola. Por algo automatizado se refiere a "La técnica, método o sistema para operar o controlar un proceso por medios altamente automáticos, como por dispositivos electrónicos, reduciendo al mínimo la intervención humana.". 

En la parte 2 es importante distinguir un trabajo (por ejemplo, ser tenista) de las tareas que implican ese trabajo (correr, golpear de derecho, golpear de revés, servir, volear, hacer dropshots, pegar con efecto, etc.). Algunas tareas son fáciles de automatizar con ML y otras no tanto. Eso es de lo que se trata el paper: qué características tienen las tareas SML (suitable to be automated by Machine Learning)

Tu ejemplo la verdad que se va demasiado lejos, describes una gran variedad de tareas y acciones. Ya con "... reducir al mínimo la intervención humana" para realizar una tarea, estás automatizando,  y (siendo redundante) piensa en tareas cuyas características son las que se pueden automatizar con SML.

Denis Parra
