### ISSUE TITLE
I2, citas

### ISSUE THREAD

**Issue by boltibolti** [Exploratorio-DCC-PUC/Syllabus#278]
un poco rara la pregunta, pero se puede buscar informacion por internet? (despues se cita)

**Comment by IchottMano** [comment]
Hola!

Si, no hay problema con eso, sin embargo si vas a usar información de internet, ojalá esta no sea copiada y pegada directamente, y se espera también que dejes el link de donde lograste obtener la información.

Saludos!

**Comment by boltibolti** [comment]
Gracias!
