### ISSUE TITLE
I2: Pregunta 1 - Parte 4

### ISSUE THREAD

**Issue by Flvilches** [Exploratorio-DCC-PUC/Syllabus#279]
Hola! Tengo una duda con la pregunta 1 de la parte 4. 
Lo que sucede es que dice que tenemos que describir un caso de distribución de datos donde las medidas de clustering (cohesión y separación) funcionarían bien para evaluar el resultado y otro caso de distribución de datos donde estas medidas no permitirían evaluar adecuadamente el resultado. Cuando habla de describir el caso, se refiere a decir como por ejemplo (bien vago): La cantidad de actores es... o La cantidad de empresas de videojuegos no ...., o hay que graficamente dar ejemplos de esto, es decir, hacer graficos con los puntos separados y otro con los puntos lejos y decir cual es un buen cluster por la distancia.
Espero haberme expresado bien. :)

**Comment by Jiruiz2** [comment]
Se te pide que entregues ciertas características que deben cumplir la distribución de los datos para que se cumpla lo solicitado. No es necesario que entres en tanto detalle como qué representan estos datos (actores, videojuegos, etc.) sino que hables de la distribución completa.

**Comment by Flvilches** [comment]
Muchas gracias! :)
