### ISSUE TITLE
TC1 - Duda sobre los requisitos de Codecademy

### ISSUE THREAD

**Issue by AndresFaure** [Exploratorio-DCC-PUC/Syllabus#28]
Hola. Estoy un poco confundido sobre lo que se pide hacer en Codecademy. Hice el tutorial gratuito, me tomó sus dos horas y me enseñó a hacer la gran mayoría de lo necesario para la tarea. Mi perfil se ve así:

![Captura](https://user-images.githubusercontent.com/42186981/63272210-a1000b00-c269-11e9-9704-1ff6a4a3b7aa.PNG)

![Captura](https://user-images.githubusercontent.com/42186981/63272877-e2dd8100-c26a-11e9-8906-9dd00f7aba24.PNG)

Ahora, mi duda viene con el correo que mandaron hace unos días, explicando que debemos realizar las lecciones PRO. Entiendo que me faltaría hacer las lecciones PRO, pero la verdad lo encuentro un poco innecesario ya que en este punto debería meter una tarjeta de crédito o hacerme otra cuenta. 

Perdón por si la pregunta parece un poco redundante con lo que se ha dicho, pero quería confirmar si realmente necesito hacer la parte PRO antes de hacerlo.

Gracias en adelantado.

**Comment by ValentinaAlvarezG** [comment]
Efectivamente, debes hacer los cursos de la parte pro

**Comment by AndresFaure** [comment]
Ok, gracias.
