### ISSUE TITLE
Duda pregunta 4 parte 4

### ISSUE THREAD

**Issue by Francescorodriguezg** [Exploratorio-DCC-PUC/Syllabus#280]
Hola! Tengo una duda con la pregunta 4.4

¿Se espera que solo respondamos si las relaciones son verdaderas o falsas, o también es necesario incluir el programa que permite establecer estas relaciones? Si resulta necesario esto último, ¿es posible subir dos veces el pdf en canvas?

Gracias!

**Comment by mimadri** [comment]
Hola!
Se espera que incluyas los predicados necesarios.
Puedes subir más de una vez el pdf a canvas :)
Saludos!

**Comment by Francescorodriguezg** [comment]
Perfecto, gracias!
