### ISSUE TITLE
I2, Pregunta 4 Parte 4

### ISSUE THREAD

**Issue by airiquelme** [Exploratorio-DCC-PUC/Syllabus#281]
Muy rápido, incluyo medios hermanos? O sea, si comparten papá pero no mamá, los cuento igual como hermanos? O deben ser hermanos "nucleares"?

**Comment by Pyralspite** [comment]
Hola!
En principio solo les pedimos que consideren hermanos "nucleares". Sin embargo, si alguien ya implementó su solución incluyendo medio hermanos va a estar bien mientras lo aclaren en su respuesta.
