### ISSUE TITLE
Dudas con el enunciado - TC4

### ISSUE THREAD

**Issue by Bea2000** [Exploratorio-DCC-PUC/Syllabus#282]
Hola!
Tengo dos dudas sobre el enunciado:
1. Si es que el guía llega a llamar al servicio meteorológico local, ¿Tenemos que asumir que este siempre le contestan?.
2. No entiendo bien a que se refiere con que "Represente a las entidades con que se relacionan como ejecutores como entidades abstractas independientes"

Muchas gracias de antemano.

**Comment by mimadri** [comment]
Hola!
1. Sí puedes asumir que obtendrás una respuesta desde el servicio meteorológico.
2. Este punto hace referencia a que los actores que se involucran en el flujo se vean bien representados en sus respectivos pools y lanes.
