### ISSUE TITLE
[Tarea chica 4] Preguntas BPMN

### ISSUE THREAD

**Issue by sopadeoliva** [Exploratorio-DCC-PUC/Syllabus#283]
Hola, tengo algunas dudas que creo que no fueron respondidas en la clase de modelación de procesos.

1. Un subproceso puede contener más de un lane?
2. Si hay una bifuración (gateway) de tipo A, y esta vuelve a converger más tarde, tiene que converger también en una de tipo A, o puede ser de tipo B? (Por ejemplo, si uso un gateway basada en eventos, puedo convergerla en una paralela?) 

Muchas gracias <3

**Comment by mimadri** [comment]
Hola!
1. Para el nivel de complejidad que les pedimos en la tarea no es necesario que utilicen subprocesos, ya que habría que entrar en detalle de qué son los subprocesos embebidos, reutilizables, múltiples, entre otros.
2. Cada vez que haya un gateway que divida el flujo, debe converger con el mismo tipo de gateway. Cabe destacar que hay algunas combinaciones que pueden ir de la mano, como los gateways basados en eventos con los exclusivos.  
Saludos :)
