### ISSUE TITLE
Repositorio

### ISSUE THREAD

**Issue by Baelfire18** [Exploratorio-DCC-PUC/Syllabus#284]
Al repositorio de la TC4 solo se le debe agregar el bpmn en formato .pdf y puede tener cualquier nombre?

**Comment by Pyralspite** [comment]
Hola!

Sip, cualquier nombre. Lo único importante es que el diagrama se entregue como pdf. Solo en caso de que hayan hecho algún supuesto, también deben incluir un segundo pdf con los supuestos. 
Saludos :3
