### ISSUE TITLE
Cómo correr TChica.pyc si tengo python 3.8 en Windows?

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [Exploratorio-DCC-PUC/Syllabus#287]
- Ve a la página de python y descarga python 3.7

- Instálalo, pero **no agregues esta versión de python al path**, recuerda donde quedó instalado, por ejemplo: "C:/Users/alvar/AppData/Local/Programs/Python/Python37/python.exe"

- Abre una consola de git en la carpeta donde tienes TChica.pyc y escribe los siguientes comandos:

    ```alias python='winpty C:/Users/alvar/AppData/Local/Programs/Python/Python37/python.exe'```

    ```python TChica1.pyc digito```

    donde dígito es el último dígito de tu número de alumno. 

Deberían empezar a imprimirse unos porcentajes hasta alcanzar el 100%, se habrá creado la carpeta que necesitas para trabajar.

**Comment by mateogs** [comment]
funcionó graciass

**Comment by kvonstorch** [comment]
Hola, me sale `winpty: error: cannot start 'C:UsersmaxivAppDataLocalProgramsPythonPython37python.exe': Not found in PATH 
` que puedo hacer?
