### ISSUE TITLE
Se cierra TChica1.pyc al intentar abrirla

### ISSUE THREAD

**Issue by patriciavsy** [Exploratorio-DCC-PUC/Syllabus#288]
Hola! no se si estoy haciendo algo mal, pero me pasa que al intentar ejecutar los comandos del pdf en la terminal que se abre, esta terminal se cierra y no se por qué. Dura menos de un segundo abierta.

**Comment by JupaOlivares** [comment]
Hola! Se generan por lo menos los archivos de la tarea? en el mismo repositorio se te deberia generar una carpeta con multiples carpetas adentro.
