### ISSUE TITLE
carpeta padre

### ISSUE THREAD

**Issue by amardones23** [Exploratorio-DCC-PUC/Syllabus#289]
Hola
Cuando me piden crear un archivo en la carpeta padre, se refiere a la carpeta anterior a la que me encuentro en ese momento, o a la primera carpeta de todas (que creo que vendría siendo tc1-2020-2-usuario ) ??

**Comment by ValentinaAlvarezG** [comment]
Hola!
La carpeta padre sería la generada, es decir, TareaChica1
