### ISSUE TITLE
Enunciado Tarea

### ISSUE THREAD

**Issue by bmurtagh01** [Exploratorio-DCC-PUC/Syllabus#29]
Hola tengo un duda en cuanto el enunciado.
En el caso 7 y 8, por ejemplo, cuando me dicen que yo ya curse el curso, puedo asumir eso en mi codigo (por lo tanto no revisar si efectivamente lo curse o no) o debo en todos estos casos revisar en mis archivos si lo que se me dice es efectivo??

**Comment by ValentinaAlvarezG** [comment]
Debes asumirlo no más
