### ISSUE TITLE
Mover varios archivos simultáneamente en la terminal

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#290]
Hola!!! Estoy complicada con esta parte de mover archivos que parten con el mismo nombre y tienen la misma extensión. Los logré encontrar con find pero ahora quiero moverlos a otra carpeta. Sé que el comando mv me serviría pero sólo podría moverlos de a uno, ¿Tengo que moverlos de a uno? (son hartos jajaja)

Gracias!!!

**Comment by ValentinaAlvarezG** [comment]
Hola!
Efectivamente son hartos jaja es la idea de la tarea, solo puedo decirte que se mueven mover más de un archivo a la vez.
