### ISSUE TITLE
Espacios en nombre del archivo

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#291]
Cuando ejecuto el codigo de python en mi carpeta personal, un archivo tiene un nombre complejo, en este caso: "Familia Cruz Busse", osea con espcios. Como escribo esos espacios en el GIT Bash?

**Comment by ValentinaAlvarezG** [comment]
Hola!
Puedes ver si esto te funciona? 

https://platzi.com/discusiones/1557-git-github/18101-alguien-sabe-como-llamar-un-directorio-con-espacios-en-su-nombre-ej-mis-docs-con-git-bash-he-intentado-con-comillas-y-comilla-y-nada-2/
