### ISSUE TITLE
¿En el primer paso al mover los archivos debo mantener sus nombres originales?

### ISSUE THREAD

**Issue by ferperezh** [Exploratorio-DCC-PUC/Syllabus#293]
En el primer paso pude encontrar todo los archivos con tareachica1*.bla pero al moverlos quiero poner todos esos archivos con el mismo nombre? se puede?

**Comment by ValentinaAlvarezG** [comment]
Hola!
Si, el nombre debe mantenerse. Cuando mueves archivos a una carpeta existente, se mantienen los nombres.
