### ISSUE TITLE
¿que es .DS_Store?

### ISSUE THREAD

**Issue by RocioOpazo** [Exploratorio-DCC-PUC/Syllabus#294]
¿a alguien le apareció el archivo ".DS_Store"? honestamente, no se que hace, pero no se si va a pasar algo malo si lo borro, de modo que quería saber si se supone que debe aparecer.

**Comment by JupaOlivares** [comment]
Hola, son archivos generados por los computadores mac, el borrarlos no deberia afectar el funcionamiento de tu computador (sobre todo si usas windows o linux)

**Comment by JupaOlivares** [comment]
Encontre este link en wikipedia que habla sobre ellos https://es.wikipedia.org/wiki/.DS_Store , por si te interesa.
