### ISSUE TITLE
Capturas de pantalla

### ISSUE THREAD

**Issue by mtaguero** [Exploratorio-DCC-PUC/Syllabus#297]
Hola, cuando ejecutamos los comandos para pasar a otro paso, ¿debemos explicar cada comando (Como por ejemplo cd/ubicación) o solo debemos sacar pantallazo de los comandos importantes (Por ejemplo, cat y no cada vez que cambiamos de ubicación (cd))?

**Comment by ValentinaAlvarezG** [comment]
Hola!
Deben explicar cada comando que uses para lograr completar la tarea,  qué es lo que hace ese comando y el pantallazo. Si explicaste una vez como funciona cd, no es necesario que lo digas de nuevo, pero si por ejemplo indicar a la carpeta final a la que te diriges. Puedes sacar un pantallazo de toda la ejecución por ejemplo de los cd juntos.
