### ISSUE TITLE
Mi carpeta TareaChica1 no aparece

### ISSUE THREAD

**Issue by LukasGuthrie** [Exploratorio-DCC-PUC/Syllabus#299]
Hola! No sé que hice o que pasó pero en mi repositorio personal ya no veo el directorio de tareachica1, por si lo pueden ver porfavor

**Comment by ValentinaAlvarezG** [comment]
Hola! pero lo habías podido generar? lo subiste al repositorio o slo estaba local en tu computador?

**Comment by LukasGuthrie** [comment]
sii, si lo había podido generar pero algo hice que ya no está

**Comment by ValentinaAlvarezG** [comment]
Lo puedes generar de nuevo corriendo los comandos del enunciado. Por lo que veo no lo pudiste subir a tu repo, así que tendrías que generarlo de nuevo.
