### ISSUE TITLE
Carpeta ayudantias de los jugadores

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#3]
En el enunciado aparece que cada jugador tiene una carpeta de ayudantías, sin embargo no existe en mi repositorio, nose si se habrá descargado mal o hay que crearla nosotros.

**Comment by ValentinaAlvarezG** [comment]
Hola!

Hubo un error al crear el repositorio que se les entregaba a ustedes. Subiré un anuncio al respecto, pero básicamente tendrán que crear ustedes esas 4 carpetas (una carpeta para cada jugador) tal como se indica en la parte de estructura de directorios del enunciado.
