### ISSUE TITLE
Me adelanté y no sé qué poner en el piso 3

### ISSUE THREAD

**Issue by FloValdes** [Exploratorio-DCC-PUC/Syllabus#3]
Hice el tutorial de CodeAcademy, le saqué foto e hice commit de la foto. Después hice el piso 1, respondí en el readme e hice otro commit. En el piso 2 puse de respuesta el último commit que hice (el del piso 1) pero al llegar al piso 3 no sé que poner, ¿cambio mi respuesta del piso 2 por el hash del primer commit como si nunca hubiera hecho uno yo antes del piso 3? ¿O dejo la del piso 2 y en el piso 3 pongo solo el hash del commit del piso 2?

Gracias!

**Comment by figarrido** [comment]
Hola, no hay problema con que hayas hecho commits antes.

Deja las respuestas que ya pusiste en el piso 2. Luego continúa normalmente.

**Comment by FloValdes** [comment]
Gracias
