### ISSUE TITLE
uso de comando read

### ISSUE THREAD

**Issue by Margarita-Paz** [Exploratorio-DCC-PUC/Syllabus#30]
para mis códigos, al momento de necesitar información de un jugador, curso o evento es factible preguntárselo al usuario y usar el comando "read"?

**Comment by ValentinaAlvarezG** [comment]
Esta información no se la preguntas a algún usuario, los archivos están y solo debes leerlos. Para esto utilizas otro comando que lee datos de archivos y muestra su contenido.
