### ISSUE TITLE
"No tengo repositorios"

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#300]
Hola, resulta que estoy bastante confundido, quería saber que debería haber o no en mi cuenta de github, como para ponerme al dia. Seleccione mi nombre en el link de la tarea que esta en el pdf pero aparece que no tengo repositorios, ni publicos ni privados, me gustaria saber si me pueden ayudar con esto gracias.

**Comment by ValentinaAlvarezG** [comment]
Hola!
Este es tu repositorio, si se creó.

https://github.com/Exploratorio-DCC-PUC/tc1-2020-2-SmokeAndMirrorsIKILLY

Este es el que deberías clonar y donde deberías subir tu tarea.

**Comment by Ikilly0** [comment]
Muchas gracias!
