### ISSUE TITLE
¿solo en terminal?

### ISSUE THREAD

**Issue by RocioOpazo** [Exploratorio-DCC-PUC/Syllabus#301]
me preguntaba si todos los procesos deben de hacerse en el terminal, para el paso en el que estoy se me ocurre una manera de hacerlo en Python, y en las instrucciones sale que hay que tener Python, ¿o hay que solo hacer los comandos en el terminal?

**Comment by ValentinaAlvarezG** [comment]
Hola! Si, todos los comandos deben ser ejecutados solo por la terminal, ya que precisamente el objetivo de la tarea es que aprendan a usarla. Python lo necesitan solo para generar la carpeta de trabajo.
