### ISSUE TITLE
Grafico de Torta

### ISSUE THREAD

**Issue by DaToMC9** [Exploratorio-DCC-PUC/Syllabus#31]
Para hacer mi grafico de torta considerare los 10 generos mas escuchados, mi pregunta es:
¿Tomo los 10 generos como el 100% de los datos o le agrego una categoria "Otro" que contenga a todos los generos restantes?

**Comment by zaertis0** [comment]
Pero se puede poner como un 11va categoría como otros ya que se sabe la cantidad de todos los datos??
