### ISSUE TITLE
Tarea Grande, libreria os

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#31]
Se puede utilizar la libreria os para la tarea grande? Es que como en la parte 1 trabajo en la carpeta /parte_1 y los datos estan en una carpeta /dataset y estos estan en el mismo nivel, es decir, tengo que "devolverme un directorio" para acceder a la otra carpeta.

**Comment by diflores** [comment]
¡Hola!

Deberías poder "devolverte" de forma similar a como lo harías en consola, con `../`. Así, puedes acceder a algún archivo en la carpeta `dataset` de la siguiente manera: `../dataset/nombre_archivo.extensión_archivo`.

Te recomiendo cargar los _datasets_ utilizando la librería `pandas`.

¡Saludos!

**Comment by perezpefaur** [comment]
Gracias!
