### ISSUE TITLE
Contar archivos de la carpeta padre

### ISSUE THREAD

**Issue by FelipeLara00** [Exploratorio-DCC-PUC/Syllabus#313]
Hola! Tengo la duda de como contar bien los archivos totales para el paso 3 ya que en internet hay varias formas para contar, algunas cuentan los directorios y otras no. He probado con 3 numeros distintos pero ninguno me da el resultado correcto.

**Comment by FelipeLara00** [comment]
Sigo teniendo problemas,me entrega un numero pero los ultimos 3 digitos me dejan en una carpeta con SubSubSubCarpetas. Mi duda es si esta mal lo que hago o falta agregar un digito para que entre a alguna de esas SubSubSubCarpetas?

**Comment by ValentinaAlvarezG** [comment]
Hola! puede ser que en los pasos anteriores te haya faltado agregar un archivo o puede que hayas agregado más de los que debías. A veces pasa que en el camino cuando uno no conoce bien los comandos puede ir haciendo cosas que afectan a este número que nosotros esperamos. Tienes dos opciones:  (1) ahora que ya sabes bien cuales son los comandos a usar, intentar hacer la tarea de nuevo de corrido con los comandos que deberías tener anotados, (2) Dado que este es el último paso de la tarea, puedes simplemente dejarlo hasta ahí, nosotros corregiremos que los comandos hasta encontrar la cantidad de archivos, sean los correctos, no importa si no llegan hasta el archivo final.
