### ISSUE TITLE
Problemas al sincronizar repo local con el del sitio web

### ISSUE THREAD

**Issue by VichoAburto** [Exploratorio-DCC-PUC/Syllabus#315]
Hay una carpeta que está en una ubicación específica en mi repo local, en cambio, en el de github me aparece doble, en la ubicación anterior y la nueva. Cómo puedo eliminar esa carpeta antigua, o hacer que se actualice bien??

**Comment by JupaOlivares** [comment]
Entonces al actualizar el repositorio online con add, commit, push desde tu repositorio local se deberia eliminar la repetida online

**Comment by VichoAburto** [comment]
Buenaa, al final puse "git add .", commit y push, y ahí funcionó. Graciass. Btw, que significa el "." del git add?

**Comment by ValentinaAlvarezG** [comment]
Con el punto agregas la carpeta donde estás, de manera recursiva si no me equivoco. En este link puedes leer un poco sobre las diferencias entre las formas que hay de hacer ``git add`` https://stackoverflow.com/questions/26042390/git-add-asterisk-vs-git-add-period

**Comment by JupaOlivares** [comment]
> Btw, que significa el "." del git add?

Muy buena pregunta!
El punto "." es la forma con la que el computador entiende que te estas refiriendo a la carpeta local o a la direccion en la que estas parado, esto es por convencion en el uso de rutas de la terminal. si haces "cd Desktop" es lo mismo que hacer "cd ./Desktop" (porque te estas moviendo de un directorio en el que estas situado a desktop o escritorio). Como ejemplo puedes tomar el doble puntuacion ".." que sirve para referirse a la carpeta padre de la que estas parado, si haces "cd .." te devuelves un nivel o "subes" a la carpeta padre con respecto a la que estabas situado.  (Aca te dejo otro link que habla sobre como son las rutas https://desktop.arcgis.com/es/arcmap/10.3/tools/supplement/pathnames-explained-absolute-relative-unc-and-url.htm)
Exito!
