### ISSUE TITLE
no me deja "subir" en la terminal para leer entradas anteriores

### ISSUE THREAD

**Issue by a-ck** [Exploratorio-DCC-PUC/Syllabus#318]
Solo puedo leer las cosas que caben en la terminal en ese momento, como que no hay scrollbar ni tampoco puedo subir con mi pad ni nada :/

**Comment by JupaOlivares** [comment]
Hola! que terminal ocupas? no te funciona mover 2 dedos a la vez para desplazar el texto?

**Comment by a-ck** [comment]
no, no funciona con 2 dedos a la vez tampoco. Mira no estoy segura pero creo que pasó después de que cambiara algunas cosas en options > window. La cosa es que no sé exactamente qué cambié ni cómo viene por default

**Comment by JupaOlivares** [comment]
Prueba ocupando los botones pg up y pg down! esos son los botones que hacen de ruedita de mouse por default a veces tiene que meterle un shift boton para funcionar (Peor de los casos no funciona y estas obligada a conseguirte un mouse jajaja)
Exito!
