### ISSUE TITLE
Borrar un commit en la nube

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#319]
Hola, hice un commit de la parte 1 y 2 pero estaba malo, osea lo hice incompleto. Hice git reset --hard Head ~1 y se borró mi ultimo commit, pero no se como hacer que esto ocurra aca en la nube en github.

**Comment by JupaOlivares** [comment]
Hola me parece que tienes que hacer push para que se actualice el repo de Github, si tienes mas problemas manda pantallazo de lo que te aparece para poder ver tu situacion.
