### ISSUE TITLE
[Gráfico de líneas] - No muestra las etiquetas de los datos

### ISSUE THREAD

**Issue by VicenteVicenteVicenteVicenteVicente** [Exploratorio-DCC-PUC/Syllabus#32]
Solo sucede con este tipo de gráfico, si lo cambio a uno de barras, por ejemplo, estas sí aparecen. ¿Qué puedo hacer para solucionar este problema? 🤯

**Comment by diflores** [comment]
Tienes que entregar los labels tú. [Aquí](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.pie.html) puedes ver la documentación del gráfico de torta.

¡Saludos!

**Comment by VicenteVicenteVicenteVicenteVicente** [comment]
Pero es un gráfico de líneas, no de torta 😿, de todos modos, lo solucioné poniendo manualmente cada etiqueta con el comando:
`plt.xticks([posiciones], [nombres])`
Si es que hay algún otro método más óptimo para solucionar este problema con los gráficos de líneas, sería muy útil 😸

¡Saludos!
