### ISSUE TITLE
[Espacios][Error] [Bash] [Winpy] "winpy cannot start" 

### ISSUE THREAD

**Issue by matyjjn14** [Exploratorio-DCC-PUC/Syllabus#320]
Hola, desde el día de la ayudantía que he tenido problemas con obtener la tarea ya que tenía la version 3.8. Seguí los pasos que nos recomendaron ( descargando 3.7) pero el código no me funciona, me aparece lo siguiente: 
![image](https://user-images.githubusercontent.com/64443045/90988523-622e2080-e561-11ea-90a9-4896e86bbe1e.png)
Porfa que alguien me ayude uwu, de antemano gracias.

**Comment by matyjjn14** [comment]
Al parecer no se ve bien en la imagen, adjuntare un word con ella.
[Problema compu.docx](https://github.com/Exploratorio-DCC-PUC/Syllabus/files/5114970/Problema.compu.docx)

**Comment by JupaOlivares** [comment]
Hola! puede ser que no estas corriendo el comando en una sola linea?

**Comment by matyjjn14** [comment]
lo hice y ahora me sale esto: **winpty: error: cannot start 'C:UsersMatías': Not found in PATH**
![image](https://user-images.githubusercontent.com/64443045/91079029-81848680-e611-11ea-823a-d97518c2c95d.png)

**Comment by ValentinaAlvarezG** [comment]
Puedes intentar con / en vez de \?

**Comment by matyjjn14** [comment]
lo intente y ahora me aparece esto
![image](https://user-images.githubusercontent.com/64443045/91086805-6ae42c80-e61d-11ea-86cc-4ede7f45075c.png)

**Comment by matyjjn14** [comment]
se cortó el primer comando pero si lo cambio a una linea me arroja lo mismo

**Comment by ValentinaAlvarezG** [comment]
Ah, lo que pasa es que tienes una carpeta con espacios, puedes intentar con algunas de las cosas que salen en este link? https://stackoverflow.com/questions/24557224/git-bash-path-cannot-parse-windows-directory-with-space

**Comment by matyjjn14** [comment]
ahora sí!!, muchas gracias
