### ISSUE TITLE
Problemas en abrir TChica1

### ISSUE THREAD

**Issue by BenitoOl** [Exploratorio-DCC-PUC/Syllabus#321]
es un problema que han comentado mucho pero yo aun no logro abrirlo, trate desde Python/Python37-32 (que fue donde me dijo que se guardaria) y desde Python/Python37 que es donde yo veo que esta guardado (la version 3.7.x de python que tengo)
![IMG_5714](https://user-images.githubusercontent.com/69522774/90991435-0a9aaf80-e577-11ea-8e09-f1035b565a1b.jpg)

**Comment by Njcampos1** [comment]
Hola, prueba a ejecutar git bash, directamente sobre la carpeta en la que tienes los archivos Readme y TareaChica, y luego aplicar los comandos dependiendo de tu sistema operativo

**Comment by BenitoOl** [comment]
mmm trate y me dice que no existe tal carpeta aunque la este viendo, deberia borrar y volver a descargar?

**Comment by ValentinaAlvarezG** [comment]
Hola! Donde abres la consola de git cuando corres ``python TChica1.pyc`` ?
