### ISSUE TITLE
Untracked files ?

### ISSUE THREAD

**Issue by joalonsosch** [Exploratorio-DCC-PUC/Syllabus#322]
Hola!
Recién me metí a mi repositorio personal e hice "git bash here", luego "git status", a lo que me respondió:

It took 2.11 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').

Pensé que podía estar desactualizado o algo e hice "git pull", a lo que me respondió que estaba al día.
Después hice "git status -uno" y me tiró un texto parecido al de arriba, diciéndome que tenía "untracked files".
Que pasó y que debo hacer para solucionarlo?

Gracias de antemano

**Comment by joalonsosch** [comment]
Hola de nuevo,
Vuelvo a escribir porque hace poco volví a abrir git bash en mi repositorio personal clonado y volví a hacer los pasos anteriores recibiendo los mismos comentarios. Probé hacer "git add ." y me arrojó lo siguiente:

fatal: Unable to create 'C:/Users/Jos├® Alonso/tc1-2020-2-joalonsosch/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

Unos días antes hice un "git commit" pero no me dejaba hacer nada con él, así que decidí cerrar git bash en vez de hacer git push, creo que ese puede ser el causante del error por lo que dice arriba, pero no se como arreglarlo, ya que no se que debería remover manualmente, la carpeta TareaChica1?

Gracias por su tiempo

**Comment by ValentinaAlvarezG** [comment]
Hola! puedes intentar con lo que dice acá? A otros alumnos que les pasó lo mismo les funcionó esto. 

https://stackoverflow.com/questions/38004148/another-git-process-seems-to-be-running-in-this-repository

**Comment by joalonsosch** [comment]
Hola!
Gracias por tu respuesta. Antes de verla vi otra en la que alguien preguntaba como "reiniciar" la tarea, a lo que el ayudante respondió que si no tenía commits podía borrar la carpeta clon del repositorio personal y partir desde 0. Como yo no tenía ningún commit hice eso y me funcionó bien, partí desde 0 pero ahora si pude hacer add commit y push, así que solucionó mi problema.
Nuevamente gracias por la respuesta de todos modos, buenas tardes.

**Comment by JupaOlivares** [comment]
> a lo que el ayudante respondió que si no tenía commits podía borrar la carpeta clon del repositorio personal y partir desde 0. 

Hola! Debi haber sido yo jajaja, si bien funciona y me ha sacado de aprietos... Me gustaria aclarar que es una opcion muy poco "correcta" porque la idea de git es crear un espacio donde se registren todos los cambios y poder desarrollar proyectos. Con esta opcion nos estamos "saltando" todas las herramientas que tiene git para arreglar situaciones como esta, arriesgandonos a perder cambios hechos y no registrados.

Exito! y que bueno que hayas solucionado tu problema

**Comment by joalonsosch** [comment]
Hola @JupaOlivares, agradezco tu comentario.

Por el nivel de progreso en el que estaba mi tarea, no fue mucha la pérdida al partir de cero. Donde creo que tienes toda la razón es cuando dices que "con esta opción nos estamos 'saltando' todas las herramientas que tiene git para arreglar situaciones", ya que hoy abrí git bash de nuevo en mi repo personal clonado y haciendo git status volví a recibir un mensaje parecido al que puse al principio.

No quiero darte la lata, pero te cuento un resumen general de lo que ha sido mi uso de git bash, a ver si me puedes ayudar a solucionar el problema: Cloné mi repo personal en mi computador, generé la carpeta TareaChica1, luego hice git add . y después git commit (sin el -m "mensaje"). Ahí me devolvió un montón de lineas y un texto que decía que había commiteado mal, por lo que en vez de hacer git push cerré git bash. Luego de eso cada vez que me metí a git bash e hice git status me salió el mensaje que puse al principio de la issue, por lo que decidí no commitear mis avances. Como desde github salía que no tenía hecho ningún commit en mi repo personal fuera del inicial hecho por el profe, borré el repositorio clonado como mencionabas en otra issue. Cloné de nuevo el repo, generé de nuevo la carpeta TareaChica1 e hice git add . luego git commit -m "un mensaje" y finalmente git push, lo que no arrojó ningún problema. Verifiqué que se hubiera hecho el commit en mi repo en github y todo bien. No seguí avanzando. Hoy quería avanzar así que entre a git bash desde mi repo personal clonado, hice git pull y no hubo problemas, hice git status y me salió esto:

On branch master
Your branch is up to date with 'origin/master'.


It took 3.43 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
nothing to commit, working tree clean

Después hice git status -uno y me dijo esto:

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit (use -u to show untracked files)

Hice git status -u y me arrojó el mismo texto que al hacer git status antes, solo que en vez de "3.43 seconds" me dijo "2.22 seconds". A pesar de que no tenía nada que commitear, porque no había vuelto a avanzar, hice git add . después git commit -m "un mensaje" (donde de nuevo me dijo lo mismo que al hacer git status con otra cantidad de segundos) y git push, a lo que me dijo que todo estaba al día y no subió nada (no había nada que subir tampoco). Me metí a github y en mi repo personal no salía ese nuevo commit, así que cerré git bash, lo abrí de nuevo y repetí los pasos desde el git status en el mismo orden, donde salió lo mismo siempre solo que con otra cantidad de segundos.

Como no he avanzado, es lógico que no guarde nuevos commits cuando se los pido, pero es raro que me siga apareciendo el mensaje y no se si será un problema o si debería solo ignorarlo y avanzar con la tarea.

Perdón por escribirte tan largo, espero no molestar. Quedo atento a cualquier comentario, muchas gracias

**Comment by JupaOlivares** [comment]
@joalonsosch No te preocupes por esos mensajes, como explique por la ayudantia es normal que hayan "untracked files" para que te dejen de aparecer tienes que hacer git add --all, y tambien en este caso es normal que se demore tanto el git status, dado que se generan aproximadamente 30.000 archivos con el pyc por lo que es dificil hacer seguimiento de tantos archivos, lo que te debes cerciorar es de poder hacer minimo 2 commits efectivos (son requisitos para la tarea) uno despues de crear la carpeta y otro despues de terminarla. Para esto asegurate de hacer git add --all primero y git push al final, ademas de agregar -m para tener un mensaje **descriptivo** del commit (tambien es requisito ajjaajja)
Suerte!

**Comment by joalonsosch** [comment]
Hola @JupaOlivares, gracias por tu respuesta.
Por suerte había hecho git add, commit y push tras generar la carpeta TareaChica1 al inicio con su respectivo mensaje. No hice git add --all, sino que hice git add ., puede que ahí esté el tema de las untracked files. Igual hoy terminé la tarea e hice git add --all (como me habías dicho en la ayudantía), commit (con su mensaje) y push. Verifiqué y se subió correctamente a github, además que ya no me muestra el comentario de las untracked files al hacer git status, ¿será que ese git add --all del final lo solucionó? Aprovecho para preguntarte por git commit -a, ¿ese comando commitea de nuevo a todo lo que alguna vez hice add, o sea "sobrescribe" los commits "individuales" que había hecho antes? Lo pregunto porque no he querido usarlo pensando que podría pasar eso y no quiero perder el tema de tener la cantidad de commits que se piden, además de que no sería muy buen control de versiones si sobrescribo todo y queda una única versión final.
Gracias desde ya.

**Comment by JupaOlivares** [comment]
Hola @joalonsosch! Me encanta tu curiosidad jajajaja

el flag -a en git commit es utilizado para "trackear" cambios sobre archivos sobre los cuales ya se ha hecho seguimiento ("git add"), por lo que te ahorras el uso de este ultimo comando. Sirve cuando editaste un archivo que ya ha sido agregado o editado antes, (yo por lo general no lo ocupo). Por otro lado, no hay cantidad maxima de commits que se pida asi que sientete libre de jugar con los comandos (mientras tengas tiempo de arreglar posibles errores, no es buena idea hacerlo horas antes de la fecha de entrega jajaja...). Lo que revisamos nosotros es el **ultimo commit pusheado  antes de la fecha de entrega.**

Te invito a revisar la documentacion de git para mas dudas y preguntar por aca lo que no tengas claro.
Suerte!

**Comment by joalonsosch** [comment]
Hola @JupaOlivares, gracias por la respuesta y el comentario!

Me quedó claro, probé hacer git add --all y git commit -am "mensaje" para terminar con git push pero no tenía cambios en mi repositorio desde el último commit, así que voy a probarlo una vez haga algún cambio (no dentro de la tarea actual porque ya la entregué).
Sobre el mismo tema, me metí a github a ver si había subido bien las modificaciones de la carpeta TareaChica1 y el pdf y pude ver que lo primero está todo bien, pero cuando abro la vista previa del pdf de mis comandos en github hay algunas imágenes que no se ven y comandos que no están (se nota porque les puse números y de repente se ve que pasa del 13 al 21 por ponerte un ejemplo).
¿Qué debería hacer? Mi pdf se ve bien desde mi computador, desde el clon de mi repo personal, desde google drive, pero solo se ve mal en la vista previa de github ¿será que no influirá a la hora de que descarguen los pdfs para revisarlos, o debería subirlo de nuevo?

Desde ya muchas gracias y buen domingo!

**Comment by JupaOlivares** [comment]
Hola nosotros lo vamos a revisar descargando el PDF! asi que si al descargarlo se ve bien no hay problema!
Exito

**Comment by joalonsosch** [comment]
Buenísimo @JupaOlivares, te pasaste por la ayuda y también tú @ValentinaAlvarezG. Lo descargué desde github y se ve bien, así que confiaré en eso jajajaja de nuevo gracias y buena semana a ambos!
