### ISSUE TITLE
Carpeta TareaChica1

### ISSUE THREAD

**Issue by nsancha** [Exploratorio-DCC-PUC/Syllabus#323]
Hola, tengo un problema no logro crear la carpeta al inicio, pongo los comandos  alias python=’winpty python.exe’ y python TChica1.pyc 3 pero no pasa nada, no me esta creando la carpeta. tenia instalado python 3.8.5 y no me funcionaba, lo des-instale e instale el 3.7.7 y sigue sin funcionar

**Comment by joalonsosch** [comment]
No soy ayudante, pero ojo con las comillas, tienen que ser como esta ' y no como esta ´. En tu comentario arriba pusiste las que no deben ser, verifica si también pones esas en git bash, suerte ;)

**Comment by ValentinaAlvarezG** [comment]
Hola! como indica tu compañero es importante que tengas cuidado con las comillas. Si aún no te funciona, puedes mandar un pantallazo con la ejecución? para poder ver que otro problema podría ser.

**Comment by nsancha** [comment]
Ya lo logre, gracias igual

**Comment by Ikilly0** [comment]
Hola, como lo lograste?  tengo el mismo problema

**Comment by nsancha** [comment]
Desinstale ambos python y descargue nuevamente el 3.7.7 y durante la instalación te pregunta si lo quieres agregar al path, pon que si y funciona

**Comment by Ikilly0** [comment]
Hise eso mismo jaja, sigue sin decirme nada despues del primer comando pero el segundo me tira error y me dice que TChica1.pyc no esta en el path
