### ISSUE TITLE
contar numero de archivos

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#324]
Hola, pude contar el numero de files y me dio 29073, pero cuando voy a Carpeta0, SubC7,SubSubC3, no está el siguiente paso. Qué puedo hacer?

**Comment by ValentinaAlvarezG** [comment]
Hola! puede ser que en los pasos anteriores te haya faltado agregar un archivo o puede que hayas agregado más de los que debías. A veces pasa que en el camino cuando uno no conoce bien los comandos puede ir haciendo cosas que afectan a este número que nosotros esperamos. Tienes dos opciones: (1) ahora que ya sabes bien cuales son los comandos a usar, intentar hacer la tarea de nuevo de corrido con los comandos que deberías tener anotados, (2) Dado que este es el último paso de la tarea, puedes simplemente dejarlo hasta ahí, nosotros corregiremos que los comandos hasta encontrar la cantidad de archivos (incluyendo este comando), sean los correctos, no importa si no llegan hasta el archivo final.

**Comment by vcrb18** [comment]
perfecto! Lo que pasa es que intente resetear la tarea pero como tenia un commit en el repositorio online no sé si al borrar la carpeta y hacer los pasos denuevo la estoy empezando de cero. Es decir, ya hice esto de partir de 0 y sigue sin funcionar, pero bueno si no funciona haré la opción 2 nomas

**Comment by vcrb18** [comment]
Ignorar mensaje anterior, lo logré y llegué a ElFin!

**Comment by ValentinaAlvarezG** [comment]
Ah bacan ! me alegro caleta
