### ISSUE TITLE
[Error] [Git] [Git-Bash] [Windows] "Another git process seems to be running..." 

### ISSUE THREAD

**Issue by LukasGuthrie** [Exploratorio-DCC-PUC/Syllabus#325]
Hola! por error de leer bien las instrucciones subí a mi repositorio personal la carpeta NombreApellido y cuando intento hacer git add TareaChica1/ me aparece esto
![2020-08-24 (2)](https://user-images.githubusercontent.com/69617185/91081589-5865f500-e615-11ea-86f9-6fc3c0d0c119.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! puedes intentar con lo que dice el siguiente link : https://stackoverflow.com/questions/38004148/another-git-process-seems-to-be-running-in-this-repository

**Comment by LukasGuthrie** [comment]
Funcionó, muchas gracias!
