### ISSUE TITLE
Al usar git status me muestra archivos "eliminados"

### ISSUE THREAD

**Issue by amardones23** [Exploratorio-DCC-PUC/Syllabus#326]
![WhatsApp Image 2020-08-24 at 22 17 47](https://user-images.githubusercontent.com/69521429/91115573-7f91e600-e658-11ea-9acb-98399ded1b4b.jpeg)
![WhatsApp Image 2020-08-24 at 22 17 06](https://user-images.githubusercontent.com/69521429/91115567-7dc82280-e658-11ea-9044-5f233d6c29c1.jpeg)

Hola como se ve en la primera imagen adjunta al usar git status me aparecen los archivos _tareaChica*.bla_ que moví a la carpeta _NombreApellido_, no se como corregir esto y me parece raro porque dicen "deleted" y no los he borrado solo los moví. Ahora quiero arreglar eso para hacer commit en los cambios.
Además como se ve en la segunda imagen, intenté git add con un archivo y no se que hacer con el comando que me salió.
porfis ayuda :( <3

**Comment by JupaOlivares** [comment]
Hola! 
Trata con git add --all de esta forma se van a agregar todos los cambios realizados sobre el repositorio de forma rapida! (esto porque por lo que dijiste no borraste los archivos solo los moviste). Puede ser que al mover archivos git perdio el "tracking" porque en verdad fueron copiados y pegados en otra parte. Comentanos lo que te aparezca!
Exito!

**Comment by amardones23** [comment]
ahí me funcionó, muchas gracias <3
