### ISSUE TITLE
¿Donde ubico el pdf?

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#327]
el archivo pdf tiene que ir en la carpeta padre(TareaChica1)? y después hay que hacer git add "archivo.pdf"?

**Comment by ValentinaAlvarezG** [comment]
Hola! No, el archivo debe ir antes de esto, onda en la carpeta del repositorio. Tu te metes a tu repo y se debe ver ahí mismo.
