### ISSUE TITLE
No puedo abrir Escritorio con comando cd

### ISSUE THREAD

**Issue by FelipeDavis** [Exploratorio-DCC-PUC/Syllabus#328]
Cuando intento usar el comando cd con Escritorio me sale No such file or directory
![image](https://user-images.githubusercontent.com/69520702/91231553-71e16c80-e6fb-11ea-94b9-fb20b82f92a5.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! Puede que tenga que ser Desktop? Si no te funciona puedes hacer ``ls`` ahí donde estás para saber que opciones tienes de moverte

**Comment by FelipeDavis** [comment]
Ok hice ls y no tengo la opción de Escritorio ni de Desktop. ¿Uso otra carpeta cualquier para clonar mi repositorio?
![image](https://user-images.githubusercontent.com/69520702/91231868-051aa200-e6fc-11ea-8c7b-019cbfb8ed3b.png)

**Comment by ValentinaAlvarezG** [comment]
Mmm puedes clonar tu repositorio en la carpeta que quieras en verdad. Si lo quieres dejar en escritorio puedes tratar de buscar la ruta donde está el escritorio o irte moviendo, o simplemente puedes hacer click derecho en el escritorio y clickear en Git Bash Here y abrir la consola ahí mismo.

**Comment by FelipeDavis** [comment]
Ok Escritorio estaba en OneDrive, por eso no lo encontraba. Muchas gracias
