### ISSUE TITLE
Error en Windows PowerShell

### ISSUE THREAD

**Issue by josefeliuf** [Exploratorio-DCC-PUC/Syllabus#329]
Hola! anteriormente todos los comandos me servían perfectamente pero ahora haciendo la tarea denuevo para sacar las screenshots, me indica el siguiente error: 

![errorgithub](https://user-images.githubusercontent.com/62085104/91245586-d1e80b00-e71b-11ea-814e-4937d1be2331.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! tienen que usar git bash para la tarea
