### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by totichi** [Exploratorio-DCC-PUC/Syllabus#33]
Quería consultar cuál era la ventaja de ocupar Atom como editor de css y HTML por sobre por ejemplo ocupar un bloc de notas.A simple vista no se ve fácilmente.

**Comment by diflores** [comment]
Atom tiene, en mi opinión ventajas como:

- Syntax highlighting para varios lenguajes
- Mucha personalización del editor
- Plugins útiles para git y otras cosas relevantes al desarrollo, por ejemplo.

La elección de un editor es un tema de gustos. Usa algo con lo que te sientas cómodo y productivo.

¡Saludos!
