### ISSUE TITLE
Como citar codigo en el pdf

### ISSUE THREAD

**Issue by sofiaolmedos** [Exploratorio-DCC-PUC/Syllabus#330]
Hola! Me entró la duda de cuando es necesario citar cosas. ¿Solo se cita cuando copio un código? O por ejemplo también tenemos que citar en la Tarea Chica 1 si buscamos información de algunos comandos
Gracias!

**Comment by ValentinaAlvarezG** [comment]
Hola! en este caso, como aparte de código tienen que explicar cosas, si buscas explicaciones de comandos y te vas a basar en eso para escribir tu explicación, deberías poner igual el link.

**Comment by joalonsosch** [comment]
Hola!
Perdón que me meta de la nada, quería saber que pasa si la información sobre lo que hacen los códigos la saqué de un pdf y no me se su url?

**Comment by ValentinaAlvarezG** [comment]
Hola!  Eeeeh puedes poner el nombre del pdf o algo así, que se entienda mas o menos de donde lo sacaste.
