### ISSUE TITLE
Descargue python 3.7.7 y no me funciona

### ISSUE THREAD

**Issue by jaimet99** [Exploratorio-DCC-PUC/Syllabus#331]
Hola! he escrito python con diferentes comillas, lo he copiado y pegado y no me funciona de ninguna manera. Me ha aparecido respuestas como "stdout is not tty", "winpty coomand not found","no such file in directory", "command not found", etc.
¿como lo hago para poder empezar la tarea?
![2020-08-26 (1)](https://user-images.githubusercontent.com/69590019/91348525-e4ad1f00-e7b1-11ea-830d-53f725278520.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! Tenias python 3.8 e instalaste python 3.7? de todos modos, en el caso cuando estás corriendo el comando con el path de donde está python 3.7 fíjate que estás copiando y pegando el mío (de mi computador) asumo que no tienes una carpeta ``alvar`` , ve donde está instalado python 3.7, que debería ser un path muy similar al mío pero probablemente con tu nombre, y ejecuta el comando con ese path. Avísame como te va.

**Comment by jaimet99** [comment]
si copie el tuyo que estaba escrito en otra issue y despues lo busque en donde estaba en mi pc pero no entendi como escribirlo como de otra manera

**Comment by ValentinaAlvarezG** [comment]
Eeeeh a veces es un poco difícil de encontrar, pero puedes intentar en el buscador de windows, o bien puedes cachar si está en una carpeta similar a la mía, onda anda en el explorador de archivos de windows anda a C: después a Users o Usuarios, de ahí busca cual es tu usuario y anda moviéndote así hasta encontrar python 3.7

**Comment by jaimet99** [comment]
lo encontre y la escribi de diferentes maneras utilizando mis datos de como ubicacion de python 3.7 y sigue sin funcionar
![2020-08-26 (3)](https://user-images.githubusercontent.com/69590019/91354825-44f48e80-e7bb-11ea-9f4c-bbf8c6fa480b.png)

**Comment by ValentinaAlvarezG** [comment]
Mmm es que creo que no es ese, porque son accesos directos los que se guardan ahí, puedes irte moviendo así en el explorador de archivos:?

``C:/Users/HP RADEON/AppData/Local/Programs/Python37/python.exe``

**Comment by jaimet99** [comment]
me lo cancela como por el espacio que existe en "HP RADEON" 
y en el buscador al incio de la pagina me aparece     C:\Users\HP RADEON\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.7

**Comment by jaimet99** [comment]
en el explorador si voy como retrocediendo desde donde lo encoenmtre entre el HP RADEON y app data no hay forma de llegar del primero al segundo

**Comment by ValentinaAlvarezG** [comment]
Osea, si po , en la terminal te va a dar dramas por los espacios, pero onda si te vas al explorador de archivos, puedes llegar a esa carpeta?, me interesaba saber si ahí esta realmente instalado ahí. En este link https://stackoverflow.com/questions/24557224/git-bash-path-cannot-parse-windows-directory-with-space puedes ver como trabajar con directorios que tengan espacio para hacerlo directo en la terminal. Y bueno por eso te decía que a veces es un poco complicado de buscar, porque en el buscador de windows te tira esos accesos directos. 

No entendí esto último que mencionaste de ir retrocediendo.

**Comment by jaimet99** [comment]
en la ultima foto que te mande, como en el buscador (arriba donde aparece este equipo) fui apretando desde python37 hasta que llegue a HPRADEON y no existia conexion entre estos dos ultimos, es decir, que si lo empiezo a buscar desde este qeuipo no deberia poder llegar a AppData para seguir avanando con mi busqueda

**Comment by ValentinaAlvarezG** [comment]
Mmm  a ver Pero no partas desde atrás, onda parte desde C: y trata de irte moviendo como te dije: Después Users, luego HP RADEON, después AppData, después Local, uego Programs y ahí Python37, ve si lo puedes encontrar así

**Comment by jaimet99** [comment]
esta guardado, pero cuando llego a "HP RADEON" no puedo seguir moviendome como dirigiendome a donde esta python

**Comment by ValentinaAlvarezG** [comment]
A que te refieres con que no puedes seguir moviéndote? onda no está la carpeta AppData?

**Comment by jaimet99** [comment]
no, no esta

**Comment by jaimet99** [comment]
y no entiendo porque si la busco, en  "abrir ubicacion del archivo" me aparece lo que mande antes, pero ahora no entiendo porque no aparece como buscandolo avanzando en las carpetas

**Comment by ValentinaAlvarezG** [comment]
Aaaaaaaah es que parece que esa carpeta es una carpeta oculta, 

![image](https://user-images.githubusercontent.com/26123660/91360777-124f9380-e7c5-11ea-8c43-07ba76c524fb.png)

En vista, marca que se puedan ver elementos ocultos, ahí vas a poder ver la carpeta.

**Comment by jaimet99** [comment]
logre hacer que se puedan ver lo elementos ocultos pero sigo sin poder hacerlo. No sera algo del pc que no funciona nomas?
![2020-08-26 (4)](https://user-images.githubusercontent.com/69590019/91361840-2a281700-e7c7-11ea-99cf-f0695be9fb25.png)

**Comment by ValentinaAlvarezG** [comment]
Tu tenías python 3.8? y onda lo desinstalaste o no lo desinstalaste? o solo tienes python 3.7 en tu computador?

**Comment by jaimet99** [comment]
tengo los dos
desinstale el 3.8 y instale el 3.7 y despues lo volvi a instalar el 3.8

**Comment by ValentinaAlvarezG** [comment]
Tienes alguno agregado al PATH?

**Comment by jaimet99** [comment]
no estoy seguro que esto es el PATH, pero supongo que es esto, 
C:/Users/"HP RADEON"/AppData/Roaming/Microsoft/Windows/"Menu Inicio"/Programas/"Python 3.7"/python.exe

**Comment by ValentinaAlvarezG** [comment]
mmm me refería a las variables de entorno. Algo como lo que sale en este link: https://datatofish.com/add-python-to-windows-path/     pero tienes que trabajar con el otro path, onda este C:/Users/HP RADEON/AppData/Local/Programs/Python37/python.exe, porque el otro segun yo no sirve porque son accesos directos de windows. De todos modos puedes en el explorador de archivos llegar hasta aca C:/Users/HP RADEON/AppData/Local/Programs/Python37/python.exe? para ver que efectivamente este instalado ahí

**Comment by jaimet99** [comment]
en el explorador de archivos no encuentra nada si busco exactamente esto C:/Users/HP RADEON/AppData/Local/Programs/Python37/python.exe
puede ser porque el pyton esta escrito como 3.7

**Comment by ValentinaAlvarezG** [comment]
Puedes mandarme un correo? creo que sale más fácil si lo solucionamos por ahí
