### ISSUE TITLE
[Errno 2] No such file or directory, No puedo crear la carpeta TareaChica1 

### ISSUE THREAD

**Issue by jfurriola** [Exploratorio-DCC-PUC/Syllabus#332]
Hola, instale python, creo que lo coloqué bien en el path, pero el segundo comando me arroja un error
![image](https://user-images.githubusercontent.com/69520599/91361301-03b5ac00-e7c6-11ea-8905-432520b6e444.png)

**Comment by JupaOlivares** [comment]
[Para efectos de si alguien tiene el mismo error]
Estaba mal escrito, le falto el 1 en "TChica.pyc"
