### ISSUE TITLE
[Bonus] Obtener bytes de cada archivo o de todos juntos.

### ISSUE THREAD

**Issue by RobinC-Jr** [Exploratorio-DCC-PUC/Syllabus#333]
En la tarea bonus, debo obtener la cantidad de bytes de cada archivo (Ej: 3 tc1.bla; 5 tc2.bla; 12 tc3.bla...) o de todos juntos (Ej: 447 total)? Y si uso un comando que me da ambos (Primero individuales y al final todos juntos) estaría bien?

**Comment by JupaOlivares** [comment]
Hola! 
Tengo entendido que es de todos juntos, mientras aparezca esta info no hay problema si aparecen los individuales.
Suerte!
