### ISSUE TITLE
formato pantallazo de los comandos, ¿debo incluir "cd"?

### ISSUE THREAD

**Issue by dasobarzo** [Exploratorio-DCC-PUC/Syllabus#334]
hola! en la TC1 dice "un pantallazo del comando siendo ejecutado en su computadora", este debe ser un pantallazo en donde este TODO junto u puede ser por partes(tipo primer paso un pantallazo, segundo paso un pantallazo...). Es que mi duda principal es que si en el pantallazo debe verse como retrocedí al directorio principal o carpeta madre.. o eventualmente en cada paso puedo empezar de 0.

**Comment by JupaOlivares** [comment]
Hola!
Puede ser por partes y tambien puedes omitir los "cd" (change directory) y empezar de 0. No es relevante el como te devolviste a las carpetas padres entre pasos (o si te dio lata devolverte y abriste y cerraste el terminal jajaja...)
Exito!
