### ISSUE TITLE
Termine la tarea pero no tengo pantallazos de lo que hice

### ISSUE THREAD

**Issue by andrius6789** [Exploratorio-DCC-PUC/Syllabus#335]
Hice toda la tarea pero al llegar al final me pregunte si era todo lo que tenia que hacer por lo que volví a leer "TC1.pdf" y me di cuenta que tenia que sacar pantallazos de todo lo que hice y crear un PDF con la explicación de mi tarea y que se vean los comandos. Que hago en vista de que ya cerré git bash?

**Comment by ValentinaAlvarezG** [comment]
Hola! pucha tienes que hacerlo de nuevo porque los pantallazos son parte de la tarea. Tendrías que borrar y generar la carpeta de trabajo de nuevo.
