### ISSUE TITLE
No puedo retroceder con ../

### ISSUE THREAD

**Issue by jfurriola** [Exploratorio-DCC-PUC/Syllabus#336]
Holaa, estoy intentando retroceder a la carpeta TareaChica1 pero no se si estoy ocupando bien '../' ya que no funciona.
![image](https://user-images.githubusercontent.com/69520599/91471417-11ba0a00-e864-11ea-8522-40bf30b88014.png)

**Comment by jfurriola** [comment]
![image](https://user-images.githubusercontent.com/69520599/91472070-f8658d80-e864-11ea-84c2-86f499c6605e.png)
ahi creo que se ve mejor xd

**Comment by ValentinaAlvarezG** [comment]
Hola! lo que pasa es que tienes que usar ``cd``, recuerda que ``cd`` es el comando que te permite cambiar al directorio que le indiques, por otro lado, ``../`` es el directorio padre, entonces si o si tienes que ocupar ambos.

En resumen, con ``cd`` le indicas que se mueva a ``../`` que es el directorio padre.
