### ISSUE TITLE
Tarea Chica 1 - paso 3.2

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#337]
Hola, estoy en windows, estoy teniendo problemas usando este commando, es la primera parte el punto 3.2 la que genera las carpetas.

![image](https://user-images.githubusercontent.com/69522095/91516644-668c6d80-e8c2-11ea-914d-8cd6f3187dce.png)

Lo que estaba tratando es esto:
![image](https://user-images.githubusercontent.com/69522095/91516739-a05d7400-e8c2-11ea-9f6d-e8a0f5e607fc.png)
 
Ahi llego a la carpeta, despues.

![image](https://user-images.githubusercontent.com/69522095/91516787-b79c6180-e8c2-11ea-9c4a-3a865f4a9047.png)

Despues me sale esto, tengo Python 3.7
![image](https://user-images.githubusercontent.com/69522095/91516813-cc78f500-e8c2-11ea-9fb0-d24b619e5d29.png)

Todavia no uso el python TChica1.pyc digito ya que no me funciona el anterior, o quizas debo usarlos juntos? Gracias.

**Comment by ValentinaAlvarezG** [comment]
Hola! copiaste y pegaste el comando? o lo escribiste tu? si es que lo copiste te recomiendo que lo escribas tu porque a veces tiene problemas con las comillas que se copian. Avísame si eso te funciona.

**Comment by Ikilly0** [comment]
No me funciono, ahora que lo escribo yo mismo y pongo enter no sale nada, estoy muy confundido jajaja.

![image](https://user-images.githubusercontent.com/69522095/91629942-a0817080-e9a3-11ea-984d-afe17c68e4ac.png)

**Comment by SmokeAndMirrorsIKILLY** [comment]
Debo decir que no estan apareciendo las carpetas, estoy un poco preocupado porque me estoy quedando sin tiempo, espero poder resolver esto rapido.

**Comment by Ikilly0** [comment]
Perdon por ver todo esto tan tarde, espero me alcance el tiempo

**Comment by JupaOlivares** [comment]
Hola!
 si tienes 3.7 tambien puedes probar el cmd.exe para crear los archivos. Con respecto al tiempo no te preocupes, tienes hasta el 1 de septiembre (fecha que aparece en el enunciado) para hacerla.
Exito

**Comment by Ikilly0** [comment]
Como es eso? Usar cmd? y como tendria que escribir los comandos?

**Comment by JupaOlivares** [comment]
El cmd es un tipo de terminal igual que el git bash, que viene por defecto en windows, prueba sin usar el alias

**Comment by Ikilly0** [comment]
trate con esto
![image](https://user-images.githubusercontent.com/69522095/91646163-a79b9380-ea22-11ea-9423-2882354ef5b3.png)
y despues esto
![image](https://user-images.githubusercontent.com/69522095/91646166-b124fb80-ea22-11ea-8334-034924e41be2.png)

siento que hay algo muy basico que estoy haciendo mal ya que ninguno funciona bien, apreto enter y no sucede nada.

**Comment by JupaOlivares** [comment]
Podrias mandar una foto mas completa? no alcanzo a ver los outputs y de paso podrias correr python --version

**Comment by Ikilly0** [comment]
![image](https://user-images.githubusercontent.com/69522095/91646406-2f829d00-ea25-11ea-8e8c-9ad00fce8d31.png)

**Comment by Ikilly0** [comment]
algo anda mal parece, python --version tampoco funciono, que podria ser?

**Comment by Ikilly0** [comment]
Quizas algo de la terminal no esta bien o estoy colocando mal los archivos?
![image](https://user-images.githubusercontent.com/69522095/91647984-1cc59380-ea38-11ea-9264-3f2d6d401234.png)

**Comment by ValentinaAlvarezG** [comment]
Tienes instalado python 3.7? y lo otro, puedes intentar corriendo ``python3 --version`` o ``py --version``  a ver si con alguno de esos funciona. Si es que tienes python instalado, lo tienes agregado a las variables de entorno?

**Comment by Ikilly0** [comment]
![image](https://user-images.githubusercontent.com/69522095/91648071-7aa6ab00-ea39-11ea-8831-6fda6dc4b107.png)

**Comment by Ikilly0** [comment]
Ahi esta, el segundo funciono
No estoy seguro de lo que son las variables de entorno

**Comment by ValentinaAlvarezG** [comment]
Ya perfect, entocnes puedes ahi en la terminal moverte hasta tu repositorio? onda donde está el archivo TChica1.pyc.
Cuando llegues ahí, ejecuta ``py Tchica1.pyc 2`` y avísanos si funciona.

**Comment by Ikilly0** [comment]
Perfecto! muchas gracias, ahi si funciono jajaj.
![image](https://user-images.githubusercontent.com/69522095/91663636-88ebda00-eac0-11ea-9524-64d88d25e459.png)
![image](https://user-images.githubusercontent.com/69522095/91663639-8f7a5180-eac0-11ea-8a7f-a525ccaf1e95.png)

**Comment by ValentinaAlvarezG** [comment]
Ya bacan! me alegro
