### ISSUE TITLE
3.2 problema con el codigo

### ISSUE THREAD

**Issue by jacorderoluco** [Exploratorio-DCC-PUC/Syllabus#338]
Hola, estoy teniendo problemas al ingresar el código, cada vez que lo hago me da not found, tengo la version correcta de python.

**Comment by ValentinaAlvarezG** [comment]
Hola! puedes mandar un pantallazo?

**Comment by jacorderoluco** [comment]
![1 11](https://user-images.githubusercontent.com/69521986/91616012-d0ecee80-e952-11ea-9510-27ca810af394.JPG)

**Comment by ValentinaAlvarezG** [comment]
Hola! copiaste el comando? intenta escribiéndolo tu porque a veces tiene problemas con las comillas cuando se copia y pega. Además los comandos se corren por separado, primero ``alias python='winpty python.exe'`` y después ``python TChica1.pyc 7``.

**Comment by jacorderoluco** [comment]
gracias, creo q ya funcionó, adjunto la foto para q me confirmes jajaja. gracias
![1 2](https://user-images.githubusercontent.com/69521986/91618762-4360cd00-e959-11ea-8471-a485be9e2b53.JPG)

**Comment by ValentinaAlvarezG** [comment]
Si! ahí estas perfect, se te generó la carpeta para trabajar.

**Comment by jacorderoluco** [comment]
ok, gracias
