### ISSUE TITLE
Dudas Lectura 1 Perusall

### ISSUE THREAD

**Issue by joalonsosch** [Exploratorio-DCC-PUC/Syllabus#339]
Hola!

Hace poco me metí a perusall para crear una cuenta y ver la lectura 1, como nos dijo el profesor en los anuncios de canvas y quedé con algunas dudas:
1) ¿Cuál es el plazo para leer y comentar el documento?
2) ¿A qué se refieren con "anotaciones significativas", tiene que ser algo que nos interesó, una duda buena por ejemplo, o solo respuestas buenas a dudas de compañeros?
3) ¿En que parte de perusall puedo ver a los integrantes de mi grupo?

Gracias de antemano, buen fin de semana!

**Comment by JupaOlivares** [comment]
Hola! 
Con respecto a la 2da duda te puedo decir que, tienen que ser comentarios que ayuden a la compresion del texto, puede ser sobre algo que te llamo la atencion o que ayude a la comprension del texto.
Suerte!

**Comment by JupaOlivares** [comment]
Tienen hasta la noche antes de la I1 para comentar el documento!
