### ISSUE TITLE
Usar archivos .svg para los gráficos

### ISSUE THREAD

**Issue by Panckx** [Exploratorio-DCC-PUC/Syllabus#34]
Hola! Está bien si exporto los gráficos de la parte 1 como imagen vectorial en vez de exportarlos como imagenes de pixeles o me bajan puntaje si hago eso? Se pueden abrir igual de bien en el html, solo que si se agrandan quedan más bonitos.

**Comment by diflores** [comment]
Hola,

Sí se puede.

¡Saludos!

**Comment by Panckx** [comment]
Gracias!
