### ISSUE TITLE
[error] Waiting for your editor to close the file...

### ISSUE THREAD

**Issue by jvergara-sanguesa** [Exploratorio-DCC-PUC/Syllabus#340]
![problema](https://user-images.githubusercontent.com/69873516/91625806-40c1a000-e978-11ea-9110-e36c297aefec.jpeg)
hola me aparece este problema al hacer commit.  me abre el instalador de pycharm cuando ejecuto commit. desistale git y lo instale denuevo para que no lo tome como editor de texto, he probado de todo, nose que hacer

**Comment by ValentinaAlvarezG** [comment]
Te funciona hacer commit si le pones el -m y el mensaje, onda ``git commit -m "Mensaje descriptivo" `` ?

**Comment by JupaOlivares** [comment]
Hola! 
Puede ser que tengas un programa abierto que tenga un conflicto con el git bash te sugiero revisarlo. Pero lo mas probable es lo que dice Valentina, recordarte que el enunciado dice **que se debe incluir un mensaje descriptivo en el commit**, por lo que te sugiero incluirlo usando **git commit -m "hice tal cosa..."**
Exito!

**Comment by jvergara-sanguesa** [comment]
muchas gracias, eso era. 
son unos grandes ,se merecen el cielo
