### ISSUE TITLE
Duda citas de comandos, "flags" y similares

### ISSUE THREAD

**Issue by jguzman8** [Exploratorio-DCC-PUC/Syllabus#341]
Hola! Si es que ejecuto un  comando + --help, la consola me sugiere unas especies de sufijos, los cuales me sirvieron para desarrollar el paso BONUS. ¿Esto lo debo citar o mencionar en el PDF?

**Comment by JupaOlivares** [comment]
La explicacion de las "flags" o sufijos si debe estar incluida en la explicacion del comando en el PDF

**Comment by jguzman8** [comment]
Ok, gracias
