### ISSUE TITLE
Mover carpeta tc1...

### ISSUE THREAD

**Issue by mateogs** [Exploratorio-DCC-PUC/Syllabus#342]
Pasa algo si cambio la ubicación de la carpeta tc1? tendré problemas después con el repositorio?

**Comment by ValentinaAlvarezG** [comment]
A que te refieres con cambiar su ubicación? a donde la quieres mover?

**Comment by mateogs** [comment]
mover la carpeta dentro de mi pc, ponerla dentro de otra carpeta

**Comment by ValentinaAlvarezG** [comment]
Es que necesitas tener los archivos dentro de tu repositorio para poder hacer push a github
