### ISSUE TITLE
Crear carpetas. TC1 punto 3.2. no funciona git bash ni cmd.

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#343]
Hola, perdón que escriba de nuevo, sigo tratando de crear las carpetas pero ni git bash ni cmd responden, el unico commando que me aceptan es py --version. tengo python 3.7.5.  Espero me puedan ayudar, estoy muy perdido, el PDF no explica que otras condiciones deberia cumplir, todavia esta el otro issue pero siento que se alargo y desvio mucho asique cree este.

**Comment by Ikilly0** [comment]
dejo esto aqui por si aclara algo, borre la carpeta y lo hise desde 0
![image](https://user-images.githubusercontent.com/69522095/91652659-c5dbb080-ea6f-11ea-800e-6e86880a1ebd.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! prueba lo que te dejé en la otra issue!
