### ISSUE TITLE
Mostrar archivos de texto.

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#344]
A que se refiere con "mostrar archivos de texto"? hay que hacer que con un comando se muestren en la terminal?
![image](https://user-images.githubusercontent.com/69522095/91667732-0e7d8300-eadd-11ea-89ef-14e1a3836af9.png)

me refiero a esta parte:
![image](https://user-images.githubusercontent.com/69522095/91667747-2f45d880-eadd-11ea-9666-9f8a453d5ed1.png)

Me recomiendan algun lugar para sacar comandos para lograr esto? o encontrar esos lugares tambien es parte de la tarea?

**Comment by ValentinaAlvarezG** [comment]
Hola! es un comando de terminal que te permita ver todos los archivos de texto que tengan ``||``al mismo tiempo.
