### ISSUE TITLE
No pasa nada al ejecutar los comandos del punto 3.2

### ISSUE THREAD

**Issue by tomasnusser** [Exploratorio-DCC-PUC/Syllabus#345]
![image](https://user-images.githubusercontent.com/69521898/91671112-b69d4700-eaf1-11ea-9ace-62c5c4164121.png)
Seguí todas las instrucciones y escribí los comandos, pero no pasa nada luego de ejecutarlos. Por otro lado, tampoco aparece un error pero no se crea la carpeta que debería crearse.

**Comment by ValentinaAlvarezG** [comment]
Hola! Que versión de python tienes?

**Comment by tomasnusser** [comment]
Tengo 3.7.x, no recuerdo bien que versión pero sé que es 3.7

**Comment by ValentinaAlvarezG** [comment]
Puedes intentar con lo que comentamos en la issue #337  ?

**Comment by joalonsosch** [comment]
Buena Tomas!
Acá unos tips que me sirvieron a mi:
1) Pon ojo con las comillas, en el pdf sale que son de este tipo ´ pero las que debes poner son así '.
2) Te recomiendo escribir los comandos tu mismo en vez de copiar y pegar.
3) Si no logras solucionarlo con sólo eso cambia el "python" que dice en la fila de abajo por "py" nomás.
Ánimo con la tarea!

**Comment by tomasnusser** [comment]
Bueena @joalonsosch. El cambiar python por py funcionó. Muchas gracias!!
