### ISSUE TITLE
Ayuda por favor! Una fatídica catástrofe con git :'(

### ISSUE THREAD

**Issue by nvaldiviesoo** [Exploratorio-DCC-PUC/Syllabus#346]
Hola! Estaba haciendo la tarea y en el paso de contar los archivos, busqué la subcarpeta en base al número de archivos y no encontré el siguiente paso, así que asumí que cometí un error en alguna parte.

No entiendo mucho de git aún, así que quise hacer todo el proceso de nuevo, borré la carpeta con el repositorio local  (trabajo con MacOs) y cuando intento clonar de nuevo el repositorio, me arroja:

"la ruta de destino 'tc1-2020-2-nvaldiviesoo' ya existe y no es un directorio vacío."

Ahora resulta que la carpeta local la borré y pareciera no estar en el computador, pero tampoco puedo volver a clonar mi repositorio. 

Intenté hacer el proceso de nuevo descargando el repositorio como zip, pero los números de carpetas que me arrojaba para intentar los siguientes pasos habían cambiado respecto a la primera vez y me mandaba a carpetas sin los archivos para continuar

Hay alguna forma de hacer un borrón cuenta nueva? Estoy desesperado, lloraré :'(

**Comment by ValentinaAlvarezG** [comment]
Hola! oh baia, puedes intentar con lo que dice este link? http://git.dokry.com/fatal-la-ruta-de-destino-opencv_contrib-ya-existe-y-no-es-un-directory-vaco.html  hay una parte que dice: 

```
Comtesting si opencv_contrib ya es un repository de Git:

 cd opencv_contrib git status 
Si lo es, una git pull (suponiendo que todavía está en el master ) debería actualizarlo.

Si no es un repository de Git, y está seguro de que no necesita lo que contiene, simplemente elimine el directory e intente de nuevo:

 cd .. rm -rf opencv_contrib/ 
```

Avisa si te funciona o no y que pasa.

**Comment by nvaldiviesoo** [comment]
@ValentinaAlvarezG Probé lo que comentaste y hasta ahora parece que ha funcionado!!!!! 
Aunque es como tercera vez que hago la tarea jajaja pero será.
Muchas gracias por contestar tan pronto y a estas horas. Sos un sol

**Comment by ValentinaAlvarezG** [comment]
jaja ya bacan! me alegro, puchita, ánimo!!
