### ISSUE TITLE
Mensaje al hacer git add de TareaChica1

### ISSUE THREAD

**Issue by FelipeDavis** [Exploratorio-DCC-PUC/Syllabus#347]
Cuando usé el comando git add me apareció esto y no entendí qué significaba
![image](https://user-images.githubusercontent.com/69520702/91788389-1242ff80-ebda-11ea-94aa-d7d5afc854cb.png)

**Comment by RobinC-Jr** [comment]
Creo que no importa, a mi también me apareció,  pero nada cambió

**Comment by ValentinaAlvarezG** [comment]
Hola! para términos de la tarea no importa, es solo un warning. Si te interesa saber más al respecto y tienes curiosidad, te dejo este link https://es.stackoverflow.com/questions/320373/por-qu%C3%A9-al-hacer-git-add-me-dice-lf-will-be-replaced-by-crlf-the-file-will-h
