### ISSUE TITLE
Contar archivos de la carpeta padre

### ISSUE THREAD

**Issue by dasobarzo** [Exploratorio-DCC-PUC/Syllabus#348]
hola! estoy en la parte 3 en contar archivos y encontré un comando que me cuenta los archivos. el problema es que me arroja un numero que no me dirige bien, es decir no es. y lo he hecho 11 veces todo desde cero🙂. y pues sigue dando el mismo numero...

que hago???:(

**Comment by dasobarzo** [comment]
que son los DS_Store?

**Comment by ValentinaAlvarezG** [comment]
Hola! Tranqui, ese es el ultimo paso y nosotros revisaremos los comandos, así que si no llegas al final no importa, igual podrías sacarte el 7 si es que los comandos están bien. Sobre tu segunda pregunta, son unos archivos que generan los mac https://es.m.wikipedia.org/wiki/.DS_Store, la verdad no se mucho más de ellos porque nunca he usado mac jajaja perdoncito, pero ahi te deje un link y probablemente google sabe que yo al respecto.

**Comment by dasobarzo** [comment]
muchas gracias! ahi pude, existe un comando que los calcula wowww y también los elimina.
