### ISSUE TITLE
Mover archivos.bla a carpeta NombreApellido

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#349]
Hola, busque muchos comandos que podrian mover todas las carpetas de una accion pero lamentablemente ninguno esta funcionando, me gustaria saber si me pueden ayudar con este paso.
![image](https://user-images.githubusercontent.com/69522095/91794650-02cfb080-ebf2-11ea-8c64-b9b7a7b0fd4d.png)
ahi probe dos comandos y ninguno me sirvio para mover los archivos .bla :C

**Comment by ValentinaAlvarezG** [comment]
Hola! Si bien un comando similar a ese te funciona para hacer lo pedido, tendrías que buscar bien como funciona he visto a veces que hay que ponerle \ antes de + o cosas así, tendrías que buscar y probar más cosas, pq lamentablemente no podemos ayudarte mas :/
Te puedo decir si que hay una forma más simple de hacerlo y te prometo que no es difícil de encontrar en google, te recomiendo buscar en ingles porque generalmente hay más respuestas. Éxito con la tarea!

**Comment by Ikilly0** [comment]
Llevo arto rato y artas paginas en google pero realmente no encuentro nada :/

**Comment by Ikilly0** [comment]
lo que intente no me dejo mover solo las .bla y movio todas

**Comment by ValentinaAlvarezG** [comment]
Pucha no se como mas ayudarte. Recuerda que lo que buscas es **mover varios archivos a un directorio**  :c

**Comment by JupaOlivares** [comment]
Hola! como recomendacion utiliza **palabras claves** como **en que** estas trabajando (tipo de terminal) y **las acciones** que quieres hacer (eliminar, copiar, etc). Tambien hay veces que la duda puede estar respondida en **ingles** (generalmente las paginas como stackoverflow tienen su mayor cantidad de dudas en ese idioma)
