### ISSUE TITLE
Convertir las fechas

### ISSUE THREAD

**Issue by Iawinter** [Exploratorio-DCC-PUC/Syllabus#35]
Al convertir las fechas a un formato mas legible, que debemos hacer con las fechas convertidas? Debemos modificar el archivo csv y dejarlo con las nuevas fechas ya convertidas?

**Comment by diflores** [comment]
¡Hola!

Debes mostrar en el _notebook_ que las fechas del _DataFrame_ tienen el nuevo formato. Es decir, se deben ver al menos las 5 primeras filas con el nuevo formato de fechas (de todas formas verificaremos que el resto de las filas cumplan con el formato pedido).
