### ISSUE TITLE
10 mas escuchadas

### ISSUE THREAD

**Issue by valeeeriquelme** [Exploratorio-DCC-PUC/Syllabus#35]
Para ver las diez más escuchadas ocupe el comando que aparecia en la Ayudantía 2 df.groupby(["Track"]).count()["Date"].sort_values(ascending=False)[0:10]...mi problema es que eso me entrega una serie y al momento de graficar no puedo acceder a los nombres de las canciones y a los numeros por separado...¿que puedo hacer? ¿mejor usar otros comandos?

**Comment by totichi** [comment]
Puedes utilizar la función index.tolist() para obtener los nombres , aplicándola luego de count(); pero tendrías que hacer 2 variables. Por ejemplo, una para los números y otra para los nombres.
