### ISSUE TITLE
Entrega Tarea

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#350]
Hola, una duda muy pequeña, esque el PDF no explicita donde debe ir el documento que registre nuestro progreso, tiene que ir en la carpeta principal o en tareachica1 o en otro lado?

**Comment by JupaOlivares** [comment]
Hola! 
Como se ha comentado en otras iisues debe ir en la carpeta principal, que "quede a plena vista"
Exito!
