### ISSUE TITLE
bonus comando en mac

### ISSUE THREAD

**Issue by dasobarzo** [Exploratorio-DCC-PUC/Syllabus#351]
Hola! por alguna razón no me funciona el comando para contar bytes en el Mac, me da en M (ej. 182M) y lo saco para que me de en bytes y me dice "illegal option.....", pero esa parte en si es la única que me lo arroja en bytes.

**Comment by JupaOlivares** [comment]
Hola! 
Que raro tu caso, si tu error es parte de tu computador podrias adjuntar pantallazo explicando tu situacion (en caso de que no sea, no te deberia descontar puntaje bonus) en cualquier caso incluye la conversion.
Exito!
