### ISSUE TITLE
Crear grupo TareaGrande1

### ISSUE THREAD

**Issue by FelipeLara00** [Exploratorio-DCC-PUC/Syllabus#352]
Hola! Fui a link que hay en el anuncio de la traea y me pide crear un equipo pero no se si hay que escribir el nombre de los integrantes o el numero o nombre de grupo.

**Comment by IchottMano** [comment]
Hola!

A grandes rasgos, lo que debes hacer en ese link es ingresar un nombre para tu equipo y crearlo, para que luego tu compañero ingrese a tu grupo. De lo contrario si tu compañero ya creó un grupo, sólo es necesario que ingreses a él.

Saludos!

**Comment by FelipeLara00** [comment]
Gracias!
