### ISSUE TITLE
Creación repositorio TG1

### ISSUE THREAD

**Issue by josefeliuf** [Exploratorio-DCC-PUC/Syllabus#353]
Hola! quería saber que opción debemos utilizar para la creación del repositorio.
Me sale lo siguiente:

![issuegithub](https://user-images.githubusercontent.com/62085104/91995957-71059780-ed06-11ea-89b1-1d87b162aa0f.png)

Gracias!

**Comment by clolate** [comment]
Hola, se respondió en la ayudantia tambn, pero esta bien eso! Eso pasa porque se crea el repo vacío
cualquiera de los 3 es lo "mismo", depende que tanto sabes, así que te recomiendo la opción 2
