### ISSUE TITLE
Busco compañero para TG1

### ISSUE THREAD

**Issue by iavasquez1** [Exploratorio-DCC-PUC/Syllabus#354]
Hola!, busco compañero para realizar la tarea grande 1. Ofrezco responsabilidad y compañerismo.

**Comment by mateogs** [comment]
yo apaño, estoy solo

**Comment by iavasquez1** [comment]
Ok, trabajemos juntos, mi correo es iavasquez@uc.cl para que me envíes tu número y para que te agregue
