### ISSUE TITLE
Error intentando correr código en jupyter

### ISSUE THREAD

**Issue by En-clases** [Exploratorio-DCC-PUC/Syllabus#357]
Hola, cuando intento correr el código en jupyter hecho en la ayudantía de pandas y altair me salta error, cómo lo puedo arreglar?
![image](https://user-images.githubusercontent.com/69520590/92281399-824ad180-eec9-11ea-94e3-739d011c175f.png)

**Comment by IchottMano** [comment]
Hola!

Para poder correr ese código debes primero descargar la librería `pandas` en tu computador.
Para esto es necesario que coras el siguiente comando:

`pip install pandas`

Quedo atento a cualquier problema.

Saludos!
