### ISSUE TITLE
Tablas TG1

### ISSUE THREAD

**Issue by En-clases** [Exploratorio-DCC-PUC/Syllabus#358]
Hola, hemos utilizado algo tal que nos junte los ratings de "Rotten Tomatoes". 
![Tablaa](https://user-images.githubusercontent.com/69520590/92309541-68b29400-ef74-11ea-85df-1d63020702ca.png)

Sin embargo, no podemos acceder a dicha columna para crear nuestro gráfico ya que nos salta el error: "Rotten Tomatoes encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data".
Existe una forma de solucionar este problema?

**Comment by clolate** [comment]
No puedo ayudarte si solo me dices que utilizaron algo, pero adivinando puede ser que los rating de rotten terminan con un %, o esto: [https://stackoverflow.com/questions/61695087/encoding-error-using-altair-interactive-plot](url) y tendrían que asegurarse de ver que tienen los mismos nombres (case-sensitive)
