### ISSUE TITLE
TG1 - Pregunta 3

### ISSUE THREAD

**Issue by mateogs** [Exploratorio-DCC-PUC/Syllabus#359]
Hola, en la pregunta 3 se deben hacer dos gráficos? uno para los promedios de IMDb y otro para Rotten Tomatoes?
No sale especificado en el enunciado.
muchas gracias

**Comment by clolate** [comment]
Estamos decidiendo que hacer, mandaremos un anuncio pronto

**Comment by amardones23** [comment]
Hola, al final cual es la respuesta? no encontré el anuncio:(

**Comment by clolate** [comment]
Hola, perdón por no responder, efectivamente no habíamos mandado el anuncio 😓 
Dicho eso se considerará cualquiera de las opciones válidas, promedio de IMDb o de Rotten Tomatoes,  de ambos o hasta una media de los dos.
