### ISSUE TITLE
contador de apariciones de cada canción

### ISSUE THREAD

**Issue by migil1005** [Exploratorio-DCC-PUC/Syllabus#36]
Al ejecutar mi función para contar canciones, me aparecen la cantidad de veces que se repite cada canción bien, pero me aparecen nombres que no están ni en el archivo, trate de bajarlo de nuevo por si lo había modificado pero no me deja.

**Comment by diflores** [comment]
El dataset no está subido solo a sus repositorios privados base, sino también en el [Syllabus](https://github.com/Exploratorio-DCC-PUC/Syllabus/tree/master/Tareas/TG1/dataset).

¡Saludos!
