### ISSUE TITLE
Muchos Generos para el grafico de torta

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#36]
Nose si tendremos que poner un top 5/10/etc... o todos los generos en el grafico. De ser asi el grafico se ve ilegible y desordenado. El enunciado dice: "Generar un gráfico de torta de los géneros musicales más escuchados por el usuario", pero no especifica cuantos hay que incluir.  
![image](https://user-images.githubusercontent.com/48262438/63448087-3be41b00-c40b-11e9-8d78-5d40e34169ee.png)

**Comment by diflores** [comment]
¡Hola!

Es mejor que pongas los top 5.

¡Saludos!

**Comment by perezpefaur** [comment]
Hola! Esto cambiaria el porcentaje de la torta, ya que se reparte entre menos generos. Si creo un dataframe con los 5 generos mas grandes y despues hago el grafico, cambian los porcentajes. Nose si me explico. Entonces nose si estaria bueno de todas maneras o habria que crear una nueva categoria de "otros".

**Comment by diflores** [comment]
¡Hola!

Por simplicidad, calcula los 10 géneros más escuchados y haz el gráfico de ellos.

¡Saludos!

**Comment by perezpefaur** [comment]
Perdon por seguir molestando pero me quedaria algo asi:
![image](https://user-images.githubusercontent.com/48262438/63465209-bf633380-c42e-11e9-97d4-1808849d4ce6.png)
Ocupo top 5 mejor?
EDIT: Pude hacer caber mejor
![image](https://user-images.githubusercontent.com/48262438/63465406-30a2e680-c42f-11e9-99b7-56e8f129689e.png)

**Comment by diflores** [comment]
¡Está bien el que pusiste en EDIT!

**Comment by bmurtagh01** [comment]
Que buen issue!
