### ISSUE TITLE
Problema con gráfica de pregunta 1

### ISSUE THREAD

**Issue by matyjjn14** [Exploratorio-DCC-PUC/Syllabus#361]
Hola! lo que pasa es que al realizar el gráfico de barras de la pregunta 1, al eje x se le suma un numero más, y la verdad no entendemos por qué sucede. Espero nos puedan ayudar. De antemano muchas gracias.
Adjunto imágenes con el código y del gráfico.
![image](https://user-images.githubusercontent.com/64443045/92336530-2b372f00-f078-11ea-97da-37474018902c.png)

![image](https://user-images.githubusercontent.com/64443045/92336503-b532c800-f077-11ea-8b35-29f5327b374f.png)

**Comment by clolate** [comment]
Hola! debe ser la configuración _default_ de la función. Si quieren cambiarlo tienen que ir a la documentación y encontrar la configuración/propiedad que lo _setea_, aunque no tiene descuento ni bonus eso
Quizás esto les sirva [https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-limits](url)
