### ISSUE TITLE
Eje X grafico de porcentajes "Rotten Tomatoes"

### ISSUE THREAD

**Issue by lpalacios1** [Exploratorio-DCC-PUC/Syllabus#362]
¡Hola! 
En la parte 1, en la pregunta 1, no se especifica en que intervalos debe ir el eje x en los 5 graficos de puntaje porcentual de Rotten Tomatoes. 
Gracias!

**Comment by clolate** [comment]
Para los gráficos de Rotten en la pregunta 1, tienen que agrupar por intervalos de diez puntos porcentuales. `[0,9)%  [10,19)% [20,29)%  ...   [90-100]` Uds pueden elegir si incluyen la cota inferior o la superior, lo importante es que lo especifiquen en su informe.
Por ejemplo, en este grafico agrupan por edad con intervalos de 2 años
![imagen](https://user-images.githubusercontent.com/37159005/92440642-32972f00-f183-11ea-80a9-8f0d70926069.png)

**Comment by vicentecerda** [comment]
OK muchisimas gracias!
