### ISSUE TITLE
Pregunta 3 Parte 1 TG01

### ISSUE THREAD

**Issue by imant1** [Exploratorio-DCC-PUC/Syllabus#363]
Hola!
En la pregunta 3 nos piden graficar el promedio de los puntajes en relación al año en el que fue lanzada la película.
¿Para calcular el promedio de un año debemos ocupar tanto el puntaje de IMDb como de Rotten Tomatoes (realizando una conversión adecuada para que queden en la misma escala)? ¿O debemos poner dos gráficos ocupando la puntuación de IMDb en uno y Rotten Tomatoes en el otro?

**Comment by clolate** [comment]
#359
