### ISSUE TITLE
Problema al crear gráficos en la Parte 1

### ISSUE THREAD

**Issue by camilamoya** [Exploratorio-DCC-PUC/Syllabus#364]
Cuando intentamos hacer un gráfico para la pregunta 1 con este código:
![Anotación 2020-09-07 202842](https://user-images.githubusercontent.com/69520472/92420319-0e1e6100-f149-11ea-96ac-8c9959d436ef.png)
Sale este error : 
*ValueError: Puntaje_IMDb encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.*
No sabemos que hacer :(

**Comment by clolate** [comment]
Estan segurxs que ` imdb_agrupados` es un dataframe? pueden verificarlo poniendo:
```
print(type(imdb_agrupados), type(imdb_agrupados.Puntaje_IMDb))
```
eso deberia retornarles:

`<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>`

Avisenme si no es eso para seguir buscando

**Comment by camilamoya** [comment]
Sale que `imdb_agrupados` es `class 'pandas.core.series.Series'`. Intenté convertirlo en DataFrame usando `.to_frame()` pero salió este error:
`AttributeError: 'DataFrame' object has no attribute 'to_frame'`

**Comment by camilamoya** [comment]
Ya funcionó, creo que no funcionaba por un problema de Google Colab, pero al cargar todo de nuevo funcionó bien 👍

**Comment by ferperezh** [comment]
hola hablando de los gráficos intento hacer las barras un poco más gruesas y no se como hacerla
