### ISSUE TITLE
Problemas Pregunta 2 #TG1

### ISSUE THREAD

**Issue by mati-gonz** [Exploratorio-DCC-PUC/Syllabus#365]
En la pregunta dos tengo tres dudas. Primero pasa que en el enunciado dice que se quiere saber cual ver primero y cual después pero no da ninguna clasificación como para saber como definir eso. 
Segundo al momento de querer hacer el grafico de dispersión, dice que Altair no acepta más de 5000 datos para el gráfico, lo tengo que cortar ahí? Si no es así como hago que me acepte más de 5000?.
Y ultimo y creo que esta es la más importante, se pide que el color de los círculos sea de acuerdo al lenguaje de la película, y que solo se muestre uno en el caso de aquellas que tienen más de uno, pero el tema es que sin poder ocupar ciclos, no encuentro ninguna función con la pueda hacer que se seleccione solo el primer lenguaje de cada película, ya he revisado toda la documentación de pandas y no llego a nada.

**Comment by IchottMano** [comment]
Hola!

Dejame responder tus dudas en orden:

1.- Eso queda a su criterio, no es muy importante.

2.- Te recomiendo que veas esta página: https://altair-viz.github.io/user_guide/faq.html

3.- Para esto se puede simplemente usar la funcion [map](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.map.html) de pandas, puede usarse para lo que necesitas sin necesidad de usar ciclos.

Saludos!
