### ISSUE TITLE
Error Jupyter

### ISSUE THREAD

**Issue by manearaya** [Exploratorio-DCC-PUC/Syllabus#366]
Hola! 

El archivo jupyter donde esta la parte 1 de la tarea no muestra los graficos hechos en altair (antes si los mostraba) y lanza el siguiente error:

`Error loading script: Script error for "vega-util", needed by: vega-embed http://requirejs.org/docs/errors.html#scripterror`

Saben como se podria arreglar esto? :(

**Comment by fbarrosalcalde** [comment]
A mi me paso lo mismo, tampoco sé como arreglarlo.

**Comment by IchottMano** [comment]
Hola!

Estan usando google colab para abrir esos archivos?

Si intentan abrirlos usando por ejemplo jupyter, van a necesitar descargar vega para poder visualizar las imágenes, además de tener que poner las lineas de código correspondientes, que pueden encontrar en el siguiente link.

https://altair-viz.github.io/user_guide/display_frontends.html#displaying-charts

No recomiendamos el uso de otros programas, como VSCode para trabajar con altair.

Saludos!

**Comment by fbarrosalcalde** [comment]
Ahí me funcionó, gracias!

**Comment by manearaya** [comment]
A mi también, gracias!
