### ISSUE TITLE
Error en google collab

### ISSUE THREAD

**Issue by nicolaspoli** [Exploratorio-DCC-PUC/Syllabus#367]
hola! 
nos sale varias veces este error, no nos perjudica para seguir trabajando, pero no sabemos si es importante o no 

gracias de antemano
![Screenshot_320](https://user-images.githubusercontent.com/69522096/92663405-93378080-f2d7-11ea-8659-fc01c4449728.png)

**Comment by IchottMano** [comment]
Hola!

Mientras les funcione, no hay problema con que pase eso.

Saludos!
