### ISSUE TITLE
Pregunta 2, color null

### ISSUE THREAD

**Issue by jguzman8** [Exploratorio-DCC-PUC/Syllabus#368]
Hola! Tengo un problema: al hacer el gráfico de puntos en pregunta 2, en la parte de los colores (idiomas) aparece uno llamado 'null'. ¿Esto tenemos que dejarlo así o elminarlo?

**Comment by ferperezh** [comment]
con la pregunta 2 también tengo un problema, los datos de runtime e IMDb se deben aproximar como en la pregunta 1?
