### ISSUE TITLE
Imágenes de graficos

### ISSUE THREAD

**Issue by gatochico** [Exploratorio-DCC-PUC/Syllabus#37]
Hola! :cat: Las imagenes de los gráficos deben ser generadas por comandos de python una vez corran la tarea para revisarla, o tienen que venir ya guardadas en la carpeta img? 

Y en la parte de la rubrica donde dice que las imagenes deben estar alineadas, esto es que cuando se cambie el tamaño del browser se ajusten? Y todas deben tener el mismo tamaño para que queden "alineadas"? Por que me parece que hay graficos que se aprecian de mejor forma en tamaños distintos...

**Comment by diflores** [comment]
Hola,

Lo ideal es que vengan guardadas en la carpeta `img`, pues son partes distintas de la tarea. Sobre lo de la alineación de las imágenes, tiene que ver más con que la página sea *responsive*. No todas deben ser, necesariamente, del mismo tamaño.
