### ISSUE TITLE
Spotipy

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#37]
Aparte de la pagina de Spotipy, hay algun otro lado para aprender, es que por mas que busque en la pagina no encuentro como obtener el danzability de una cancion.

En youtube hay unos tutoriales pero nada sobre danzability o como obtener informacion de canciones. Habra algun material extra que nos puedan dar?

Cualquier codigo que copio y pego de la pagina me dice: http status: 401, code:-1 - https://api.spotify.com/v1/search?q=artist%3AJeff&limit=10&offset=0&type=artist:
 No token provided

Creo que requiere credenciales

**Comment by malopez16** [comment]
Hola!
Primero que nada, nuestra recomendación es que dejes la parte de Spotify para el final. Puede que demores y sólo son 5 décimas.

En cuanto a tu problema, efectivamente requiere credenciales. Un tutorial que a mí me sirvió fue [este](https://sotiriskakanos.com/2017/08/05/using-spotifys-web-api-with-python/ ) para autentificarme con la API. 

También veremos una aproximación a la API durante la siguiente ayudantía.
Saludos!
