### ISSUE TITLE
Acceder al atributo Rotten Tomatoes en Df

### ISSUE THREAD

**Issue by joseaguirrem** [Exploratorio-DCC-PUC/Syllabus#370]
Hola! 

Al estar trabajando con data frame para visualizar las tablas en IMDb accedí al siguiente código que llama al atributo IMDb, el tema es que no he podido acceder al atributo Rotten Tomatoes para las otras tablas dado a que no se cómo está ingresado (tiene espacios entre medio). He buscado pero no he logrado dar con el acceso. Alguien me podría ayudar?

<img width="493" alt="Captura de Pantalla 2020-09-10 a la(s) 16 27 39" src="https://user-images.githubusercontent.com/69520728/92790865-8f146d00-f382-11ea-9fd6-df5c87e0caf6.png">

**Comment by clolate** [comment]
```
data = pd.read_csv("movies.csv")
data["Rotten Tomatoes", "Title", "IMDb"]
```

**Comment by clolate** [comment]
no cierren las issues, se cierran cuando se termina el plazo de entrega

**Comment by joseaguirrem** [comment]
Oka! Perdón 😅
