### ISSUE TITLE
Interacción con los gráficos 

### ISSUE THREAD

**Issue by FelipeLara00** [Exploratorio-DCC-PUC/Syllabus#372]
Hola! 
Tenemos una duda respecto al formato para visualizar los 10 gráficos de la pregunta 1 en la parte 2. Es obligación que se muestren 3 todo el rato o se pueden mostrar 4 al mismo tiempo. Esto nos paso porque hay gráficos mas anchos por lo que hicimos otro contenedor para ellos que se adaptara a su ancho.
![image](https://user-images.githubusercontent.com/61998555/92817118-9e081900-f39c-11ea-83d9-27d4749d73cb.png)

**Comment by clolate** [comment]
![imagen](https://user-images.githubusercontent.com/37159005/92817898-78c7da80-f39d-11ea-9c01-70b7764fb73e.png)
![imagen](https://user-images.githubusercontent.com/37159005/92817985-8f6e3180-f39d-11ea-959b-7f4714eb07d3.png)

**Comment by FelipeLara00** [comment]
Gracias! 
Osea que no importa si los gráficos mas anchos se ven mal?

**Comment by clolate** [comment]
En la parte 1 con altair debes configurar la relación de aspecto del eje Y para que coincida mejor (~1:1) con el eje X, para eso encontré buscando en la documentación esta opción para cambiar la altura/ancho
`chart.properties(width=200, height=100)`
tendrías que jugar con los números un rato para que se vean mejor a como lo estas mostrando actualmente, sin duda deben existir otras opciones en internet para mejorarla, si no quedas conforme con esta te recomiendo buscar.
