### ISSUE TITLE
Rotten enunciado

### ISSUE THREAD

**Issue by dasobarzo** [Exploratorio-DCC-PUC/Syllabus#373]
hola! en el archivo pdf dice "otros cinco para Rotten Tomatoes. Esto quiere decir queen su eje x tenga las notas de 1 a 10 y el otro de **_0 a 100%_**, y que en el eje y tengan la cantidad de películas que tienen esa nota."  

lo que me hace preguntarme, es que en mi gráfico tengo graficado del 1 al 100% por cada 1% que va pasando hay una barra.
en otra issues dice creo que hay que agrupar por intervalos del 1-10 10-20.....pero eso creo que no dice el enunciado(al menos específicamente), es obligatorio?

**Comment by mateogs** [comment]
like
