### ISSUE TITLE
NaN en gráficos // Parte 1

### ISSUE THREAD

**Issue by joseaguirrem** [Exploratorio-DCC-PUC/Syllabus#375]
Hola!

Quería saber si en los gráficos debemos incluir los NaN. Esto tanto para Rotten como IMDb. Si es así, hay que valorizarlos como 0s?

Saludos🙌

**Comment by IchottMano** [comment]
Hola!

Los NaN **no** deben incluirse en los gráficos, sin embargo esto sólo importa para las columnas con las que se encuentren trabajando.

Saludos!
