### ISSUE TITLE
Duda sobre el orden de los divs

### ISSUE THREAD

**Issue by illanes00** [Exploratorio-DCC-PUC/Syllabus#376]
Hola! 
Quería saber si el encabezado va dentro del cuerpo de la pagina web o no y en que parte ponemos los botones (o eso es libre?).
Gracias de antemano!

**Comment by clolate** [comment]
Hola, si el encabezado de la página web va en el cuerpo del html. El encabezado que les pedimos es una parte de lo que se visualiza en la pagina web, es decir una parte en el body. No confundir el encabezado de la pagina web con el head del html. Es libre donde ponen los botones, ojala cerca del elemento que cambia para que tenga sentido.
