### ISSUE TITLE
Duda botones parte 2

### ISSUE THREAD

**Issue by amardones23** [Exploratorio-DCC-PUC/Syllabus#378]
Hola, no entiendo qué deberían hacer los botones en la segunda parte de la tarea. Me explican porfiss
Gracias por adelantado♡

**Comment by clolate** [comment]
Hola! el botón específico que les pedimos es de cambiar el modo de la página entre normal y _darkmode_ con los parámetros que establece el enunciado.
Para la parte del 'menú' hay varias formas de implementarlo; una de ellas es poner un botón como siguiente, otra es poner unas vistas muy pequeñas de las imágenes y al hacer clic se agrandan, etc. Puedes buscar en internet otras formas de implementar esas transiciones.
![imagen](https://user-images.githubusercontent.com/37159005/93110560-df921000-f68b-11ea-8c4a-167b1dfa62d5.png)
