### ISSUE TITLE
SettingWithCopyWarning

### ISSUE THREAD

**Issue by dreamflash3r** [Exploratorio-DCC-PUC/Syllabus#379]
Hola! Al reemplazar columnas con datos modificados en los dataframes creados obtengo la siguiente advertencia:

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Al parecer SettingWithCopyWarning tiene que ver con una diferencia entre una referencia al DF original y una copia de esta? En mi caso lo que me interesa es obtener una copia modificada. He sido capaz de crear los gráficos sin problema, pero las múltiples advertencias en el archivo atentan contra la limpieza del notebook. No he sido capaz de obtener ninguna solución convincente.

**Comment by IchottMano** [comment]
Hola!

Si bien no es importante, ya que lo mas importante es hacer los gráficos, pueden intentar con el código que les estan entregando en el mismo error.

Saludos!
