### ISSUE TITLE
Grafico plot

### ISSUE THREAD

**Issue by NicolasCastillo24** [Exploratorio-DCC-PUC/Syllabus#38]
Hola,
Hice el primer grafico de barra de la siguiente manera:
`CENSURADO`.
Me entrega el gráfico todo bonito pero con "<matplotlib.axes._subplots.AxesSubplot at 0x1148d2470>" justo arriba, asumo que se debe a un pequeño error con el uso de plot, que me entrega información de un objeto, debería preocuparme? o lo puedo ignorar?
Gracias!

**Comment by diflores** [comment]
Hola,

Puedes ignorar estas cosas: `<matplotlib.axes._subplots.AxesSubplot at 0x1148d2470>`, pues no habrá descuento por su aparición.

PS: tuve que editar tu *issue*, pues daba demasiadas pistas para llegar a la respuesta y eso podría ser interpretado como copia.

¡Saludos!

**Comment by amrosenblum** [comment]
ocupa el comando .show() y todas esas cosas desaparecen
