### ISSUE TITLE
Comando cantidad

### ISSUE THREAD

**Issue by rosariodiez** [Exploratorio-DCC-PUC/Syllabus#38]
Hola! Para poder poner las cantidades en el gráfico de torta existe algún comando? Llevo harto   tiempo tratando y no encuentro ninguna manera de hacerlo.
Gracias

**Comment by diflores** [comment]
¡Hola!

Creo que esto podría ayudarte: https://matplotlib.org/3.1.1/gallery/pie_and_polar_charts/pie_and_donut_labels.html
