### ISSUE TITLE
Referencias

### ISSUE THREAD

**Issue by lonxo21** [Exploratorio-DCC-PUC/Syllabus#380]
Hola, quería saber donde debería poner las referencias que use para el pagina web. En la parte 1 las puse en el notebook pero para la pagina web no se donde ponerlas.

**Comment by clolate** [comment]
Hola! en el html puedes comentar con la siguiente sintaxis `<!-- así se inserta un comentario en html -->`
en el js puedes comentar con la siguiente sintaxis:

`// comentario de una linea`
```
/*
comentario
de varias
lineas
*/
```
