### ISSUE TITLE
Márgenes responsive 5%

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#383]
Hola!!! ¿Qué significa que los márgenes sean responsive? Busqué en internet y no encontré nada 😢

**Comment by joalonsosch** [comment]
Me sumo a a pregunta

**Comment by IchottMano** [comment]
Hola!

La idea de responsiveness es que si yo tengo una pantalla mas pequeña (como la de un celular u otro despositivo distinto a un pc normal) la página igual se vea bien, sin imágenes cortadas, cosas desordenadas o espacios vacíos gigantes.

Saludos!

**Comment by denisseleiva** [comment]
Buena! @IchottMano Y para probar que me esté funcionando basta con achicar la ventana del navegador? Porque no se me ocurre cómo abrir la página en el cel 👀

**Comment by IchottMano** [comment]
Hola!

Si, esa es una buena manera de probarlo.

Saludos!
