### ISSUE TITLE
Permission denied al hacer python -m http.server en git bash

### ISSUE THREAD

**Issue by joalonsosch** [Exploratorio-DCC-PUC/Syllabus#384]
Hola!
Espero que se encuentren bien.
Abrí esta issue porque estaba intentando ejecutar el comando python -m http.server desde git bash dentro de la carpeta donde tengo mi archivo index.html (como se especifica en la nota de la última parte de la tarea), pero recibí esta respuesta:

bash: /c/Users/José Alonso/AppData/Local/Microsoft/WindowsApps/python: Permission denied

No se por qué aparece que no tengo permiso, ni tampoco se cómo "ganármelo", así que si alguien sabe cómo solucionar este problema agradecería mucho que me ayudara ;)

**Comment by IchottMano** [comment]
Hola!

Esto puede ser debido a un problema con python mismo, podrías intentar hacer algo simmilar a la tc1 con el alias, o bien podrías ver que python este correctamente instalado en tu PATH.

Quedo atento.

Saludos!

**Comment by joalonsosch** [comment]
Hola, sigue sin funcionar, no hay algún comando alternativo?

**Comment by IchottMano** [comment]
Hola!

No creo que existan comandos alternativos, debido al tiempo recomiendo que intentes hacerlo en el computador de tu compañero o en caso contrario que sólo intentes visualizar tu página web con un navegador, intentando evitar problemas al cargar imagenes locales.

Saludos!

**Comment by joalonsosch** [comment]
Hola!

Muchas gracias! Perdón por contestar tan tarde, se me había pasado tu respuesta.
Al final no funcionó ni en el computador de mi compañero ni en el mío, pero la página se ve sin problemas en ambos.

Nuevamente gracias por la respuesta, buenas tardes!
