### ISSUE TITLE
Parte 2 TG1

### ISSUE THREAD

**Issue by sofiaolmedos** [Exploratorio-DCC-PUC/Syllabus#385]
Hola! quería saber si en la parte 2, las cosas que no se especifican las podemos editar nosotros. Por ejemplo si queiro un font especifico, o ponerle color al boton.
Gracias!

**Comment by RobinC-Jr** [comment]
Tengo esta misma duda

**Comment by clolate** [comment]
Hola! si las cosas que no están especificadas en el enunciado las pueden estilizar como quieran
