### ISSUE TITLE
Duda Menu Imagenes Pagina

### ISSUE THREAD

**Issue by mpenalozag** [Exploratorio-DCC-PUC/Syllabus#386]
Hola tengo una duda,

Tengo que tener 3 imágenes viéndose siempre y cambiar estas 3 imagenes con algun boton que vaya mostrando todos los gráficos de la tarea ? 

Gracias de antemano

**Comment by clolate** [comment]
Hola, tal como dice el enunciado tienen que tener 3 imágenes viéndose siempre, la primera imagen tiene que ir cambiando entre las 12 que pide la pregunta 1, la segunda imagen es la de la pregunta 2 y la tercera imagen es cualquiera de las que hayan decidido hacer en la p3
