### ISSUE TITLE
Parte 2 graficos verticales o horizontales

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#388]
Hola, no está aclarado en la parte 2 si los gráficos al tenerlos centrados deben quedar uno arriba de otro como columna o uno al lado del otro como una fila. Me parece mejor como una fila. Quedo atento

**Comment by IchottMano** [comment]
Hola!

Esto en específico no está textual en el enunciado, así que como les parezca hacerlo..

Saludos!
