### ISSUE TITLE
Tabla del csv

### ISSUE THREAD

**Issue by FloValdes** [Exploratorio-DCC-PUC/Syllabus#39]
Cuando se crea la tabla del csv y dice que hay que poner a los 5 artistas con sus respectivas imágenes, se refiere a poner el link nomás como sale en el csv? o a sacar los links del csv y cargar cada imagen?

**Comment by diflores** [comment]
Hola,

Se refiere a sacar los enlaces del csv y cargar las imágenes usando los *links* como *source*. 

¡Saludos!
