### ISSUE TITLE
TG1 encajar graficos en limites 400x400.

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#391]
Estoy teniendo problemas adaptando los graficos a el tamaño 400x400 dentro de div class="single-image" tengo <img src= ...etc>
y en el css tengo .single-image{ 
    width: 400px;
    height: 400px;
    object-fit: scale-down;
}
pero las imagenes quedan asi
![image](https://user-images.githubusercontent.com/69522095/93270454-8f987380-f787-11ea-9933-238953d3ffa4.png)
es decir el scale down no me funciona, tambien trate contain, me pueden ayudar?

**Comment by RobinC-Jr** [comment]
En lugar de usar divs para cada imagen, podrías editar el tamaño de las imágenes en el css. Las imágenes son: img {}

**Comment by Ikilly0** [comment]
gracias, funciono
