### ISSUE TITLE
Orden intervalos Rotten Tomatoes

### ISSUE THREAD

**Issue by ctoro05** [Exploratorio-DCC-PUC/Syllabus#392]
Hola! Quería hacer una pregunta con respecto a mi código porque al parecer al momento de graficar altair no respeta el orden lógico de los intervalos. Solamente me pasa con uno que se pone de último. Ya intenté pasar los números a int.

Muchas gracias de antemano!
![image](https://user-images.githubusercontent.com/69521459/93280761-c2029a80-f7a0-11ea-8fae-d79232bc25a3.jpeg)
![image](https://user-images.githubusercontent.com/69521459/93280773-cdee5c80-f7a0-11ea-8585-99ecb91cbc3e.jpeg)
![image](https://user-images.githubusercontent.com/69521459/93280784-d6469780-f7a0-11ea-893e-3ea657c792d7.jpeg)

**Comment by IchottMano** [comment]
Hola!

Ve si te resulta lo [siguiente.](https://github.com/altair-viz/altair/issues/1245)

Saludos!
