### ISSUE TITLE
Problema al hacer git pull

### ISSUE THREAD

**Issue by camilamoya** [Exploratorio-DCC-PUC/Syllabus#393]
Mi compañera hizo git push sin ningún problema pero cuando hago git pull sale esto:

![Captura de pantalla 2020-09-16 131255](https://user-images.githubusercontent.com/69520472/93363993-64ad2e80-f81e-11ea-93a1-b95ddebd2a83.png)

No sabemos por qué pasa esto, en el repositorio en github sale todo pero no lo puedo pasar a mi computador :(

**Comment by clolate** [comment]
Hola, creo que el problema es el nombre de la carpeta `images:` la que hizo push deberia estar al día con el repo, que ella haga el cambio de nombre en la carpeta e intente hacer otro push

**Comment by camilamoya** [comment]
Gracias, sí era eso, ahora funcionó :)
