### ISSUE TITLE
¿en que repositorio se entrega?

### ISSUE THREAD

**Issue by RocioOpazo** [Exploratorio-DCC-PUC/Syllabus#395]
¿la tg1 debe entregarse individualmente en cada repositorio (ya que son dos personas) o hay que hacer otro repo?

**Comment by IchottMano** [comment]
Hola!

Para esta tarea debieron crear un repositorio grupal, que será donde entregan su tarea. El link para crearlo fue enviado vía canvas.

Saludos!
