### ISSUE TITLE
Aclaraciones estilos Parte 2

### ISSUE THREAD

**Issue by cicarrasco5** [Exploratorio-DCC-PUC/Syllabus#396]
Hola! Tenía un par de dudas en cuando a las especificaciones del enunciado de:
1. Debe tener los bordes redondos con 7px. Sobre el botón de Dark Mode, el tema es que esos 7 pixeles no me queda claro si esa medida es para el margen, el borde o el padding.
2. Deben tener un margen de 10px. En el caso de los contenedores de imágenes, ¿esta medida debe ser aplicada solo como margen : 10px?, porque en ese caso solo se aplica al lado izquierdo por defecto o debe ser 10 para top, bottom, left y right. Esta misma pregunta aplicaría si es que la respuesta de la uno es margen o padding.

Lo siento la hora, pero ha sido una semana dura :c 
😿 ❤️

**Comment by cicarrasco5** [comment]
@IchottMano 😭

**Comment by IchottMano** [comment]
Hola!

Sobre lo primero, se refiere a los bordes **del botón**, es decir que esperamos que el mismo botón se vea redondeado.

Sobre lo segundo, se espera que todos los márgenes sean de esa cantidad.

Saludos!
