### ISSUE TITLE
grabación de clases

### ISSUE THREAD

**Issue by amardones23** [Exploratorio-DCC-PUC/Syllabus#399]
Hola, donde puedo encontrar la grabación de la última clase? Gracias por adelantado!

**Comment by joalonsosch** [comment]
Tengo la misma duda, me gustaría saber dónde encontrar las grabaciones de las clases 11 y 12, muchas gracias!

**Comment by joalonsosch** [comment]
@amardones23, ya fueron subidas a canvas ;)
