### ISSUE TITLE
tutorial// editar archivo

### ISSUE THREAD

**Issue by TriniVial** [Exploratorio-DCC-PUC/Syllabus#4]
1)cuando copio el link de mi perfil de Codecademy y despues me meto me dice que esta terminado pero si reviso lo que escribí, está todo en blanco. Lo tendría que hacer denuevo?

2)el tutorial se hace hasta el paso nueve?

3)cuando quiero editar el archivo.txt de los jugadores como lo hago?
cuando

4)cuando hago git add, git commit, git push y git pull lo tengo que hacer desde la carpeta mas general que tengo? en este caso desde dccpoly?

**Comment by Pyralspite** [comment]
Hola!

1. No entiendo esta pregunta.
2. Para completar el tutorial debes hacer las 5 secciones del curso. Los 9 pasos que mencionas son solo de la primera lección (Navigation).
![image](https://user-images.githubusercontent.com/20785402/63142560-43916300-bfb8-11e9-80de-87c962bd21ca.png)
3. Con los comandos que aprenderás en el tutorial.
4. No, desde tc1-2019-2-nombredeturepo
