### ISSUE TITLE
Pregunta 4.3 I1

### ISSUE THREAD

**Issue by cicarrasco5** [Exploratorio-DCC-PUC/Syllabus#401]
¿El código html lo añadimos al pdf como una imagen (screenshot del editor) o copiamos el texto con los espaciados correspondientes?

**Comment by vcrb18** [comment]
El código debe incluir CSS? O únicamente HTML?

**Comment by dani-sschlack** [comment]
por lo que vi en la foto, puedes hacerlo todo solo con html, no hay necesidad de css o js 👍🏼

**Comment by dani-sschlack** [comment]
y yo lo añadí como imagen, que al escribirlo en word se me desordena 👎🏼

**Comment by denisparra** [comment]
Hola, no pueden pegar imagen, tienen que escribir el código. Basta con escribir con HTML, no es necesario CSS.

Si quieren escriben el HTML en su editor favorito y luego pegan el texto en el word, pero una imagen no se va a considerar  como respuesta válida.
