### ISSUE TITLE
Parte 3, pregunta 1

### ISSUE THREAD

**Issue by dani-sschlack** [Exploratorio-DCC-PUC/Syllabus#402]
cuando preguntan que lenguaje usar, yo considero que son por lo menos 3 las opciones, en donde ninguna es mejor que la otra, puesto que las 3 son usadas para lo mismo, y tienen el mismo resultado.
Pongo las 3 opciones? o escojo una al azar? o menciono las 3 y describo solo una?
ayudaaaa

**Comment by denisseleiva** [comment]
Hola (no soy ayudante) pero yo entiendo que tienes que elegir el tipo de lenguaje a usar (compilado o interpretado) ☺️

**Comment by dani-sschlack** [comment]
dale gracias!!, es que en la clase hicieron una pregunta parecida y se decía qué tipo de lenguaje  (python, erlang ,etc), entonces estaba con la duda Xd

**Comment by denisparra** [comment]
Efectivamente, la pregunta se refiere a el tipo de lenguaje, no a un lenguaje en particular.
