### ISSUE TITLE
Duda de idioma en preguntas de lectura

### ISSUE THREAD

**Issue by PatoLands** [Exploratorio-DCC-PUC/Syllabus#403]
Quería preguntar hasta qué punto la respuesta debe estar en español, esto porque me gustaría citar fragmentos del texto o usar las palabras dichas en él de forma directa, pero no sé si cada vez que pongo algo en inglés debo traducirlo y explicarlo, o si simplemente asumo que se entienden ambos idiomas.

**Comment by IchottMano** [comment]
Hola!

Todas las respuestas deben estar en español, sin embargo siempre existen términos que no pueden ser traducidos, estos puedes dejarlos sin traducir. 

Saludos!
