### ISSUE TITLE
Link sobre cómo citar no abre

### ISSUE THREAD

**Issue by PatoLands** [Exploratorio-DCC-PUC/Syllabus#405]
En el enunciado se dice que  "Es necesario que los alumnos sepan cómo citar correctamente las fuentes de información (http://www.puc.cl/sw_educ/gnosis/citas/citas.htm)." pero ese link no existe.
Agradecería si indican cómo citar para esta prueba para saber el formato adecuado de citación.

**Comment by joalonsosch** [comment]
A mi tampoco me abre, igual traté poniendo la "l" que le falta al final a "html" en el link, pero tampoco...

**Comment by denisparra** [comment]
Hola, disculpen la UC tiene algunos links cortados. En este link hagan click en los items de los menu a la izquierda
https://guiastematicas.bibliotecas.uc.cl/normasapa/citas

![image](https://user-images.githubusercontent.com/208111/94866275-64638480-0415-11eb-8383-63297f95cc4b.png)
