### ISSUE TITLE
Parte 2 pregunta 2 "Dibuje los 6 patrones consultados"

### ISSUE THREAD

**Issue by PatoLands** [Exploratorio-DCC-PUC/Syllabus#406]
Quiero confirmar si con esto se pide que dibujemos las 6 firmas de los VIFs pedidos, o si dibujamos una especie de ejemplo de los patrones.

**Comment by denisparra** [comment]
@PatoLands no entiendo tu pregunta. Se pide identificar las 6 firmas VIF que son patrones. Puedes dibujar los patrones o ejemplos de patrones.
