### ISSUE TITLE
Cálculos Pregunta 4.1

### ISSUE THREAD

**Issue by FelipeDavis** [Exploratorio-DCC-PUC/Syllabus#407]
¿Es necesario escribir todos los cálculos realizados para las distintas tablas? Las fórmulas están en el enunciado y supuse que con **calcule** solo teníamos que llenar las tablas vacías.

**Comment by IchottMano** [comment]
Hola!

Si, esperamos que en el desarrollo de esta pregunta estén los cálculos, de lo contrario no podemos verificar si hubo copia o no.

Saludos!
