### ISSUE TITLE
¿log o ln? (4.1)

### ISSUE THREAD

**Issue by RocioOpazo** [Exploratorio-DCC-PUC/Syllabus#408]
para la 4.1, ¿se usa logaritmo base 10 o base E?

**Comment by IchottMano** [comment]
Hola!

Debido a como funcionan los logaritmos, esto no suele ser un problema ya que es fácil transformar entre ambos.
Puedes asumir que, al no aparecer la base y no ser **explícitamente** un logaritmo natural, este es base 10.

Saludos!
