### ISSUE TITLE
Formato Fecha

### ISSUE THREAD

**Issue by StroveLight** [Exploratorio-DCC-PUC/Syllabus#41]
El formato que piden es HH:MM, pero en el ejemplo es HH:MM:SS, cual de los dos se usa?

Además, asumo que las horas vienen en gmt-4?

![image](https://user-images.githubusercontent.com/48263952/63599908-87740180-c590-11e9-93ab-f89d5d0522a4.png)

**Comment by diflores** [comment]
¡Hola!

Usa HH:MM:SS. Si bien las fechas están en GMT -4, en todas las librerías que he ocupado para trabajar con tiempo, he tenido que indicar que están en dicha zona horaria. En caso contrario, se asume UTC y eso altera los valores que esperamos ver en los gráficos.

¡Saludos!
