### ISSUE TITLE
TC1 - Notas

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#410]
Hola, una pregunta, me aparece que no entregue la TC1, siendo que si esta aqui, y me sale para responder una pregunta con una carita que respondí sin querer. Espero me puedan ayudar, gracias!

**Comment by ValentinaAlvarezG** [comment]
Eso te sale en canvas? Aún no publicamos las notas, cuando estén les mandaremos un anuncio.

**Comment by Ikilly0** [comment]
Sip, eso me paso en Canvas, recién me apareció la evaluacion TC1, que no me salía antes, además sin querer la respondí, tengo cero puntos siendo que entregue por aqui la TC1 en el repositorio como se pedia.

**Comment by ValentinaAlvarezG** [comment]
Si, no te preocupes, aún estamos subiendo las notas así que les pedimos paciencia.
