### ISSUE TITLE
Notas ponderaciones

### ISSUE THREAD

**Issue by josefinadunner** [Exploratorio-DCC-PUC/Syllabus#411]
Hola!
Busqué los porcentajes de cada tarea para la nota final y no lo pude encontrar. Sé que las tareas valen 70% de la nota de presentación y los controles 30%. Me gustaría saber cuánto porcentaje valen específicamente las tareas grandes y chicas.
Si alguien me puede ayudar estaría muy agradecida.

Desde ya muchas gracias!

**Comment by IchottMano** [comment]
Hola!

Un tema recurrente de este curso es la dificultad de el cálculo de notas, principalmente debido al tema de la eliminación de una nota.

Los porcentajes que das son correctos, sin embargo debes considerar que se puede eliminar un control **o** una tarea chica. Esto se explica mas en la primera clase, pero simplemente, la nota de controles es el promedio de los controles (si se elimina un control, este promedio queda como la nota del otro control), mientras que la nota de las tareas es mas compleja de calcular.

Para calcular la nota de las tareas, debes calcular el promedio de 4 "tareas grandes". Estas son:

1. Nota Tarea Grande 1
2. Nota Tarea Grande 2
3. Promedio TC1 y TC2
4. Promedio TC3 y TC4

El promedio de estas 4 notas será su nota de tareas. **Sólo se puede eliminar una tarea chica, si no se eliminan controles.** En caso de eliminar una tarea chica, la nota de la "tarea grande" correspondiente queda como la nota de la otra tarea chica.

Ahora, para calcular que nota se elimina, sacamos la nota que maximice su nota final.

De todos modos, en el futuro tenemos planeado enviarles un excel para facilitarles el cálculo de su nota.

Saludos!

**Comment by josefinadunner** [comment]
perfecto, me quedo super claro.
Muchas gracias!
