### ISSUE TITLE
"No entrega"

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#412]
Me aparece que no entregue la tarea, a mi si me aparece, y que hace un mes la subi, ademas esta con el pdf explicando todo. No entiendo que paso ni porque en canvas me sale "No entrega".

**Comment by ValentinaAlvarezG** [comment]
Hola! me puedes mandar el link de tu repo?

**Comment by Ikilly0** [comment]
https://github.com/Exploratorio-DCC-PUC/tc1-2020-2-SmokeAndMirrorsIKILLY


no pense que afectaria en algo pero me cambie el nombre para que fuera mas breve, quizás por eso no les aparece

**Comment by ValentinaAlvarezG** [comment]
Aaaah ok, lo reviso altiro, para cuando esten las recorrecciones listas deberías poder ver tu nota.
