### ISSUE TITLE
Consultas anidadas TC2

### ISSUE THREAD

**Issue by josefeliuf** [Exploratorio-DCC-PUC/Syllabus#413]
Hola!
Se considera consulta anidada si renombro la tabla?
por ejemplo:
SELECT tabla_renombrada.atributo_1 FROM (SELECT * FROM tabla WHERE ...  AS tabla_renombrada)
Es claro que para un ejemplo así de básico no me sirve de nada, pero cuando tenemos funciones de agregación me es util, como en la consulta número 4.
Gracias!

**Comment by ValentinaAlvarezG** [comment]
Hola! si se consideraría consulta anidada.

**Comment by josefeliuf** [comment]
y si uso la clausula WITH? @ValentinaAlvarezG

**Comment by ValentinaAlvarezG** [comment]
Eeeeh si es que lo necesitas si, pero no deberías necesitarlo. Revisa bien si es que si quizás te estás dando una vuelta más compleja porque de verdad todas las consultas están pensadas para ser respondidas de forma sencilla.
