### ISSUE TITLE
Bonus TC2

### ISSUE THREAD

**Issue by josefeliuf** [Exploratorio-DCC-PUC/Syllabus#414]
Hola! Al final del enunciado indica que en el PDF de la parte 2 se pueden añadir las respuestas del bonus, pero he leído el enunciado como 3 veces y aun no lo encuentro :(

> Otro archivo PDF con las consultas de la parte II junto con sus respectivos pantallazos. En este archivo puedes incluir las respuestas del bonus.

**Comment by ValentinaAlvarezG** [comment]
Hola! perdón, yo me pifié al escribir el enunciado, no hay bonus para esta tarea :c
