### ISSUE TITLE
Consultas SQL Ayudantía

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [Exploratorio-DCC-PUC/Syllabus#416]
Hola! subiré en esta issue los comandos que usé en la ayudantía por si no los pudieron ver bien de la pantalla o algo. 

```SELECT * FROM autos;```

```SELECT color FROM autos;```

```SELECT DISTINCT(color) FROM autos;```

```SELECT * FROM AUTOS WHERE marca = "KIA"; ```

```SELECT * FROM AUTOS WHERE marca = "KIA" and color = "rojo"; ```

```SELECT * FROM PERSONAS, AUTOS;```

```SELECT * FROM PERSONAS, AUTOS WHERE PERSONAS.rut = AUTOS.dueño;```

```SELECT PERSONAS.nombre, COUNT(autos.id) FROM PERSONAS, AUTOS WHERE AUTOS.dueño = PERSONAS.rut GROUP by PERSONAS.nombre;```

```SELECT PERSONAS.nombre, COUNT(autos.id) as c FROM PERSONAS, AUTOS WHERE AUTOS.dueño = PERSONAS.rut GROUP by PERSONAS.nombre HAVING c>3;```

**Recuerden además mirar el material de apoyo que es super importante!!!!!!!!**

Ánimo con la tarea c:

**Comment by ignaciomansuy** [comment]
Hola, ¿donde puedo encontrar el material de apoyo?

Saludos :)
