### ISSUE TITLE
Ciudades con nombre repetidos y dudas parte1 TC2

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#417]
Hola! Tengo una duda en la 1ra parte de la TC2. Cuando dice que en un país pueden existir ciudades con nombre repetidos, lo único que se me ocurre es hacer lo que aparece al final del material de apoyo con la tienda en línea cuando dice que un usuario puede comprar más de un producto, que es agregar una entidad. Pero a nosotros ya nos dieron las entidades, entonces asumo que no se hace así. Entonces no entiendo tampoco como darle su nombre id a la ciudad, ya que este puede salir repetido. Segundo, todas las entidades DEBEN tener su id nocierto? Independiente de que no se diga explícito en el enunciado. Tercero, todas las relaciones deben tener atributos? Si la respuesta es sí, lo debo sacar por lógica, ya que no está explícito en el enunciado?
Quedo atento!!

**Comment by ValentinaAlvarezG** [comment]
Hola! a ver, son varias cosas, trataré de responder todo e ir aclarando algunas cosas:
- No les dimos **todas** las entidades, solo avanzamos un poco el diagrama, si ustedes consideran que es necesario agregar otra entidad, la pueden agregar sin problema.
- Lo que aparece al final del material de apoyo es sobre las **relaciones**, ya que si tienes una relación, se asume que si primary key es la combinación de las primary key de las entidades que relaciona y si es que tu crees que con eso no basta para "diferenciar una fila de otra" entonces la relación necesita su propio id y por lo tanto se modela como entidad. En cambio ciudad, como les pasamos en el diagrama base, ya es una entidad y cuando hablamos de esa restricción que mencionas es  básicamente indicarles que no debes usar el **nombre** de la ciudad como primary key, porque los nombres se pueden repetir, entonces le tienes que dar su propio identificador. 
- Todas las entidades y las relaciones **deben** tener una primary key, que puede ser un atributo o varios a la vez, tu trabajo es decidir qué atributo representará este id,  lo que menionábamos en la ayudantía es que para personaspor ejemplo, uno sabe que el rut no se repite, por lo que lo podrías usar como identificador, pero para  otros casos, generalmente uno debe crear el id.
- Una relación puede o no tener atributos, si es que tiene quizás te lo damos, o dependiendo de tus supuestos le puedes agregar.

Avísame si se me fue algo c:

**Comment by vcrb18** [comment]
Me quedó clarísimo! Te pasaste por la aclaración.
