### ISSUE TITLE
Consulta respecto a parte 1 TC2

### ISSUE THREAD

**Issue by iavasquez1** [Exploratorio-DCC-PUC/Syllabus#418]
Hola!, tengo una duda respecto a la parte 1 de la TC2. ¿Los museos deben pertenecer al menos a una ciudad o podría haber alguna ciudad que no tenga museos?.
De antemano muchas gracias :)

**Comment by ValentinaAlvarezG** [comment]
Hola! los museos deben pertenecer al menos a un ciudad, pero una ciudad no necesariamente tiene museos.

**Comment by vcrb18** [comment]
Pero el enunciado dice explícitamente "una ciudad puede tener uno o más museos en su interior", por lo tanto una ciudad si tiene al menos un museo.

**Comment by ValentinaAlvarezG** [comment]
Eso igual es un poco particular de la bd pq no pusimos cuidades que no tuvieran museos, pero igual da un poco lo mismo porque no les pedimos tanto detalles de desde hasta donde va N, onda la ciudad puede tener museos, y puede ser varios y eso se representa por N, da lo mismo si es que alguna ciudad no tiene.
