### ISSUE TITLE
Consulta material de apoyo TC2, Diagrama E/R

### ISSUE THREAD

**Issue by imant1** [Exploratorio-DCC-PUC/Syllabus#419]
Hola!
En el material de apoyo, en la parte de **modelación más compleja**, en la figura 7, en la entidad Compra no se indica que esa entidad tiene los atributos uid, pid y fecha. Sin embargo, un poco más abajo, definen la entidad con palabras y se define con esos atributos. Quería saber si :
1. ¿la entidad **Compra** obtiene esos atributos implícitamente de **Usuario**  y **Producto** y por eso no se indica en el diagrama? En caso de que la respuesta sea afirmativa, ¿entonces todas las entidades  obtienen los atributos de las entidades con las que están relacionadas?
2. ¿Qué significa **c_u** en las relaciones de la figura 7?

Saludos y gracias de antemano :)

**Comment by ValentinaAlvarezG** [comment]
Hola! igual en el diagrama de esa figura no están todos los atributos en comparación con el esquema (donde está con palabras), era como para representar más que nada la diferencia con el ejemplo de la figura 6, y en la aclaración 3 indican que están creando atributos. Sobre tus preguntas:
 
1. No, las entidades no obtienen los atributos de las entidades con que están relacionadas, las **relaciones** obtienen como primary key, la combinación de las primary key de las entidades que relacionan. 
2. Creo que hay un pequeño typo ahí que da un poco lo mismo, la relación que une compra con producto debería ser **c_p**, esto lo explicamos un poco en la ayudantía, pero dos entidades siempre tienen que estar conectadas mediante una relación, así que como de la figura 6 a la 7 pasamos Compra de relación a entidad, necesitamos una relación entre Compra y Usuario y otra relación entre Compra y producto, que serían c_p y c_u, quedan con esos nombres porque da lo mismo un poco si ahí no quedan como con un verbo, si se te ocurre un verbo mejor que los relacione, bacan, pero no nos complicamos para esas relaciones que se tienen que agregar. 

Una pequeña aclaración: recuerda que cuando las relaciones son N:N necesitamos hacer una tabla para esa relación, pero cuando tenemos relaciones que son 1:1 o 1:N no es necesario hacer una tabla para esa relación, sino que basta con poner el identificador del atributo "que va en el 1" en la tabla que "tiene el N". Entonces en la figura 7, Compra y usuario se relacionan con cardinalidad 1:N entonces en la tabla que tiene el N (Compra) ponemos el identificador de Usuario (por eso cuando definimos la entidad más abajo "con palabras", es decir, ponemos el esquema de la tabla, compra tiene un uid que es el identificador del usuario). Luego pasa lo mismo con compra y producto, se relacionan 1:N y como compra "tiene el N", en compra ponemos el identificador del "que tiene el 1" que sería pid (producto).

Espero que haya servido la aclaración, avísame si tienes dudas.
