### ISSUE TITLE
Error importación de librerías

### ISSUE THREAD

**Issue by jcgarcia3** [Exploratorio-DCC-PUC/Syllabus#42]
Hola, al momento de importar las liberías en el jupyter notebook me tira este error y no se como arreglarlo:
![importacionlibrerias](https://user-images.githubusercontent.com/53884836/63613174-1c392800-c5ae-11e9-98af-2408259c7570.PNG)

**Comment by diflores** [comment]
Hola, en la consola de tu computador (cmd en Windows, Terminal en Mac), debes escribir `pip install matplotlib`.
Si estás en Mac, usa `pip3` en vez de `pip`.
¡Saludos!
