### ISSUE TITLE
Duda cardinalidad y relaciones

### ISSUE THREAD

**Issue by sofiaolmedos** [Exploratorio-DCC-PUC/Syllabus#420]
Hola! Tengo una duda sobre que significan las cardinalidades al relacionarse las entidades.
No entiendo bien si al definir estas relaciones son como a lo largo de todo el tiempo o en un instante. 
Por ejemplo en la relación N a N que se muestra en el material de apoyo, no entiendo si eso implicaría que un trabajador puede estar en muchos proyectos al mismo tiempo, o si en general puede estar en muchos proyectos pero solo uno a la vez.

**Comment by ValentinaAlvarezG** [comment]
Hola depende de como te lo plenteen en el enunciado o de los supuestos que hagas tu. Si no hacen relación al tiempo es que es mas o menos al mismo tiempo, por ejemplo con los trabajadores, que un trabajador puede trabajar en varios proyectos a la vez, pero por ejemplo también te podrían decir que a lo largo del tiempo los trabajadores pueden haber trabajado en varios proyectos y quizás te dan las fechas de inicio y término en que ese trabajador participó en cada proyecto. En la vida, depende de como lo quieras modelar y de los datos que tengas o vayas a tener y de las consultas que quieras hacer eventualmente. No se si se aclara un poco más la idea.
