### ISSUE TITLE
Relaciones con el mismo nombre

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#421]
Hola!!! Tengo una duda del diagrama E/R. ¿Puedo poner dos relaciones con el mismo nombre? Por ejemplo conectar dos entidades con una relación "Contiene" y otras dos con otra relación "Contiene". 

Gracias!

**Comment by ValentinaAlvarezG** [comment]
Hola! La idea es que no, ojalá buscar otros verbos similares para que no queden nombres iguales, sino busca la manera por último de diferenciarlas.

**Comment by denisseleiva** [comment]
Bacan, gracias! @ValentinaAlvarezG
