### ISSUE TITLE
Duda con relaciones en parte 1

### ISSUE THREAD

**Issue by sofiaolmedos** [Exploratorio-DCC-PUC/Syllabus#422]
Hola! Quería saber si es necesario que en la parte 1 se expliciten los atributos que tienen las relaciones, o si se puede asumir que estos son la mezcla las *primary keys* de las entidades que se relacionan. Y si en ese sentido me puedo ahorrar ponerlo en el diagrama y en el READ ME explicar que asumi eso.
Gracias!

**Comment by ValentinaAlvarezG** [comment]
Hola! Creo que hay una pequeña confusión, una cosa son las primary key y otra cosa son los atributos. La primary key de una relación es la combinación de las primary key de las entidades que relaciona, estas no se ponen en el diagrama y ni siquiera es necesario que lo explicite en el readme. Ahora, si la relación necesita otros atributos por alguna razón, ya sea de enunciado o por supuesto tuyo, ese atributo si debes ponerlo en el diagrama.
