### ISSUE TITLE
Explicaciones TC2

### ISSUE THREAD

**Issue by kvonstorch** [Exploratorio-DCC-PUC/Syllabus#423]
Hola!

Tengo una duda respecto a la entrega;
¿Es necesario explicar el diagrama o basta con adjuntarlo como pdf? y en la parte 2 es necesario explicar cada comando utilizado o basta con citar el lugar de donde se extrajo la información y comandos extras que ocupamos?

¡Saludos y gracias de antemano!

**Comment by ValentinaAlvarezG** [comment]
Hola, no es necesario añadir explicaciones, si quieres hacerlo, puedes hacerlo en el readme, si crees que algo no es muy claro o algún supuesto que hagas, pero puedes entregar el diagrama no mas y los comandos sin explicar (si, para los comandos, si usaste algo de Internet debes poner el link)
