### ISSUE TITLE
Parte 2 pregunta 1 y 2, duda id museo y ciudad draw.io

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#424]
Hola, en la 1ra consulta de la parte 2, debo agregar también el nombre del artista? En la 2da consulta, debo agregar una columna del país también para que haga más sentido? Ahora, en el draw.io, para la ciudad debo elegirle yo un id único, o puedo poner "cid"? Lo mismo para museos, debo poner un id que los identifique o puedo poner "mid"?

**Comment by ValentinaAlvarezG** [comment]
Hola!, para las consultas basta con que cumplas lo que pide el enunciado, si quieres agregar otra columna pq crees que así se entiende mejor, no hay problema. Sobre los id en el diagrama, si no hay algo que te demos que pueda usarse como id, debes crearlos tu, la forma en que lo indicas es lo más común: cid y mid.
