### ISSUE TITLE
Uso de ";" en SQL Online TC2

### ISSUE THREAD

**Issue by mati-gonz** [Exploratorio-DCC-PUC/Syllabus#425]
Hola! Lo que pasa es que ya terminé la parte de las consultas de la TC2 y también el pdf, pero no ocupe el ";" al final de los códigos porque no era necesario en SQL online, esto afectaría de alguna manera al momento de corregir?

**Comment by ValentinaAlvarezG** [comment]
Hola! No importa, no afectará la nota.
