### ISSUE TITLE
Duda 5 decimas por comentarios C1

### ISSUE THREAD

**Issue by robertoorrego** [Exploratorio-DCC-PUC/Syllabus#427]
Hola,
Tengo la duda sobre si las 5 decimos de bonus por hacer comentarios en el paper para el C1 ya se agregaron en la plantilla excel que mandaron mas temprano hoydia.

**Comment by IchottMano** [comment]
Hola!

Para ser sincero, se nos fué completamente. Voy a hablar con Denis sobre el tema, y cuando estén disponibles las notas actualizadas con el bonus enviaremos un aviso.
Muchas gracias por indicarnos el problema!

Saludos!

**Comment by IchottMano** [comment]
Estimado!

Se encuentran ahora actualizadas las notas con el bonus de Perusall.
Cualquier duda por este bonus me lo pueden hacer directamente a mi mail reschilling@uc.cl

Saludos!
