### ISSUE TITLE
comentarios anónimos perusall

### ISSUE THREAD

**Issue by josefinadunner** [Exploratorio-DCC-PUC/Syllabus#428]
Hola!
En la lectura para la I2 luego de hacer los comentarios, al poner el mouse encima del texto me aparece que estos serán anónimos para los demás. ¿Esto afectará que el profe no pueda ver qué comentarios hizo cada uno de forma individual? :( 
No sé si me pasa solo a mí o si alguien sabe como arreglarlo? Si alguien me puede  ayudar estaría muy agradecida.

Adjunto una foto de como se ve.
 
![Captura de pantalla 2020-10-28 195121](https://user-images.githubusercontent.com/69522233/97505547-d0270780-1957-11eb-90f7-c29192c5395a.png)

**Comment by IchottMano** [comment]
Hola!

Si bien los demás alumnos no podrán ver quien dejó el mensaje, el profesor si podrá verlo. No te preocupes.

Saludos!

**Comment by josefinadunner** [comment]
perfecto, muchas gracias!
