### ISSUE TITLE
Duda parte 1 TG2

### ISSUE THREAD

**Issue by FelipeLara00** [Exploratorio-DCC-PUC/Syllabus#430]
Hola!
1) Para la parte D nos pide hacer una normalización de la tabla y nosotros utilizamos una formula que encontramos en internet (x-min(x))/(max(x)-min(x)), pero no estamos seguros de  si eso es a lo que se refieren con normalizar. 

2) Tampoco entendemos muy bien a que se refiere con crear un label (como se hace y su función). Pensamos que puede ser un rango de percentil que los ubique según la cantidad de calorías respecto a los demás.

Saludos !

**Comment by felipegarcia98** [comment]
Hola  😁/

1. Efectivamente esa es una de las [ideas de normalizar](https://empresas.blogthinkbig.com/precauciones-la-hora-de-normalizar/#:~:text=Para%20que%20funcionen%20mejor%20muchos,est%C3%A9n%20en%20un%20rango%20definido.) a la que nos referimos, que forma parte de un [conjunto de técnicas de preprocesamiento de datos](https://blog.powerdata.es/el-valor-de-la-gestion-de-datos/preprocesar-y-normalizar-datos-4-pasos-para-limpiar-y-mejorar-datos) que son [habituales en la industria](https://docs.microsoft.com/es-es/azure/machine-learning/team-data-science-process/prepare-data). Recuerden que las decisiones que tomen deben justificarlas.

2.  Precisamente eso es lo que uds. deben decidir. La idea detrás del label es poder clasificar los datos en función de algo, calorías para este caso, y uds. deben decidir la manera de clasificar que sea más útil y/o reveladora para lo que deseen hacer. En este proceso pueden que tengan que hacer un par de iteraciones (avanzar, evaluar y corregir) para decidir, de manera clara, qué tipo de función y criterios les conviene. Recuerden que la forma en que los determinen también deben justificarla.

Saludos y éxito con la tarea 😁✌🏽

PD: Como "hint" les puedo decir que hay una función de Pandas muy útil para hacer labels, que permite cortar los datos en función de algo.
PD2: Perdón por la demora, pero feriado 🧘🏽‍♂️
