### ISSUE TITLE
Parte 1 TG2 análisis de las características

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#431]
Hola! En el enunciado cuando dice "deberán mostrar al menos un gráfico que muestre, por
ejemplo: la distribución de prevalencia de obesidad y diabetes por estado." Tiene que ser un gráfico con ambos datos(obesidad y diabetes) o puedo hacer un gráfico estados/diabetes y otro estados/obesidad

Gracias!

**Comment by denisseleiva** [comment]
Otra pregunta ajajjaj se puede hacer con gráfico de barras verdad?

**Comment by felipegarcia98** [comment]
hola 🤠/ 
&nbsp; &nbsp;  🐴 
Puedes hacerlo en gráficos distintos o en el mismo, queda a tu criterio, pero recuerda que hay estilos más convenientes que otros 🤯 .  Lo mismo respecto al gráfico de barras 😨 . 

En resumen, puedes hacer todo lo que dijiste, pero no puedes olvidarte de justificar tu elección 🧐 

Saludos ✌🏼

**Comment by denisseleiva** [comment]
Okaaa muchas gracias 😁
