### ISSUE TITLE
Interrogación 2: Consultas de alumnos

### ISSUE THREAD

**Issue by denisparra** [Exploratorio-DCC-PUC/Syllabus#432]
1. alumno xyx : Para la pregunta 1 de la parte 3 ¿Profesor necesito usar el computador para responder la pregunta de SQL, debo pegar un pantallazo?

Repuesta: No es necesario, sólo se pide como  respuesta la consulta (código) en SQL

2. alumn zyx: Para dar ejemplos de las técnicas de propaganda en la pregunta 2 de la parte 1, ¿puedo responder con un pantallazo?

Repuesta: es necesario explicar en palabras, pero pueden usar un pantallazo de soporte para responder.

**Comment by iavasquez1** [comment]
En la pregunta 3.1 ¿donde se encuentra la base de datos para hacer las consultas?

**Comment by ValentinaAlvarezG** [comment]
Hola! No hay base de datos, con los esquemas de las tablas que dimos es suficiente para que puedan realizar las consultas.

**Comment by kvonstorch** [comment]
En la pregunta 2 de la parte 1 ¿Es necesario explicar los ejemplos?

**Comment by vcrb18** [comment]
Me sumo a lo preguntado de arriba, cuando dicen que en la pregunta 2 parte 1 hay que explicar con palabras los ejemplos, podemos usar los explicados en palabras del paper?

**Comment by denisparra** [comment]
> En la pregunta 2 de la parte 1 ¿Es necesario explicar los ejemplos?

Sí, es necesario.

**Comment by denisparra** [comment]
> Me sumo a lo preguntado de arriba, cuando dicen que en la pregunta 2 parte 1 hay que explicar con palabras los ejemplos, podemos usar los explicados en palabras del paper?

Puedes usar los ejemplos del paper, pero debes explicar con tus propias palabras para evidenciar entendimiento del tema.

**Comment by mati-gonz** [comment]
Hola! en la pregunta 4.1 cuando se nos pide generar una estrategia para clasificar los dataset mp3, tenemos que nosotros decir que es lo que podría hacer un método con aprendizaje supervisado y no supervisado, o tenemos que decir alguno de los que vimos en clases?

**Comment by denisparra** [comment]
> Hola! en la pregunta 4.1 cuando se nos pide generar una estrategia para clasificar los dataset mp3, tenemos que nosotros decir que es lo que podría hacer un método con aprendizaje supervisado y no supervisado, o tenemos que decir alguno de los que vimos en clases?

Por "estrategia" me refiero a los insumos que necesitas en términos generales. Si quieres agregar detalles del métodos supervisado, según lo que vimos en clases, es bueno pero no 100% necesario.

**Comment by mati-gonz** [comment]
Gracias profesor. Otra duda, si tengo malo el bonus, me perjudicaría en la nota?

**Comment by felipegarcia98** [comment]
> Gracias profesor. Otra duda, si tengo malo el bonus, me perjudicaría en la nota?

ñope, solo suma
