### ISSUE TITLE
Consulta de base de datos parte 3

### ISSUE THREAD

**Issue by iavasquez1** [Exploratorio-DCC-PUC/Syllabus#433]
Para la pregunta 3 no me queda claro en que parte se encuentra la base de datos. ¿Donde está para realizar las consultas?

**Comment by ValentinaAlvarezG** [comment]
Hola! No hay base de datos, con el esquema de las tablas dadas es suficiente para que hagan las consultas.

**Comment by iavasquez1** [comment]
Ok, muchas gracias!
