### ISSUE TITLE
I2 Parte 3.2

### ISSUE THREAD

**Issue by martin-iturralde** [Exploratorio-DCC-PUC/Syllabus#434]
Hola! A que se refiere que tenemos quedar un ejemplo concreto? Es decir, tenemos que poner a nivel de codigo, o puedo explicar como casos entre la diferencia entre usar python o SQL?

**Comment by denisparra** [comment]
Hola, puedes usar código o también puedes no usarlo. Ojo que estoy hablando del Sistema de administración de bases de datos y todo lo que implica, no solamente una comparación a nivel de lenguaje SQL vs. Python.

**Comment by denisseleiva** [comment]
Hola profe @denisparra , sigo con la duda. Con ejemplos se refiere a "razones" de por qué sería mejor usar un sist de BDD? O realmente ejemplos en que se haya elegido usar BDD antes que un codigo de python 🤔

**Comment by denisparra** [comment]
Disculpa lo tarde, razones o ejemplos estarían OK, porque los ejemplos deberían justificarse con razones.
