### ISSUE TITLE
Uso de librerías en Tarea Grande 2 parte 1

### ISSUE THREAD

**Issue by En-clases** [Exploratorio-DCC-PUC/Syllabus#435]
Hola, tengo una duda acerca de las librerías que podemos utilizar en la tarea grande 2 parte 1. Podemos utilizar, por ejemplo, la librería ```numpy``` para hacer operaciones sobre las columnas del dataset?

**Comment by felipegarcia98** [comment]
Hola 🧒🏼/
&nbsp; &nbsp; 🐔 

yes, aunque ojo que también puedes hacerlo con Pandas, mediante broadcasting, apply y otras funciones. Pandas trabaja con Numpy de fondo, por lo que hartas de sus funcionalidades están incluidas

Éxito 😄

**Comment by En-clases** [comment]
Ok!! gracias.
