### ISSUE TITLE
Problema con graficos de TG2

### ISSUE THREAD

**Issue by PabloLaporte** [Exploratorio-DCC-PUC/Syllabus#437]
Hola, hemos intentado varias formas de graficar con matplotlib y nos dimos cuenta que no esta mal el codigo, sino que por alguna razon sale este error: _/usr/local/lib/python3.6/dist-packages/pandas/plotting/_matplotlib/core.py:328: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = self.plt.figure(figsize=self.figsize)
*c* argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with *x* & *y*.  Please use the *color* keyword-argument or provide a 2-D array with a single row if you intend to specify the same RGB or RGBA value for all points._
y no nos salen los graficos.

**Comment by PabloLaporte** [comment]
Me falto agregar que intentamos hacerlo con un sample ya que el error dice que se abrieron mas de 20 figuras pero tampoco funciono.

**Comment by felipegarcia98** [comment]
yaa, si. En matplotlib las figuras serían como cada gráfico, por lo que hacer samples no afecta ya que el tema es el código, que le está exigiendo mucho al matplotlib.

Sería interesante si pudieras mostrar una idea de lo que es tu código (no el código en sí), para poder entender que puede ocasionar el tema. A lo mejor te esta haciendo falta un plt.show() o te excediste con algún parámetro.
