### ISSUE TITLE
Duda preprocesamiento de datos (específicamente NaN)

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#438]
Hola, me surgió una duda con respecto al tema del preprocesamiento. En nuestro caso revisamos cuantos valores nulos habían en el dataset y eran 44 de 1387 filas, por lo que eran solo aproximadamente un 3% del total. Entonces argumentamos que como es solo un 3% no nos va a influenciar que saquemos esas filas del dataset. Sin embargo después se me ocurrió, por ejemplo que que pasaba si justo esas de repente tenían la mayor cantidad de bookmarks en comparación a las otras por ejemplo, entonces podrían haber sido muy importantes las filas que borré, o no solo con los bookmarks, con cualquier otra columna. Entonces mi pregunta es, que tan estricto tengo que ser, que tan estricta será la evaluación de los argumentos que usemos? Quedo atento
Vicente Cruz

**Comment by felipegarcia98** [comment]
sinceramente, no seremos tan estrictos. Queremos que ustedes piensen, razonen y justifiquen lo que hagan.  Me intriga eso que dices de la cantidad de bookmarks. Yo creo que  sería interesante si pudieras contra argumentar con algo  desde el análisis del dataset o de la literatura, pero un 3%, para un trabajo de este nivel, es marginal y puedes no considerarlos. Teneis mi permiso :3-Percent Pass:
