### ISSUE TITLE
Duda creación de label TG2

### ISSUE THREAD

**Issue by srodriguezp** [Exploratorio-DCC-PUC/Syllabus#439]
Hola, en la parte 1 de la tarea nos piden crear un label en función de las calorías de las recetas y nos dan como referencia los sellos de las comidas, no entiendo bien como hacer la relación ya que solo existe un sello que se calcula en función de las calorías. También me quedan dudas al momento de la clasificación ya que si hacemos esta solo en función de las calorías, el resto de los atributos de la receta no contribuirían en nada.

**Comment by felipegarcia98** [comment]
Hola o/ 

Los sellos de la comidas se setean bajo umbrales por porción, donde las comidas que los superan adquieren los determinados sellos  correspondientes a los umbrales pasados. Ahora, los sellos solo dicen "Alto en {característica}", pero que pasaría si hicieran una escala más grande, más informativa. Algo así es lo que les pedimos.

En términos matemáticos podrían no contribuir en nada, pero esto es data science :tehc: y creemos que la información de los datos pueden reflejar tendencias y características que permitan clasificarla sin poseer su clasificación (eso sonó enredado jjsjs). A qué me refiero? ustedes tienen todos los datos y tendría poco sentido crear un clasificador que catalogue el nivel de calorías de alimentos si es que ya tengo los datos de las calorías y la función clasificadora, pero ese no es el caso si por X razón pierdo la información de las calorías y debo clasificarlas en función de las otras categorías. Es ahí donde entran los clasificadores que les pedimos hacer

**Comment by denisseleiva** [comment]
Holis @felipegarcia98  podrías explicarlo de otro modo quizás? Estoy igual de perdida con la explicación que le diste al compañero 😥

**Comment by felipegarcia98** [comment]
Chaaaale, que te complico?

Ya, para lo primero cambiare la referencia. Ahora tomen como referencia una posible escala de transformación de notas tradicionales a notas de religión, pasando de números del 1 al 7 a una escala de insuficiente hasta excelente. Es más o menos esa la idea, solo que notas tradicionales serán las calorías.

Para lo segundo, consideren lo que les dijimos en ayudantía. Aquí uds van a trabajar con 2 algoritmos clasificadores del tipo Supervisado, por lo que requieren una etiqueta y, ante eso, nosotros les pedimos que la etiqueta sea en función de las calorías. Ahora, no tendría mayor sentido construir un clasificador que clasifique a los estudiantes  y prediga sus promedios de religión si es que ya puede acceder a ellos y tampoco es el caso que queremos analizar, sino que el caso donde el clasificador no tiene esos promedios y debe intuirlos de otras características. Para intuirlo de las otras características, debe ser entrenado para clasificar, prediciendo algún promedio en función del resto de características.

Quizás les complica entender el pq  inventar un label en función de algo que ya tenemos y tratar de predecirlo si ya lo tenemos, pero hay que entender que la idea es que nuestros modelos-clasificadores sean capaces de determinar a que categoría pertenece una instancia  que podría no venir del mismo dataset, que podría no tener  ese label o esa característica que lo determina, etc. Ahora, resulta que ese label no venía inicialmente, por lo que ustedes deben inventarlo en pos de poder ocupar algoritmos supervisados

**Comment by denisseleiva** [comment]
Mmmm entiendo un poco mejor pero igual es como muy abstracto todo jajjaajja tengo más dudas puntuales pero voy a hacer otra issue para que le dejen de llegar notificaciones al autor de esta issue ajjaja

**Comment by srodriguezp** [comment]
Ahi me quedo mas claro, gracias!
