### ISSUE TITLE
Donde escribo el codigo HTML

### ISSUE THREAD

**Issue by migil1005** [Exploratorio-DCC-PUC/Syllabus#44]
Estoy confundido con esta parte porque en todos lados te explican como escribirlo, pero no donde o como abrirlo para que parezca pagina web y no código html.
Gracias a cualquiera que me ayude

**Comment by diflores** [comment]
Hola,

No entendí muy bien tu pregunta, pero intentaré responder: lo primero que debes hacer es crear tu archivo de extensión `.html` con tu editor de texto favorito (Atom, Sublime Text, Visual Studio Code, Bloc de Notas, etc) y luego, para ver cómo luce, puedes abrirlo con tu navegador favorito (Chrome, Firefox, Safari, Internet Explorer, etc). Click derecho y "abrir con" te puede ayudar a alternar entre editar tu código y verlo en el navegador.

¡Saludos!

**Comment by migil1005** [comment]
Gracias!!
