### ISSUE TITLE
Cuales son los géneros mas escuchados

### ISSUE THREAD

**Issue by jitorralba** [Exploratorio-DCC-PUC/Syllabus#44]
Hola! Cuando se refieren a los géneros más escuchados, ¿considera o no el numero de reproducciones que tienen los artistas que están en el otro archivo? O solamente se refiere a un conteo de los géneros que estás en artists_genres_images?

**Comment by diflores** [comment]
Hola:
Efectivamente se considera el número de reproducciones. Es por esto que se sugiere usar el método `merge` de `pandas` para combinar la información de ambos archivos.

¡Saludos!
