### ISSUE TITLE
Encoder parte 1

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#440]
Hola, estoy teniendo demasiados problemas con el encoding de los state y county. Lo he intentado solo con el county ahora, y no sé como hacerlo, porque claramente no puedo ocupar LabelEncoder ya que los números tan grandes me van a pesar muy distinto y si uso Binarizer encoder me están quedando infinitas columnas. De verdad no sé como seguir avanzando en esto y por eso acudo aquí :(. Quedo atento.

**Comment by felipegarcia98** [comment]
hola o/

Habemus infinitas columnas entonces. 
Bienvenida sean las dummies variables

&nbsp; &nbsp; &nbsp; &nbsp;  &nbsp;🔥\🤪/🔥

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html

Nos comunicas si hay problemas

**Comment by vcrb18** [comment]
Al final no ocupé el Binarizer con más de mil columnas que sentí que no se entendía nada y ocupé otro encoder y después lo arreglé un poco para que me quedara en un rango más pequeño de números. Gracias igual!
