### ISSUE TITLE
Seaborn

### ISSUE THREAD

**Issue by ctoro05** [Exploratorio-DCC-PUC/Syllabus#441]
Hola!! Estaba haciendo la parte del pre procesamiento pero al momento de ejecutar códigos con seaborn me aparece esto ![image](https://user-images.githubusercontent.com/69521459/98400568-ff6a0280-2042-11eb-864b-848480ea0eba.jpeg)

Que puede ser eso?

Gracias!!

**Comment by felipegarcia98** [comment]
emmmm, podría ser hartas cosas, desde que diste un parámetro equivocado hasta que este haciendo print de una func o variable que no retorna nada legible. Necesito un poco mas de info :3 (aunque poniendo una idea de código)
