### ISSUE TITLE
Uso de funciones parte 1 TG2

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#444]
Hola!!! Quería saber si está permitido el uso de funciones para la parte 1 de la tarea usando el método _apply_ de pandas

Gracias 😁

**Comment by felipegarcia98** [comment]
Hola o/
Estaría terrible no poder usar funciones jsjsjsj. Nosotros prohibimos ciclos (no intenten evitarlos usando recursiones, la idea es vectorizar).

PD: Por qué pensaste que no se podían ocupar funciones? 😅

**Comment by denisseleiva** [comment]
No sé jajaj me entró la duda y preferí preguntar me perd0nas? 😔

**Comment by felipegarcia98** [comment]
![image](https://user-images.githubusercontent.com/42228743/98419392-bc6c5700-2063-11eb-93d1-b63e398f0dda.png)
