### ISSUE TITLE
Nombre informal del repositorio

### ISSUE THREAD

**Issue by PatoLands** [Exploratorio-DCC-PUC/Syllabus#445]
Hola, con mi compañera queriamos cambiarle el nombre al repositorio debido a que le pusismos "patrigna uwu 2" antes de leer el requisito de formalidad del nombre.
No sabemos si crear otro repositorio o si se le puede cambiar el nombre.

**Comment by felipegarcia98** [comment]
Me declaro ignorante si es posible cambiarle el nombre o no. Se les perdona por esta vez, pero  que no vuelva a ocurrir uwu


PD: No creo perdonar a alguna otra pareja o trabajo #aviso :3
