### ISSUE TITLE
Label parte 1 TG2

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#446]
Holis
Tengo unas dudas puntuales sobre la creación de labels
1. Entiendo que tenemos que definir este label basado en otras características y que tenemos que asignarne un label al dataset actual, entonces es algo como si hay tanta cantidad de proteinas y tanta de grasa entonces determino que el label será X?
2. Cuando dicen que el sello de las comidas sería una referencia interesante, se refieren a que los valores del label sean onda "Alto en calorias", "Alto en azucares"? Como que  no entiendo si el label es sólo en base a calorías que tomemos como referencia lo de los sellos. 
3. El label debe ser creado antes o después de normalizar? O da lo mismo el orden?

Gracias por responder jeje no puedo avanzar sin esto del label 😭

**Comment by felipegarcia98** [comment]
1.- Casi. Tienes que definir el label basado en la categoría calorías, pero busca entrenar y predecir en función de las otras, entonces sería "X calorías clasifica los datos en la categoría Z" (preprocesamiento), "tío clasificador, aprenda que si se dan estas relaciones entre características, entonces debe decir que son esta categoría" (entrenamiento, fit) y luego "tío clasificador, tengo estas instancias con todas estas características, dime cuales serían sus categorías" (clasificación, predict)

2.- Hacía la referencia pensando en un string que se adjudica cuando se cumple [cierta condición, cierto umbral](https://www.minsal.cl/ley-de-alimentos-manual-etiquetado-nutricional/), y era interesante porque hablan de las características de la comida, pero no era para que intentaran hacerlos homólogos. Ahora, nosotros les dijimos que sean 4 categorías, por lo que, siguiendo esa "referencia interesante", tendrían que ver como asignar 4 sellos para diferentes niveles de calorías (siento que es más fácil verlo con las notas de religión de la issue pasada)

3.- No sabría decirte si da lo mismo el orden, pero decide tu el orden que deseas realizar y justifica. Realmente depende del tipo de función-condición que impongas para establecer los labels y de qué tanto sentido haga, pero no te recomiendo calentarte tanto la cabeza 😉 

jsjsjsjs u.u éxito

**Comment by denisseleiva** [comment]
jajajajaajaja ya me calenté la cabeza hace rato🤯🤯🤯🤯🤯🤯🤯🤯🤯
Voy a meditar tu respuesta, muchas gracias!

**Comment by felipegarcia98** [comment]
asjkjakj dale, suerte y étixo 😄  recuerda que también puedes ver la ayudantía para guiarte un poco sobre la normalización 😉
