### ISSUE TITLE
Dudas generales en el preprocesamiento

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#447]
Hola, perdón que haga otro issue pero me está costando bien entender qué hacer en esta tarea. 
1) No entiendo como saber que columnas van a ser importantes después para mi algoritmo, cómo hago para saber esto? Esto me influye muchísimo ya que con esto voy a saber que columnas necesito normalizar o ver que columnas puedo sacar.
2) Qué se debe hacer primero, normalizar o hacer el label? Es decir, normalizo y después separo en mi matriz y el vector (como aparece en el pdf de TG2), o separo en matriz y vector y ahí normalizo la matriz?( como aparece en la ayudantía).
3) Deben estar todas las columnas normalizadas por igual, es decir por ejemplo todas de 0 a 1? Sé que esto depende según la importancia que le quiera dar a cada columna posteriormente para el algoritmo, pero esto acude de nuevo a mi duda del inicio, de cómo hago para saber que es más importante para el algoritmo.
4)"crearemos un label en función de las calorías, el cual
debe tener, al menos, 4 posibles valores (los sellos de las comidas son una referencia interesante)." Según entendí en la ayudantía debería crear mi matriz con las columnas, sin incluir en este caso las calorías porque esta columna será mi vector de label. Sin embargo, me pierdo con la parte de "el cual debe tener al menos 4 posibles valores", (sé que esto lo contestaron en otros issues pero no lo logro entender). A qué se refiere eso? No entiendo la lógica :S.
Perdón por lo largo del issue pero no logro avanzar hasta que no entienda esto :/.

**Comment by felipegarcia98** [comment]
Esta bien, haga issues no más 😉 

1.- Recuerdo que lo mencionamos en alguna de las 2 ayudantías ( o ambas).  Hay múltiples enfoques, desde una selección a priori donde te "tiras a la piscina" pensando en que algunas te sirven y otras no, pasando por una donde ver los niveles de correlación entre cada feature con su label, hasta un simple y efectivo "prueba y error" donde vas entrenando y ves como varía el rendimiento de tus clasificadores.

2.- No te calientes tanto la cabeza 😉 , si quieres puedes guiarte por lo que se hizo en la ayudantía 😄 👍🏼 

3.- Cuidado, no es que necesariamente uno deba decidir el orden de importancia o el más importante para un algoritmo. Lo que se menciona en la ayudantía es que a veces uno puede querer que haya algunos pesos para que ciertas características importen más, pero, para este caso, no es necesario establecer mayor diferencia entre las columnas elegidas (será el clasificador el que determinara a que características hacerle más caso)

4.- Ya, digamos que debo hacer un label en función de las proteínas de los alimentos. Yo podría decir que haré labels del tipo "{bajo/medio/alto} en proteínas" y que estableceré ciertas condiciones para que estén en una u otra categoría. Por ejemplo:
* bajo si tiene menos del 5% de su masa en proteínas, medio si bajo 15% y alto sobre 15%
* bajo si tiene menos de un 5% de la Dosis Diaria Recomendada, medio si bajo 30% y alto sobre un 30% de la DDR
* bajo si tiene menos que el percentil 25 de los alimentos del dataset, medio si bajo el percentil 75 del dataset y alto sobre el percentil 75
* bajo si es líquido y menos de 1% de la masa en proteínas o si es sólido y menos del 10%, medio si menos del 3% para líquidos o menos del 20% para sólidos y alto desde esos valores para arriba
* etc

**Comment by vcrb18** [comment]
te pasaste!!
