### ISSUE TITLE
Error parte 3 TG2

### ISSUE THREAD

**Issue by En-clases** [Exploratorio-DCC-PUC/Syllabus#448]
Hola, tengo un problema para ejecutar el algoritmo KNN (probé con el código que se mostró durante la ayudantía). La siguiente imagen muestra el error al intentar ejecutar el código:
![image](https://user-images.githubusercontent.com/69520590/98448601-eb3e0800-210b-11eb-8460-f3bfcbb25bc8.png)
He buscado en internet y he intentado cambiar algunas cosas para ver si el problema se arreglaba pero siempre aparece lo mismo :c. Espero puedan ayudarme, gracias.

**Comment by felipegarcia98** [comment]
Bueno, según lo que veo tienes que revisar tus datos, específicamente buscando NaNs en tu X. Si no fuera eso, entonces tendrías que revisar si es que tienes valores decimales con números enteros grandes y decimales grandes o cosas de ese tipo, pero me inclino a que trata sobre lo primero que menciono

**Comment by En-clases** [comment]
Tenías razón, tenía NaNs en mis datos y no me había dado cuenta. Gracias!
