### ISSUE TITLE
Consulta modificación de columnas

### ISSUE THREAD

**Issue by matyjjn14** [Exploratorio-DCC-PUC/Syllabus#449]
Hola, en mi grupo salió la duda, de que si es posible modificar los datos de las columnas, en específico si queremos encasillar todos los datos de calorías en 4 grupos , podemos modificar los datos de esta columna en numero del 0 al 3?

**Comment by felipegarcia98** [comment]
hola o/ 

efectivamente es una manera, siempre y cuando no los modifiques azarosamente xD. Personalmente recomendaria que fuera un string, como para hacerlo más autoexplicativos los labels
