### ISSUE TITLE
Cómo elijo de que forma normalizar

### ISSUE THREAD

**Issue by josefinadunner** [Exploratorio-DCC-PUC/Syllabus#450]
Hola! 
Al momento de normalizar los datos, como sé cual forma es la mejor usar? Me refiero a que por ejemplo, en qué casos me sería más útil usar minmax y en qué casos sería más útil usar standard scaler? 
Si alguien me podría dar un ejemplo random de cuándo usar cada uno sería muy bacán, que no sé bien distinguir por qué se debería elegir uno o otro para cierta situación:(

Desde ya muchas gracias.

**Comment by felipegarcia98** [comment]
puchi, la idea es que eso lo busques tu :c te recomiendo pegarte una búsqueda en google en inglés preguntando eso

**Comment by josefinadunner** [comment]
ah yayaya, gracias iwal
