### ISSUE TITLE
Duda con valores del dataset TG2

### ISSUE THREAD

**Issue by josefeliuf** [Exploratorio-DCC-PUC/Syllabus#451]
Hola! al estudiar el dataset me surgió la siguiente duda:
El enunciado nos indica que que la columna 'cal' es:

> 'cantidad de calorías promedio de las recetas de dicho condado en USA.' 

y que la columna 'cal_fat' es:

> 'cantidad de calorías provenientes de la grasa promedio de las recetas de dicho condado en USA'. 

Al usar el metodo 'describe' de pandas, pude acceder al promedio de ambos respecto al dataset completo, cuyos valores son 336.682920 para 'cal' y 159126.651824 para 'cal_fat'. Estos valores, si nos guiamos por el enunciado, no tienen ninguna relación. Asumo entonces que la unidad de medida para 'cal' es Kilocalorías (en contraste a lo que dice el enunciado) y para 'cal_fat' es efectivamente Calorías? y ahí si tendría sentido. O es un error?

**Comment by felipegarcia98** [comment]
efectivamente es lo que haría sentido y así es. Sería interesante cambiar los valores a uno común, no?

**Comment by josefeliuf** [comment]
oka! muchas gracias
