### ISSUE TITLE
ACLARACIONES Sobre la creación de Labels

### ISSUE THREAD

**Issue by felipegarcia98** [Exploratorio-DCC-PUC/Syllabus#452]
Se me ha hecho notar que estan muy acomplejados con esta parte, así que abro esta ayuda:

1. La idea al crear los labels es que existan categorías con las que puedan hacer un aprendizaje supervisado. Una vez creados los labels, estos son el vector Y y la matriz X sería todo el resto de características (yo no dejaría la calorías en esta matriz, ya que la transformación sería directa para que el clasificador determine los labels). 
Luego, para el **entrenamiento (fit)**, uds le pasan los X_train y los Y_train al modelo, para que el aprenda que dado ciertos patrones en la matriz de características, se obtienen determinadas categorías. 
Después de entrenado el modelo, ustedes deben evaluar el rendimiento, para lo cual deben usar los X_test e Y_test (en esta parte el clasificador intenta **predecir-predict-** los labels de las instancias dadas las características en X_test)
2. Ustedes deben hacer 4 labels en función de las calorías. Cómo se pueden establecer estas **categorías (bins)**? En la issue #447 puse un ejemplo como si hiciera 3 labels en función de las proteínas. No es la idea que la complejicen más, solo basta que establezcan conjuntos dentro del espectro de las calorías.
3. No consideren el ejemplo de los sellos, ya que esta enredando más de lo que esta ayudando. Es mejor pensarlo como si quisieran hacer una transformación de notas entre promedios tradicionales y "promedios de religión" como señale en la #439 , donde uds transforman un conjunto de números reales (notas de promedio) a un conjunto de strings (promedios Muy Bueno, Bueno, Suficiente, Insuficiente) .
4. Una función que siento que les podría ser de utilidad para el proceso de crear los labels es la función [**cortar (cut), de Pandas**](https://pandas.pydata.org/docs/reference/api/pandas.cut.html). Anteriormente intente colarles las pista hablando de cortar, but anyway.
5. Sobre si normalizar los datos de los labels o si hacerlo antes o después, no se calienten mucho la cabeza. Háganlo como se les muestra en la ayudantía, como les haga sentido o como les sea más fácil, pero justifiquen.
6. Sobre el enfoque de la tarea, insisto, la tarea se hizo sin pensar en complicarles la vida. Lo que buscamos es que ustedes conozcan y aprendan cosas, por lo que les pedimos que hagan cosas, que tomen decisiones y las justifiquen. Las justificaciones es lo que más importa, los resultados pueden variar según las decisiones e hiperparámetros que consideren, pero son las dudas, los problemas y las resoluciones de estas las que importan en su aprendizaje. Tampoco les vamos a pedir que consulten infinitas fuentes, ni que nos hagan un ensayo o que no dejen espacio para dudas o pequeños errores de justificación, pero si que se vea un proceso racional detrás de sus elecciones y que tengan un background de conocimiento detrás

**Comment by josefeliuf** [comment]
Hola @felipegarcia98!
Hay algo que no me hace mucho sentido:
¿Por qué las calorías son el label en esta tarea?, a lo que voy es que en estricto rigor no hay nada que predecir, pues a partir de los gramos de proteinas, carbohidratos y grasas promedio, podemos calcular directamente las calorías promedio que va a tener la comida (pues 1g de proteinas y carbs corresponden a 4kcal y 1g de grasas corresponden a 9kcal). Por lo tanto, si en vez de hacer un algoritmo para predecir las calorías, hacemos el calculo directamente, nuestro algoritmo tendría un 100% de efectividad. 
Espero que se entienda,
Saludos
_EDIT:_ A lo que voy es que las calorías no son algo que se debe predecir, sino que siempre son un valor fijo si es que tenemos las cantidades de los macronutrientes que componen esa comida, como en este caso.

**Comment by diegoalvarado10** [comment]
Hola @felipegarcia98 
Hay que botar el feature calorias despues de crear el label?
gracias

**Comment by felipegarcia98** [comment]
Interdisciplinaridad  😍 efectivamente lo que dices es correcto ~y me encanta que lo hayan notado~ y definitivamente puede ser un enfoque más correcto dada la situación que damos, pero queremos que experimenten con machine learning y puede servir.

Ahora, unas preguntas interesantes que se pueden hacer es por qué sus algoritmos no llegan a 100% siendo que, en teoría, el paso de las características a las diferentes calorías es sumamente directo (combinación lineal yera); qué pasaría si los datos tienden al infinito (n suficiente grande); si es que hay casos en que podría tener sentido entrenar tamaña herramienta para matar moscas; etc. Sad que no preguntamos eso directamente, pero se puede analizar en la parte 1 😥



<br><br>
<br>


Es recomendable que boten esa feature, ahí ya sería demasiado directa la transformación feature->label para el clasificador (sería esperable que literalmente ignore el resto de características)

**Comment by JupaOlivares** [comment]
También pueden ver como otros factores inciden en las calorías 👀, como por ejemplo si existe relacion entre bookmarks y calorias (en una de esas a la gente le gusta las recetas con mas calorias y generan un buen predictor), entre otros. Asi puedes justificar mejor tu elección de predictor
