### ISSUE TITLE
Busco pareja TG2

### ISSUE THREAD

**Issue by SamWeinstein** [Exploratorio-DCC-PUC/Syllabus#453]
Busco pareja, no conozco a nadie :( y no se donde encontrar pareja, fui ayudante de programación avanzada (para incentivar a alguien a ser conmigo xd). Me pueden contactar al +56 9 9129 5286

**Comment by JupaOlivares** [comment]
Hola, te recomiendo mandar mensaje por Canvas, eso les avisa a todos!
