### ISSUE TITLE
Gráficos parte 2 - TG2

### ISSUE THREAD

**Issue by kvonstorch** [Exploratorio-DCC-PUC/Syllabus#455]
Hola, tengo dos dudas respecto a los gráficos en la parte 2 de PCA y T-SNE. 

1. ¿Hay que graficar solo una visualización 2D del PCA (en nuestro caso) o también hay que graficar la eficiencia el PCA (de la misma forma que vamos a tener que hacerlo con KNN)? 
2. ¿Podemos ocupar la librería plotly para graficar el PCA en la segunda parte?

**Comment by felipegarcia98** [comment]
1.- Te recomiendo revisar lo que es el PCA. Para este caso, no importa saber la "eficiencia" del PCA
2.- Si puedes ocupala para graficar

**Comment by vcrb18** [comment]
Me sumo a este issue, porque no entiendo por qué no es importante saber la eficiencia, en todos los links que he buscado he encontrado el código que termina mostrándote el accuracy del PCA. La mayoría no muestra nada de graficar entonces no entiendo bien el enfoque de esta parte. Como además no lo vimos en la ayudantía estoy medio perdido. Acepto todo tipo de ayuda :).

**Comment by felipegarcia98** [comment]
O sea, realmente no es que no sea importante saber la eficiencia, pero nos redujimos a que solo se enfoquen en lo principal que nos interesa. Los algoritmos PCA y t-SNE suelen tener muy buenos rendimientos, explicando con las primeras 2 variables gran parte de la información (varianza), por lo que omitimos esta parte de visualizar su rendimiento (caso distinto hubiera sido si les pidiéramos que clasifiquen en función de los resultados de la reducción). 
Luego, al tener una buen resumen de la información en 2 o 3 variables, la visualización de ellos te permite tener una buena idea (bastante acertada) de como se distribuyen los datos, lo cual es lo que nos interesaba  revisar. 
Entonces, qué nos interesaba revisar? Ver cómo es que los datos se agrupan (clusters), que características tienen en común los miembros de un cluster y en qué se diferencian con otros clusters, cómo se puede caracterizar nuestro dataset en función de estos clusters y sus densidades, etc.
