### ISSUE TITLE
Prueba de distintos hiperparámetros parte 3 TG2

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#456]
Hola!
En esta parte de la tarea se prueban los hiperparámetros del clasificador y además se cambia el tamaño del set de prueba? O sólo los hiperparámetros? Pregunto porque en el enunciado dice "los pasos señalados anteriormente deben ser repetidos" y me entró la duda. 

Lo otro, para cada combinación de hiperparámetros hay que calcular las 4 métricas separadas o puedo, por ejemplo, sólo fijarme en el accuracy para ver cuál combinación es mejor y luego calcularle las 4 métricas a esa combinación?

Gracias! :3

**Comment by felipegarcia98** [comment]
Hola o/
* El cambio de tamaños de set de pruebas es independiente de lo pedido para los hiperparámetros. 
* Lo recomendable sería que vieras los diferentes parámetros y no debiera ser tanto más complicado, como un classification report. Considerar que una métrica no cubre todo los aspectos del rendimiento de un modelo, pero si decides enfocarte en alguno, justifica (también justifica si miras todos xD)

:3
