### ISSUE TITLE
Duda TG2 - Preguntas

### ISSUE THREAD

**Issue by josefeliuf** [Exploratorio-DCC-PUC/Syllabus#457]
Hola! 
Las preguntas se pueden ir respondiendo a medida que hacemos la tarea, sin especificar cual pregunta estamos respondiendo? o necesariamente se debe hacer un apartado al final para responder pregunta por pregunta?

**Comment by JupaOlivares** [comment]
Hola!
Las respuestas deben estar respondidas en un apartado final, indicando la pregunta.

**Comment by josefeliuf** [comment]
Da lo mismo si repetimos información que ya habíamos puesto cuando explicabamos paso a paso lo que hicimos?

**Comment by felipegarcia98** [comment]
Da lo mismo, no son excluyentes. De hecho, puede ayudarte a explicar mejor
