### ISSUE TITLE
Problemas Parte 4

### ISSUE THREAD

**Issue by vcrb18** [Exploratorio-DCC-PUC/Syllabus#458]
Hola, estoy haciendo el Decision Tree, luego de ya haber trabajado con el knn. Con el knn logré llegar a un 83% de accuracy, lo que siento que está bien y ahora me toca hacer este proceso con el Decision Tree, pero no logro pasar de 26% accuracy y es independiente del max_length. Es decir, cambio ese parámetro, pero el accuracy no me cambia y tampoco logro subirlo. Qué puedo estar haciendo mal? Intenté hacer todo lo que hice en knn para mejorar la "eficiencia" del algoritmo pero no me resulta. Quedo atento

**Comment by felipegarcia98** [comment]
variaste el min samples ? 

Recuerda que lo que más nos importa son las justificaciones y el análisis que puedas hacer
