### ISSUE TITLE
Parte 3 hiperparametros

### ISSUE THREAD

**Issue by josefinadunner** [Exploratorio-DCC-PUC/Syllabus#459]
Hola! 
En la parte 3, al ir modificando los hiperparámetros para hacer distintas instancias, ¿es válido modificar también el set de entrenamiento y testeo? ¿o debo mantener el mismo set de entrenamiento y testeo para todas las distintas instancias a las cuales les cambio los hiperparámatros?

Desde ya muchas gracias!

**Comment by felipegarcia98** [comment]
Hola o/

Es válido, pero, al igual que todo, debes justificar. El hábito de mantener constante, de _ceteris paribus_, va más por la búsqueda de hacer un proceso de experimentación con A/B Testing, que es como lo tradicional, más claro de hacer y que es más exhaustivo

**Comment by josefinadunner** [comment]
perfecto, muchas gracias!
