### ISSUE TITLE
Labels y KNN

### ISSUE THREAD

**Issue by tomasnusser** [Exploratorio-DCC-PUC/Syllabus#460]
Hola! La verdad es que a mi compañero y a mi nos ha costado harto entender la tarea (inclusive viendo las ayudantías) por eso queríamos pedir ayuda en la parte de labels y KNN por este medio. Leí algunas issues al respecto pero sigo sin entender.

Utilizamos el mismo método que en la ayudantía para crear la matriz (normalizamos de otra forma pero quedó bien hecho) y aún así nos tira un error. Más que eso me cuesta saber como arreglarlo porque no sé muy bien lo que estoy haciendo y tal vez me estoy complicando más de lo necesario.

Agradecería una ayudita en esta parte para agarrarle el ritmo a la tarea y poder seguir. Muchas gracias :)

**Comment by felipegarcia98** [comment]
Hola  o/ 
U.U obvio que les ayudo 😉

qué error les tira? haciendo qué?

**Comment by tomasnusser** [comment]
Primero que nada, por lo que entendí de los labels hay que crear una nueva columna que los contenga y no sabemos como hacer eso :v 
Segundo, nos tiraba un error al hacer el KNN pero ya lo arreglamos. Ahora eel problema es que nos tira un porceentaje pero muy bajo (0.5% aprox) pero lo hacemos igual a la ayudantía entonces no sabemos en qué eestamos mal

**Comment by felipegarcia98** [comment]
en la issue de aclaración #452  resumí bastante las diferentes issues y señalé que una función que podría serles útil es pd.cut()  (para mayor info puedes ir a la documentación o hacer  pd.cut? en el notebook), aunque tmbn podrías  hacer tu mismo una rutina de funciones pandas que lo hagan.  Ahora, tmbn puedes reemplazar la actual columna calorías con los labels, lo cual no sería crear una nueva columna en estricto rigor 🤔

Un KNN tan bajo puede deberse a múltiples razones, desde que no ocupan hiperparámetros adecuados hasta que no le estan dando suficientes datos para entrenar, pero, según lo que estoy viendo con mi intento rápido, puede deberse a que tienen maal los datos
