### ISSUE TITLE
Problema con el Decision Tree

### ISSUE THREAD

**Issue by PabloLaporte** [Exploratorio-DCC-PUC/Syllabus#461]
Hola, cuando usamos knn funciono todo bien pero cuando puse el codigo del decision tree salto el error: ValueError: Expected 2D array, got 1D array instead:
que puede estar mal?

**Comment by felipegarcia98** [comment]
mmmmmmmmmm, pueden suceder muchas cosas, estas seguro que estas usando bien el X y el Y?

**Comment by PabloLaporte** [comment]
No, quizas es eso, pero el knn si nos funciono por lo que creo que si pusimos bienel X y el y, otro problema es que en la ayudantia no sale como guarda los valores del accuracy y lo hemos intentado de varias formas y no nos funciono (como guardarlo todo, el k y el accuracy de cada k, en una variable llamada acc)
