### ISSUE TITLE
TG2 Parte 2

### ISSUE THREAD

**Issue by Ikilly0** [Exploratorio-DCC-PUC/Syllabus#462]
Hola, queria ver si me podian guiar un poco, estamos en la parte de reduccion de dimensionalidad, antes de empezar me gustaria saber como deberian verse nuestros datos (ya normalizados? por ejemplo). Ademas de eso, supongo que hay datos que querian que sacaramos, y que al mismo tiempo dejaramos las labels. Que seria de estas labels en el proceso de reduccion? Gracias y disculpen si pregunte algo que no debia.

**Comment by felipegarcia98** [comment]
Bueno, depende de todo un poco sjsjsj depende de cómo normalizas, de qué columnas tomas en cuenta, de cómo creas los labels, de si haces cosas extra, etc, aunque creo que en gral. se verá como una mancha agrupada (un cluster). Lo importante son las decisiones que tomes y el análisis que hagas

Por ejemplo, hace un rato hice unos ejemplos de PCA (por eso me demore un rato 🙈) y me quedaron así:

Cuando normalice y no quite columnas (excepto cal) me quedo así:
![image](https://user-images.githubusercontent.com/42228743/98762618-d638d180-23b6-11eb-9986-7e25322eb584.png)

Luego quite un par de columnas que encontré que no me interesaban y me quedó asi
![image](https://user-images.githubusercontent.com/42228743/98762673-f36da000-23b6-11eb-8742-dd7ca40fa8fb.png)
![image](https://user-images.githubusercontent.com/42228743/98763338-94108f80-23b8-11eb-91a9-2982a4fa1518.png)

y luego en 3D lo visualice así para la vista de planta
![image](https://user-images.githubusercontent.com/42228743/98762855-5f500880-23b7-11eb-9333-348f940fce1a.png)
y así para la vista de perfil
![image](https://user-images.githubusercontent.com/42228743/98762894-74c53280-23b7-11eb-8cd3-822ea6f40c25.png)


PD: Si alguien quiere darle con esmero, se puede [hacer que los puntos tengan hover](https://stackoverflow.com/questions/7908636/possible-to-make-labels-appear-when-hovering-over-a-point-in-matplotlib) y desplieguen una especie de anotación donde señalen datos del punto, como su label o el id, lo que les puede permitir entender mejor que hace que algunos datos esten mas arriba o abajo, etc.

**Comment by Ikilly0** [comment]
pregunto, que significan el eje x , y, z de los graficos exactamente?

**Comment by felipegarcia98** [comment]
en estricto rigor, significan pca1, pca2 y pca3. Ahora, eso es distinto a que no se pueda intuir que alguna característica importa más dentro de un eje pca, que es, más o menos, lo que se les pregunta
