### ISSUE TITLE
Sobre sacar los outputs

### ISSUE THREAD

**Issue by PabloLaporte** [Exploratorio-DCC-PUC/Syllabus#464]
Hola, en la ayudantia dijeron que antes de bajar el ipynb debiamos sacar los outputs o eliminarlos, no entendimos eso. Que es lo que debemos hacer?, eliminar todos los comandos que generen outputs ej: (df) o solo apretar x en los outputs?

**Comment by felipegarcia98** [comment]
Solo apretar x en los outputs. Básicamente queremos que su notebook sea solamente código y texto markdown, nada de outputs, gráficas o cosas especiales que les salgan. La idea es que si quisieramos /necesitaramos revisar  lo que les devuelve, nos baste con solo ejecutar las celdas

**Comment by En-clases** [comment]
Hola, también tengo una pregunta relacionada con los outputs. Cada vez que ejecuto el código para hacer el gráfico de reducción de dimensionalidad, por ejemplo, el gráfico resultante es distinto al que se tenía antes (también me pasa con las métricas de los algoritmos en la parte 3).  Es por esto que cuando se responden las preguntas, estas están hechas en base al gráfico que yo ejecuté pero quizás cuando ustedes lo ejecuten se vea un poco distinto. Esto es un problma?

**Comment by felipegarcia98** [comment]
No tanto. Cuánto varía? 
Cuando dices que ejecutas el gráfico de reducción de dimensionalidad, qué consideras? solo una celda plot, todo el pca u otra cosa más grande?

**Comment by En-clases** [comment]
No sé muy bien a qué te refieres con plot y pca 😭 . Para hacerlo considero todos los datos que dejé en mi dataset.

**Comment by felipegarcia98** [comment]
jjssj yap. 

Lo primero, la reduccion de dimensionalidad se pretende que sea sobre los datos que vayan a la parte 3, por lo que si usas todos las features, también debes justificarlo (justificar el que no hayas eliminado columnas)

Lo segundo, el pca es el Principal Component Analysis (PCA) que es una de las maneras de hacer reducción de dimensionalidad (otra que mencionamos es t-SNE). Cuando me refiero a "todo el pca" quiero decir la celda que contiene el código de la rutina que reduce la dimensionalidad

Lo tercero, con plot me refiero a graficar. Cuando me refiero a "celda plot" quiero decir a la celda que contiene el código de la rutina que crea las gráficas

Básicamente estaba preguntando a qué te refieres con "el código", si te refieres al notebook completo, una celda que involucra solo los gráficos o si todo el proceso de reducción de dimensionalidad. Igualmente, [hay parámetros que puedes setear para que sea determinista el proceso](https://stackoverflow.com/questions/48108469/sklearn-pca-transform-gives-different-results-for-different-trials)
