### ISSUE TITLE
Problema con importar el dataset

### ISSUE THREAD

**Issue by En-clases** [Exploratorio-DCC-PUC/Syllabus#465]
Hola, para importar el archivo data.csv a google colab utilicé el mismo método que se ocupó en la TG1 (copiando el link del archivo). Sin embargo, luego vi que en el formato de entrega de la tarea no se debe subir el archivo data.csv por lo que lo eliminé de la carpeta del repositorio. Ahora importar el archivo con el método descrito no me funciona ya que al parecer el link es incorrecto (error: ```HTTPError: HTTP Error 404: Not Found```). Como puedo arreglar esto?

**Comment by felipegarcia98** [comment]
Mira, no tengo idea xD pero en los siguientes links encontré referencias interesantes que podrían servirte para solucionar el tema
* Un error [404 - Not Found](https://github.com/Kaggle/kaggle-api/issues/110)
* Uno que hace [referencia a uno similar con API](https://stackoverflow.com/questions/57851953/how-to-fix-an-error-during-uploading-custom-dataset-in-to-colab)

Nos mantienes informado

**Comment by En-clases** [comment]
Ok. Pero con lo de eliminar el archivo ```data.csv``` esta bien? Lo pregunto porque al momento de crear el repositorio este archivo venía incluido. Es por eso que quizás no haya que eliminarlo a pesar de que en las indicaciones se dice que no hay que subir tal archivo.

**Comment by felipegarcia98** [comment]
Yap, el tema del archivo csv es que si tu lo subes y todos los demas lo hacen, los ayudantes tendremos +100 veces el mismo archivo y nuestra velocidad de descarga va a morir. Entonces, considerando que es innecesario para nosotros (ya tenemos el archivo) y que uds pueden evitarlo, se los solicitamos "amablemente" :33 <3 

*Para las correcciones, muchas veces se descargan los zips de todos los repositorios

**Comment by En-clases** [comment]
Ok! Muchas gracias.
