### ISSUE TITLE
Parte 4 TG2

### ISSUE THREAD

**Issue by PabloLaporte** [Exploratorio-DCC-PUC/Syllabus#466]
Hola, estamos respondiendo la parte 4 y esta pregunta no la entendemos, nos la pueden explicar mejor?
### Para el clasificador, explica la diferencia entre las métricas del set de pruebas para cada clase, ¿Qué nos dice de la calidad del clasificador por cada clase?. Justifica.
a que se refiere con diferencias entre metricas? a que se refiere con calidad por clase? que es calidad,? el acc, precision, recall, f1-score o support? y en el por clase se refiere por label o por columna?

**Comment by felipegarcia98** [comment]
hola o/, 

yes, eso mismo. 
métricas del set de pruebas = acc, precision, recall, f1-score Y support (ideal que cubras la mayoría) cuando predices sobre el set de prueba
clase = label 
calidad del clasificador por cada clase = que tan bueno es el clasificador cuando se trata de las diferentes clases

Un ejemplo de ello es el que pueden ver en ...(no recuerdo si en clase, ayudantía o librería sklearn) ... donde los clasificadores suelen ser buenos clasificando al cluster que está alejado, pero no muy buen clasificador de los 2 que están más o menos juntos.

Entonces, en resumen, les pedimos que nos digan que tan bueno o malo es el clasificador clasificando, sobre el dataset de prueba, para cada una de las clases. Ojalá que cubran la mayoría de las métricas que les salen (básicamente, no se queden solo con el accuracy)

**Comment by PabloLaporte** [comment]
Muchas gracias, y una duda del bonus, que no puedo encontrar lo que es un regresor

**Comment by felipegarcia98** [comment]
Con regresor nos referimos a un algoritmo que ejecute regresiones. En la documentación de Sklearn puedes encontrar info para complementar tmbn :3

**Comment by tomasnusser** [comment]
Una pregunta sobre esta misma parte. En hacer la diferencia entre todas ellas igual ocupé hartas lineas y luego tengo que especificar la calidad para cada clasificador...es un poco difícil hacer todo eso en 4 líneas. Se aceptan más o hay que mantenerse deentro de esas 4? Muchas gracias

**Comment by felipegarcia98** [comment]
jsajkaj yap. Es un mas o menos, es una restricción para que no nos hagan leer una enciclopedia y para que uds puedan expresarse en pocas palabras. Igual recuerda que no tiene que ser taaaaaaan exhaustivo en esa parte
