### ISSUE TITLE
Parte 2 TG2

### ISSUE THREAD

**Issue by antonia-matamala** [Exploratorio-DCC-PUC/Syllabus#467]
La verdad es que estamos muy perdidas con la parte 2 de la tarea, no sabemos como empezar. Nos pueden guiar un poco mas por favor?

**Comment by felipegarcia98** [comment]
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

una vez realizada la parte 1, los pasos serían algo así:
1. Llamar una instancia de reducción de dimensionalidad
2. Fitear y transformar
3. Plottear

En un buen par de ejemplos en sklearn, en las partes sobre PCA o t-SNE
