### ISSUE TITLE
[TG2] Formato de entrega

### ISSUE THREAD

**Issue by imant1** [Exploratorio-DCC-PUC/Syllabus#468]
Hola! En la sección formato de entrega dice que "Es sumamente importante que elimines el output de tu Jupyter notebook.", ¿cómo puedo hacer esto? No encuentro una opción para borrar todos los outputs en el _collab_.

También dice que no debemos subir el dataset a nuestro repositorio, pero el repositorio se creó con el dataset en él, ¿debemos eliminarlo del repositorio?

Gracias y saludos! :)

**Comment by felipegarcia98** [comment]
En colab, puedes seleccionar 'borrar resultados' en las opciones de cada celda o clicar 'Borrar resultados' en la pestaña 'editar' del notebook

Sobre lo del dataset, es probable. Estamos discutiéndolo, pero considera que si pediremos que lo borren

**Comment by camilamoya** [comment]
El README.md también hay que borrarlo?

**Comment by felipegarcia98** [comment]
El readme pueden dejarlo, pero probablemente no lo veremos

**Comment by felipegarcia98** [comment]
Confirmo que les pediremos que borren el csv del repo

**Comment by imant1** [comment]
@felipegarcia98 en nuestro collab cargamos el dataset con el url de dataset de nuestro repositorio personal. Si lo borramos no tenemos como acceder al dataset, puesto que en la carpeta TG2 del syllabus no se encuentra el _csv_ del dataset.

**Comment by Ikilly0** [comment]
Tengo el mismo problema, de donde deberiamos cargarlo entonces? si no es del repositorio?

**Comment by scagender** [comment]
x3

**Comment by felipegarcia98** [comment]
tranquilein mi gente, disculpen la tardanza. 
`
print('Subimos el csv al syllabus del curso')
`
`
print('fino') if pueden_cambiar_el_enlace else  print('p***, tranqui')
`
