### ISSUE TITLE
Duda acerca medidas de rendimiento parte 3

### ISSUE THREAD

**Issue by JoseTRebolledo** [Exploratorio-DCC-PUC/Syllabus#469]
En la parte 3, al calcular accuracy, precision, recall y f-1 score, cuando en el enunciado dice:  Se debe reportar las métricas para
cada clase en el set de pruebas ¿se refiere a que si mis clases son alto, bajo etc, se deben calcular las medidas por separando de cada una de ellas?

**Comment by felipegarcia98** [comment]
yes. En todo caso, hay una función que hace por defecto eso y creo que se muestra en la ayudantía
