### ISSUE TITLE
Jupyter no corre 

### ISSUE THREAD

**Issue by estefaniiaaa** [Exploratorio-DCC-PUC/Syllabus#47]
He intentado abrir el archivo que contiene los links de los artistas pero solo me aparece '*', como que corre el programa pero no lo termina nunca, que puedo hacer?

**Comment by malopez16** [comment]
Hola! En qué momento te aparece? Sólo al importar algo o al hacer lo que sea?

**Comment by estefaniiaaa** [comment]
Hola, ya lo solucioné,  era al correr cualquier cosa, interrumpí Kernel y luego de eso corrió bien. 
Gracias igual !
