### ISSUE TITLE
ayuda con el grafico de la parte de reduccion de la dimensionalidad

### ISSUE THREAD

**Issue by Kevinnevik** [Exploratorio-DCC-PUC/Syllabus#470]
Hola, tengo un problema corrí mis grafico por primera vez y aparecía un grafico en la parte 2, después volví a correr el código sin cambiar nada y el gráfico no volvió a aparecer. Realmente no se que paso.

**Comment by felipegarcia98** [comment]
hola o/

mmmmm, puede  ser que en esa celda tengas alguna función que modifique tu dataset o el valor que le entregas a las funciones

vale decir, si tuvieras una función drop que se cayera cuando no encuentra el valor, la primera vez que lo hagas te funcionara bien sobrescribiendo el dataset, pero para la segunda se te caería
