### ISSUE TITLE
Consulta respecto a recorrecciones TG1

### ISSUE THREAD

**Issue by iavasquez1** [Exploratorio-DCC-PUC/Syllabus#471]
Estimados ayudantes, tengo una consulta respecto a las recorrecciones de la TG1. Quería saber cuando se van a subir estas notas debido a que se subieron las notas de la TC2 y aún la nota no se ha modificado a pesar de haber solicitado la recorrección de la TG1. 
De antemano muchas gracias!
PD: Si desean saber en qué fecha envié la solicitud le envío una copia por mail de la solicitud de recorrección realizada.

**Comment by mimadri** [comment]
Hola! 

En uno de los últimos anuncios avisamos que se daría plazo para contestar las recorrecciones de la TG1 hasta este viernes.
Por lo que aún queda tiempo (considerar que las recorrecciones no estarán listas ese mismo día).

Saludos 👍
