### ISSUE TITLE
Repositorio personal TC 3

### ISSUE THREAD

**Issue by En-clases** [Exploratorio-DCC-PUC/Syllabus#472]
Hola, normalmente envían un link en el enunciado de la tarea para crear nuestro repositorio personal. Sin embargo, no encuentro ese link.

**Comment by Pyralspite** [comment]
Hola! 
Lo mandamos en un anuncio cuando publicamos la tarea.
[Este es el link](https://classroom.github.com/a/wwS8hvMe)

**Comment by En-clases** [comment]
No me había dado cuenta 😥 . Gracias!
