### ISSUE TITLE
Nivel de detalle parte 1 informe

### ISSUE THREAD

**Issue by denisseleiva** [Exploratorio-DCC-PUC/Syllabus#473]
Hola! Para la parte 1 del informe, ¿Qué tan detallada es la explicación del funcionamiento?,  por ejemplo, si estoy realizando restas , ¿Debo explicar qué hace la máquina al enfrentarse a cada caso? O basta con explicar que el funcionamiento es con restas. Pregunto porque en la parte 3 siento que estaría repitiendo lo mismo 🤔

Graciass!

**Comment by Pyralspite** [comment]
Hola!

Sí, en la parte 1 debes explicar como tu máquina realiza la resta en cada caso. No es necesario que menciones los estados involucrados a menos que creas que apoyan tu explicación.
En la parte 3 puedes agrupar estados que realizan la misma tarea. Por lo tanto sería válido que pusieras algo como:

Estados: resta_1_0, resta_1_1, ....
Se pasa a estos estados después de _alguna condicion en comun_
Puede pasar a los estados `estados` si _condición_ o a los estados `otros estados` si ocurre _otra condicion_.
Durante estos estados la máquina escribe el resultado de la resta.

Avisame si sigues con dudas c:

**Comment by denisseleiva** [comment]
bacaan
otra pregunta, no importa que los estados sean como qconstante_determinada o q_restanegativa? O tienen que ser como más formales como con números jajajaja 😅

**Comment by mimadri** [comment]
Hola!
No es necesario que los nombres de los estados tengan números, de hecho se recomienda mucho que estos tengan nombres descriptivos, para que sea mas fácil leer el código.
Ánimo y suerte con la tarea :)

**Comment by denisseleiva** [comment]
Genial, graciass!
