### ISSUE TITLE
Formato de entrega parte 1 de tarea chica 3 

### ISSUE THREAD

**Issue by ferperezh** [Exploratorio-DCC-PUC/Syllabus#474]
Tengo una pregunta de cómo entregar la parte 1 de la tarea chica 3. Ya que use la pagina de Turning Machine, pero no se como obtener el archivo txt. para la entrega.

**Comment by mimadri** [comment]
Hola!
El simulador no ofrece la opción de descargar un archivo .txt directamente. 
Lo que puedes hacer es copiar todo el código que contiene tu tarea, crear manualmente un archivo .txt, y pegarlo en él.
Suerte con la tarea!
