### ISSUE TITLE
Desarrollo informe

### ISSUE THREAD

**Issue by VichoAburto** [Exploratorio-DCC-PUC/Syllabus#476]
Hola, tengo dos pregunta,

1. El informe es un texto completo en el que se incluye la explicación a los 3 puntos/preguntas? O es literal?:
                   1) Rpta preg 1
                   2) Rpta preg 2
                   3) Rpta preg 3

2. Como en la tercera parte me piden explicar cada uno de los estados y cómo se pasan a ellos, esto quiere decir que la primera parte es como una explicación bien general (aunque igual completa) del proceso que hace la máquina, cierto? Es decir que, no menciono los estados en 1ra parte?

Gracias

**Comment by Pyralspite** [comment]
Hola!

1. La idea es que el informe cuente con tres secciones, donde cada una sea la respuesta a la pregunta correspondiente.
2. Exacto. Puedes mencionar algunos estados si crees que apoyan tu explicación, pero no es necesario.

**Comment by VichoAburto** [comment]
Buenísima, muchas gracias :)
