### ISSUE TITLE
Consulta respecto a subida de archivos a repo personal TC3

### ISSUE THREAD

**Issue by iavasquez1** [Exploratorio-DCC-PUC/Syllabus#477]
Hola!, quisiera saber si los archivos que se deben subir al repo que se bajan en el .zip deben ser subidos sin comprimir junto con el código y el .pdf generado o estos deben estar en el .zip tal cual como se baja desde overleaf.
Saludos y muchas gracias por sus respuestas!

**Comment by mimadri** [comment]
Hola! 
Todo lo que debes entregar en el repo es:

- El archivo .txt que contiene el código de tu máquina.
- El informe en formato PDF.
- El archivo .tex que compila tu informe en Latex.

En caso de haber ocupado archivos extra en la elaboración del informe, es necesario que estos se incluyan también (no es necesario que se compriman en un zip). Espero haber aclarado tu duda :) 

Saludos

**Comment by josefinadunner** [comment]
Hola! Respecto a lo mismo, debemos borrar el resto de archivos que estaban originalmente en el repositorio y dejar solo los 3 que se pide?
Desde ya muchas gracias.

**Comment by Pyralspite** [comment]
Hola, no es necesario borrar el readme ni la imagen. Si dejas el archivo main.tex asegurate de que el otro se llame informe.tex, para que sea fácil identificar cual debemos revisar.

**Comment by josefinadunner** [comment]
perfecto, muchas gracias!
