### ISSUE TITLE
Ponderación notas.

### ISSUE THREAD

**Issue by robertoorrego** [Exploratorio-DCC-PUC/Syllabus#478]
Hola, tengo un par de dudas que creo que son muy relevantes al curso.

Primero, agradeceria que confirmen los porcentajes de ponderación de cada nota. (Cuanto valen la TG y las TC)

Segundo, me gustaría saber como van a calcular las notas para evaluar la eximicion. Se considera como un rojo la nota que se borra? Es decir, tengo puras notas azules y solo un rojo que se va a borrar, necesito promediar promediar sobre 5.5 o 6.0??

**Comment by Pyralspite** [comment]
Hola!

La ponderación es 

NT = ( TG1 + TG2 + ((TC1+TC2)/2) + ((TC3+TC4)/2) )/4
NC = (C1 + C2)/2

En el caso de borrar una tarea chica, la que la "acompaña" pasa a valer lo mismo que una tarea grande.
En el caso de borrar un control, NC pasa a tomar el valor del otro.

La nota de presentación NP = 0.3 * NC + 0.7 * NT
Los criterios de eximición se consideran **después** de borrar la peor nota, por lo que si se elimina tu único rojo, necesitas un 5.5 para eximirte.
