### ISSUE TITLE
"Aprendizaje coorporativo"

### ISSUE THREAD

**Issue by nicolaspoli** [Exploratorio-DCC-PUC/Syllabus#479]
Hola!
En la tc4, cuando el cliente rechaza la propuesta se dice que se debe enviar un correo, pero por el texto no me queda claro si es el cliente quien manda un correo "general" como a toda la empresa o es le ejecutivo quien debe enviarlo de forma interna en la empresa. Pareciera ser el ejecutivo, pero prefiero asegurar.

Dejo la parte del texto a la que me refiero:
Cuando la empresa cliente adjudica la licitación a uno de los proponentes, el ejecutivo debe procesar el resultado. En caso que la propuesta no haya sido adjudicada, debe enviar un correo a todos los involucrados en MuySegurosCorp, describiendo las razones por las que no se ganó; esto contribuye al aprendizaje corporativo.

Gracias de antemano :D

**Comment by mimadri** [comment]
Hola!

Efectivamente la parte mencionada puede resultar ambigua, pero es el ejecutivo quien debe enviar el correo a los trabajadores, ya que esto se realiza después de procesar el resultado.
Espero haberte ayudado y ánimo con la tarea!

Saludos 👍

**Comment by nicolaspoli** [comment]
ok! muchas gracias! :D
