### ISSUE TITLE
TC4 Duda de Instrucciones

### ISSUE THREAD

**Issue by PabloLaporte** [Exploratorio-DCC-PUC/Syllabus#480]
Tengo una duda con esta instrucción:
"La descripción puede ser incompleta en algunos aspectos. Puede hacer todos los supuestos que estime conveniente, siempre y cuando los explique apropiadamente."
Donde y como puedo explicar los supuestos ? o no es necesario?

**Comment by mimadri** [comment]
Hola
Cualquier supuesto que desees incluir, que aporte a que se entienda mejor tu solución, debe ser incluido en el mismo pdf que contiene tu diagrama. Esto es de carácter opcional.
Saludos :)
