### ISSUE TITLE
Escribir en diagrama

### ISSUE THREAD

**Issue by martin-iturralde** [Exploratorio-DCC-PUC/Syllabus#481]
Hola! Cuando hago el diagrama por ejemplo, si es que se envia un mensaje o se recibe, tengo que escribir un texto bajo el mensaje? O, no es necesario?
Y, se debe poner el tiempo? Ejemplo: persona se demora X tiempo. Debo poner la imagen del tiempo? Y escribir un texto sobre eso?
Gracias de antemano!

**Comment by mimadri** [comment]
Hola!
Para los mensajes, se recomienda agregarles abajo un texto descriptivo, pero ojalá muy cortito (no más de tres palabras). También es recomendable que se especifique de cuánto tiempo se está hablando. Todo esto es para facilitar la lectura del diagrama.
Suerte con la tarea :)
