### ISSUE TITLE
Especificación Lanes

### ISSUE THREAD

**Issue by dani-sschlack** [Exploratorio-DCC-PUC/Syllabus#482]
Podemos juntar dos lanes en un mismo grupo, por ejemplo si tengo a Panadero A y Panadero B, los puedo juntar en un mismo lane de nombre Panaderos???

**Comment by mimadri** [comment]
Hola!
Si los lanes de los que hablas comparten la actividad que deben realizar, no hay problema en que se junten en uno solo. Se debe considerar que en algunos casos la actividad a realizar es muy similar, pero no es la misma, ya que puede depender del cargo que tenga alguno de los sujetos en cuestión, entonces en este caso debería haber un lane para cada cargo.
Espero haberte ayudado :)

**Comment by dani-sschlack** [comment]
Hola, aun me queda la duda, voy a tratar de ser más especifica xd:
si tengo a dos personas pertenecientes a un mismo departamento, en el lane puedo solo poner al  departamento al que pertenecen???

**Comment by mimadri** [comment]
Hola!
Más que fijarte en que si dos personas pertenecen o no a un mismo departamento, te recomiendo guiarte por los cargos de cada uno, si difieren entonces deben ir en lanes separados.
Saludos :)
