### ISSUE TITLE
TC4 Adjudicación de licitación

### ISSUE THREAD

**Issue by josefinadunner** [Exploratorio-DCC-PUC/Syllabus#483]
Hola!
En el enunciado cuando dice: "El ejecutivo debe hacer seguimiento a la propuesta enviada. Cuando la empresa cliente adjudica la licitación a uno de los proponentes, el ejecutivo debe procesar el resultado". No me queda claro cómo el ejecutivo se entera del resultado de la licitación. Se podría asumir que el ejecutivo hace el seguimiento, y luego el cliente envía un mensaje con el resultado de la licitación y luego a partir de eso el ejecutivo procesa estos resultados?

No sé si se entiende mi duda:(
Desde ya muchas gracias.

**Comment by mimadri** [comment]
Hola!
Efectivamente, puedes asumir que una vez que el ejecutivo empieza el seguimiento le llegará un mensaje por parte del cliente en el cual le avisarán cuál es el resultado.
Ánimo con el fin de semestre :)

**Comment by josefinadunner** [comment]
Muchas gracias!
