### ISSUE TITLE
Compuertas Bizagi

### ISSUE THREAD

**Issue by mati-gonz** [Exploratorio-DCC-PUC/Syllabus#484]
Hola! Estoy ocupando Bizagi para realizar el Modelo, el tema es que en Bizagi las compuerta exclusivas no llevan una X en medio, son las que están en blanco. Qué puedo hacer al respecto?

**Comment by mimadri** [comment]
Hola!
No hay problema con eso, ya que en el póster que se les entregó también se considera que las compuertas exclusivas se pueden representar como un rombo en blanco. 
Suerte con la tarea :)

**Comment by mati-gonz** [comment]
Gracias. Ahora tengo otro problema, terminé pero al momento de exportar el diagrama se ve super pixeleado cuando le hago zoom entonces no se ve nada  :( cómo lo hago para que se exporte bien el pdf?

**Comment by mati-gonz** [comment]
Creo que al exportarlo como imagen conserva más los pixeles, pero al momento de exportarlo las puntas de las flechas desordenan y apuntan a cualquier lado. Es mucho problema esto? considerando que se nota claramente hacia donde va la flecha?

**Comment by mati-gonz** [comment]
No, no se logra arreglar exportandolo como imagen se sigue viendo muy pixeleado :( qué hago?

**Comment by mati-gonz** [comment]
Logré exportarlo y conservar la resolución, tuve que exportarlo como una imagen con formato .svg y luego pasar esto a pdf con un conversor online. Eso si, sigo teniendo las dudas con lo de las flechas :(

**Comment by amaiajuanchuto** [comment]
Holaa!! 

Que bueno que pudiste solucionar el tema de la exportación. 😄 

Respecto a lo de las flechas, si es que dices que se nota claramente hacia donde van no creo que sea un problema. Ahora si hay alguna parte donde no se entienda bien su flujo por el tema de las flechas, quizás es bueno que lo escribas abajo de tu solución para que podamos entender mejor tu modelo.

Mucha suerte con la tarea! 💯
