### ISSUE TITLE
Entrega TC4, formato

### ISSUE THREAD

**Issue by kvonstorch** [Exploratorio-DCC-PUC/Syllabus#485]
Hola!
Tengo tres consultas respecto a la entrega de la tarea:

1. ¿El PDF debe tener algún nombre especial?
2. ¿Debemos eliminar los demás archivos del repositorio?
3. ¿Basta con entregar la modelación de procesos? (no son necesarias explicaciones y cosas por el  estilo)

Agradezco de antemano.

**Comment by amaiajuanchuto** [comment]
Holaa!

1. No se especifica el nombre del PDF, por lo que puedes ponerle el nombre que tu quieras.
2. No es necesario que elimines los otros archivos.
3. Cualquier supuesto o comentario que creas necesario para que entendamos mejor tu modelo tiene que estar incluida en tu solución, sin embargo no es obligatorio que expliques con palabras tu modelación. 

Mucha suerte! 💯
