### ISSUE TITLE
Hora de entrtega

### ISSUE THREAD

**Issue by camilamoya** [Exploratorio-DCC-PUC/Syllabus#486]
Hola, en el enunciado de la tarea dice que la fecha de entrega es hoy hasta las 11:59 am y quería confirmar que eso está correcto, debido a que todas las otras tareas han sido hasta las 11:59 pm. ¿Es un error o definitivamente es hasta el medio día?

**Comment by mimadri** [comment]
Hola, 
Efectivamente, esta tarea debe ser entregada al mediodía.
Saludos
