### ISSUE TITLE
Consultas Examen

### ISSUE THREAD

**Issue by denisparra** [Exploratorio-DCC-PUC/Syllabus#487]
Escriban por acá las consultas que les vayan saliendo durante el examen del curso, que recuerden, deben entregar antes de las 13:30 hrs en canvas.

**Comment by camilamoya** [comment]
Hay que escribir los códigos directamente en el word?

**Comment by AntonioDoberti** [comment]
Hola, tengo un problema. Al tratar de abrir los enlaces del enunciado y de plantilla me da error 502.

**Comment by pablogw** [comment]
Hola me pasa lo mismo que @AntonioDoberti, no me funciona gmail tampoco asumo que es un error con google. Nose si podrían subir el enunciado y planilla a GitHub 😄

**Comment by m-cinquegrani** [comment]
Hola, al parecer si es un error con Google, he tratado de abrir varias veces y nada, no carga el correo de Gmail ni nada 😔

**Comment by Mgagol** [comment]
Hola, tengo en mismo error no e podido descargar el enunciado, al parecer esta caído el servidor de Google

**Comment by pablogw** [comment]
Hola! Ahi se arreglo parece!

**Comment by denisparra** [comment]
Hola todos voy respondiendo de a uno

**Comment by denisparra** [comment]
> Hay que escribir los códigos directamente en el word?

Sí, codigo directamente ahí

**Comment by denisparra** [comment]
> Hola, tengo un problema. Al tratar de abrir los enlaces del enunciado y de plantilla me da error 502.

debería funcionar ahora, al parecer se cayeron servicios de google por un rato, voy a subir un link alternativo en el mismo canvas por si acaso

**Comment by denisparra** [comment]
> Hola, tengo un problema. Al tratar de abrir los enlaces del enunciado y de plantilla me da error 502.

problema de servicio de Google, ya resuelto

**Comment by denisparra** [comment]
**Archivos de enunciado y plantilla**
Link nuevo a examen por si sigue caido o se vuelve a caer el de Google Drive

https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Examen_IIC_1005_2020_2.pdf

y la plantilla para responder:

https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/plantilla_examen.docx

**Les amplié la hora de entrega hasta las 14:00 horas.**

**Comment by denisparra** [comment]
> Hola me pasa lo mismo que @AntonioDoberti, no me funciona gmail tampoco asumo que es un error con google. Nose si podrían subir el enunciado y planilla a GitHub 😄

esto hicimos !
