### ISSUE TITLE
Invitaciones desactivadas para la Tarea 1

### ISSUE THREAD

**Issue by aenrione** [Exploratorio-DCC-PUC/Syllabus#488]
![imagen](https://user-images.githubusercontent.com/60358967/111985587-8ba92d80-8aeb-11eb-921e-a053fc7b3183.png)
Hola, al parecer las invitaciones para el assignment de la Tarea Chica 1, están desactivadas, por lo que no deja crear el repositorio personal.

**Comment by pacalein** [comment]
Hola Alfredo, por favor revisa nuevamente ya que he hecho un cambio en la activación del link. Quedo atenta.
