### ISSUE TITLE
Problema Paso 3 Tarea Chica 1

### ISSUE THREAD

**Issue by nicoguz** [Exploratorio-DCC-PUC/Syllabus#489]
Holaa!!
Seguí las instrucciones de la tarea chica 1 al pie de la letra y todo estaba saliendo perfecto hasta el paso 3. Estoy a 1 archivo de la respuesta correcta (la encontré accidentalmente en una carpeta 😅) y no logro entender por qué. He intentado muchas aproximaciones y ninguna ha funcionado. Si alguien me pudiera ayudar se lo agradecería muchísimo!!

**Comment by pacalein** [comment]
Hola Nicolas, estamos revisando el error. ¡Te avisamos!
🚀

**Comment by hebusch** [comment]
Me sumo a la duda, estoy un archivo más del archivo final, será qué es por el archivo 'progreso.txt'?

**Comment by EEchenique** [comment]
A mi me paso que estoy a un archivo menos de la respuesta y si cree el archivo "progreso.txt"

**Comment by pacalein** [comment]
Actualizamos los archivos de python para la tarea, según la versión que tengan instalada. Los pueden encontrar aquí https://drive.google.com/drive/folders/137az9Ocx6y7nXOhNHXe7ke4o-S9oGQZH
🚀
