### ISSUE TITLE
Uso de cmd en Tarea Chica 1

### ISSUE THREAD

**Issue by franc1899** [Exploratorio-DCC-PUC/Syllabus#490]
Hola,

Quería saber si es necesario usar Git Bash en Windows o si acaso simplemente puedo usar la cmd para ejecutar los comandos necesarios para realizar cada paso. Esto ya que a veces los comandos en cmd son distintos que en Git Bash pero de todas formas cada comando tiene su equivalencia para su uso en cmd.

Saludos!

**Comment by pacalein** [comment]
Hola Francisco, como recomendación preferimos que usen Git Bash ya que buscamos que se familiaricen con los comandos tipo UNIX. De todas formas no es obligatorio mientras puedan realizar la tarea en su totalidad. Lo importante es que nos vayas comentando en el informe cuáles son los comandos que utilizaste en cada paso y qué es lo que hacen.

Cualquier duda me respondes en este thread. 
¡Saludos! 🚀
