### ISSUE TITLE
Carpeta Padre

### ISSUE THREAD

**Issue by hebusch** [Exploratorio-DCC-PUC/Syllabus#491]
Hola buenas, al mencionar la carpeta padre se están refiriendo a la carpeta **tc1-2021-1-xxxx** o a **TareaChica1**?
Saludos. :smile:

**Comment by pacalein** [comment]
Hola Heinz, la carpeta padre para este ejercicio sería "TareaChica1".
¡Saludos! 🚀

**Comment by hebusch** [comment]
Muchas gracias! :smile:
