### ISSUE TITLE
Ayuda para paso 3 de la tarea

### ISSUE THREAD

**Issue by nolate26** [Exploratorio-DCC-PUC/Syllabus#492]
Hola, estaba realizando lo primeros pasos de la tarea, descargué Git Bash (tengo windows), lo que me pasa es que trato de abrir el archivo TC1 y no se me abre, además no entiendo donde debo ejecutar el comando "alias python=’winpty python.exe’ ... python TC1.pyc digito"
De antemano muchas gracias, 
Nicolás

**Comment by pacalein** [comment]
prueba usando directamente el comando `python TC1.pyc <digito>`
🚀

**Comment by nolate26** [comment]
¡muchas gracias! ya lo logré todo
