### ISSUE TITLE
Carpetas desordenadas en github

### ISSUE THREAD

**Issue by m1guel-angel** [Exploratorio-DCC-PUC/Syllabus#494]
Hola, realicé la tarea y al momento de entrar a github para verificar si se habían subido correctamente los archivos me di cuenta de que algunas carpetas se desordenaron, pero en mi computador siguen igual, ¿tendré que hacer commit de nuevo? 
Gracias de antemano.

**Comment by pacalein** [comment]
Hola! A qué te refieres con desordenadas? Puedes ser un poco más especifico? :=)

**Comment by m1guel-angel** [comment]
Me refiero a que hay carpetas que se movieron de lugar, por ejemplo en la carpeta TareaChica1/Carpeta_0/SubCarpeta_4/ hay carpetas que ya no están, o en TareaChica1/Carpeta_0/ la SubCarpeta_1 solo contiene la SubSubCarpeta_3.

**Comment by pacalein** [comment]
Oka entiendo. No se por qué pasaría eso, pero tu repo debiera estar lo más integro posible. Las carpetas que ves en tu repo debieran ser las mismas que ves en tu PC local. Haz otro commit y ve que pasa. Recuerda agregar todos los archivos desde la carpeta padre con el comando `add .` antes de declarar el commit.

Si sigues teniendo problemas podemos conversarlo en la ayudantía del miércoles.
🚀

**Comment by m1guel-angel** [comment]
ok muchas gracias :)

**Comment by m1guel-angel** [comment]
creo que lo que pasa es que no se copian las carpetas que están vacías

**Comment by anibalriveros** [comment]
Alfinal en que quedo esto, porque me paso lo mismo. No se me subieron las carpetas vacias.

**Comment by pacalein** [comment]
¡Hola! Si git no les añade los directorios vacíos, pueden probar agregando un .gitkeep en esos directorios.

Para agregar un archivo vacío `.gitkeep` en cada carpeta vacía, podemos automatizar el proceso de la siguiente forma usando find:

`find $PATH_TO_REPOSITORY -type d ! -path "*.git*" -empty -exec touch '{}'/.gitkeep \;`

En este caso deben reemplazar $PATH_TO_REPOSITORY por el path de su repo en el compu local. Recuerden eso si actualizar el repositorio con `git add .` para que no se les escape nada antes del commit.
¡Me cuentan cómo les va!
🚀

**Comment by anibalriveros** [comment]
Ahi me resultó. Muchas gracias
