### ISSUE TITLE
¿Cómo indicar la posición utilizando un pipe?

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#495]
Hola!, me gustaría saber cómo indicar la posición a la cual quiero que la pipe ingrese como argumento a la siguiente función.

Ejemplo:
![image](https://user-images.githubusercontent.com/66154723/112240747-a54f8f80-8c27-11eb-8327-f4845d278404.png)
_Clarifico que es un ejemplo en particular sin relevancia, pero mi pregunta es en general_

**Comment by fernandosmither** [comment]
Encontré la respuesta en internet. [Fuente](https://stackoverflow.com/questions/22388480/how-to-pipe-the-results-of-find-to-mv-in-linux)
![image](https://user-images.githubusercontent.com/66154723/112243001-8eab3780-8c2b-11eb-8f9c-75cbbafa51d7.png)

Dejo la sintaxis en la imagen anterior por si a alguien más le sirve, y de paso aprovecho para preguntar si se aceptará esta sintaxis en la _**TC1**_
Saludos!

**Comment by pacalein** [comment]
Si todo bien.
🚀
