### ISSUE TITLE
Duda de ejemplo, Nicolás Gutiérrez

### ISSUE THREAD

**Issue by NicoJGutierrez** [Exploratorio-DCC-PUC/Syllabus#496]
Esta es una duda de ejemplo, para ver cómo funciona este sistema de dudas. Cuando vean esta duda por favor respondan "recibido", junto con cualquier dato importante sobre cómo debería preguntar mis dudas futuras.

Atentamente:
Nico.

**Comment by pacalein** [comment]
recibido.

Pregunta por aquí lo que necesites y nosotros ayudantes asignaremos la etiqueta correspondiente a la duda. Si la duda ya ha sido resuelta, agregaremos la etiqueta verde Resuelto.
🚀
