### ISSUE TITLE
Tarea1 3.2 problema "permission denied" 

### ISSUE THREAD

**Issue by emiliaup** [Exploratorio-DCC-PUC/Syllabus#497]
Hola! Cuando trato de ejecutar 

alias python=’winpty python.exe’
python TC1.pyc digito

en gitbash (tengo windows) me sale un error: Permission denied. 
Nose que hacer ayuda porfa :/

**Comment by fcontardo** [comment]
Holaa, me pasa lo mismo, pero el error que me tira es:

bash: alias: python.exe’: not found

**Comment by AlejandraBeas** [comment]
me pasa lo mismo

**Comment by emiliaup** [comment]
ya me funciono :)

lo hice en el cmd, en mi carpeta de repositorio, y puse:  py TC1.pyc digito 
@AlejandraBeas 
@fcontardo 
Ojala les funcione :)

**Comment by AlejandraBeas** [comment]
gracias te pasaste :'ooo, también me funcionó, creo sjsdj
