### ISSUE TITLE
mover varios archivos a la ves

### ISSUE THREAD

**Issue by antoniablanco** [Exploratorio-DCC-PUC/Syllabus#498]
Hola, utilizando un comando busque todos los archivos que necesito mover por lo que se que existen. Pero cuando utilizo el comando de mover me aparece el siguiente error: 
mv: illegal option -- t
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
y en otros casos me dice:  No such file or directory
Cual podría ser la razón de este error?

**Comment by pacalein** [comment]
¡Hola Antonia! el comando `mv <source> <target>` sólo actúa sobre los archivos que estén en el directorio inmediato y no entrará a los subdirectorios a buscar más archivos con el nombre que buscas. Si no encuentra el archivo entonces indicará 'No such file or directory'

Para resolver esta parte de la tarea, recomendamos usar el comando `find`, el cual se especializa en ejecutar acciones dentro de la jerarquía de archivos. No debiera haber errores al encontrar y mover los archivos de esta forma, y es más rápido que entrar a cada uno de los directorios y ejecutar manualmente el comando `mv`.

Me avisas como vas en este mismo thread.
🚀

**Comment by antoniablanco** [comment]
Con el comando find pude encontrar toda la lista de archivos que cumplen
con la descripcion indicada. Pero en internet solo encontre el comando mv
para lograr moverlos.
Muchas gracias

**Comment by pacalein** [comment]
Claro, es posible además incluir un comando a ejecutar luego de encontrar el archivo que le pides. Busca la sintaxis correcta, es super fácil encontrarlo en internet bajo "find command console" o similar. No lo coloco aquí sólo porque estaría dando la respuesta T^T.
🚀
