### ISSUE TITLE
Tarea 1, parte 3.2 me sale "not found"

### ISSUE THREAD

**Issue by AlejandraBeas** [Exploratorio-DCC-PUC/Syllabus#499]
Para generar la carpeta de trabajo puse: alias python= "winpty python exe" en el bit bash, estando en la carpeta de la tarea y me salió "command not found". Luego puse python: TC1-37.pyc 7 , y me salió "not found". Tengo instalada la versión 3.7 del python y no entiendo por qué no me funciona. Necesito ayuda :(

**Comment by emiliaup** [comment]
para la tarea necesitas tener instalado python 3.8.x sino no te va a funcionar

**Comment by max-orm** [comment]
Despues de descargar el archivo TC1-37.pyc debes agregarlo a la carpeta de tu repositorio y luego usar los comandos git add, git commit y git push, tal como en un video tutorial que mandaron.

**Comment by fcontardo** [comment]
> Despues de descargar el archivo TC1-37.pyc debes agregarlo a la carpeta de tu repositorio y luego usar los comandos git add, git commit y git push, tal como en un video tutorial que mandaron.

Yo hice eso, borrando en Github también el archivo que servia para la versión anterior, pero me sigue saliendo "Not found"  al poner lo del alias.
Qué hace esa línea del alias?

**Comment by pacalein** [comment]
Prueba `python TC1-37.pyc 7` sin el doble punto que indicas que usaste.
🚀

**Comment by Sigonzalez5** [comment]
a mi me sale 'python.exe' : Not found in PATH

**Comment by JupaOlivares** [comment]
> a mi me sale 'python.exe' : Not found in PATH

Hola Hola! lo mas probable es que no agregaste python al PATH cuando tenias que instalarlo.

¿Qué es el PATH? son las rutas que maneja nuestro computador hacia las aplicaciones programas, para que podamos accederlas desde nuestras terminales.

¿Cómo agrego python al PATH? La opción mas fácil es volver a instalar Python y fijarte que en la instalación la casilla que diga algo como add python to path este marcada (Por default **NO** esta marcada, por lo que mucha gente tiene este problema)

Si esto no funciona no desesperéis, comunícate con nosotros y podemos ver que mas esta pasando
Exito!

**Comment by JupaOlivares** [comment]
> Para generar la carpeta de trabajo puse: alias python= "winpty python exe" en el bit bash, estando en la carpeta de la tarea y me salió "command not found". Luego puse python: TC1-37.pyc 7 , y me salió "not found". Tengo instalada la versión 3.7 del python y no entiendo por qué no me funciona. Necesito ayuda :(

Ojo que el comando es _python TC1-37.pyc 7_  sin los ":" , por otro lado si no funciona manda pantallaso de los errores que te aparezcan
