### ISSUE TITLE
GitHub Classroom

### ISSUE THREAD

**Issue by absoto4** [Exploratorio-DCC-PUC/Syllabus#5]
Hola, la barra de progreso ha estado todo el día donde mismo (derecha), ¿tienen alguna idea de a qué se deba esto? Igual mi repositorio personal ya se creó y funciona bien, de hecho ya hice un par de commit, pero no entiendo que pasa con el resto.

![Screenshot_1](https://user-images.githubusercontent.com/39503197/63133327-b687e300-bf92-11e9-8c04-0704a6549630.png)

**Comment by Pyralspite** [comment]
Hola!
Aparentemente es un bug de Github Classroom. Mientras puedas acceder a tu repositorio no hay problemas c:
