### ISSUE TITLE
¿Qué entendemos por filtrado? - Piso 4

### ISSUE THREAD

**Issue by jearaneda** [Exploratorio-DCC-PUC/Syllabus#5]
En el piso 4 se pide filtrar las líneas que incluyan los caracteres '@@'. ¿Significa esto que nuestro comando -y por ende el resultado- deben eliminar las '@@' luego de realizar la búsqueda, o simplemente mostramos el mensaje con los caracteres incluidos?

**Comment by figarrido** [comment]
Solo se debe mostrar el mensaje, no es necesario eliminar los caracteres.
