### ISSUE TITLE
diseño responsive

### ISSUE THREAD

**Issue by danustilovsky** [Exploratorio-DCC-PUC/Syllabus#50]
Hola, entendiendo el concepto de diseño responsive, me preguntaba como podia probar que este se cumpliera, basta con ver en diferentes navegadores o tambien debe funcionar en el celular por ejemplo. En caso de que sea lo segundo, ¿como se puede testear?
gracias

**Comment by diflores** [comment]
Puedes usar algún *framework* CSS que asegure que tu página sea responsive (si fue bien utilizado, por supuesto), como *Bootstrap*.
