### ISSUE TITLE
Directorio y nombre PDF TC1

### ISSUE THREAD

**Issue by retamalcito** [Exploratorio-DCC-PUC/Syllabus#500]
¡Hola! ¿Cuál es el directorio en el que debe estar el archivo PDF al momento de entregarlo? Además, ¿debe tener algún nombre en específico?

¡Gracias!

**Comment by pacalein** [comment]
¡Hola! El archivo en PDF con su informe debe llevar por nombre 'NombreApellido.pdf', y deben ubicarlo en la raíz del repositorio, al mismo nivel que la carpeta TareaChica1 y el archivo .pyc

Ejemplo de como se debe ver su repo:

TareaChica1
FranciscaCattan.pdf
README.md
TC1.pyc

Me cuentas si resolví tu duda.
🚀

**Comment by retamalcito** [comment]
¡Muchas gracias!
