### ISSUE TITLE
Qué pasos son los que se entregan en el PDF? A

### ISSUE THREAD

**Issue by mhassangodoy** [Exploratorio-DCC-PUC/Syllabus#501]
Hola! Estoy haciendo la tarea, he clonado mi repositorio y ya he hecho 2 cambios en él: Hice el push por el cambio del archivo TC1 (Lo tuve que cambiar al TC1-37) y el push por el ingreso de la carpeta "TareaChica1"
El tema es que no se guardaron los schreenshots de esa parte del proceso y en mi terminal ahora sólo sale hasta el segundo push 🤦 (El texto que sale en la terminal es tan largo que se perdió todo lo hecho anteriormente por más que suba, adjunto foto de el último texto que quedó guardado)  
![image](https://user-images.githubusercontent.com/80768643/112386434-ab994680-8ccf-11eb-9747-001f8d4b7f91.png)

Sin embargo, el enunciado dice "Deberás entregar un archivo .pdf que incluya el comando utilizado para cada paso de la tarea (...).", entonces ¿El registro es desde lo hecho en PrimerPaso.md o desde que se clona la carpeta? Y en caso de que no pude registrar la clonación y todo lo ya explicado, ¿Debo borrar todo y empezar de nuevo? D: 

Muchas gracias de antemano y perdón 🙇

**Comment by pacalein** [comment]
¡Hola! Es común que la terminal no dé para visualizar todos lo ocurrido en el espacio de una sola ventana. Sobre todo cuando estamos subiendo repositorios, git imprime en la consola una lista completa de los archivos que va agregando.

Como bien indicas, queremos que vayan paso a paso mostrando el comando que utilizaron y cómo este se visualiza en la consola. Es necesario que tengan un registro de cada uno de los pasos. Mas que borrar todo, puedes repetir el ejercicio y asegurarte de ir capturando los pantallazos necesarios para cubrir cada uno de los pasos. Una visualización de la consola puede abarcar más de una linea de comando, claramente.

Para responder más específicamente a tu última duda, no es necesario que muestren la visualización de la clonación del repo. Pueden partir desde el paso 1.

Quedo atenta a si sientes que solucioné tu pregunta.

🚀

**Comment by mhassangodoy** [comment]
¡Aaaah, muchas gracias! 😭 No había podido ver la respuesta antes, ¡Disculpa el atraso! Pero si lo considero solucionado, así que cerraré el issue, ¡Muchisimas gracias y perdón de nuevo! 🙇🙇🙇
