### ISSUE TITLE
Contar la cantidad de archivos de un directorio y sus subdirectorios

### ISSUE THREAD

**Issue by JorgeGuzz** [Exploratorio-DCC-PUC/Syllabus#502]
Hola! Estoy teniendo problemas para contar la cantidad de archivos en la tarea, ya que al ocupar distintos comandos me da que tengo 4879 archivos, pero segun la tarea deberia terminar en 896 (Carpeta/SubCaperta/SubSubCarpeta)

**PD: Se pueden adjuntar en este tipo de consultas los comandos utilizados para que los revisen?

**Comment by PabloAylwin** [comment]
Tengo la misma duda
