### ISSUE TITLE
Duda sobre comando a utilizar

### ISSUE THREAD

**Issue by Juancagp** [Exploratorio-DCC-PUC/Syllabus#503]
hola, tengo la duda sobre si el siguiente comando debería ser aplicable a git bash (pues tenia entendido que al ser ambos unix deberian funcionar por igual), porque lo he probado pero me lanzan a cualquier cosa menos algo correcto): 
mv *.png ~/Imagenes. En otra pagina también me entrega el codigo mv *.bla /ruta/de/destino.
intentando ambas me sale algo del tipo: 

$ mv *.bla /JuanG
mv: cannot stat '*.bla': No such file or directory

que podría hacer? he buscado mucho en google pero no logro dar con un codigo que me funciones bien

**Comment by pacalein** [comment]
¡Hola!
Primero que todo cuando indicas un directorio de fuente o destino iniciando con el símbolo `~/` le dices que parta desde el directorio raíz que sería en la mayoría de los casos la carpeta de Usuario.

1. El comando para mover un archivo de lugar es como indicas: `mv <ruta_archivo> <ruta_destino>`
Tienes que ver donde estas parado para poder indicar bien el archivo que necesitas mover y el destino al que quieres llegar. Puedes usar el comando `pwd` para que la consola imprima donde estas situado en el directorio.

2. Al incluir el símbolo `*` en el comando `mv <ruta_archivo> <ruta_destino>` lo que haces es indicar que se ejecute el comando sobre todos los archivos que contengan el string indicado. Por ejemplo:
-  `mv Downloads/TareaChica1/file* Downloads/TareaChica1/NuevaCarpeta` --- ejecutará el comando sobre todos los archivos que encuentre **sólo dentro de la carpeta indicada**, que empiecen con el string 'file'.
-  `mv Downloads/TareaChica1/*.png Downloads/TareaChica1/NuevaCarpeta` --- ejecutará el comando sobre todos los archivos que encuentre  **sólo dentro de la carpeta indicada**, que terminen con el string '.png'

Quedo atenta al seguimiento.
🚀

**Comment by Juancagp** [comment]
entendi la idea, pero tengo otra pregunta, debería hacer esto metiendome a cada sub_carpeta existente en el archivo? o con este comando debería ser capaz de mover todos los archivos.bla a la carpeta indicada? (aun cuando tengo estoy dentro de la carpeta TareaChica1)

intento unir el comando find para encontrar todos los archivos "tareaChica*.bla" pero al intentar unirlo con | <comando mv> me algo tipo 
$ find . -name "tareaChica*.bla" | mv *.bla JuanG
mv: cannot stat '*.bla': No such file or directory

**Comment by pacalein** [comment]
¡Hola de nuevo! el comando `mv <source> <target>` sólo actúa sobre los archivos que estén en el directorio inmediato y no entrará a los subdirectorios a buscar más archivos con el nombre que buscas. Si no encuentra el archivo entonces indicará `'No such file or directory'`

Tienes dos opciones, puedes hacerlo a mano como indicas entrando a cada subcarpeta y moviendo cada archivo, o puedes aprender una nueva forma de resolverlo. Recomendamos que aprendan a usar el comando `find`, el cual se especializa en ejecutar acciones dentro de la jerarquía de archivos. No debiera haber errores al encontrar y mover los archivos de esta forma, y es más rápido que entrar a cada uno de los directorios y ejecutar manualmente el comando `mv`.

Me avisas como vas en este mismo thread.
🚀

**Comment by pacalein** [comment]
Claro en ese caso la sintaxis que recomiendo es ` -exec mv {} ./JuanG` . Recuerda cerrar bien el comando o no te va a funcionar y te tirará el error `'unknown primary or operator'`.
Avísame como te va.
🚀
