### ISSUE TITLE
Duda sobre mensaje de advertencia

### ISSUE THREAD

**Issue by max-orm** [Exploratorio-DCC-PUC/Syllabus#504]
Hola buenas, me pasó que al hacer git add, git commit y git push a la carpeta TareaChica1 me salieron los siguientes mensajes:

$ warning: LF will be replaced by CRLF in TareaChica1/Carpeta_3/SubCarpeta_5/progreso.txt.
bash: warning:: command not found

$ The file will have its original line endings in your working directory
bash: The: command not found

Solo quiero saber si hay que prestarle atención o no a esos mensaje? Igual revisé la carpeta que se subió a mi directorio de github y parece estar todo bien.

**Comment by amaiajuanchuto** [comment]
Hola!

LF y CRLF son formas de hacer un salto de línea en algún archivo. Esos mensajes solo te están diciendo que va a modificar la codificación de tus saltos de línea de LF a CRLF, no es necesario que te preocupes por ese _warning_. 😄

**Comment by pacalein** [comment]
¡Hola! +1 al reply de arriba. Si verificas que los archivos subidos a tu repo están ok, todo bien. Parte importante de aprender a usar la consola y bash es aprender a resolver estos mensajes de error si van apareciendo.
🚀

**Comment by max-orm** [comment]
Buenoo gracias por las respuestas! Y ya caché como configurar al advertencia advertencia😁.
