### ISSUE TITLE
No se encontró Python

### ISSUE THREAD

**Issue by Sigonzalez5** [Exploratorio-DCC-PUC/Syllabus#506]
Hola, hice todo lo de git add, pull, push en mi repositorio, pero cuando coloco python TC1.pyc 8 me aparece: "No se encontró Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuración > Administrar los alias de ejecución de aplicaciones."
¿Qué hago? tengo python 3.8 recién instalado.

**Comment by clolate** [comment]
Hola! quizas te falta agregar python al path. para confirmar que tienes python en consola si pones` $python --version` debería ponerte la version que en tu caso sería 3.8 si te sale el mismo error u otro y tienens python instalado entonces lo más probable es que sea un problema de PATH:
Aqui hay un tutorial que te puede servir [agregar al path](https://recursospython.com/guias-y-manuales/python-no-se-reconoce-como-un-comando-interno-o-externo/)
Otra cosa: a veces, no se que versión o que consola, pero a mi a veces me pasaba que hay otros comandos que servian. Si estas en la carpeta puedes usar:
```
$ archivo.py 
$py archivo.py
$python archivo.py
```

**Comment by pacalein** [comment]
¡Hola! Todavía tienes el problema?

**Comment by Sigonzalez5** [comment]
siiii
