### ISSUE TITLE
Problema al contar la cantidad de archivos

### ISSUE THREAD

**Issue by cristobalba** [Exploratorio-DCC-PUC/Syllabus#508]
Hola, cuando me piden contar la cantidad de archivos en la carpeta padre y usar los ultimos tres digitos para llegar al siguiente paso, me paso por 2 archivos. Es decir si debería llegar a la SubSubCarpeta_3, estoy llegando a la SubSubCarpeta_5. Podría ser posible que al realizar algún comando haya duplicado algún archivo o algo así? También, aclarar que si estoy usando el archivo "TC1" arreglado que subieron a un drive.

**Comment by fsazo** [comment]
Hola, tengo un problema parecido, al contar los archivos me cuenta uno menos de los que debería contar. ¿Qué puede estar pasando?

**Comment by emiliaup** [comment]
Tengo el mismo problema :/ me cuenta uno menos de los que deberia de contar. ¿Tengo que tomar en cuenta tambien el archivo TC1-38 o no?

**Comment by JupaOlivares** [comment]
> Hola, cuando me piden contar la cantidad de archivos en la carpeta padre y usar los ultimos tres digitos para llegar al siguiente paso, me paso por 2 archivos. Es decir si debería llegar a la SubSubCarpeta_3, estoy llegando a la SubSubCarpeta_5. Podría ser posible que al realizar algún comando haya duplicado algún archivo o algo así? También, aclarar que si estoy usando el archivo "TC1" arreglado que subieron a un drive.

Hola si generaste la carpeta usando el archivo del Drive no deberías tener problemas al encontrar "el paso final", esto puede haberse generado por algún archivo extra creado durante la tarea (para ese paso se asume que no creaste nada mas de lo que deberías crear), chequea los comandos que usaste y los archivos que generaste y si te aproblema te aconsejo generar de nuevo la carpeta y empezar de 0 (no te debería tomar tiempo si ya tienes los comandos para llegar)

Éxito!

**Comment by JupaOlivares** [comment]
> Tengo el mismo problema :/ me cuenta uno menos de los que deberia de contar. ¿Tengo que tomar en cuenta tambien el archivo TC1-38 o no?

Hola! No! Solo se cuentan los que están dentro de la carpeta tarea chica y los que se te piden generar durante la tarea
