### ISSUE TITLE
Cantidad de Pasos

### ISSUE THREAD

**Issue by ignacio-quera** [Exploratorio-DCC-PUC/Syllabus#509]
Tengo una duda sobre la cantidad de pasos de la tarea, ya que llegué al final de está pero temo que me salté algún paso. Saludos

**Comment by pacalein** [comment]
Hola Ignacio, puedes ser un poco más específico con la duda?

El primer paso se encuentra en un documento .md
El segundo y tercer paso en un documento .txt
El cuarto y último paso se encuentra en un documento .md

Quedo atenta para ayudarte mejor.
🚀
