### ISSUE TITLE
Encontrar y mover elementos

### ISSUE THREAD

**Issue by CristianD16** [Exploratorio-DCC-PUC/Syllabus#510]
Hola! He estado buscando y no encuentro la forma de filtrar ciertos archivos y luego moverlos de ubicación. Traté algunas combinaciones, pero no me resulta. 

Saludos!

**Comment by pacalein** [comment]
Hola! Esta duda ha aparecido harto en otros issues y ya ha sido resuelta. Copiaré de todas formas aquí lo que hemos conversado y les resulta a todos.

¡Hola de nuevo! el comando `mv <source> <target>` sólo actúa sobre los archivos que estén en el directorio inmediato y no entrará a los subdirectorios a buscar más archivos con el nombre que buscas. Si no encuentra el archivo entonces indicará 'No such file or directory'

Recomendamos que aprendan a usar el comando `find`, el cual se especializa en ejecutar acciones dentro de la jerarquía de archivos. No debiera haber errores al encontrar y mover los archivos de esta forma, y es más rápido que entrar a cada uno de los directorios y ejecutar manualmente el comando `mv`.

Busca la sintaxis correcta, es super fácil encontrarlo en internet bajo "find command console" o similar. No lo coloco aquí sólo porque estaría dando la respuesta T^T.

Me avisas como vas en este mismo thread.
🚀
