### ISSUE TITLE
bonus

### ISSUE THREAD

**Issue by jtvaldivia** [Exploratorio-DCC-PUC/Syllabus#511]
El bonus se puede hacer ocupando bibliografia de google ?

**Comment by pacalein** [comment]
Hola! Te refieres al bonus de 0,5 de la tarea chica 1? Si es así, como menciona el enunciado en la sección 5 Recomendaciones, alentamos a que ustedes busquen lo que necesiten usando el motor de búsqueda que prefieran. En ese caso debes colocar el link de donde sacaste el comando para que podamos entrar y revisar.

Porfa dime si te refieres a otro bonus, ya que quedé medio enredada con tu pregunta.
🚀

**Comment by jtvaldivia** [comment]
Si me referia a ese bonus. 
Muchas gracias
