### ISSUE TITLE
git commit 

### ISSUE THREAD

**Issue by sachondo7** [Exploratorio-DCC-PUC/Syllabus#512]
hola intento hacer git commit desde la terminal pero me sale este error, alguna idea de como solucionarlo?
![Screenshot 2021-03-27 at 17 39 20](https://user-images.githubusercontent.com/80768647/112734261-6a00d980-8f23-11eb-8b1d-977b2ae6e5c1.png)

**Comment by pacalein** [comment]
¡Hola! Para que git pueda autenticar tu usuario, debes antes agregar tu info.

Corre en la consola
`git config --global user.email "email"` --- y aquí coloca el correo que usas en Github, con el que tienes tu usuario.
`git config --global user.name "name"` --- y aquí coloca tu nombre, puede ser el mismo usuario de Github.

Luego debiera hacer commit sin problemas, o es probable que te pida la pass que usas en Github también. 

Viendo tu historial de la consola, te recomiendo evitar problemas en el commit ejecutando `git add .` desde el directorio que será tu repo. De esa forma agregas todo lo que se encuentra desde ahí en adelante y no sólo una carpeta.

Me cuentas como vas.
🚀
