### ISSUE TITLE
Mover archivos 

### ISSUE THREAD

**Issue by angegazitua** [Exploratorio-DCC-PUC/Syllabus#513]
¡Hola! En el primer paso de la tarea cuando utilizo el comando para encontrar los archivos y moverlos me dice que "permission denied". ¿Por qué sucede esto? ¿Hay alguna forma de cambiarlo?
![2021-03-27 (9)](https://user-images.githubusercontent.com/80768594/112739943-f96fb200-8f4e-11eb-89f2-a51dc6595865.png)

**Comment by BenediktKd** [comment]
Me está pasando el mismo problema. Me sumo a esperar la respuesta.

**Comment by sachondo7** [comment]
tengo el mismo problema :c

**Comment by JupaOlivares** [comment]
Hola estuve pensando y se me ocurren varias razones:

1. Tal vez haya algún proceso que este corriendo que involucre esas carpetas, por lo que no pueden moverse.
2. El comando esta mal escrito y están tratando de mover algo o hacia algo que no debería ser.
3. Git Bash puede no estar autorizado para mover archivos por configuraciones de Windows .

Pueden tratar otros comandos u otras terminales para descartar estos errores, además de reiniciar el computador para asegurarse que no haya nada que interrumpa el proceso.
