### ISSUE TITLE
Problema al contar archivos

### ISSUE THREAD

**Issue by RafaelEdwards** [Exploratorio-DCC-PUC/Syllabus#514]
Hola! 

En el paso en que se deben contar los archivos, ¿se deben contar también los directorios?
De todas formas, contando o no los directorios el número no me lleva al archivo para continuar la tarea. Además, la cantidad de archivos cambia levemente cada vez que corro el comando. 

Estoy usando la versión 3.7 y otros alumnos con la misma versión me han comentado que están teniendo problemas con este paso. ¿Existe la posibilidad de que el archivo TC1-37.pyc tenga alguna falla?

Muchas gracias.

**Comment by PabloAylwin** [comment]
Me pasa exactamente lo mismo con la versión 3.8

**Comment by RafaelEdwards** [comment]
Ya lo solucioné, estaba contando archivos invisibles .DS_Store que mac agrega.

**Comment by JupaOlivares** [comment]
> Me pasa exactamente lo mismo con la versión 3.8

revisa otras issues similares, hay varios preguntando lo mismo
