### ISSUE TITLE
Ausencia commit tareas terminadas

### ISSUE THREAD

**Issue by bhenriquezsoto** [Exploratorio-DCC-PUC/Syllabus#515]
No pude guardar un ultimo commit del paso 3 debido a que no hubieron cambios desde la finalizacion del paso 2, por lo que solo quedo la finalizacion del paso 2 y el commit de cuando se termino todo y se subio el pdf; es esto un problema?

**Comment by pacalein** [comment]
Hola Benja, vi tu línea de commits y está ok, tienes por lo menos 10 contando el inicial. Lo que queríamos era que experimentaran registrar sus cambios usando commit, y lo lograste.
Si consideras que tu tarea está completa, entonces estás listo.

Saludos y me dices si es que resolví tu duda.
🚀

**Comment by bhenriquezsoto** [comment]
Sip, todo bien, muchas gracias :)
