### ISSUE TITLE
Paso 3.2

### ISSUE THREAD

**Issue by SebaMartinezM** [Exploratorio-DCC-PUC/Syllabus#516]
Una consulta, al realizar el paso 3.2 en la parte de ingresar el comando "python TC1.pyc digito" accidentalmente no utilice el ultimo digito de mi numero de alumno. De todas formas se me crearon las carpetas correctamente. Hay algún problema con eso? o tengo que borrar y hacerlo de nuevo?

**Comment by JupaOlivares** [comment]
El enunciado pide que se haga con tu numero de alumno por lo que si, tienes que crearlo de nuevo

**Comment by SebaMartinezM** [comment]
ok, gracias.
