### ISSUE TITLE
problema contando archivos

### ISSUE THREAD

**Issue by sachondo7** [Exploratorio-DCC-PUC/Syllabus#517]
hola! he reiniciado 2 veces ya mi tarea porque estoy teniendo problemas en contar archivos. me arroja un numero terminado en 104 y deberia ser 992. Además, ya me aseguré de hacerlo bien con la versión de python correspondiente y también me aseguré de borrar los arvhicos DS_store que crea el mac por defecto, y aún así no logro llegar al número correcto. 
Alguna recomendación de que puede ser?

**Comment by JupaOlivares** [comment]
Hola revisa bien que comando estas usando y de donde lo estas corriendo, además de actualizar el .pyc (si ya lo hiciste no tienes orque actualizarlo de nuevo) es demasiado extraño que los números discrepen tanto.

Ojo que ese paso considera los archivos que tu tienes que crear en pasos anteriores y cualquier archivo extra que crees altera el numero.

**Comment by sachondo7** [comment]
Hola JP. Sabes que hice todo eso y aún así me siguen dando números distintos. Es posible que nos conectemos un poco antes o un poco después de la ayudantía para mostrarte el problema y ver si me puedes ayudar? 
Muchas gracias.

Saludos,

Sebastián

**Comment by JupaOlivares** [comment]
> Hola JP. Sabes que hice todo eso y aún así me siguen dando números distintos. Es posible que nos conectemos un poco antes o un poco después de la ayudantía para mostrarte el problema y ver si me puedes ayudar? Muchas gracias. Saludos, Sebastián


Ya hablamos por privado pero para futuras referencias el problema es que estaba contando carpetas

**Comment by sachondo7** [comment]
Ya lo pude solucionar gracias!!

Saludos,

Sebastián
