### ISSUE TITLE
Problema con directorio borrado desde github

### ISSUE THREAD

**Issue by andresiacobelli** [Exploratorio-DCC-PUC/Syllabus#518]
Hola!
Sin querer subí la carpeta del ejercicio lista (TareaChica1) en un commit equivocado (describía mal el "update"). Para subirla con el comentario del commit corresponiente, la eliminé desde github. El tema es que eso ahora me quedó guardado como un commit y si bien todavía tengo la carpeta intacta en mi computador, no me es posible volver a subuirla. Me sale que el repositorio remoto y local están "up to date"

**Comment by pacalein** [comment]
Hola! Revisé tu repo y tu historia de commits y se ve ok. El directorio parece completo a primera vista. Quizás necesito más detalles para entender el problema si aún no lo haz resuelto.

Eso sí, el archivo en pdf debe tener tu nombre, y además veo que no está el archivo de python en tu repo. Debes arreglar eso antes de terminar.

Dime como te va.
🚀
