### ISSUE TITLE
Problema con subir PDF

### ISSUE THREAD

**Issue by CataLebe** [Exploratorio-DCC-PUC/Syllabus#519]
Holaa, resulta que ya subí la carpeta TareaChica1 con los cambios que le corresponden a mi repositorio, pero al intentar usar los mismos comandos para subir mi PDF me aparece un error y no me deja. ¿El PDF se sube de otra forma ?
Graciass

**Comment by pacalein** [comment]
Hola! Puedes adjuntar el error para ver específicamente cómo resolverlo? El archivo en pdf se sube al repo, tu directorio final se debiera ver así:

TareaChica1
FranciscaCattan.pdf
README.md
TC1.pyc

🚀

**Comment by CataLebe** [comment]
Logré arreglarlo dentro de la mañana, sorry por el leseo.
Gracias !
