### ISSUE TITLE
Error importando pandas

### ISSUE THREAD

**Issue by YehudaGurovich** [Exploratorio-DCC-PUC/Syllabus#52]
Cuando hago shift enter en la parte de importar las librerias me tira este error.

ImportError                               Traceback (most recent call last)
<ipython-input-29-71225e3ad40e> in <module>
----> 1 import pandas as pd
      2 import matplotlib.pyplot as plt

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\__init__.py in <module>
     15 if missing_dependencies:
     16     raise ImportError(
---> 17         "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
     18     )
     19 del hard_dependencies, dependency, missing_dependencies

ImportError: Unable to import required dependencies:
numpy: cannot import name 'core' from 'numpy' (c:\users\user\appdata\local\programs\python\python37\lib\site-packages\numpy\__init__.py)

**Comment by malopez16** [comment]
Hola!
Prueba [esto](https://stackoverflow.com/a/42939561) y avisame cómo te va :)

**Comment by YehudaGurovich** [comment]
Funcionó perfecto. Mil gracias.
