### ISSUE TITLE
Dudas con contenido PDF

### ISSUE THREAD

**Issue by CataLebe** [Exploratorio-DCC-PUC/Syllabus#520]
Holaa, una duda ¿el contenido del PDF debe incluir pantallazos hasta donde se terminan los pasos de la tarea ? ¿O hay que incluir también pantallazos de los comandos que usamos para subir la tarea ?
Graciaas

**Comment by pacalein** [comment]
Hola! En el enunciado dice que el pdf debe contener "los comandos utiliza-dos en su tarea, junto con la explicación de este y el pantallazo de su ejecuciónen consola." Como subir la tarea al repo es parte del punto 3.4, debe estar incluido en el informe.

Me cuentas como vas.
🚀

**Comment by pacalein** [comment]
Hola! En el enunciado dice que el pdf debe contener "los comandos utilizados en su tarea, junto con la explicación de este y el pantallazo de su ejecuciónen consola." Sin embargo, eso está dicho explícitamente en el punto 3.3, así que queda a tu criterio si quieres agregar los comandos del punto 3.4.

Me cuentas como vas.
🚀
