### ISSUE TITLE
intro-a-la-web-2

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#522]
Hola!

No me quedan del todo claras las intrucciones del intro a la web 2, ¿podrían mostrar un _screenshot_ de más o menos qué se espera que podamos hacer?

Gracias

**Comment by denisparra** [comment]
Hola, lo que está entre paréntesis cuadrados serían botones

![image](https://user-images.githubusercontent.com/208111/113739863-3580e080-96ce-11eb-9aa0-bdee601c1d96.png)
