### ISSUE TITLE
Prohibición For loops TG2

### ISSUE THREAD

**Issue by aenrione** [Exploratorio-DCC-PUC/Syllabus#524]
Hola quería preguntar para confirmar, en el enunciado cuando dice:
![imagen](https://user-images.githubusercontent.com/60358967/113628046-55fb5d00-9632-11eb-836d-8b280bd2ce19.png)
Se refiere a que no se puede usar absolutamente ninguna for loop, o solo las que no no utilizan metodos de Pandas, gracias.

**Comment by IchottMano** [comment]
Hola!

Se refiere a que no pueden usar ningun for loop, pero pueden usar funciones de pandas que implementen loops por dentro si lo necesitan.

Saludos!

**Comment by IchottMano** [comment]
Hola! 

Por favor *no cierren las issues*

Nosotros lo haremos cuando sea necesario!

Saludos
