### ISSUE TITLE
intro-a-la-web-2 (js)

### ISSUE THREAD

**Issue by bhenriquezsoto** [Exploratorio-DCC-PUC/Syllabus#525]
Holaa, tengo una duda sobre el funcionamiento de javascript, he intentado ver distintas fuentes pero aun no se muy bien que esta fallando, sera posible poder adjuntar el codigo del practico sin nota?

**Comment by denisparra** [comment]
Hola Benja, no es posible en primera instancia. Lo hizo el profesor Fernando Florenzano que no está en el equipo docente actualmente. Le pediré a alguno de los ayudantes que lo resuelva. Y te avisamos.
