### ISSUE TITLE
Problemas con participantes

### ISSUE THREAD

**Issue by NicoJGutierrez** [Exploratorio-DCC-PUC/Syllabus#526]

**Comment by NicoJGutierrez** [comment]
Mi anterior compañero botó el ramo y me acabo de juntar con otra persona para la TG1. Sin embargo, no se puede meter al grupo porque le aparece que está lleno. El grupo es el 69.420

**Comment by IchottMano** [comment]
Hola!

Eliminaré el grupo para que puedas hacer otro con tu nuevo compañero.

Saludos!

**Comment by NicoJGutierrez** [comment]
El problema no se solucionó, creé otro grupo pero este parece haber tomado la arquitectura del grupo anterior o algo (?????????) y mi compañero sigue sin poderse unir

**Comment by IchottMano** [comment]
Hola!

Por favor intentalo ahora 😓 

Saludos!
