### ISSUE TITLE
Pregunta 4 Parte 1 TG1

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#528]
Hola, con mi compañera no tenemos claro lo que hay que hacer en la pregunta 4 de la parte 1. Nos podrían explicar mejor que hay que hacer por favor

**Comment by usdonoso** [comment]
Hola, en la ayudantía del miércoles se explicó un poco mejor esa parte. ¿Revisaron el video?
Si ya revisaron el video y todavía tienen dudas entonces escribanos de nuevo y buscamos otra manera de resolver la duda. :)

**Comment by usdonoso** [comment]
> Hola, con mi compañera no tenemos claro lo que hay que hacer en la pregunta 4 de la parte 1. Nos podrían explicar mejor que hay que hacer por favor

Hola, en la ayudantía del miércoles se explicó un poco mejor esa parte. ¿Revisaron el video?
Si ya revisaron el video y todavía tienen dudas entonces escribanos de nuevo y buscamos otra manera de resolver la duda. :)
