### ISSUE TITLE
Pregunta 03 parte 01

### ISSUE THREAD

**Issue by sachondo7** [Exploratorio-DCC-PUC/Syllabus#529]
Hola, tengo la duda de que en la pregunta 3 de la parte 1, dice que tenemos que hacer gráficos de torta para los 5 mejores anime. 
Estos se refieren a los 5 mejores anime por "score", o bien los 5 mejores anime de "completed","watching",y "plan to watch" respecitvmente?

Gracias

**Comment by Stomicicp** [comment]
Tengo la misma duda

**Comment by usdonoso** [comment]
Exacto, como lo primero que mencionas.
Primero deben buscar cuáles son los 5 mejores animes de acuerdo a su "score". Luego deben hacer 3 gráficos, uno de "Completed", otro de "Watching" y otro de "Plan to watch", donde en cada uno se ve la distribución de personas que están en esta "etapa" para los 5 anime seleccionados. 

:)

**Comment by usdonoso** [comment]
> Hola, tengo la duda de que en la pregunta 3 de la parte 1, dice que tenemos que hacer gráficos de torta para los 5 mejores anime.
> Estos se refieren a los 5 mejores anime por "score", o bien los 5 mejores anime de "completed","watching",y "plan to watch" respecitvmente?
> 
> Gracias

Exacto, como lo primero que mencionas.
Primero deben buscar cuáles son los 5 mejores animes de acuerdo a su "score". Luego deben hacer 3 gráficos, uno de "Completed", otro de "Watching" y otro de "Plan to watch", donde en cada uno se ve la distribución de personas que están en esta "etapa" para los 5 anime seleccionados.

:)

**Comment by nzamorano** [comment]
Hola, nos pasa que al ordenar los animes por score el anime número 4, 5 y 6 tienen el mismo score, entonces para elegir el top 5 lo hacemos por orden alfabético, por el más visto o por otro método?

**Comment by usdonoso** [comment]
> Hola, nos pasa que al ordenar los animes por score el anime número 4, 5 y 6 tienen el mismo score, entonces para elegir el top 5 lo hacemos por orden alfabético, por el más visto o por otro método?

Entiendo la duda. Para esos tres deben elegir por ID, es decir, los primeros dos según su ID, que incluso es el criterio que usa la función de pandas que selecciona las primeras cinco filas del dataframe. :)
