### ISSUE TITLE
Gráfico por día

### ISSUE THREAD

**Issue by rosariodiez** [Exploratorio-DCC-PUC/Syllabus#53]
Hola! En el gráfico de días de la semana tienen que estar los días en orden o da lo mismo?

**Comment by rosariodiez** [comment]
y tiene que mostrar porcentaje también?

**Comment by diflores** [comment]
¡Hola!

En Altair es difícil ordenar los ejes, así que si utilizan esa librería, pueden poner los días desordenados.
Sobre los porcentajes, sí, deben ser incluidos.

¡Saludos!
