### ISSUE TITLE
Preguntas parte Dashboard Tarea-Grande-1

### ISSUE THREAD

**Issue by MaxiNavia** [Exploratorio-DCC-PUC/Syllabus#530]
Hola, con mi compañero tenemos las siguientes preguntas sobre la parte del Dashboard de la Tarea Grande 1:
1) ¿Las imágenes de los siete gráficos con ScrollReveal pueden estar desde el inicio o tienen que aparecer una vez se selecciona con los botones?

2) ¿Importa como se ven los gráficos de torta si mantienen el formato pedido? Porque se ven comprimidos hacia los lados, entonces en vez de círculo parecen más un óvalo.

3) ¿Los títulos y los labels de los gráficos tienen que estar en español o en inglés? ¿Poner "Completed" o "Completado"?

4) ¿Se pueden agregar títulos extras en la página para dar más orden a las cosas? Por ejemplo poner título de "Histogramas" a los gráficos de Histogramas?

5) ¿En la parte final de Fullmetal Alchemist: Brotherhood Mode se pueden hacer más modificaciones aparte de los pedidos? Por ejemplo cambiar el color de los botones, el texto, entre otras cosas.

Muchas gracias de antemano :D

**Comment by usdonoso** [comment]
> Hola, con mi compañero tenemos las siguientes preguntas sobre la parte del Dashboard de la Tarea Grande 1:
> 
> 1. ¿Las imágenes de los siete gráficos con ScrollReveal pueden estar desde el inicio o tienen que aparecer una vez se selecciona con los botones?
> 2. ¿Importa como se ven los gráficos de torta si mantienen el formato pedido? Porque se ven comprimidos hacia los lados, entonces en vez de círculo parecen más un óvalo.
> 3. ¿Los títulos y los labels de los gráficos tienen que estar en español o en inglés? ¿Poner "Completed" o "Completado"?
> 4. ¿Se pueden agregar títulos extras en la página para dar más orden a las cosas? Por ejemplo poner título de "Histogramas" a los gráficos de Histogramas?
> 5. ¿En la parte final de Fullmetal Alchemist: Brotherhood Mode se pueden hacer más modificaciones aparte de los pedidos? Por ejemplo cambiar el color de los botones, el texto, entre otras cosas.
> 
> Muchas gracias de antemano :D

Hola 

1. Deben aparecer una vez se selecciona algún botón. 
2. Tal vez trata de modificar el tamaño del gráfico o figura al momento de crearlo. Pero, si no les resulta, no hay problema, no se les hará un descuento por eso. 
3. Es más correcto ponerlo en inglés, porque así se respetan los nombres originales del dataset.
4. Sí, si les queda más ordenado es completamente aceptable. La parte gráfica de la página debe cumplir con los elementos mínimos que solicitamos, pero son libres de agregar elementos, mientras mantengan las funcionalidades e interacciones.
5. Sí, por lo que dije anteriormente, pueden darle personalidad a la página mientras cumplan con los mínimos. :)
