### ISSUE TITLE
Pregunta 4 de la TG1

### ISSUE THREAD

**Issue by cristobalba** [Exploratorio-DCC-PUC/Syllabus#531]
Hola, al hacer el gráfico de regresión para la pregunta 4, los datos del eje x que corresponden a los años desde el 2000 hasta el 2021, me lo acota hasta el 2020 nomas, pero se ve como que el gráfico continua. Hay alguna forma de poder expandir el grafico hasta el 2021 o esta bien asi? Adjunto foto de como se ve
![graf](https://user-images.githubusercontent.com/80768909/114444949-75980580-9b9d-11eb-8bf3-731c7eb98b4e.png)

**Comment by usdonoso** [comment]
No, no hay problema, en el fondo tu eje X está marcando cada dos años y medio, pero igual se grafican todos los años, así que no hay problema. Eso sí, ojo con el eje Y, se supone que son scores, por lo tanto los números parecen ser incoherentes con eso. 
Saludos :)

**Comment by usdonoso** [comment]
> Hola, al hacer el gráfico de regresión para la pregunta 4, los datos del eje x que corresponden a los años desde el 2000 hasta el 2021, me lo acota hasta el 2020 nomas, pero se ve como que el gráfico continua. Hay alguna forma de poder expandir el grafico hasta el 2021 o esta bien asi? Adjunto foto de como se ve
> ![graf](https://user-images.githubusercontent.com/80768909/114444949-75980580-9b9d-11eb-8bf3-731c7eb98b4e.png)

No, no hay problema, en el fondo tu eje X está marcando cada dos años y medio, pero igual se grafican todos los años, así que no hay problema. Eso sí, ojo con el eje Y, se supone que son scores, por lo tanto los números parecen ser incoherentes con eso.
Saludos :)

**Comment by cristobalba** [comment]
Gracias por la respuesta!
 Ese gráfico corresponde a la regresion de los  promedios de "Plan to watch" por año, por eso los numeros del eje y son altos. Con mi compañero entendimos del enunciado que hay que hacer un grafico de regresion para score, otro para completed, otro para watching y otro para plan to watch, es correcto esto? o solo se pide el grafico de regresion de scores promedio al año??

**Comment by usdonoso** [comment]
Claro, es correcto lo que entendieron, son 4 gráficos en esa parte. :)

**Comment by usdonoso** [comment]
> Gracias por la respuesta!
> Ese gráfico corresponde a la regresion de los promedios de "Plan to watch" por año, por eso los numeros del eje y son altos. Con mi compañero entendimos del enunciado que hay que hacer un grafico de regresion para score, otro para completed, otro para watching y otro para plan to watch, es correcto esto? o solo se pide el grafico de regresion de scores promedio al año??

Claro, es correcto lo que entendieron, son 4 gráficos en esa parte. :)
