### ISSUE TITLE
Pregunta 4 Parte 1 

### ISSUE THREAD

**Issue by IgnaciaGonzlez** [Exploratorio-DCC-PUC/Syllabus#532]
Hola!
tenemos problemas para generar los gráficos de regresión, resulta que nos tira el siguiente error:

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

Intentamos con las DataFrames y ejemplos de la página de seaborn y si resultan los gráficos, lo que nos hace sospechar que quizás sea una un problema de nuestra data, la que generamos sacando promedios para cada año de los datos necesarios. Cabe destacar que al poner data.head() nuestra data tiene el mismo formato que la que probamos de internet. 
Muchas gracias de antemano :)

**Comment by IchottMano** [comment]
Hola!

Lo que probablemente les ocurre ahí es que su columna de años es un string y no un número. 
Intenten lo que sale en [esta página](https://datatofish.com/convert-string-to-float-dataframe/) para solucionarlo, y me cuentan si les funciona.

Saludos!

**Comment by IgnaciaGonzlez** [comment]
Muchísima gracias!
efectivamente eso había pasado, ahora funciona bien :D
