### ISSUE TITLE
Duda sobre Regla en Parte 1 TG1

### ISSUE THREAD

**Issue by Juancagp** [Exploratorio-DCC-PUC/Syllabus#533]
hola, no tengo muy bien entendido a que se refiere con Hardcoding en los graficos, asi como los datos numerico y animes.
![image](https://user-images.githubusercontent.com/81201399/114493104-e49a4c00-9be7-11eb-89be-3aecc0d25277.png)
por ejemplo, yo al menos para poder hacer la parte 1, tuve que ocupar comandos para manipular los datos como: sort, iloc, copy, astype, etc...
especificamente en una parte tuve que copiar una columna del dataframe orginial y aregarlo a la misma como una columna auxiliar. Eso contaría como hardcoding?

**Comment by IchottMano** [comment]
Hola!

Lo que me dices está bien, la idea principal de esta regla es evitar por ejemplo que creen manualmente dataframes con los datos de las medias para graficar.

Saludos!

**Comment by RafaelEdwards** [comment]
Hola, 

¿con dataframes con los datos te refieres a dataframes que por ejemplo tengan explícitamente los nombres de algunos animes?

¿Se podría crear un dataframe que contenga por ejemplo {"scores" :[data["Score1"], data["Score2"],...]} index =[ "Score1", "Score2"...] o contaría como hardcoding?

Saludos!
