### ISSUE TITLE
Tarea grande librerias 

### ISSUE THREAD

**Issue by emiliaup** [Exploratorio-DCC-PUC/Syllabus#534]
Hola! Para la tarea grande 1, que librerias estan permitidas? Puedo ocupar numpy o matplotlib??

**Comment by usdonoso** [comment]
> Hola! Para la tarea grande 1, que librerias estan permitidas? Puedo ocupar numpy o matplotlib??

Hola
Sí, incluso la idea es que uses pandas, numpy, matplotlib y seaborn. :)

**Comment by emiliaup** [comment]
gracias!! :)
