### ISSUE TITLE
Parte 2 cuerpo del HTML

### ISSUE THREAD

**Issue by cristobalba** [Exploratorio-DCC-PUC/Syllabus#535]
Hola, no entendemos a que se refiere con que el margen del cuerpo (de la pagina HTML) debe ser del 3% de la pantalla
Salu2

**Comment by usdonoso** [comment]
> Hola, no entendemos a que se refiere con que el margen del cuerpo (de la pagina HTML) debe ser del 3% de la pantalla
> Salu2

Hola
Los márgenes pueden expresarse en pixeles pero también en unidades de porcentaje, entonces simplemente se les pide que sea un margen de 3%. Esto deben crearlo o editarlo en su archivo CSS. 

Espero haber entendido su duda, cualquier cosa vuelvan a escribir :)

**Comment by cristobalba** [comment]
Perfecto! eso si, como se pide respecto de la pantalla esto se indica como 3% solamente? o es un 3% en todas las direcciones (arriba, abajo, izquierda, derecha)?
Graciaas

**Comment by usdonoso** [comment]
> Perfecto! eso si, como se pide respecto de la pantalla esto se indica como 3% solamente? o es un 3% en todas las direcciones (arriba, abajo, izquierda, derecha)?
> Graciaas

Exacto, solo indicando el valor de 3% en la propiedad del margen funcionará bien. Solo debes preocuparte de escribir esto en la declaración que corresponde al cuerpo de tu página. :)
