### ISSUE TITLE
Problema Pregunta 1, "Year"

### ISSUE THREAD

**Issue by Maxi1805** [Exploratorio-DCC-PUC/Syllabus#536]
Hola, empecé a trabajar en la carga de datos del archivo "animes_clean.csv", sin embargo cuando ocupo read.csv de la librería pandas me dice que no existe la columna "Year", pero si me lo toma como "Year;", no entiendo si hay que mantenerlo asi o de alguna manera tenemos que eliminar ese ";" de todas las columnas.

**Comment by fernandosmither** [comment]
Confirmo
<img src="https://pbs.twimg.com/media/DTok42rU0AA_uQu.jpg" alt="drawing" width="200"/>

**Comment by IchottMano** [comment]
Hola!

Puedo ver claramente que en el archivo que les dimos no hay ningún ;.
Probablemente modificaron el archivo sin querer, recomiendo que revisen cualquier cambio que hagan hecho y lo reviertan.

Saludos
