### ISSUE TITLE
Parte 2 Encabezado y Cuerpo

### ISSUE THREAD

**Issue by cristobalba** [Exploratorio-DCC-PUC/Syllabus#537]
Holaa, el encabezado y el cuerpo deben estar en contenedores flex distintos o puede ser el mismo?
gracias :)

**Comment by usdonoso** [comment]
Distintos :)
Es incluso más lógico hacerlo de es manera.

**Comment by usdonoso** [comment]
> Holaa, el encabezado y el cuerpo deben estar en contenedores flex distintos o puede ser el mismo?
> gracias :)

Distintos :)
Es incluso más lógico hacerlo de es manera.
