### ISSUE TITLE
Contenedor del cuerpo

### ISSUE THREAD

**Issue by angegazitua** [Exploratorio-DCC-PUC/Syllabus#538]
¡Hola! En los requerimientos de la parte 2 se indica que el cuerpo debe ser un contenedor flex. ¿Se refieren a que dentro de este contenedor debemos poner todos los otros elementos (gráficos, botones, etc.) o podemos hacer diversos contenedores, por ejemplo para cada pregunta, con el mismo formato?

**Comment by usdonoso** [comment]
> ¡Hola! En los requerimientos de la parte 2 se indica que el cuerpo debe ser un contenedor flex. ¿Se refieren a que dentro de este contenedor debemos poner todos los otros elementos (gráficos, botones, etc.) o podemos hacer diversos contenedores, por ejemplo para cada pregunta, con el mismo formato?

Para aclarar, un área del documento que contiene un flexbox es llamada contendedor flex, por lo tanto, cuando pedimos que el cuerpo sea un contenedor es para que sea mucho más ordenado y lógico la forma en que arman la página. En la tarea hay un link para entender esto y tiene unos ejemplos muy útiles al final. Con esto, además, le das el formato a los distintos elementos, en este caso, al cuerpo, en tu archivo CSS. 
Entonces, no estoy segura de si entendí bien tu pregunta, pero lo importante es que uses este sistema para organizar los elementos de tu página y darles el formato que quieras. Idealmente los gráficos y botones van a estar dentro de otros contenedores, que pueden llegar a tener otro formato y que van a estar dentro de tu cuerpo, logrando organizar ordenadamente los elementos. 
Si no respondí tu pregunta, por favor escríbeme de nuevo :3 
Y te recomiendo revisar estos ejemplos que mencioné, pueden ser muy útiles :)

**Comment by vicentethomas** [comment]
Hola! Con mi compañero seguimos un poco confundidos con que el cuerpo deba ser un contenedor flex. Nuestro problema es que no entendemos si el body tiene que ser un contenedor flex en sí, o si se refieren a que dentro de body deben haber contenedores flex? Tratamos de hacer que el body entero fuera un contenedor flex pero nos genera problemas a la hora de crear otros contenedores flex dentro del body, por ejemplo el encabezado. 
Gracias!

**Comment by usdonoso** [comment]
La idea es 

> Hola! Con mi compañero seguimos un poco confundidos con que el cuerpo deba ser un contenedor flex. Nuestro problema es que no entendemos si el body tiene que ser un contenedor flex en sí, o si se refieren a que dentro de body deben haber contenedores flex? Tratamos de hacer que el body entero fuera un contenedor flex pero nos genera problemas a la hora de crear otros contenedores flex dentro del body, por ejemplo el encabezado.
> Gracias!

La idea es que el cuerpo sea un contenedor, pero pueden hacerlo incluyendo un contenedor en el cuerpo con la etiqueta "div" para que les quede más claro y no les genere problemas. Aquí les dejo un video de ejemplo, revisen el minuto 5:20. 
https://www.youtube.com/watch?v=Q2imkhmhOFo
