### ISSUE TITLE
Margen parte 2

### ISSUE THREAD

**Issue by clementestreeter** [Exploratorio-DCC-PUC/Syllabus#539]
Hola! En la parte 2 sale que el cuerpo tiene que tener un margen de 3%, ese margen también aplica para el backround color? Osea, nuestra pagina deberia estar bordeada por un margen de 3% blanco, o del color indicado? 
Gracias!!

**Comment by usdonoso** [comment]
> Hola! En la parte 2 sale que el cuerpo tiene que tener un margen de 3%, ese margen también aplica para el backround color? Osea, nuestra pagina deberia estar bordeada por un margen de 3% blanco, o del color indicado?
> Gracias!!

Debería estar bordeada por un margen de 3% del color indicado. :)
