### ISSUE TITLE
Descuento de nota

### ISSUE THREAD

**Issue by sebastianferrer** [Exploratorio-DCC-PUC/Syllabus#54]
Hola, si utilizo una biblioteca distinta a pandas en la pregunta de convertir el tiempo se descuenta nota?

**Comment by diflores** [comment]
Hola:

No hay descuento, pero es esperable que uses `pandas` para realizar operaciones sobre los datos. Por ejemplo, no usar varios `for` para añadir los nuevos datos o transformarlos, sino aprovechar las funciones de `pandas`.

¡Saludos!
