### ISSUE TITLE
Directorio de imagenes

### ISSUE THREAD

**Issue by IgnacioEngelberger** [Exploratorio-DCC-PUC/Syllabus#540]
Tenemos la duda de que en el archivo .md del repositorio dice que debemos usar la carpeta "img" para guardar las imágenes de la página, por otro lado en el pdf donde se encuentran las instrucciones dice que las imágenes deben estar en una carpeta llamada "images". Entonces no sabemos si debemos dejarlas en la carpeta "img", en la carpeta "images" y borrar la "img" o bien dejar la carpeta "images" dentro de la "img."

Porfa ayuda.
Gracias.
Estamos desesperados.
Menos carga academica plz.

**Comment by fernandosmither** [comment]
> Porfa ayuda.
> Gracias.
> Estamos desesperados.
> Menos carga academica plz.
<img src="https://i.kym-cdn.com/entries/icons/original/000/005/393/IKIFEEL.jpg" alt="drawing" width="200"/>

**Comment by usdonoso** [comment]
> Tenemos la duda de que en el archivo .md del repositorio dice que debemos usar la carpeta "img" para guardar las imágenes de la página, por otro lado en el pdf donde se encuentran las instrucciones dice que las imágenes deben estar en una carpeta llamada "images". Entonces no sabemos si debemos dejarlas en la carpeta "img", en la carpeta "images" y borrar la "img" o bien dejar la carpeta "images" dentro de la "img."
> 
> Porfa ayuda.
> Gracias.
> Estamos desesperados.
> Menos carga academica plz.

Dejen el nombre de la carpeta como "images". :)
