### ISSUE TITLE
Órden en gráficos Pregunta 4

### ISSUE THREAD

**Issue by FranGomez03** [Exploratorio-DCC-PUC/Syllabus#541]
Hola, quisiera preguntar si en los gráficos de regresión de la pregunta 4 de la parte 1 hay que elegir el **orden** que mas se asemeje a los puntos de cada año o si no es necesario. A orden me refiero a si es necesario un orden lineal, cuadrático o cubico, o con que pongamos uno solo basta para todos. Gracias de antemano

**Comment by fernandosmither** [comment]
cps
