### ISSUE TITLE
Concurso de memes

### ISSUE THREAD

**Issue by agustinbc7** [Exploratorio-DCC-PUC/Syllabus#542]
Hola, una pregunta sobre esto, ¿Cuántos memes puede subir cada equipo como máximo?

**Comment by usdonoso** [comment]
> Hola, una pregunta sobre esto, ¿Cuántos memes puede subir cada equipo como máximo?

Máximo un meme por equipo. :)

**Comment by agustinbc7** [comment]
Gracias!
