### ISSUE TITLE
Encabezado?

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#543]
Qué es el encabezado?
![image](https://user-images.githubusercontent.com/66154723/115170929-d341bb80-a08f-11eb-9b5a-a52637084c96.png)

Y con título a elección propia se refieren al title del head? o a un h1 al inicio de la página?

**Comment by usdonoso** [comment]
> Qué es el encabezado?
> ![image](https://user-images.githubusercontent.com/66154723/115170929-d341bb80-a08f-11eb-9b5a-a52637084c96.png)
> 
> Y con título a elección propia se refieren al title del head? o a un h1 al inicio de la página?

Con encabezado nos referimos a la zona superior de la página. En los ejemplos del enunciado, el encabezado sería la zona color gris claro, que tiene escrito "Título". Para efectos prácticos, para elaborar un encabezado hay varias formas, pero te recomiendo hacerlo usando header.
Aquí te mando un ejemplo y explicación de la estructura, https://vinkula.com/estructura-del-codigo-html5-anatomia-de-una-pagina-web/ 
:)

**Comment by fernandosmither** [comment]
> > Qué es el encabezado?
> > ![image](https://user-images.githubusercontent.com/66154723/115170929-d341bb80-a08f-11eb-9b5a-a52637084c96.png)
> > Y con título a elección propia se refieren al title del head? o a un h1 al inicio de la página?
> 
> Con encabezado nos referimos a la zona superior de la página. En los ejemplos del enunciado, el encabezado sería la zona color gris claro, que tiene escrito "Título". Para efectos prácticos, para elaborar un encabezado hay varias formas, pero te recomiendo hacerlo usando header.
> Aquí te mando un ejemplo y explicación de la estructura, https://vinkula.com/estructura-del-codigo-html5-anatomia-de-una-pagina-web/
> :)

Sobre el encabezado, este debería ser absoluto como se ve en el ejemplo, o estar dentro del margen de 3% del cuerpo?
![image](https://user-images.githubusercontent.com/66154723/115247791-184c0900-a0f5-11eb-935c-c88817a8faec.png)
(aquí lo de color salmón es nuestro encabezado hasta ahora)

**Comment by usdonoso** [comment]
> > > Qué es el encabezado?
> > > ![image](https://user-images.githubusercontent.com/66154723/115170929-d341bb80-a08f-11eb-9b5a-a52637084c96.png)
> > > Y con título a elección propia se refieren al title del head? o a un h1 al inicio de la página?
> > 
> > 
> > Con encabezado nos referimos a la zona superior de la página. En los ejemplos del enunciado, el encabezado sería la zona color gris claro, que tiene escrito "Título". Para efectos prácticos, para elaborar un encabezado hay varias formas, pero te recomiendo hacerlo usando header.
> > Aquí te mando un ejemplo y explicación de la estructura, https://vinkula.com/estructura-del-codigo-html5-anatomia-de-una-pagina-web/
> > :)
> 
> Sobre el encabezado, este debería ser absoluto como se ve en el ejemplo, o estar dentro del margen de 3% del cuerpo?
> ![image](https://user-images.githubusercontent.com/66154723/115247791-184c0900-a0f5-11eb-935c-c88817a8faec.png)
> (aquí lo de color salmón es nuestro encabezado hasta ahora)

Así como lo tienen está perfecto :)
