### ISSUE TITLE
Contenedor de imagen

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#544]
![image](https://user-images.githubusercontent.com/66154723/115181097-28d49300-a0a5-11eb-8841-44207c7d3aa2.png)
## En caso que sea una div nueva, las imágenes de inicio, aparte de pertenecer al contenedor de inicio, deben también pertenecer a este?

**Comment by usdonoso** [comment]
> ![image](https://user-images.githubusercontent.com/66154723/115181097-28d49300-a0a5-11eb-8841-44207c7d3aa2.png)
> 
> ## Con esto se refieren a .img en general, o a que creemos una clase de div nueva para ese tipo?
> ## En caso que sea una div nueva, las imágenes de inicio, aparte de pertenecer al contenedor de inicio, deben también pertenecer a este?

La idea es crear un contenedor que utilices en todas las imágenes. Esto tiene el objetivo de que las imágenes tengan un formato más estandarizado, como el color de fondo blanco, las medidas y su margen. Entonces, primero creas este contenedor, por ejemplo ".images-container", con todo lo indicado para el formato y luego, al incluir una imagen en tu página le asignas, en su clase, este contenedor. De esta manera, todas las imágenes tendrán la misma clase. 
En el link que está en la tarea, al final de la página, hay unos ejemplos que te podrían ayudar mucho, sobre todo el primero. Puedes revisar el código en html y css para entender lo que hacen al insertar los cuadros del ejemplo. 
Cualquier cosa, pregunta de nuevo :)

**Comment by fernandosmither** [comment]
> > ![image](https://user-images.githubusercontent.com/66154723/115181097-28d49300-a0a5-11eb-8841-44207c7d3aa2.png)
> > ## Con esto se refieren a .img en general, o a que creemos una clase de div nueva para ese tipo?
> > ## En caso que sea una div nueva, las imágenes de inicio, aparte de pertenecer al contenedor de inicio, deben también pertenecer a este?
> 
> La idea es crear un contenedor que utilices en todas las imágenes. Esto tiene el objetivo de que las imágenes tengan un formato más estandarizado, como el color de fondo blanco, las medidas y su margen. Entonces, primero creas este contenedor, por ejemplo ".images-container", con todo lo indicado para el formato y luego, al incluir una imagen en tu página le asignas, en su clase, este contenedor. De esta manera, todas las imágenes tendrán la misma clase.
> En el link que está en la tarea, al final de la página, hay unos ejemplos que te podrían ayudar mucho, sobre todo el primero. Puedes revisar el código en html y css para entender lo que hacen al insertar los cuadros del ejemplo.
> Cualquier cosa, pregunta de nuevo :)

Con los ejemplos te refieres a las screenshots del pdf?
y la otra duda, las 2 imágenes del inicio, que están arriba de los botones, deben solamente estar bajo el contenedor de imágenes inicio, o también de imágenes general?

**Comment by usdonoso** [comment]
> > > ![image](https://user-images.githubusercontent.com/66154723/115181097-28d49300-a0a5-11eb-8841-44207c7d3aa2.png)
> > > ## Con esto se refieren a .img en general, o a que creemos una clase de div nueva para ese tipo?
> > > ## En caso que sea una div nueva, las imágenes de inicio, aparte de pertenecer al contenedor de inicio, deben también pertenecer a este?
> > 
> > 
> > La idea es crear un contenedor que utilices en todas las imágenes. Esto tiene el objetivo de que las imágenes tengan un formato más estandarizado, como el color de fondo blanco, las medidas y su margen. Entonces, primero creas este contenedor, por ejemplo ".images-container", con todo lo indicado para el formato y luego, al incluir una imagen en tu página le asignas, en su clase, este contenedor. De esta manera, todas las imágenes tendrán la misma clase.
> > En el link que está en la tarea, al final de la página, hay unos ejemplos que te podrían ayudar mucho, sobre todo el primero. Puedes revisar el código en html y css para entender lo que hacen al insertar los cuadros del ejemplo.
> > Cualquier cosa, pregunta de nuevo :)
> 
> Con los ejemplos te refieres a las screenshots del pdf?
> y la otra duda, las 2 imágenes del inicio, que están arriba de los botones, deben solamente estar bajo el contenedor de imágenes inicio, o también de imágenes general?

No, me refiero a este link https://css-tricks.com/snippets/css/a-guide-to-flexbox/
Si ingresas, al final, hay unos ejemplos muy buenos :) este link está en el enunciado.
Respecto a tu segunda duda, es exactamente lo que mencionas, las imágenes del inicio deben estar en ambos contenedores, pero, por si acaso, no significa que deban tener dos clases, sino que, por ejemplo, puedes tener una etiqueta div que es un contenedor y que contenga tus imágenes. :3
