### ISSUE TITLE
Diseño de botones

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#546]
Vimos que nuestros botones son muy distintos a los de los ejemplos. Sabemos que no necesariamente deben ser iguales, pero es esto más o menos lo que se pide? o no es así
![image](https://user-images.githubusercontent.com/66154723/115248638-de2f3700-a0f5-11eb-8938-f2a52cdb7ea7.png)

**Comment by fernandosmither** [comment]
> > Vimos que nuestros botones son muy distintos a los de los ejemplos. Sabemos que no necesariamente deben ser iguales, pero es esto más o menos lo que se pide? o no es así
> > ![image](https://user-images.githubusercontent.com/66154723/115248638-de2f3700-a0f5-11eb-8938-f2a52cdb7ea7.png)
> 
> Están bien, pero se ven muy delgados los bordes, estos deben ser de 7px. También, esto es opcional, pueden agregarle un padding para que no queden tan ajustado al texto.

@usdonoso 
Cuando mencionan "Debe tener los bordes redondos con 7px." No se refieren al radio de borde? porque si es así, es lo que tenemos puesto

**Comment by usdonoso** [comment]
> > > Vimos que nuestros botones son muy distintos a los de los ejemplos. Sabemos que no necesariamente deben ser iguales, pero es esto más o menos lo que se pide? o no es así
> > > ![image](https://user-images.githubusercontent.com/66154723/115248638-de2f3700-a0f5-11eb-8938-f2a52cdb7ea7.png)
> > 
> > 
> > Están bien, pero se ven muy delgados los bordes, estos deben ser de 7px. También, esto es opcional, pueden agregarle un padding para que no queden tan ajustado al texto.
> 
> @usdonoso
> Cuando mencionan "Debe tener los bordes redondos con 7px." No se refieren al radio de borde? porque si es así, es lo que tenemos puesto

Perdón la demora. Nos referimos al grosor del borde, no al radio del borde. :) gracias por la duda

**Comment by fernandosmither** [comment]
> > > > Vimos que nuestros botones son muy distintos a los de los ejemplos. Sabemos que no necesariamente deben ser iguales, pero es esto más o menos lo que se pide? o no es así
> > > > ![image](https://user-images.githubusercontent.com/66154723/115248638-de2f3700-a0f5-11eb-8938-f2a52cdb7ea7.png)
> > > 
> > > 
> > > Están bien, pero se ven muy delgados los bordes, estos deben ser de 7px. También, esto es opcional, pueden agregarle un padding para que no queden tan ajustado al texto.
> > 
> > 
> > @usdonoso
> > Cuando mencionan "Debe tener los bordes redondos con 7px." No se refieren al radio de borde? porque si es así, es lo que tenemos puesto
> 
> Perdón la demora. Nos referimos al grosor del borde, no al radio del borde. :) gracias por la duda

@usdonoso 

Esque como decía "Debe tener los bordes redondos con 7px." asumimos que solo era el radio del borde.
Entonces, mantuve el radio de borde de 7px y le añadí un borde de 7px, como mencionaste grosor, supuse que convendría poner un color sólido, y puse el botón y su borde del mismo color para que no se vea feo.
![image](https://user-images.githubusercontent.com/66154723/115484002-eedbcc00-a21f-11eb-936b-e36014dacb93.png)

¿Está bien?

**Comment by usdonoso** [comment]
> > > > > Vimos que nuestros botones son muy distintos a los de los ejemplos. Sabemos que no necesariamente deben ser iguales, pero es esto más o menos lo que se pide? o no es así
> > > > > ![image](https://user-images.githubusercontent.com/66154723/115248638-de2f3700-a0f5-11eb-8938-f2a52cdb7ea7.png)
> > > > 
> > > > 
> > > > Están bien, pero se ven muy delgados los bordes, estos deben ser de 7px. También, esto es opcional, pueden agregarle un padding para que no queden tan ajustado al texto.
> > > 
> > > 
> > > @usdonoso
> > > Cuando mencionan "Debe tener los bordes redondos con 7px." No se refieren al radio de borde? porque si es así, es lo que tenemos puesto
> > 
> > 
> > Perdón la demora. Nos referimos al grosor del borde, no al radio del borde. :) gracias por la duda
> 
> @usdonoso
> 
> Esque como decía "Debe tener los bordes redondos con 7px." asumimos que solo era el radio del borde.
> Entonces, mantuve el radio de borde de 7px y le añadí un borde de 7px, como mencionaste grosor, supuse que convendría poner un color sólido, y puse el botón y su borde del mismo color para que no se vea feo.
> ![image](https://user-images.githubusercontent.com/66154723/115484002-eedbcc00-a21f-11eb-936b-e36014dacb93.png)
> 
> ¿Está bien?

Sí, está perfecto :33
Si, faltó detallar el enunciado, gracias por el feedback :)
