### ISSUE TITLE
[TG1] Librería scipy

### ISSUE THREAD

**Issue by retamalcito** [Exploratorio-DCC-PUC/Syllabus#547]
¡Hola!

¿Podemos usar la librería `scipy` para el desarrollo de la parte 1 de la TG1? ¿O debemos utilizar estrictamente las mencionadas en la *issue* #534?

¡Gracias!

**Comment by usdonoso** [comment]
> ¡Hola!
> 
> ¿Podemos usar la librería `scipy` para el desarrollo de la parte 1 de la TG1? ¿O debemos utilizar estrictamente las mencionadas en la _issue_ #534?
> 
> ¡Gracias!

no hay problema, puedes usar la librería scipy :)
