### ISSUE TITLE
Duda Hardcoding

### ISSUE THREAD

**Issue by cpschulz** [Exploratorio-DCC-PUC/Syllabus#548]
Hola! 
Podrían especificar mas a que se refieren con Hardcoding, porque para la parte de separar los animes por tipo tenemos una variable por tipo de anime con ese nombre (hay una variable para TV, una para Music y asi), y usamos get_group con cada tipo y queríamos hacer lo mismo para separalos por año, pero no sabemos si eso es Hardcoding o no...
Se puede usar eso?

**Comment by IchottMano** [comment]
Hola!

Lo primero que dicen es casi hardcoding, pero no hay problema en ese sentido. Sin embargo, hacer una variable, por ejemplo, para cada año hacer una tabla ya es mas hardcodeado, asi que no está permitido.

Saludos!
