### ISSUE TITLE
Cambio de color del encabezado en modo anime

### ISSUE THREAD

**Issue by FeBalla** [Exploratorio-DCC-PUC/Syllabus#549]
Sé que no es tan importante, pero por si acaso. Cuando se usa el botón para el cambio de modo, ¿es estrictamente obligatorio que el encabezado cambie a un color rojo ("`red`") o puede ser alguna variante tipo burdeo o algo para que no se vea tan chillón?

**Comment by IchottMano** [comment]
Hola!

No hay problema, mientras sea parecido a rojo. Entre mas bonita les quede la pagina mejor!

Saludos!
