### ISSUE TITLE
Clases sistema operativo

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [Exploratorio-DCC-PUC/Syllabus#55]
Hola! cuando van a subir las slides de sistema operativo?

**Comment by aaossa** [comment]
Hola, ya la subí, gracias por avisar! Puedes verla [aqui](https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Clases/Clase08%20-%20Sistemas%20Operativos.pdf)
