### ISSUE TITLE
Uso del logo Last.fm

### ISSUE THREAD

**Issue by amparostevens** [Exploratorio-DCC-PUC/Syllabus#55]
En una de las carpetas del repositorio hay una imagen con el logo de Last.fm, ¿es necesario ponerla en la página web? porque en ninguna parte del pdf de la tarea sale que hay que usarla

**Comment by diflores** [comment]
¡Hola!
En el `README` de sus repositorios sale la razón de que esté esa imagen:

> Logo de LastFM, incluido solo para poder hacer push de esta carpeta del repositorio, donde se espera que almacenes las imágenes de las que no dispones hipervínculo.

Puedes usarla si quieres, pero no es obligatorio.
