### ISSUE TITLE
Comentarios de código

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#551]
Sé que se pide comentar el código para los gráficos, pero esto también es requerido en el html, css y js?

**Comment by IchottMano** [comment]
Hola!

La idea de comentar el código en los gráficos es un poco evitar que simplemente copien y peguen código de internet. Esperamos que ustedes puedan tanto explicar bien qué está haciendo su código como explicar un poco que les dicen los gráficos que se generan, si bien no muy profundamente.

Para la parte 2 de la tarea esto ya no es tan necesario, sin embargo recordar que cualquier código que saquen de internet o de las ayudantías **debe ser debidamente citado**. 

Saludos!
