### ISSUE TITLE
Sobre extensión de archivos

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#553]
## Hola!, se habló harto de la personalización de la web, y como nos gustó la idea le estamos _"echando ganas"_ , sin embargo vamos en la mitad más o menos, y el html ya tiene 158 líneas, el css 75 y el js tiene 134 líneas de código, con lo cual, pregunto si hay una extensión límite de los archivos, o podemos personalizarlos _laissez faire_.

**Comment by fernandosmither** [comment]
Duda afín, sé que como tal no hemos visto ni html, css o javascript en profundidad ni mucho menos,. Por lo mismo, se evaluarán las malas prácticas? y de hacerlo, cuáles se considerarán?

**Comment by IchottMano** [comment]
Hola!

No hay límite en la extensión de archivos. Por lo mismo, aparte de las malas prácticas prohibidas (hardcoding) no nos importan mucho las málas prácticas que puedan tener. La idea de esta tarea es simplemente un acercamiento a estos lenguajes de programación.

Saludos!
