### ISSUE TITLE
Sobre notas

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#555]
![image](https://user-images.githubusercontent.com/66154723/115920277-f67db980-a447-11eb-9d0b-3c07f83de09b.png)
## Qué significan las columnas? Y cuál es la diferencia entre NP y NF?

**Comment by fernandosmither** [comment]
## Also, por qué hay notas sobre 7 en la TC1? y eso significa que se convierte a 7 o esas décimas suman al promedio?

**Comment by IchottMano** [comment]
Hola!

NP se refiere a el promedio que se usa para calcular la eximición, mientras que NF es la nota final del curso. Son bajas porque aún faltan bastantes notas.

Las notas sobre 7 se deben a las bonificaciones que dimos para la tarea, se usan sin modificar para calcular los promedios, la única restricción es que el promedio final no puede ser mayor a 7.

Saludos!
