### ISSUE TITLE
Citaciones

### ISSUE THREAD

**Issue by carmebe** [Exploratorio-DCC-PUC/Syllabus#556]
Hola buenas, tengo una duda con respecto a las fuentes y citaciones, el asunto es que en la TG1 me he fijado tanto en que quedasen bien explicado los comandos y gráficos en el jupyter notebook que se me olvidó citar las APIs de las librerias usadas, esto conlleva algún descuento? O se infiere que al usar las librerías se tiene que se ha investigado de ellas en sus propias páginas web? Es solamente eso, ya que si cité las fuentes de los comandos para la parte de crear el sitio web.

Saludos

**Comment by usdonoso** [comment]
> Hola buenas, tengo una duda con respecto a las fuentes y citaciones, el asunto es que en la TG1 me he fijado tanto en que quedasen bien explicado los comandos y gráficos en el jupyter notebook que se me olvidó citar las APIs de las librerias usadas, esto conlleva algún descuento? O se infiere que al usar las librerías se tiene que se ha investigado de ellas en sus propias páginas web? Es solamente eso, ya que si cité las fuentes de los comandos para la parte de crear el sitio web.
> 
> Saludos

Perdón la demora. No, no implica un descuento, no te preocupes :3
Saludos, Uranía.

**Comment by carmebe** [comment]
Ya, muchas gracias!
