### ISSUE TITLE
Diagrama e/r

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#557]
Hola, para la confección del diagrama se puede empezar de cero? Es decir puedo no usar la base que me dan y hacerlo de otra manera (siempre manteniendo las reglas de un diagrama e/r) ?

**Comment by ValentinaAlvarezG** [comment]
Hola, puedes empezar de cero si quieres, pero la verdad no sé porque habrías de querer hacerlo. Queda bajo tu responsabilidad que el diagrama te vaya a quedar bien modelado.

**Comment by clolate** [comment]
Hola, el diagrama que les entregamos contiene lo mínimo que les pedimos de normalización para este problema, Dadas esas entidades se evaluan las relaciones, atributos y cardinalidades que se piden en la tarea. Como dice Valentina, hacerlo de otra forma arriesga que haya un descuento porque te van a faltar cosas.
