### ISSUE TITLE
Fecha I1?

### ISSUE THREAD

**Issue by naquiroz** [Exploratorio-DCC-PUC/Syllabus#56]
Hola, solo una pequeña duda, porque la prueba es el viernes si en la Clase3 sale que es el 12 de abril?

**Comment by aaossa** [comment]
La fecha oficial es el viernes, tal como aparece en buscacursos (que contiene las fechas oficiales asignadas) y tal como se avisó hace 5 días en el aviso a través del Sidnig. Perdón por la confusión, la imagen tiene mala la fecha 😢
