### ISSUE TITLE
Orden de los graficos en css

### ISSUE THREAD

**Issue by Iawinter** [Exploratorio-DCC-PUC/Syllabus#56]
Cuando elijo la posición de cada gráfico con css, el orden tiene que ser exactamente el de la imagen o puede ser uno distinto, mientras cumpla con la figura pedida.
Por ejemplo: Grafico 1 tiene que ser el gráfico de las 10 canciones más escuchadas, el 2 el gráfico de los géneros musicales más escuchados, etc. O puedo yo elegir cual es el 1 y así.

![image](https://user-images.githubusercontent.com/48302727/63990217-3349af80-cab1-11e9-9d4f-9a90b071d3de.png)

**Comment by malopez16** [comment]
Hola!
Los gráficos se deben poner en el orden en el que están enumerados en el enunciado, tal como aparece en esta sección:

![image](https://user-images.githubusercontent.com/26126519/64020343-5b5fff80-caff-11e9-8146-ef5a0f444ef0.png)

saludos!
