### ISSUE TITLE
TC2 draw.io access denied 

### ISSUE THREAD

**Issue by NicoJGutierrez** [Exploratorio-DCC-PUC/Syllabus#561]
Si lo pillo por el github dice:
![image](https://user-images.githubusercontent.com/80768621/116482468-359a7900-a853-11eb-9dc9-013f334c0998.png)

Si lo pillo por mi dispositivo dice:
![image](https://user-images.githubusercontent.com/80768621/116482420-1ef42200-a853-11eb-9228-d5a74423c47f.png)

Si reintento como loco dice:
https://www.youtube.com/watch?v=hq_ivuq4PvM 

Me pasa por clonar el repositorio a mi computador sin pensar o por usar opera o por mi nombre tener muchos tildes o porque mi cordura acaba de llegar al overflow negativo o porque en realidad esta es mi forma de participar en el concurso de memes aún si no logro siquiera empezar la tarea?

**Comment by NicoJGutierrez** [comment]
Descartado opera de la lista de posibles culpables:
![image](https://user-images.githubusercontent.com/80768621/116483323-d89fc280-a854-11eb-84cc-535149df9f00.png)

**Comment by ValentinaAlvarezG** [comment]
Hola! como lo  estás intentando abrir?

**Comment by NicoJGutierrez** [comment]
https://sqliteonline.com parece que tampoco me deja cargar archivos .db a mi computador de momento, espero poder arreglarlo de alguna forma

**Comment by NicoJGutierrez** [comment]
> Hola! como lo estás intentando abrir?

![image](https://user-images.githubusercontent.com/80768621/116483692-93c85b80-a855-11eb-95e5-b726c0bad87a.png)
(click en github)
![image](https://user-images.githubusercontent.com/80768621/116483708-9cb92d00-a855-11eb-87c6-0c7c0f82e26f.png)
(click en open existing diagram)
![image](https://user-images.githubusercontent.com/80768621/116483764-b65a7480-a855-11eb-92fb-7d07ea026982.png)
(click en authorize, se abre una ventana emergente a github, que se cierra luego de un inicio de sesión)
![image](https://user-images.githubusercontent.com/80768621/116483803-cc683500-a855-11eb-9208-4ca7f86b5547.png)

**Comment by ValentinaAlvarezG** [comment]
Ah, es que a ver, en  https://sqliteonline.com  tu solo subes el .db, para abrir el drawio tienes que meterte a https://app.diagrams.net/ --> open existing diagram --> upload --> arrastras tu draw io base que te pasamos.

**Comment by NicoJGutierrez** [comment]
![image](https://user-images.githubusercontent.com/80768621/116483888-ff122d80-a855-11eb-9b4c-6e714d27c2bd.png)
(click en file)
![image](https://user-images.githubusercontent.com/80768621/116483918-09ccc280-a856-11eb-9ab6-a2508da6a93f.png)
(click en open .db)
![image](https://user-images.githubusercontent.com/80768621/116483960-20731980-a856-11eb-94da-41e2322aacc3.png)
(click en tc2.db)
![image](https://user-images.githubusercontent.com/80768621/116484011-37b20700-a856-11eb-97d6-242b1ed13cc5.png)
(no pasa absolutamente nada)

**Comment by ValentinaAlvarezG** [comment]
Pero ahí se abrió, en el FROM van las tablas,  no el nombre de la base de datos, deberías hacer algo como 
```sql 
SELECT * FROM  Artistas
```

**Comment by NicoJGutierrez** [comment]
eso funciona, vuelvo a trabajar

**Comment by NicoJGutierrez** [comment]
Todavía no he solucionado el problema de los diagramas tho

**Comment by ValentinaAlvarezG** [comment]
Tienes clonado el repo? onda tienes el drawio local?  para que lo hagas como te indiqué, onda https://app.diagrams.net/ --> open existing diagram --> upload --> arrastras tu draw io base que te pasamos.

**Comment by NicoJGutierrez** [comment]
Cuando coloco open existing diagram dice:
![image](https://user-images.githubusercontent.com/80768621/116488635-d479a200-a860-11eb-8b2f-d17171c100fd.png)

**Comment by ValentinaAlvarezG** [comment]
Iniciaste sesión o algo así?

**Comment by NicoJGutierrez** [comment]
Si, inicié sesión con github

**Comment by clolate** [comment]
Si abres el diagrama en una pestaña de incognito, sin iniciar sesion en nada, deberias poder modificarlo sin problemas.

Los repositorios que usan son creados por github classroom que pueden ver y modificar, pero no son de uds por tanto no pueden darles permisos y por eso sale access denied.

**Comment by NicoJGutierrez** [comment]
Me funciona usar el programa, pero cuando intento guardar los cambios me sale
![image](https://user-images.githubusercontent.com/80768621/116791431-50a1fe80-aa88-11eb-9852-0b97289ab6c7.png)

**Comment by clolate** [comment]
Sigues teniendo probolemas con esto? porque la pagina va guardando automaticamente los cambios cada cierto tiempo. Si quieres ir guardando tus cambios respaldados en una plataforma puedes hacerlo con la opcion `Save as` y seleccionas `XML .drawio` y te recomiendo guardarlo local por los permisos, aunque drive no deberia tener ningun problema.
