### ISSUE TITLE
Diagramas E/R TC2

### ISSUE THREAD

**Issue by clementestreeter** [Exploratorio-DCC-PUC/Syllabus#562]
Hola! Una pregunta de los diagramas E/R. Pueden ser un "ciclo"? Me refiero puede la entidad 1 estar relacionada con la 2, la 2 con la 3 y la 3 con la 1?

**Comment by ValentinaAlvarezG** [comment]
Si! no hay problema, mientras se relacionen entre ellas con las relaciones correctas todo bien.

**Comment by clementestreeter** [comment]
Gracias!
