### ISSUE TITLE
i1, descripción del experimento

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#564]
### ¿Qué tanta profundidad se espera en la pregunta de descripción del experimento? Un _overview_ general del procedimiento, o detallar sobre intervalos de tiempo, dataset de contenido, etc? (no describo más para no soplarla)

**Comment by amaiajuanchuto** [comment]
Hola!

Con tal de que se entiendan los diferentes pasos del experimento y se indique que datos se usaron como estímulo para el estudio con usuarios no deberías tener problemas. La idea no es que sea tan detallado, sino que sepamos que entendiste el experimento y su procedimiento. 

Mucha suerte 😄
