### ISSUE TITLE
I1, Parte 3, Pregunta 2

### ISSUE THREAD

**Issue by cpschulz** [Exploratorio-DCC-PUC/Syllabus#565]
La pregunta pide compara con el flujo de una app de delivery, a esto se refiere con todo el proceso que ocurre hasta que llega la informacion para que comiencen a preparar el pedido o hasta que se entrega el pedido al cliente o se confirma la recepción el la cocina o hasta donde?

**Comment by clolate** [comment]
Continua la analogia hasta que completes el flujo completo de una instrucción en una computadora
