### ISSUE TITLE
Pregunta 4.3 Javascript

### ISSUE THREAD

**Issue by SCarcG1** [Exploratorio-DCC-PUC/Syllabus#566]
En esta pregunta solamente tiene que cambiar el texto y quedarse todo el tiempo en el texto modificado, o cuando quitemos el mouse tiene que volver al anterior?

**Comment by clolate** [comment]
El profe comentó en el horario de consulta que da lo mismo si lo devulves al texto anterior, basta con que al pasar el mouse se cambie
