### ISSUE TITLE
Parte 3.2 Duda arquitectura

### ISSUE THREAD

**Issue by SCarcG1** [Exploratorio-DCC-PUC/Syllabus#568]
En esta pregunta, tomamos en cuenta que se dio por ejemplo el primer paso y seguimos con el siguiente de inmediato, o tenemos que volver a hacer una analogía del primer paso?

**Comment by mimadri** [comment]
Hola! 
No es necesario volver a hacer una analogía del primer paso, debes considerar el que se entrega en el enunciado.
Suerte con la prueba :)
