### ISSUE TITLE
Spotipy

### ISSUE THREAD

**Issue by fthurtado** [Exploratorio-DCC-PUC/Syllabus#57]
Hola!
Primero que nada, nuestra recomendación es que dejes la parte de Spotify para el final. Puede que demores y sólo son 5 décimas.

En cuanto a tu problema, efectivamente requiere credenciales. Un tutorial que a mí me sirvió fue [este](https://sotiriskakanos.com/2017/08/05/using-spotifys-web-api-with-python/ ) para autentificarme con la API. 

También veremos una aproximación a la API durante la siguiente ayudantía.
Saludos!

_Originally posted by @malopez16 in https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/37#issuecomment-523893770_

Copie el código de esta página, usando mi cuenta de spotify pero siempre me devuelve este error
SpotifyOauthError: Bad Request
También he probado con otros códigos que he encontrado y me aparece lo mismo.
¿Por qué puede ser?

**Comment by malopez16** [comment]
Hola,
Podrías probar con lo que dice este link: https://stackoverflow.com/a/49372790
Pero lo más seguro es que sea un problema de las ID que estás usando en sí. 
Probaste creando una app nueva?

Busqué para ver el código y no encontré ningún commit. Avísame y le doy una mirada para ver si encunentro algo raro. Igual, debería funcionar con el link de #37 y con la info de la ayudantía. Lo probé hoy mismo.

**Comment by fthurtado** [comment]
Ya la subi, mis pruebas de spotipy están al final del archivo parte 1.
Voy a revisar el código y la ayudantía.

**Comment by fthurtado** [comment]
Ya copie el código de la ayudantía exacto, y me sigue apareciendo el mismo error.

**Comment by malopez16** [comment]
Estás usando la red de la universidad?

**Comment by fthurtado** [comment]
No, la de mi casa

**Comment by malopez16** [comment]
El problema es el client_id y el client_secret. Están incorrectos. En la ayudantía está como obtenerlos y cuales son, paso a paso :)

**Comment by fthurtado** [comment]
Peerfect!!
Muchas gracias!
