### ISSUE TITLE
Pregunta 3 Parte 3

### ISSUE THREAD

**Issue by fabarcad** [Exploratorio-DCC-PUC/Syllabus#570]
Hola! Para la parte 3 es necesario dibujar las visualizaciones de datos a través de un programa específico? Se podría hacer estos dibujos a mano?
Gracias de antemano

**Comment by mimadri** [comment]
Hola!

Puedes realizar los dibujos a mano, no es necesario usar algún programa específico

Éxito en la prueba :)
