### ISSUE TITLE
[I1] Pregunta 1.2 (Features)

### ISSUE THREAD

**Issue by FeBalla** [Exploratorio-DCC-PUC/Syllabus#571]
Para cuando se piden las _features_, ¿basta con solo enumerarlas o hay que describir cada una de ellas?

**Comment by AstridESMJ** [comment]
Hola!

Solo se pregunta cuáles son las features que se utilizaron, deben describirlas también. (corección)

Éxito en la I1!

Saludos,

Astrid,
Ayudante

**Comment by AstridESMJ** [comment]
Por favor, leer corrección del comentario!
