### ISSUE TITLE
Parte 4, pregunta 3 I1 

### ISSUE THREAD

**Issue by oretmj** [Exploratorio-DCC-PUC/Syllabus#572]
Hola, en esta parte no podria cambiar el "onclick" por un "onmouseover"? Esto por que me piden que sea cuando pase el mouse por encima y no cuando haga click.

**Comment by clolate** [comment]
![imagen](https://user-images.githubusercontent.com/37159005/116606498-d09c5d00-a8fe-11eb-9b0a-4d2bbd1c43bc.png)

**Comment by oretmj** [comment]
Ok, asumo que si se puede entonces. Gracias
