### ISSUE TITLE
Extensión de hora de entrega

### ISSUE THREAD

**Issue by fcontardo** [Exploratorio-DCC-PUC/Syllabus#576]
Hola, a mí y a algunos compañeros nos está complicando la hora de entrega ya que hemos tenido clases durante el día y salió más larga la actividad de lo que pensamos, hay posibilidad de alargar la hora de entrega algunas horas más?

**Comment by nataliasuarez99** [comment]
**porfavorrrrr!!!!! :(**

**Comment by cpschulz** [comment]
AYUDA :'(

**Comment by bifernandez** [comment]
Hola! Me sumo a la petición de mi compañera. Personalmente estuve toda la mañana en clases y durante la tarde trabajé interrumpidamente, y creo que aun así no alcanzaré :(

**Comment by m5b6** [comment]
Nos serviría muchísimo que se extendiera el plazo !!

**Comment by MaxiNavia** [comment]
Por favor dennos más tiempo para entregar :(((

**Comment by IgnacioEngelberger** [comment]
Me adhiero :c

**Comment by Bastian-Fuenzalida** [comment]
Me sumo

**Comment by mgarridoch** [comment]
Por favor, es mas que necesario D:

**Comment by mhassangodoy** [comment]
Me sumo también, me falta tiempo para las últimas 2 partes :( (Adjunto al gato meperdonas para rellenar)
![image](https://user-images.githubusercontent.com/80768643/116628100-67c3dd80-a91c-11eb-8fe9-233c2600da7e.png)

**Comment by felipegarcia98** [comment]
Con calma, la petición esta siendo tramitada

**Comment by felipegarcia98** [comment]
La tramitación ha sido un éxito: La prueba se extiende hasta las 21:59 de manera extraordinaria

![AHHH](https://www.piensospascasioroman.com/wp-content/uploads/2021/01/7a97dc838a9c8d0f45415e74fe51547e.jpg)

## Las consultas se responderán hasta las 20:59 hrs, así que aprovechen de hacerlas ahora

**Comment by fcontardo** [comment]
Muchas gracias!

**Comment by Bastian-Fuenzalida** [comment]
Agradecido <3
