### ISSUE TITLE
[I1] Diferencia absoluta o normal en pregunta 3.1?

### ISSUE THREAD

**Issue by FeBalla** [Exploratorio-DCC-PUC/Syllabus#578]
Hola! quería saber si la diferencia entre el día del mes en que nací con la cantidad de comentarios debe ser una diferencia en valor absoluto o se permiten valores negativos. Gracias!

**Comment by felipegarcia98** [comment]
buenas o/ para la diferencia es más correcto expresarla como valor absoluto

[EDIT: Me corrijo, para este caso solo se evaluara com una resta, sin considerar el valor absoluto]
