### ISSUE TITLE
Duda 'formato' parte 1 tarea chica 2

### ISSUE THREAD

**Issue by Panckx** [Exploratorio-DCC-PUC/Syllabus#58]
Hola! Para la parte 1 de la tarea chica 2, en el README debo agregar solamente código SQL o, por ejemplo, debería agregar el código usado en python así:

``
conn.execute('SELECT * FROM table')
``

Se entiende la duda? Mi otra pregunta es, se espera que toda la información sea manejada a través de SQL o está bien extraer cierta información de la base de datos y limpiarla usando python?
Muchas gracias de antemano!

**Comment by fvr1** [comment]
Hola!
Tiene que ser solo el comando SQL, en tu ejemplo sería el `SELECT * FROM table`. 
Sobre la segunda duda, debes poner el resultado exacto de lo que te retorne SQL. No tienes que usar python.
