### ISSUE TITLE
cantidad de conciertos por recinto

### ISSUE THREAD

**Issue by Juancagp** [Exploratorio-DCC-PUC/Syllabus#580]
hola, tenemos que asumir que en un recinto solo puede haber un concierto a la vez verdad?

**Comment by Juancagp** [comment]
y además, el concierto es solo de UN cantante?, o tendría que asumirlo y escribirlo en el readme

**Comment by clolate** [comment]
Puedes hacer todos los supuestos que estimes conveniente, siempre y cuando no contradigan el enunciado, y debes ponerlos en tu readme
