### ISSUE TITLE
Diagrama E/R a PDF

### ISSUE THREAD

**Issue by agustinbc7** [Exploratorio-DCC-PUC/Syllabus#581]
Hola, ¿Cómo se puede convertir bien el diagrama a pdf? Lo he intentado pero se corre todo.

**Comment by ValentinaAlvarezG** [comment]
Hola!  La forma de exportarlo es  en exportar es File --> Export as --> PDF. No sé si viste la ayudantía pero al final expliqué un poco como usar draw io, tienes que tratar que te quede todo en el límite de la línea punteada por que todo eso es una página, entonces si te pasas se hacer en otra página. No sé si ese es tu problema. Dejo una foto por si te sirve:

![image](https://user-images.githubusercontent.com/26123660/116799733-e198ca00-aac8-11eb-9c2b-310d4fb22d73.png)

Lo que dejé dentro del marco morado/rosado es una página que puede pensar como página de pdf, entonces el cuadrado amarillo si te das cuenta se sale, está después de la línea punteada, entonces eso te va a quedar en otra página del pdf. Entonces para que te quede todo junto tienes que tratar de que todos elementos te queden dentro de una misma página

**Comment by agustinbc7** [comment]
Ahí lo pude solucionar, ese era el problema, muchas gracias!
