### ISSUE TITLE
Consultas SQL TC2

### ISSUE THREAD

**Issue by cpschulz** [Exploratorio-DCC-PUC/Syllabus#583]
Hola! Para la parte de consultas en SQL tenemos que mostrar SOLO lo que nos piden? Por ejemplo para la 1 nos piden el nombre de las canciones de J Balvin, ahi SOLO se debe ver los nombres de las conciones o tambienpueden ir otros atributos?

**Comment by ValentinaAlvarezG** [comment]
Hola! pueden ir otros atributos, mientras esté como mínimo lo que se pide en el enunciado.
