### ISSUE TITLE
Consulta 5 SQL TC2

### ISSUE THREAD

**Issue by ignacio-quera** [Exploratorio-DCC-PUC/Syllabus#585]
Hola! Tengo una duda con la última consulta del apartado SQL de la tarea. Cuando nos piden el promedio por país para los números de reproducciones de las canciones de Shakira por país, como lo hacemos si es que los países solamente tienen un valor para el n de reproducciones?

**Comment by ValentinaAlvarezG** [comment]
Hola! claro, los países tienen un solo valor para n de reproducciones, pero ojo que tienes que hacer es tomar las canciones de shakira que se escuchan en cierto país, y a esas sacarle el promedio de streams, luego tomas las canciones de shakira que se escuchan en otro país y sacas el promedio de streams, y así para todos los países, cachai? (obviamente no lo haces país por país de forma manual, ahí tienes que cachar cual es la forma para hacerlo por país :eyes: )

**Comment by ignacio-quera** [comment]
Gracias por la respuesta! Es posible que lo este haciendo mal, pero al agrupar por pais y luego por artista, me sale que Shakira solamente tiene una canción por país (Chantaje). Si ese es el caso, no entiendo de que tengo que sacar promedio

**Comment by ValentinaAlvarezG** [comment]
Mmmm ya es que no sé si te puedo decir mucho más, pero no deberías agrupar por artista :eyes:  ponle ojo a las condiciones que estás poniendo en el WHERE no más :eyes:

**Comment by ValentinaAlvarezG** [comment]
Puede ser que en el país se escuche solo una canción, pero es por como quedaron los datos no más, piensa que tu consulta tiene que ser válida para cualquier set de datos que te entregue. Al final el .db que les pasamos es para que igual puedan ir probando cosas no más.
