### ISSUE TITLE
Consulta 5 SQL

### ISSUE THREAD

**Issue by SebaMartinezM** [Exploratorio-DCC-PUC/Syllabus#587]
Hola, no entendí muy bien si es que hay que sacar en cada país el promedio de reproducciones por canción de Shakira o el promedio de reproducciones total de cada país (incluye todas las canciones de Shakira escuchadas en un país).

**Comment by ValentinaAlvarezG** [comment]
Hola! la segunda opción. La idea es que tengas las canciones que se escuchan que sean de shakira, luego por país tomas el promedio de reproducciones. Espero ahí se entienda mejor.

**Comment by SebaMartinezM** [comment]
Gracias!
