### ISSUE TITLE
TC2 - Parte 1 - Relaciones y Cardinalidad

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [Exploratorio-DCC-PUC/Syllabus#589]
En la parte 1 de la tarea, cuando nos dicen que los artistas realizan conciertos, se entiende que un concierto puede tener a solamente un artista, o en un concierto pueden haber varios artistas a la vez (asi como un evento tipo Lollapalooza)?

Se entiende que un artista se considera tanto como un solista como un grupo musical

**Comment by ElTioAndresCabezas** [comment]
Respecto a esta pregunta, me pregunto lo mismo relacionando artistas con sus canciones

**Comment by clolate** [comment]
Cómo el enunciado no dice específicamente que pasa con los festivales, es tarea tuya elegir un modelo y justificar tus decisiones.
Y no entendí lo de las canciones.

Mientras se mantengan las especificaciones del enunciado pueden agregar todos los supuestos necesarios que estimen conveniente, no sé está forzando a asumir nada, justifiquen sus decisiones!

**Comment by ElTioAndresCabezas** [comment]
Con lo de las canciones, me refiero a que una canción puede contar con la participación de varios artistas. Es correcto asumir esto para la tarea? (al igual que antes, el enunciado no dice nada al respecto)
Considerando lo que me dijiste anteriormente, lo añadi a los supuestos de la tarea
