### ISSUE TITLE
problema jupyter

### ISSUE THREAD

**Issue by jerrazuriz99** [Exploratorio-DCC-PUC/Syllabus#59]
hola!! tengo un problema con jupyter, antes las fechas se cambiaban bien, pero no se por que ahora solo se cambia el primer numero del unix..
que puedo hacer?

**Comment by diflores** [comment]
¡Hola!

Eso no parece un problema de jupyter, sino de tu código. Revisa que estés aplicando el método a toda la columna.

¡Saludos!
