### ISSUE TITLE
Escribir resultado

### ISSUE THREAD

**Issue by danustilovsky** [Exploratorio-DCC-PUC/Syllabus#59]
Hola,
Dado que el resultado es una tabla, se debe poner una imagen o una tabla con los resultados, y si es una tabla debe estar con ese formato o puede esta como csv?
ej: xxxx,xx,xxx,xxxx
Gracias

**Comment by fvr1** [comment]
Hola,

Queda a tu elección. El objetivo es mostrar el comando usado y los resultados. Está bien si simplemente copias y pegas lo que aparece SQL en el README.

¡Saludos!
