### ISSUE TITLE
Clase Machine learning I y II

### ISSUE THREAD

**Issue by bhenriquezsoto** [Exploratorio-DCC-PUC/Syllabus#590]
Buenas noches, espero se encuentren bien. Quería dar aviso de que ambas clases, la clase de machine learning I y II corresponden a la que en realidad sería machine learning II. Dicho de otra forma, la última clase está repetida dos veces en canvas, por lo que faltaría la clase del martes 04 de mayo. 

Muchas gracias por leer :)

**Comment by clolate** [comment]
Hola, gracias por avisar. Ya avisé al equipo para que se solucione 👍
