### ISSUE TITLE
TC2 - Parte 2 - Consultas para obtener informacion previa

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [Exploratorio-DCC-PUC/Syllabus#591]
Si en la parte 2, para realizar una consulta SQL, necesito saber antes un dato de la base de datos, puedo realizar una consulta SQL totalmente aparte a la que se pide en la tarea (Ej.: Para obtener el aid de un artista en especifico)

Se asume que debo añadir en el informe que consulta hice para obtener cierta información.

Saludos y gracias de antemano :D

**Comment by ValentinaAlvarezG** [comment]
Hola! la idea es que cada una sea una propia consulta, que además debería ser válida para otra instancia de la base de datos así que no es válido lo que planteas de por ejemplo buscar el aid y ponerlo en la consulta. Probablemente deberías repasar el concepto de join si es que no se te ocurre como hacerlas sin algo como lo que planteas.

**Comment by ElTioAndresCabezas** [comment]
Ok. Gracias!
