### ISSUE TITLE
Se puede Definir si sacar datos mediante calculo usando pandas?

### ISSUE THREAD

**Issue by Juancagp** [Exploratorio-DCC-PUC/Syllabus#598]
holaa, Despues de definir las caracteristicas que dejaremos en el dataframe mediante comentario y gráficos (por lo menos 3 graficos) puedo en algun dato (ejemplo: wifi, 4g,3g) definir si lo mantendre  o no en el data mediante comentario y Calculo usando Pnadas?

**Comment by felipegarcia98** [comment]
Holaaaa o/, perdona, pero no entendí a qué te refieres ;__; podrías reformular la pregunta?

**Comment by Juancagp** [comment]
es k en la parte 1 de la tarea, hay que primero definir que columnas no nos sirven, para eliminarlas asi del dataframe. Esto siendo como respaldado mediante graficos y analisis de los datos en el grafico  (el por qué consideramos "x" caracteristica como inncesearía), pero tambien dice que por lo menos deben ser 3 graficos, entonces mi pregunta es: si es que ya tenemos los graficos necesarios, y hay alguna caracteristica que no podamos definir si es necesaria o no mediante graficos (sorry lo repetitivo jaja), podemos tratar de definirla (innecesaria o no) mediante analisis de datos de pandas? (onda porcentajes y eso)

ademas otra pregunta jaja, si dejo alguna columna que se define mediante valores 0 y 1 en el dataframe final (3g, 4g, wifi) , en la parte de eliminar valores nulos cómo le podría hacer? (yo creo que debería como imputar algun valor distinto en las casillas con 0 no?, porque no creo que sería factible eliminar todas las columnas de ese tipo si es que ya considere que son importantes para la caracterización.

sorry lo largo y graciasss

**Comment by felipegarcia98** [comment]
ya, creo que te entendí. 
Para la primera pregunta: Lo que necesitamos (y queremos) es que justifiquen toda decisión que hagan, lo cual incluye aquellas donde estipulen que es apropiado eliminar alguna feature. Para poder argumentar bien, y de manera correcta, es necesario que se establezcan razones y evidencias que las sustenten, para lo cual pueden ser de ayuda los gráficos (por eso también exigimos que hagan algunos). Además, estos no son la única manera de justificar algo, por lo que es sensato y necesario que empleen otras maneras de analizar los datos. 

OJO que no es tan binaria la situación. Una feature puede ser necesaria, puede no serlo o puede que no se sepa y, tal vez, ni pueda saberse hasta ya usados los datos. 

Para la segunda pregunta: Recuerda que el valor `0` no es nulo, aunque para fines de algunos lenguajes, como python, puede ser un boolean falso o un valor blanco (vacío). En general, los lenguajes de programación incluyen valores como `None`, `NaN`, `null`, `nil`, etc, que representan valores nulos y que representan la verdadera ausencia del dato.  Los casos que mencionas son de columnas, donde el 0 representa que el dispositivo no tiene ese atributo (recomiendo leer la sección **Set de Datos** del [enunciado de la Tarea](https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Tareas/TG2/TG2_IIC1005_2021_1.pdf).

OJO que la ausencia de un dato puede tener significado por si misma y eso es algo que uno también debe reflexionar. Las ausencias pueden ser simple y fortuitas fallas de la base de datos y recolección de información, pueden suceder a causa de un cambio en la manera de recolectar datos, pueden ser porque en determinados casos es inevitable tener nulos dadas las condiciones del sistema (en mecánica cuántica y por ppio. de indeterminación, no tendría sentido que, dada una observación, se tenga tanto el valor de la posición como del momentum. Uno de ellos debe ser nulo y no correspondería eliminar esas muestras o rellenarlas así como así)
