### ISSUE TITLE
Duda subir archivo .csv a Google Colab

### ISSUE THREAD

**Issue by TomasOlivaresR** [Exploratorio-DCC-PUC/Syllabus#599]
Hola!
Con mi pareja tenemos una duda acerca de cómo subir el archivo "celulares.csv" a Google Colab. No sabemos si al cargar el archivo desde nuestro computador el ayudante corrector podrá acceder a él para que al correr el código completo, siga funcionando.

**Comment by felipegarcia98** [comment]
Hola o/ 
en la issue #77 se puede ver el método ideal, que es referenciar al link del raw en github. Para ello, subire el archivo csv aquí, en el repo público, que creo que evitará problemas de credenciales para el acceso a la info. Si no, igualmente no te preocupes tanto, que igual podemos cambiar la forma de cargar el dataset al revisar
