### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by clolate** [Exploratorio-DCC-PUC/Syllabus#60]
Hola, iba a descargar sqlite ahora (para la ayudantia de mñn) y me entraron dudas de si realmente estaba descargando lo que correspondia,
de esta pagina:  https://www.sqlite.org/download.html
hay varias cosas como: Source Code, Documentation, Precompiled Binaries for ---, blabla...
 en mi caso que tengo windows, 

![image](https://user-images.githubusercontent.com/37159005/38905558-dbdf870e-4287-11e8-857b-c14be9331e1f.png)

hay que descargar el dll y los tools? o solo el dll o solo los tools o ninguno de esos y es otra cosa?

**Comment by figarrido** [comment]
Hola, te recomiendo seguir [esta guía](http://www.sqlitetutorial.net/download-install-sqlite/) para que no tengas problemas con la instalación. En esta se menciona descargar la tercera opción que muestras.

> Para la tarea no es necesario que instales la GUI de SQLite
