### ISSUE TITLE
Gráficos "pauta"

### ISSUE THREAD

**Issue by diflores** [Exploratorio-DCC-PUC/Syllabus#60]
¡Hola a todos!

Estos son mis gráficos de la tarea, para que puedan comparar con los que están obteniendo:

![top10](https://user-images.githubusercontent.com/8507302/64070330-69ab3a00-cc2b-11e9-8a6d-36529b154222.png)
![generos](https://user-images.githubusercontent.com/8507302/64070331-6a43d080-cc2b-11e9-8ed1-b025072f453e.png)
![evolucion](https://user-images.githubusercontent.com/8507302/64070332-6a43d080-cc2b-11e9-9d44-932d320e1056.png)
![semana](https://user-images.githubusercontent.com/8507302/64070333-6a43d080-cc2b-11e9-9da3-eafbf845409b.png)
![hora](https://user-images.githubusercontent.com/8507302/64070335-6a43d080-cc2b-11e9-81b2-861a4d86cc8b.png)

Es importante destacar que estoy bastante segura de las fechas, pues los datos de los `DataFrames` que fui construyendo calzan con lo que dice [mi cuenta de LastFM](https://www.last.fm/user/grandaniela/library?from=2017-01-01&to=2018-03-21) (~sí, los datos son míos 🤣~).

¡Ojalá esto les sirva! Y si no les salen los mismos gráficos, no desesperen. Como Chile se mueve entre dos husos horarios y aparentemente mis datos están en ambos husos (gracias a los estudiantes que me hicieron notar eso), **se aceptarán como correctos datos en GMT-4 y GTM-3**.

¡Saludos y éxito!

**Comment by dvaldesl** [comment]
Hola! en la pauta con respecto al gráfico de las canciones mas escuchadas según día de la semana dice que debe ser en los días lunes, martes, miércoles, jueves y viernes (sin contar fin de semana), distinto al gráfico que muestras donde sí tomas en cuenta sábado y domingo. ¿nos guiamos por la pauta en este caso?

**Comment by diflores** [comment]
¡Hola!
Considerando que se puede prestar para confusión y que ya es tarde para actualizar el enunciado, se aceptarán gráficos con "días hábiles" y también con los días de toda la semana.
¡Saludos!
