### ISSUE TITLE
Forma de trabajar

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#600]
Hola, con mi compañera teníamos la duda si se puede hacer el proceso para predecir el price_range y el int_memory de manera separada. En este sentido, para cada variable a predecir generar una tabla individual donde podamos procesar los datos de acuerdo a las necesidades de cada variable y después hacer los procesos siguientes también por separado. Es decir, al hacer dos tablas por separado no significaría que las columnas que usemos, después de eliminar las que no nos sirven, sean las mismas.
Por ejemplo, podría ser que en price_range eliminemos una columna que sirva para int_memory.

**Comment by felipegarcia98** [comment]
Comprendo. De que pueden, pueden, pero siento que podrían estar complicándose más de la cuenta. De hecho, dado que para clasificar por price_range la int_memory es feature, se deduce que la tabla debe ser diferente para el regresor que trabaja por int_memory (no estaría bien que le des como feature aquello que intentas predecir sjsjsjs)
