### ISSUE TITLE
Utilizacion de graficos y comentarios

### ISSUE THREAD

**Issue by bhenriquezsoto** [Exploratorio-DCC-PUC/Syllabus#601]
Hola, espero se encuentren bien :).
Queria saber, se toman como graficos diferentes si por ejemplo utilizamos histplot de seaborn y un grafico de barras de matplotlib?
Por otro lado, vimos que en matplotlib hay ciertas pautas para generar los graficos, de los cuales, nosotros no sabemos que significan ciertas lineas y no sabemos muy bien como averiguarlo, es necesario comentar estas?
Muchas gracias de antemano!

**Comment by felipegarcia98** [comment]
Holi, esperamos lo mismo c: 

Si viene de la documentación de la librería, pueden omitir esas líneas complicadas, pero recuerden que descubrir para que sirven les puede ser útil a ustedes, tanto para la tarea como para el futuro.

Y nope, no cuenta como diferentes. Cuando hablamos de gráficos diferentes nos referimos como al tipo genérico del gráfico, no a si es de una u otra librería.
