### ISSUE TITLE
Duda de como se debe intepretar el price_range

### ISSUE THREAD

**Issue by EnzoMorata** [Exploratorio-DCC-PUC/Syllabus#602]
Hola, tengo una duda respecto a que esta representando concretamente el price_range, ya que no sabemos si se refiere al rango de precio de salida de los celulares o si es el rango a día de hoy. Entonces, creo que según como se interprete las relaciones con las features pueden ser muy distintas.

**Comment by felipegarcia98** [comment]
Wola o/, considerenlo como el precio a día de hoy
