### ISSUE TITLE
Calculo de promedio

### ISSUE THREAD

**Issue by IgnacioEngelberger** [Exploratorio-DCC-PUC/Syllabus#603]
Holas, quería saber en caso de querer eliminar una nota de interrogación o tarea chica ¿Cómo sería el calculo del promedio en estos casos? (Tipo: Se reemplazara la nota por la mas alta/baja de otra tarea/interrogación, se cambiaran los porcentajes de ponderación con tal de no necesitar rellenar la nota, etc)

**Comment by felipegarcia98** [comment]
La nota no se rellena, simplemente se deja de considerar y el valor del par* queda como el valor de la nota que se queda

Considerando O-P como controles, L-M como TGs, R-S como promedios de cada par de TCs (el promedio de promedios es igual al promedio del total de las TCs

![imagen](https://user-images.githubusercontent.com/42228743/120382600-d5837080-c2f1-11eb-977b-04c35c2dbb22.png)
En la imagen se puede ver el cálculo del promedio borrando la TC3 o la TC4

![imagen](https://user-images.githubusercontent.com/42228743/120382699-f2b83f00-c2f1-11eb-9fe1-6934c2038fa2.png)
Y aquí borrando un control

*par= (Controles) o (TC1 & TC2) o (TC3 & TC4)

**Comment by IgnacioEngelberger** [comment]
Hola de nuevo, respecto al mismo tema de la pregunta que hice antes quería saber ¿Es necesario dar la I2 para poder reemplazarla/ borrarla como nota?

Gracias de antemano.

**Comment by IchottMano** [comment]
Hola @IgnacioEngelberger !

No, no es necesario dar la I2 para poder borrarla como nota. No rendir la pruba es igual a rendirla con nota 1.

Saludos!
