### ISSUE TITLE
Parte I. Análisis de características

### ISSUE THREAD

**Issue by CristianD16** [Exploratorio-DCC-PUC/Syllabus#604]
Hola!
Respecto a la primera parte de la tarea,

Cómo a través de gráficos es que podemos encontrar los parámetros que están relacionados y nos interesa dejar en nuestra tabla??

Luego, debemos dejar una tabla para el estudio del rango de precios y otra tabla para el estudio de la memoria interna??

Saludos,
Muchas gracias

**Comment by felipegarcia98** [comment]
🤠 /

Para la segunda pregunta, la issue #600 lo explica. 
TL;DR: Es esperable que tengan dos tablas diferentes, una para cada estudio. Que tanto varíen, depende de ustedes

Para la primera pregunta, la respuesta es: Ahí ustedes entran a analizar
La relación entre datos se puede expresar de diferentes maneras, dependiendo de lo que signifiquen. Por ej. variables numéricas podrían relacionarse y eso quedar en evidencia mediante la correlación que tienen (visualizable también en una matriz). 
También puede pasar que, por construcción, una variable tenga relación con otra. Por ej. es poco probable encontrar un celular con el tamaño de una laptop o de una tablet (relación tamaño-tipo dispositivo) o es esperable que el consumo de electricidad de una casa aumente si es que tienen un refrigerador (relación energía-presencia dispositivo)

PD: Esos casos que mencioné son solo ejemplos de relaciones, no de si deben no considerarse
