### ISSUE TITLE
[TG2] Gráficos con for

### ISSUE THREAD

**Issue by FeBalla** [Exploratorio-DCC-PUC/Syllabus#605]
Hola! quería consultar si para hacer varios gráficos de una sola vez podemos usar un `for` que itera sobre el **nombre de las columnas**, ya que en estricto rigor esto no tiene nada que ver con la eficiencia del código, pues no itera sobre las filas del _dataframe_, sino que solo permite escribir menos líneas de código para hacer, por ejemplo, gráficos de distribución de diferentes variables.

**Comment by felipegarcia98** [comment]
Hola 🤠 /
Si afecta la eficiencia 👉🏼 👈🏼  pero es mínima y no la que pretendemos evitar jeje tal como dices, el for que nos preocupa es el que se hace a lo largo de las columnas y no entre ellas. Entonces sí, efectivamente puedes usar un loop, como el for, para graficar múltiples veces y evitar duplicar código. Ejemplo:

````python 
...
fig_axes = plt.figure(...)
for i, feat in enumerate(nombre_columnas_a_graficar):
    ax = fig_axes[1+i]
    ax.super_grafico_que_repetire_en_subplots_o_en_slider(df[feat])
    ...
```
