### ISSUE TITLE
Separacion features - vector de clase

### ISSUE THREAD

**Issue by cristobal-larach** [Exploratorio-DCC-PUC/Syllabus#606]
En el enunciado dice que se espera "UNA" separación entre features y vector de clase para cada caso (clasificador y regresor). ¿A qué se refiere el "UNA" ? ¿Se debe considerar los mismos features para ambas separaciones?

De antemano, gracias!

**Comment by felipegarcia98** [comment]
Hola o/
en la #600 se explica un poco el tema. Ese "UNA" era principalmente para señalar que no requerían hacer cortes extras, pero claro, es necesario que se haga la separación para el clasificador y otra separación para el regresor
