### ISSUE TITLE
Graficos de Análisis de características

### ISSUE THREAD

**Issue by cristobal-larach** [Exploratorio-DCC-PUC/Syllabus#607]
Hola!

En la parte de Análisis de características, cuando indican **_"Deberán presentar al menos 3 gráficos, considerando tres tipos diferentes (pairplot, swarmplot, histogram, etc.), que caractericen los datos con su explicación correspondiente..."_**

¿Hay que hacer 3 tipos de gráficos para cada uno de los atributos? ¿o se debe elegir 3 graficos distintos **en total** que ayuden a caracterizar cierta columna o atributo? 

De antemano, gracias!

**Comment by felipegarcia98** [comment]
Hola 😄 /
Es en total, un "esperamos que en todo el análisis de todos los datos contabilicemos al menos 3 gráficos", su ` return 'correct' if code.count(graphs) >= 3 else return 'insufficient' ` resaltando que es un al menos
