### ISSUE TITLE
Gráficos para el análisis de las características

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#608]
Hola, para los 3 gráficos que hay que hacer en el análisis de características, un gráfico debe abarcar todos los atributos o podemos confeccionar un gráfico que relacione el atributo a predecir y otro que ayuda a predecir (es decir, que contenga solo dos atributos)?

**Comment by felipegarcia98** [comment]
Wolap
Es cosa de ustedes, como les contribuya mejor para el análisis de los datos. Pueden ser todos juntos, pueden ser de a pares, pueden ser en solitario. Cada una puede aportar cosas diferentes dependiendo de cómo le usen y con qué datos le usen
