### ISSUE TITLE
Informe 

### ISSUE THREAD

**Issue by mvaldesmeller** [Exploratorio-DCC-PUC/Syllabus#609]
Hola! Ojalá se encuentren muy bien :)

Quería preguntar si al momento de hacer el "informe" , éste debe ir al final de todo el código, o si se busca que sea parte de los comentarios (es decir, al momento de normalizar, responder la pregunta sobre cómo normalizamos, etc.)?

Muchas gracias!

**Comment by felipegarcia98** [comment]
Hola, espero que tu también 😄 

Lo que nos importa es que se resalte y destaque que están respondiendo una pregunta. Vale decir, aceptamos que sean dentro del código o todo al final de notebook, pero en cualquiera de los casos se tiene que dar a entender que están respondiendo la pregunta X.

Ejemplo integrado:

> <Celda de código></Celda de código>
> < Celda Markdown>
>     <b> Pregunta 3: ¿Qué gráficos utilizaste para caracterizar los datos? ... Justifique </b>
>      <p> Para caracterizar los datos utilice ... </p>
> </Celda Markdown>

Hago notar que el uso de negrita y de headings se agradece

**Comment by mvaldesmeller** [comment]
Muchas gracias!! :)
