### ISSUE TITLE
[TC2] Inputs

### ISSUE THREAD

**Issue by dlcartagena** [Exploratorio-DCC-PUC/Syllabus#61]
Es necesario que todo se haga en una sola línea cuando necesito relacionar las tablas? O puedo sacar la información de una tabla y después ocupar esa información en la otra?

**Comment by fvr1** [comment]
Hola,

Sí, debe ser con una instrucción. La idea es que la instrucción ocupe la información desde una tabla para filtrar en la otra tabla.

¡Saludos!
