### ISSUE TITLE
Gráficos de análisis de características

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#610]
Holaa, se pueden usar los gráficos que se deben confeccionar en el análisis de características para ver si cierto feature nos sirve para predecir? o se deben usar con otro propósito?

Gracias de antemano

**Comment by felipegarcia98** [comment]
aps, hola o/, los gráficos pueden usarlos para lo que quieran, pero al menos 3 deben servir para analizar nuestro set de datos. Respecto a gráficos que digan si algo sirve para predecir, depende de cómo lo hagas, pero si involucra un análisis de nuestra DB, entonces sí
