### ISSUE TITLE
Problemas con el regresor

### ISSUE THREAD

**Issue by NicoJGutierrez** [Exploratorio-DCC-PUC/Syllabus#611]
Hola! Respecto a instanciar un regresor, no estamos entendiendo lo que tenemos que hacer. Estamos haciendo lo que se muestra en esta documentación (https://scikit-learn.org/stable/auto_examples/tree/plot_tree_regression.html#sphx-glr-auto-examples-tree-plot-tree-regression-py) y entender el procedimiento está complicado en el mejor de los casos. Además, el hecho de que nuestro problema sea una discrepancia de tamaños en los gráficos que estamos importando (?) nos hace estar desconcertados. Qué pistas o indicaciones nos podrían dar para esa parte de la tarea?

Gracias de antemano: Equipo Bot Comentador.

**Comment by felipegarcia98** [comment]
Wola o/, 
No estoy seguro de comprender exactamente el problema que tienen 🤔 les recomiendo echar una mirada a la ayudantía, que tiene bien simplificado el paso a paso, seguir comentando esta issue o mandarme un correo c: (fagarcia5@uc.cl)

**Comment by NicoJGutierrez** [comment]
Hola, estamos teniendo problemas porque no estamos seguros de cómo podríamos asegurarnos de que el algoritmo en cuestión está funcionando bien, puesto que no tenemos ninguna forma de saber si esto:
![image](https://user-images.githubusercontent.com/80768621/120941425-b8cfaa00-c6f0-11eb-92ae-32cb550f12c4.png)
es mejor que esto:
![image](https://user-images.githubusercontent.com/80768621/120941443-cb49e380-c6f0-11eb-8127-54f656820725.png)

**Comment by felipegarcia98** [comment]
Si esa gráfica no les sirve para extraer información, entonces puede que no sea la adecuada o que no se este dando lo que necesita. Recomiendo revisar esa parte de la ayudantía, donde se trabaja con el regresor, ya que hay algunos detalles que no veo acá uwu. De partida, no creo que debiera ser un gráfico de puntos unidos por líneas (lineplot), sino algo así como uno de solo puntos (scatter). Igualmente, para saber si esta funcionando bien, en la última pregunta de la parte 2 se señala que midan el rendimiento a través del MSE.

**Comment by NicoJGutierrez** [comment]
El MSE nos da 343, en qué parte de la ayudantía se menciona lo del decision tree? Si me pudieras señalar algún minuto en particular estaría muy agradecido.

**Comment by NicoJGutierrez** [comment]
Digo, de una forma más práctica, qué tipos de código deberíamos usar.

**Comment by felipegarcia98** [comment]
Desde el min 49 se ve el Decision Tree, min 51 revisión del score, min 53 revisión del t-SNE de lo predicho ...

**Comment by NicoJGutierrez** [comment]
Gracias! voy a dejar el issue abierto por si cosa

**Comment by NicoJGutierrez** [comment]
Un gustazo, ahí funcionó
