### ISSUE TITLE
[TG2] Separación matriz de features y división de set de entrenamiento.

### ISSUE THREAD

**Issue by tomytable** [Exploratorio-DCC-PUC/Syllabus#612]
Hola, espero que estén bien.

Me di cuenta durante la tarea que debido al orden en que están las instrucciones creo que hay un problema porque durante la parte 1.3 necesitamos crear las matrices de características y los vectores con los labels respectivos. Luego, en la parte 2.1 dividimos la matriz de características en set de train y de testeo pero cuando entrenamos el clasificador y le pasamos las características que hemos seleccionado, no tengo como acceder a la etiqueta de cada una porque las separamos en 1.3.

Mi pregunta entonces es, ¿Puedo incluir la columna de labels en la matriz de características y sacarla justo antes de entrenar al modelo? o ¿Puedo hacer la división train-test a partir de otra matriz que no sea la que hice en 1.3?

No sé si queda clara la duda, acabo de pushear en mi repositorio, quizás con el código se entienda más.
Espero su respuesta!

**Comment by felipegarcia98** [comment]
Holaaa o/, esperamos lo mismo. 

Creo que si queda clara. Ojo con los parámetros que recibe la función fit (entrenar el modelo), ya que, de hecho, la separación se hace para que el clasificador la tenga disponible. Dicho eso, no tendrías que hacer cosas alternativas. 

Estaré atento a la respuesta (como en 1 hr jssjs)

**Comment by tomytable** [comment]
Creo que encontré el problema, gracias!

**Comment by felipegarcia98** [comment]
U welcome
