### ISSUE TITLE
Calcular el rendimiento del clasificador y regresor

### ISSUE THREAD

**Issue by romystroh** [Exploratorio-DCC-PUC/Syllabus#613]
Hola! Espero que estén bien. Respecto de la última pregunta de la Parte 2 no nos quedó muy clara la instrucción. ¿Se debe para cada métrica clasificar todas las clases?

Muchas gracias de antemano

**Comment by felipegarcia98** [comment]
hola o/
no entendí tu pregunta, pero creo que sé qué estas preguntando. Sí, las métricas deben revisar el panorama por cada clase, algo así como lo que sale en la última slide de la parte 3 de la ayudantía

**Comment by TomasOlivaresR** [comment]
Hola!
¿Se deben utilizar las 4 métricas (accuracy, precision, recall, f-1 score) para medir el rendimiento?

**Comment by felipegarcia98** [comment]
yes, aunque ojo que es del clasificador.
