### ISSUE TITLE
hiperparametros

### ISSUE THREAD

**Issue by antoniablanco** [Exploratorio-DCC-PUC/Syllabus#615]
Hola, quería preguntar si los parámetros e hiperparametros se consideran lo mismo?

**Comment by felipegarcia98** [comment]
hola 🤠 /

uhhh, tengo miedo de alguna diferencia sutil. Si te refieres a la 3.5, usamos indistintamente los conceptos parámetros e hiperparámetros para referirnos a los hiperparámetros que tienen la funciones de sklearn, pero realmente [hay una diferencia no tan sutil entre ambos conceptos](https://machinelearningmastery.com/difference-between-a-parameter-and-a-hyperparameter/)
