### ISSUE TITLE
Limpiar valores nulos

### ISSUE THREAD

**Issue by nolate26** [Exploratorio-DCC-PUC/Syllabus#616]
Hola, en la parte de limpiar valores nulos cuando dice: _"deberán encontrar los valores nulos o NaN (Not a Number) dentro del DataFrame"_ ¿se refiere a valores Nan en el data frame y valores 0?... por ejemplo si existiera una fila que indicara que la bateria tiene un valor 0, este valor también lo debemos limpiar

**Comment by felipegarcia98** [comment]
Holap o/
nope, el valor 0 NO es un valor nulo. El valor nulo es, literalmente, un vacío (si ven el csv, veran algunos espacios con nada, que son los nulos). Cuando esos valores nulos pasan a Pandas, se convierten en NaN, que siguen representando lo mismo (nil, None, NaT para fechas, null, etc).
