### ISSUE TITLE
[TG2 - Parte 1] Duda con respecto a la separación de clases

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [Exploratorio-DCC-PUC/Syllabus#617]
Hola!
En el enunciado de la tarea, cuando dicen "se esperan UNA separación donde el vector de clase corresponda al rango de precios en el caso del clasificador y memoria interna en el caso del regresor.", esto significa que debemos tener solamente una matriz de features, en donde no contemos las columnas que se usarán como vector de clase y regresión, o se espera una matriz PARA CADA UNA de estas separaciones?
Saludos! :D

**Comment by fernandosmither** [comment]
Me sumo a la pregunta, nosotros nos decidimos en crear DOS sistemas matriz-vector, uno para naive y uno para regresión, pero veamos que nos responden

**Comment by felipegarcia98** [comment]
Hola o/
Ya fue respondida en las issues #606  y #600 . Por favor, revisar las issues  T_T
