### ISSUE TITLE
Coeficiente de determinación R^2

### ISSUE THREAD

**Issue by gBastias2001** [Exploratorio-DCC-PUC/Syllabus#618]
Hola, tengo 2 preguntas
1. Buscando documentación encontré que el coeficiente de determinación R^2 señala el error en la predicción de la regresión, mi pregunta es ¿La predicción es mejor cuando este valor es más cercano a 1 y peor cuanto más negativo sea o nada que ver?
2. Para la parte del análisis de características, los gráficos deben tener título o con mostrarlos y el análisis de cada uno es suficiente?
Gracias de antemano!

**Comment by felipegarcia98** [comment]
🤠 /
Sobre la 1, en [la documentación](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html) hay una breve explicación al respecto. Más profundamente se trata el tema en [stackoverflow](https://stats.stackexchange.com/questions/12900/when-is-r-squared-negative) y [otras páginas](http://www.fairlynerdy.com/what-is-r-squared/) encontradas con Google ("R2 negative") :33

Sobre la 2, personalmente encuentro muchísimo más apropiado que los gráficos incluyan títulos, aún cuando el análisis o descripción sean muy buenos y completos
