### ISSUE TITLE
Duda sobre las metricas 

### ISSUE THREAD

**Issue by jtvaldivia** [Exploratorio-DCC-PUC/Syllabus#619]
Hola, tengo una pregunta,
tuvimos un problema como grupo, al buscar  información de las métricas (accuracy, precision, recall y f-1 score), nos dimos cuenta que se asume un escenario donde existe un escenario positivo y otro negativo, y con mi pareja no se nos ocurre cual es el caso positivo para nuestros set de datos. Nosotros en especifico no entendemos como aplicar este tipo de evaluación al price_range. En la información que encontramos en internet  se presentan proporciones incluyendo True positive, True negative, false positive y false negative.

**Comment by felipegarcia98** [comment]
Recomiendo revisar la ayudantía, hacia el final de la parte 3, ya que ahí se explica un poco al respecto y sale un mapa bastante bueno. El caso positivo sería el caso en que tu modelo prediga correctamente la clase de una instancia de los sets de testeo.
