### ISSUE TITLE
Carpetas parte 3

### ISSUE THREAD

**Issue by vvelasco150** [Exploratorio-DCC-PUC/Syllabus#62]
Hola! para la parte 3 de la tarea en el repositorio hay unas carpetas para css, java y las imágenes, es obligación utilizarlas? o se puede importar css al html y entregar solo ese archivo con los demas necesarios para que funcione???

**Comment by malopez16** [comment]
Hola
Es ideal que se usen las carpetas para que haya orden (al fin y al cabo, están por eso). No debería cambiar mucho, sólo la [ruta relativa](https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/) la importación desde el HTML.

Saludos!
