### ISSUE TITLE
Duda con calcular el rendimiento del clasificador

### ISSUE THREAD

**Issue by Artaudd** [Exploratorio-DCC-PUC/Syllabus#621]
Hola, con mi pareja teníamos dudas sobre esta parte de la tarea (ver primera imagen). Primero que todo, en esta parte a qué se refiere con testear el rendimiento de cada clase en el clasificador? La clase no es solamente el price_range en el caso del clasificador? 

![image](https://user-images.githubusercontent.com/65875467/121248719-c1032300-c871-11eb-9b67-3a2a780f83e3.png)

Otro problema que tuvimos fue al intentar calcular las métricas pedidas para el clasificador. Al calcular el precision score, recall score y f1 score la función nos tira un error porque supuestamente el set es multiclase, y nos pide que cambiemos el parámetro "average". Adjunto imagen del error:

![image](https://user-images.githubusercontent.com/65875467/121250499-c7929a00-c873-11eb-9657-dd26ba4082d6.png)

La cosa es que para ese parámetro hay 4 opciones más (aparte de "binary" que se usa por defecto), y varias nos funcionaron, pero no sabemos cuál es la correcta a considerar :(

Gracias de antemano por las respuestas.

**Comment by MaxiNavia** [comment]
Respecto a esta misma duda sobre los hiperparámetros, con mi compañero no sabemos bien si hay que probar combinaciones solo para la parte de métricas o para todo el entrenamiento? :p
Gracias de antemano :D

**Comment by felipegarcia98** [comment]
Respecto a la primera pregunta, mira lo último que se hace en la parte 3 de la ayudantía 7 o cuando evaluan la precision del modelo en la documentación (cuando trabajan con los pétalos de las flores versicolor). Básicamente es observar las métricas en función de cada clase, que precisión tuvo evaluando celulares de bajo precio, etc.

Respecto a la segunda pregunta, para la parte de métricas, tendría algún sentido ir variando los parámetros? recuerda que nosotros pedimos que vayan cambiando los hiperparámetros del modelo, lo cual se realiza al instanciarlo (previo al entrenamiento y predicción )

**Comment by Artaudd** [comment]
@felipegarcia98 Gracias por responder! pero todavía tengo una duda :(. Aún no sabemos qué opción deberíamos considerar para modificar el argumento "average" al momento de calcular las métricas para el clasificador (en el post adjunté foto del error que nos aparece).

**Comment by felipegarcia98** [comment]
Podrían haber probado o buscado en Google :c la opción recomendada por el [primer resultado a la búsqueda en Google del error](https://stackoverflow.com/questions/52269187/facing-valueerror-target-is-multiclass-but-average-binary) es None. Aún así, yo no lo he intentado, así que prueben con 'micro' y 'macro'
