### ISSUE TITLE
Función para mejores hiperparámetros

### ISSUE THREAD

**Issue by vicentethomas** [Exploratorio-DCC-PUC/Syllabus#622]
Hola! Con mi compañero buscando en internet encontramos una función en sklearn que permite entregarle hiperparámetros del regresor y que encuentre la combinación de estos parámetros que tiene el mejor score (error pequeño). Nuestra duda es si es válido utilizar esta función, o si lo que se evalúa en la tarea finalmente es el ir tanteando con los valores de los parámetros para encontrar una con el menor error?

**Comment by felipegarcia98** [comment]
hola o/
jsjjsjj me temo que es válido, pero igual deben explicar para la 3.5 el porque creen que funciona así, por lo que deben buscar la manera de saber que hiperparámetros fueron cambiados. [No parece tan complicado](https://towardsdatascience.com/automatic-hyperparameter-tuning-with-sklearn-gridsearchcv-and-randomizedsearchcv-e94f53a518ee), pero pinta ser un overkill, especialmente por el tiempo que puede llegar a demorar
