### ISSUE TITLE
Extensión del informe

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#623]
Holaa, está la posibilidad de que podamos pasarnos un poco en el número de líneas? Lo que pasa es que estoy teniendo problemas para explicar los 3 gráficos que nos piden en la parte 1 en 10 líneas, además de que en la pregunta de los gráficos hay más 'subpreguntas' que responder.

Gracias de antemano

**Comment by felipegarcia98** [comment]
Hola o/, si, tienen permiso. Consideren un máximo de 10 líneas **por gráfico** para la 3.3

**Comment by cristobalba** [comment]
Hola, yo también tengo una duda respecto a la extensión de las respuestas y con mi compañero queríamos saber que si incluimos una tabla pequeña con datos para poder responder una pregunta, las líneas que ocupe esta tabla contarán dentro del máximo de 10 líneas o no? para ver si tenemos que cambiar la respuesta o no.
Gracias!

**Comment by felipegarcia98** [comment]
Denle no más. Tienen mi permiso, wa :v
*es real, denle no más
