### ISSUE TITLE
Prueba de distintos Hiperparámetros

### ISSUE THREAD

**Issue by Gau04** [Exploratorio-DCC-PUC/Syllabus#624]
Hola! Si se usó una rutina para poder saber que valores usar en distintos hiperparámetros, esta se deja en el código final? Además, en el markdown debo escribir todas las combinaciones probadas, o se puede solo señalar los distintos valores que se probaron para cada hiperparámetro, dado que se hicieron combinaciones entre todas las opciones?

Por último me surge otra duda sobre si es necesario que todos los comentarios sean en formato markdown, ya que se señala que esta parte si.

**Comment by felipegarcia98** [comment]
Sería bueno e interesante que dejaras la rutina en el código. Además, así serviría de base para cuando expliques cómo se eligieron 👌🏼 .
Uhhh, lo que tu encuentres apropiado. Enumerar todas las combinaciones probablemente sea innecesario, bastando mencionar cuáles se modificaron, en cuánto, qué criterio usaron para combinar, etc.
En qué parte? Si es la del informe, efectivamente lo recomendable es que la mayoría este en markdown, pero no estoy seguro a qué te refieres u.u

**Comment by Gau04** [comment]
Gracias! Lo de los comentarios me referia a los de antes del informe, como entremedio del código.

**Comment by felipegarcia98** [comment]
ahhhh, nahh, entremedio del código si pueden. No es que les obliguemos, pero realmente se hace más recomendable para no estar llenando de comentarios el código o para describir a grandes rasgos una rutina
