### ISSUE TITLE
Gráfico de Reducción de dimensionalidad

### ISSUE THREAD

**Issue by cristobalba** [Exploratorio-DCC-PUC/Syllabus#625]
Hola, estamos haciendo el bonus A con mi compañero y cuando queremos visualizar los datos reducidos por el t-SNE no estamos seguros si es el mismo tipo de gráfico que vimos en la ayudantia o este cambia debido a que estamos reduciendo a dos caracteristicas y no a una sola como se hizo en la ayudantia.

Gracias :)

**Comment by felipegarcia98** [comment]
Mmmm, depende de lo que quieras ver. En la ayudantía se quería ver la distribución de lo predicho y en el bonus se quiere ver la distribución de los datos, lo que es diferente, al variar una de las componentes. Por otro lado, tanto PCA como t-SNE establecen una cantidad n de dimensiones y uno decide cuántos usar, así que depende de cómo y cuánto quieran visualizar. Se puede ver en 1D, 2D, 3D y con otras modalidades 👌🏼
