### ISSUE TITLE
Cuaderno jupyter

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#626]
Holaa, con mi compañera teníamos la duda de como organizar el cuaderno. No sabemos si es mejor dejar todo lo del clasificador junto y después todo lo del regresor junto o hacer por puntos, es decir, en el análisis de características poner todo lo del clasificador y todo lo del regresor y hacerlo de esa manera con el resto de los puntos. 

Graciasss y perdón lo tardee.

**Comment by felipegarcia98** [comment]
Holaaa o/
nah, tranquila, las issues son anacrónicas. Para el análisis háganlo todo junto no más 😄 haganlo por puntos
