### ISSUE TITLE
Borrar archivo csv

### ISSUE THREAD

**Issue by angegazitua** [Exploratorio-DCC-PUC/Syllabus#627]
Hola, con mi compañera teníamos la duda si cuando terminamos la tarea debemos eliminar el archivo celulares.csv, ya que en las instrucciones sale _"Es sumamente importante que elimines el output de tu Jupyter Notebook. Tampoco debes subir el dataset (celulares.csv) a tu repositorio"_. De ser así, ¿Cómo debemos eliminar este archivo?

**Comment by felipegarcia98** [comment]
Hola o/
jsjsj por favor si, eliminen ese archivo. Pueden hacerlo desde la web, entrando al archivo y apretando el tacho de basura 'delete this file' o pueden hacerlo mediante un commit, pusheando la eliminación del archivo
