### ISSUE TITLE
Hiperparametros de clasificador.

### ISSUE THREAD

**Issue by AlejandraBeas** [Exploratorio-DCC-PUC/Syllabus#628]
Hola! espero que se encuentren bien. Tengo el problema de que he estado buscando mucho en varias partes cómo variar los parámetros para el clasificador. He encontrado pocas páginas en que se explique esto y no he podido entender lo que ahí sale. Estoy muy confundida y no he podido avanzar en esta etapa, ¿hay algún recurso que me puedan dar, que pueda utilizar y en que pueda entender mejor lo que tengo que realizar? Lo agradecería bastante porque me siento muy desorientada al respecto :c. Gracias!

**Comment by felipegarcia98** [comment]
Hola o/
mmm, realmente la mismísima documentación de Sklearn. Ahí salen cuáles son los parámetros e hiperparámetros a modificar, salen explicaciones de lo que cambian, lo que involucran, etc. :c
