### ISSUE TITLE
I2 [Pregunta 3.1]

### ISSUE THREAD

**Issue by CGR0** [Exploratorio-DCC-PUC/Syllabus#630]
Hola!
Cuando se habla de Proceso de negocio en la 3.1 se refiere a procesos de desarrollo o son cosas distintas?

**Comment by clolate** [comment]
No se cuales son los de desarrollo que mencionas tu, pero los de negocios están definidos y vistos en la clase de Marcos Sepulveda

**Comment by APeraltaS16** [comment]
Hola! En esta misma pregunta me surgio la duda a que se refieren con "software en una organizacion", si lo podrian explicar un poco mas?

**Comment by felipegarcia98** [comment]
Literal eso, softwares que estén en una organización. Puede ser un ERP (como SAP), el uso de un suite como la de Drive o Microsoft (Excel, Documentos, One Drive, etc.), algún software de elaboración propia (interna), incluso juegos (Flappy bird, etc)

**Comment by TomasOlivaresR** [comment]
Hola! En cuanto a eso último, entonces el software en una organización se refiere simplemente al uso del software y no a la creación de un software?

**Comment by AstridESMJ** [comment]
Hola! 

La pregunta hace referencia a software existente, debes referirte a lo que precisamente dice la pregunta.

Saludos,

Astrd,
Ayudante IIC1005
