### ISSUE TITLE
I2 [Pregunta 1.2]

### ISSUE THREAD

**Issue by APeraltaS16** [Exploratorio-DCC-PUC/Syllabus#631]
2. (1 pto.) Qué definiciones de fairness menciona el artículo. Explique cada una en sus propias palabras y ejemplos.

En esta pregunta se pide explicar en nuestras propias palabras y ejemplos, no me queda claro esto ultimo de ejemplos. ¿Hay que explicar ejemplos de cada una de estas o simplemente hay que dar ejemplos de que se puede hacer con estas?

**Comment by clolate** [comment]
Para cada una explicarla con tus palabras y para cada una dar un ejemplo
