### ISSUE TITLE
I2 [Pregunta 3.3]

### ISSUE THREAD

**Issue by angegazitua** [Exploratorio-DCC-PUC/Syllabus#632]
¡Hola! Cuando nos preguntan por definir la suma en Prolog, ¿lo debemos hacer de manera simbólica como lo hicimos en clases o que sea capaz de sumar números concretos? La misma pregunta con la resta.

**Comment by JupaOlivares** [comment]
En el caso de sumar se tiene que hacer pensando que tu programas la funcion suma (asi como una funcion de python), en el caso de la resta se espera una "demo ejecucion" de como  usar la misma función suma() pero para restar asi **como se vio en clases**

**Comment by denisparra** [comment]
El profesor Jorge Baier dio una demo en clases que va directamente a responder esta pregunta

**Comment by angegazitua** [comment]
Perfecto, muchas gracias.
