### ISSUE TITLE
I2 [Pregunta 1.3]

### ISSUE THREAD

**Issue by APeraltaS16** [Exploratorio-DCC-PUC/Syllabus#633]
3. (1 pto.) ¿Por qué se menciona el trabajo de Kearns y Hèbert-Johnson? Explique. Explique por qué es importante la interseccionalidad.
En la segunda parte donde se pide que se explique por qué es importante la interseccionalidad, se refieren a la importancia de saber que existe este problema, si no es asi,¿a que se refieren con importante?

**Comment by denisparra** [comment]
Se refiere a que tú indiques, en caso que exista el problema, por qué es importante en la investigación de fairness en IA.

**Comment by APeraltaS16** [comment]
ok, muchas gracias!
