### ISSUE TITLE
[I2] Extensión de la entrega

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#634]
Profesor, estuvimos hablando en el grupo, y algunos alumnos tenemos cruce con otras interrogaciones, (como es mi caso con Avanzada) y nos gustaría pedirle por favor un aplazo pequeño de la entrega, para poder usar ese tiempo que perderíamos en la otra i, en esta.

**Comment by fernandosmither** [comment]
Como es un medio digital, para expresar un poco mejor la solicitud, adjunto una foto que nos representa a los estudiantes ahora mismo
![image](https://user-images.githubusercontent.com/66154723/122440807-edeac080-cf6a-11eb-8340-2a6b0628ac7e.png)

**Comment by Maxi1805** [comment]
Me sumo a la peticion, yo tambien tengo otras interrogaciones hoy y no tendre tiempo para terminar la tarea de buena manera en el tiempo que quede.

**Comment by nataliasuarez99** [comment]
Me sumo!! Estoy full con entregas y no quiero "botar" esta I :(

**Comment by sachondo7** [comment]
apoyo!

**Comment by BenediktKd** [comment]
😓

**Comment by cpschulz** [comment]
Yo tambien tengo entrega de otro ramo, apoyo la peticion de mis compañeros

**Comment by clolate** [comment]
Hola, lamento informarles que **no habrá extensión del plazo** de entrega. Con anterioridad se envio un anuncio recordando la fecha de la interrogación y en esa misma oportunidad se les indicó que si presentaban algún problema avisaran con antelación para ver una solución en conjunto con los casos puntuales. En esa oportunidad nadie nos escribió.

**Comment by jtvaldivia** [comment]
apoyo a mi ahora me calza porque en temodinamica nos cambiaron una prueba del lunes por el feriado. Esto nos lo avisaron hoy por eso recien ahora puedo avisarles de mi problema
