### ISSUE TITLE
I2 [Pregunta 4.3]

### ISSUE THREAD

**Issue by cpschulz** [Exploratorio-DCC-PUC/Syllabus#635]
Para esta pregunta se espera que sepamos que es lo que esta haciendo la maquina que nos presetan? O sea que sepamos la condicion que tiene que tener el numero binario para que se termine en q_f?

**Comment by MFMG99** [comment]
¡Hola! Se espera que respondas cuál será el output (si la máquina acepta o rechaza, es decir, llega al estado final o no) dado ese input, esto implica que debes saber qué es lo que hace la máquina que presenta la pregunta. Además de explicar qué implica que la máquina haya llegado a su estado final o no.

**Comment by cpschulz** [comment]
Pero necesitamos conocer la condicion que pregunta la maquina? Por ejemplo si esta revisando que el numero sea par, o sea divisible por 3, u otro?

**Comment by MFMG99** [comment]
Si, debes entender qué está haciendo la máquina para poder explicar por qué la máquina aceptó/rechazó el input (llegó o no a su estado final)
