### ISSUE TITLE
I2 [Pregunta 2.2 ]

### ISSUE THREAD

**Issue by emiliaup** [Exploratorio-DCC-PUC/Syllabus#637]
Para la pregunta "¿considerarías correcto que se reserven cupos para mujeres que postulen a la escuela de ingeniería UC?"  tenemos que dar una opinión personal? ¿o piden lo que aparece en el artículo? ¿Hay sola una respuesta correcta? ¿O solo tenemos que respaldar lo que pensamos? 

Gracias :)

**Comment by MFMG99** [comment]
¡Hola! La idea de esa parte de la pregunta es que des tu opinión al respecto pero que la fundamentes basándote en el artículo.
No hay solo una respuesta correcta, pero se busca que respaldes lo que piensas en base al artículo.

**Comment by emiliaup** [comment]
perfecto! Gracias :)
