### ISSUE TITLE
I2 [P 1.1]

### ISSUE THREAD

**Issue by cristobalba** [Exploratorio-DCC-PUC/Syllabus#638]
hola, en el enunciado se justifica que los datos son desbalanceados porque hay dificultad para obtenerlos debido a que algunos examenes son invasivos. En base a esto, ¿se quiere decir que no todos los pacientes se realizan todos los examenes? Por ejemplo, hay pacientes que se realizan todos los examenes (invasivos o no) y hay pacientes que se realizan solo examenes no invasivos.

Gracias salu2

**Comment by AstridESMJ** [comment]
Hola!

Ambos escenarios que planteas son posibles. Puede ser que por ejemplo tengamos pacientes de edades mayores que no se realicen exámenes muy invasivos debido a restricciones por la edad. También puede que ciertas personas con comorbilidades, independiente de la edad, no puedan realizarse ciertos exámenes o sea riesgoso y no todos se los realicen. También podemos tener que cierto tipo de paciente no participe simplemente. Todo esto puede generar que tengamos datos desbalanceados.

Saludos,

Astrid,
Ayudante IIC1005

**Comment by denisparra** [comment]
Como indica Astrid, lo importante no es "cómo se llega al desbalance de clases", sino que respondas la pregunta "¿Qué tipo de distorsiones encontramos?" al momento de querer hacer un método de predicción en base a machine learning usando un dataset con estas características.
