### ISSUE TITLE
I2.pregunta 2.3

### ISSUE THREAD

**Issue by RodrigoRenco** [Exploratorio-DCC-PUC/Syllabus#639]
Los aspectos a considerar se refiere a las caracteristicas presentes en las transacciones del banco y clientes? asi como si es humano o no, si esta vivo o esta muerto, si se pago con dinero o paltas.

**Comment by denisparra** [comment]
Tú debes desarrollar tu respuesta indicando las características que crees razonables. Si para ti es razonable que un banco considere como features (características) si el cliente paga un crédito con dinero o paltas, justificalo ese uso de features. Pero OJO el foco de la pregunta está en "¿cómo debería evaluar la superintendencia de algoritmos que el método que usa el banco para dar crédito no hace discriminación arbitraria? "

**Comment by RodrigoRenco** [comment]
gracias!
