### ISSUE TITLE
Parte 1

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#64]
![image](https://user-images.githubusercontent.com/48262438/64639093-812db400-d3dd-11e9-8cdc-f6dc0caf31d8.png)
Para la parte 1 hay que ocupar esta notación? hay que ocupar también el concepto de PK y FK?

**Comment by ValentinaAlvarezG** [comment]
Hola!

-Tienes que utilizar la notación 1-1, 1-N, N-N para las cardinalidades. 
-En el diagrama, debes subrayar los atributos que consideras que corresponden a las Primary Key.
