### ISSUE TITLE
I2 - Pregunta 3.2 - ¿Ejemplos?

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [Exploratorio-DCC-PUC/Syllabus#640]
Hola!
En la pregunta 3.2, cuando nos piden que demos un ejemplo aplicado a imagenes o audio, ¿Debe ser un ejemplo visto en clases? ¿Debe ser un ejemplo de solo Deep Learning?

Saludos!

**Comment by AstridESMJ** [comment]
Hola! 

No es necesario que sea uno visto en clases, puede ser cualquier ejemplo. El ejemplo debe retratar la diferencia sobre la cual se pregunta, no solo sobre deep learning.

Saludos,

Astrd,
Ayudante IIC1005

**Comment by ElTioAndresCabezas** [comment]
Y se puede usar más de un ejemplo? Asi como un ejemplo para cada uno para retratar las diferencias?

**Comment by felipegarcia98** [comment]
si puedes, aunque es alargar un poco más la respuesta sin una necesidad real
