### ISSUE TITLE
I2 - Pregunta 4.2 - Orden de los bloques

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [Exploratorio-DCC-PUC/Syllabus#641]
Hola!
Cuando me preguntan si puedo verificar la integridad de los datos de un bloque a partir de su hash y el hash del bloque anterior, a que se refieren con "bloque anterior"?

https://prnt.sc/15qw35m

Por ejemplo, si digo que quiero verificar la integridad de los datos del bloque 2 de la imagen, el bloque anterior es el bloque 1 o el bloque 3?

Saludos!

**Comment by felipegarcia98** [comment]
Confirmo que el bloque anterior al 2 es el 1

**Comment by ElTioAndresCabezas** [comment]
Gracias!
