### ISSUE TITLE
TC3 - Resta negativa (Enunciado)

### ISSUE THREAD

**Issue by franc1899** [Exploratorio-DCC-PUC/Syllabus#642]
Hola,

En los supuestos dice que ninguna resta dará como resultado un número negativo, pero en los ejemplos de más abajo, en específico el 3 (11000#11111#10111#10110), la resta entre los primeros dos números da negativo, y es más, en el ejemplo sale que es rechazado por esa razón. 

Entonces, mi duda es si es que consideramos la posibilidad de realizar una resta en donde el minuendo sea menor que el sustraendo? O simplemente me acojo al supuesto de que el minuendo siempre será mayor al sustraendo y de esta forma me sea imposible obtener un resultado negativo?

Saludos!

**Comment by mimadri** [comment]
Hola!

En caso de que el sustraendo sea mayor que el minuendo, no es necesario definir ninguna transición, ya que el input debería ser rechazado automáticamente, y esto sucede cuando tu máquina se encuentra en una situación en la que no se le indica qué pasos seguir.

Espero haberte ayudado y mucho éxito con la tarea :)
