### ISSUE TITLE
TC3 - Distintos largos

### ISSUE THREAD

**Issue by antoniablanco** [Exploratorio-DCC-PUC/Syllabus#643]
Hola, quería saber si es que podrían entregar un input de ejemplo de que seria una linea con distintos largos?, como para que sea aceptado por la maquina los números tienen que ir disminuyendo solo se me ocurre que agreguen 0 antes del numero y que en otros casos los eliminen. Porque al agregar en alguna otra parte cambiaría el numero, según lo que yo entiendo de números binarios.

**Comment by mimadri** [comment]
Hola!

Un ejemplo de input con distinto largo sería el siguiente: **100#11#010#1**
Como esta secuencia es decreciente y consecutiva (los números entregados son 4#3#2#1), la máquina debería aceptar el input, y tal como mencionas, sólo se podrían agregar ceros al principio del número para que este no cambie.

Éxito con la tarea :)

**Comment by HAWK-EF2021** [comment]
Hola!
En la tarea sale que podemos utilizar el siguiente supuesto:

ni pertenece a {0,1}^x, donde x es una constante que representa el largo de un número
binario en la secuencia. Es decir, cada ni de una secuencia tendrá el mismo
largo x (pero este largo puede variar de una secuencia a otra).

Mi pregunta es ¿Es necesario hacer que la máquina acepte inputs con números de distinto largo o da lo mismo y efectivamente se puede tomar este supuesto?
