### ISSUE TITLE
TC3 - Optimización de código

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#644]
Hola! 😄 

¿Se evaluará la optimización del código?

Lo que sucede en mi caso en particular, es que encontré una forma de resolver el problema en una cinta, para largos variables, y solo agregando 1 símbolo extra. El tema es que es un poco ineficiente mi código (aunque relativamente corto, ~54 líneas sin contar comentarios y separadores que puse para facilitar la corrección)

Sin revelar muchos detalles, hago una operación en concreto a cada número, y esto puede repetirse en el peor de los casos, el número mayor multiplicado por la cantidad de números, por ejemplo para el input desde 63 a 58, 111111#111110#111101#111100#111011111010 los pasos fueron los siguientes:
![image](https://user-images.githubusercontent.com/66154723/122662129-97de6e80-d15e-11eb-9514-6832f565b964.png)

Pero si se prueba con un input más bajito, como por ejemplo 110#0110#000000101#11#10#1 los pasos fueron los siguientes:

![image](https://user-images.githubusercontent.com/66154723/122662213-2e129480-d15f-11eb-91c3-9e912cbfbb82.png)

De todas formas, el código es corto y creo que la explicación de cómo lo hago deja bien claro el porqué funciona. ¿No me preocupo por esto? (optimizarlo probablemente requiera comenzar desde 0 con otro método)

Saludos! - 🐒

**Comment by mimadri** [comment]
Hola!

No evaluaremos optimización de código, sólo que se expliquen bien cómo funcionan las transiciones utilizadas.

Éxito con la tarea :)

**Comment by fernandosmither** [comment]
> Hola!
> 
> No evaluaremos optimización de código, sólo que se expliquen bien cómo funcionan las transiciones utilizadas.
> 
> Éxito con la tarea :)

🥳
