### ISSUE TITLE
Pregunta Bonus 1

### ISSUE THREAD

**Issue by nolate26** [Exploratorio-DCC-PUC/Syllabus#645]
¡Hola! Para la pregunta del bonus de 0.3 puntos que dice: _"Si la máquina acepta palabras con números binarios de distinto
largo. Es decir, eliminando el tercer supuesto."._ Esto se refiere a quitar los 0s que quedan adelante luego de restar?, como algo del siguiente estilo: **101#100#11#10** ? O me estoy equivocando?
Muchas gracias, quería estar seguro.
Nicolás Olate

**Comment by mimadri** [comment]
Hola! 

Para el bonus que indicas sólo debes fijarte en que los inputs con los que trabaje tu máquina puedan ser de distinto largo. El ejemplo que señalas es correcto, y en ese caso tu máquina debería ser capaz de aceptar el input.

Éxito con la tarea :)

**Comment by nolate26** [comment]
Buena gracias, entendí perfecto. Aún así, si opto por usar este bonus me podrían aparecer inputs correctos de los 2 tipos? Como por ejemplo **101#100#11#10** y/o **101#100#011#010**. O podría ser entre ambos, lo cual me complica un poco, algo así como:   **101#100#011#10**
Muchas gracias!

**Comment by mimadri** [comment]
Los tres ejemplos que señalas deberían ser aceptados por tu máquina, el tercero contaría dentro de lo que debe manejar el bonus, ya que es de largo variable. 

Espero se haya entendido :)
