### ISSUE TITLE
TC3 - Cantidad de estados y extensión informe

### ISSUE THREAD

**Issue by carmebe** [Exploratorio-DCC-PUC/Syllabus#646]
Hola, el asunto es que ya tengo una máquina que cumple los 2 bonus, pero tiene alrededor de 29 estados (algunos son para indicar la razón de por qué se detiene, y la gran mayoría para realizar comparaciones para ciertos casos, etc.), y tengo una consulta si es que hay un límite de los estados que la máquina puede tomar, y si es que está permitido poner muchos, el informe puede quedar muy extenso (aún no lo he hecho, pero para la parte de describir los estados, este puede extenderse bastante). Igual estoy haciendo diagramas de cómo la máquina funciona que debería resumir por completo todo.

Saludos!

**Comment by MFMG99** [comment]
Hola!
No hay un límite de estados, mientras funcione y no se demore una cantidad exagerada de tiempo está todo bien :)
Si existen muchos estados que hacen lo mismo, puedes agruparlos, decir que son similares y describir lo que hacen, pero haciendo énfasis en las leves diferencias que debiesen tener (así no tienes que escribir muchas veces lo mismo uwu)
Saludos c:
