### ISSUE TITLE
Problema al clonar el repositorio

### ISSUE THREAD

**Issue by sebastiangamerre** [Exploratorio-DCC-PUC/Syllabus#647]
Hola, cambie de computador y descargue de nuevo git bash para poder clonar el repositorio (y poder subir la tarea), pero al momento de intentar clonar, la consola se queda así: (lleva como 10 min igual por 2da vez y solo se creo la carpeta sin ningún archivo)
![Sin título](https://user-images.githubusercontent.com/80768609/122847366-8b305680-d2d5-11eb-9ae5-25c68e08a6c5.png)
Que puede estar pasando?, se agradece cualquier sugerencia c: (y parece que no soy al único que le pasa jeje)

**Comment by KrishnaChaparro** [comment]
Hola, a mi me pasa lo mismo y descargue de nuevo los softwares y nada (también cambie de computador).

**Comment by MFMG99** [comment]
Hola @KrishnaChaparro @sebastiangamerre ! Solo para estar segura xd ¿Iniciaron sesión en git con su usuario de github en el que tienen acceso al repo?

**Comment by KrishnaChaparro** [comment]
sinceramente no recuerdo los comandos que se ponen antes de comenzar a utilizar el  git bash recien instalado.

**Comment by sebastiangamerre** [comment]
ese era un paso que no recordaba jajaja, pero de igual forma ahora que inicie sesión en git me sigue pasando lo mismo (verifique que estaba usando el mismo nombre de usuario y el correo asociado a github)

**Comment by MFMG99** [comment]
@KrishnaChaparro  te recomiendo ver las instrucciones de lo que hiciste a principios de semestre para configurar git, quizás este [link](https://docs.gitlab.com/ee/gitlab-basics/start-using-git.html) te sirva también

@sebastiangamerre  ¿me podrías mandar un pantallazo de lo que te sale ahora que iniciaste sesión?

**Comment by KrishnaChaparro** [comment]
Yo también lo hise y tampoco me funciona:
![1](https://user-images.githubusercontent.com/80900635/122858135-c5a2ef00-d2e7-11eb-8716-1f242c66b126.PNG)
![2](https://user-images.githubusercontent.com/80900635/122858204-e4a18100-d2e7-11eb-862a-a4d91dfe19c8.PNG)

**Comment by felipegarcia98** [comment]
Hay que cachar. En mi pc pude clonar ambos repos 🤔 

![image](https://user-images.githubusercontent.com/42228743/122860506-d48ba080-d2eb-11eb-9da3-a573857cc8de.png)

prueben actualizando (updating) git 

PD: En los permisos de GitHub sale que uds tienen acceso, por lo que no deberia ir por temas de permisos 🤔

**Comment by sebastiangamerre** [comment]
actualice git (clonando git desde git bash) y ya estaba con la ultima versión, sigo sin poder clonar el repo de la tarea, de igual forma ahora mismo estoy usando una maquina antigua con win7, no se si eso seria fuente del problema :c

**Comment by MFMG99** [comment]
Hola nuevamente! Dadas las casualidades de la vida yo también estaba en proceso de cambiarme de pc, acabo de descargar y configurar git (y pude descargar ambos repositorios), hice lo siguiente
`git config --global user.name 'USERNAME'`
`git config --global user.email 'EMAIL'`
`git clone LINK_AL_REPO`

@sebastiangamerre quizás este [link](https://stackoverflow.com/questions/4485059/git-bash-is-extremely-slow-on-windows-7-x64) sea de ayuda

**Comment by MFMG99** [comment]
@KrishnaChaparro podrías mostrarme un pantallazo de qué es lo que te sale al clonar tu repo? (hacer `git clone LINK_AL_REPO`)?

**Comment by sebastiangamerre** [comment]
acabo de volver a cambiar de pc, ahora a uno mejor, volvi a descargar git y lo configure con el usuario y correo, pero sigue sin funcionar :c (sigue quedandose pegado igual que en el primer pantallazo)

**Comment by MFMG99** [comment]
@sebastiangamerre sigue siendo windows 7? revisaste el [link](https://stackoverflow.com/questions/4485059/git-bash-is-extremely-slow-on-windows-7-x64)? si pones `git config --global --list` qué te sale?

Aquí hay otra guía de [cómo instalar y usar git en windows](https://www.computerhope.com/issues/ch001927.htm#install)

**Comment by sebastiangamerre** [comment]
ahora estoy en win10, y revise el link, ya coloque algunas configuraciones extra y lo corro como administrador, pero aun no se resuelve
![Anotación 2021-06-22 141301](https://user-images.githubusercontent.com/80768609/122977997-03455d80-d364-11eb-98d8-e3b4c27a58d7.png)

**Comment by felipegarcia98** [comment]
Te funciona si intentas clonar otro repo, no se, otra de tus tareas :🤔

**Comment by sebastiangamerre** [comment]
intente clonar otro repo, sigue sin funcionar. Ya me quede sin ideas jsjsj (cuando intento cerrar git bash me aparece esto [el numero de WPID y PID cambia cada vez])
![Screenshot 2021-06-22 211058](https://user-images.githubusercontent.com/80768609/123019400-6522b900-d39e-11eb-9176-5f3bb768ca7f.png)

**Comment by MFMG99** [comment]
@KrishnaChaparro @sebastiangamerre escriban lo siguiente en la consola y manden pantallazo de qué les sale:
`ping www.google.cl`

**Comment by sebastiangamerre** [comment]
![Screenshot 2021-06-22 212650](https://user-images.githubusercontent.com/80768609/123020644-9ac8a180-d3a0-11eb-9a37-cf28af0b9682.png)

**Comment by MFMG99** [comment]
@sebastiangamerre has estado tratando de hacer git clone con la misma conexión de internet? quizás puedas tratar cambiándola. Si no funciona puedes consultar este [link](https://docs.github.com/en/get-started/using-github/troubleshooting-connectivity-problems) y me avisas cómo te va :c

**Comment by felipegarcia98** [comment]
[Este stackoverflow promueve usar los siguientes comandos:](https://stackoverflow.com/questions/30915579/git-clone-hangs-in-windows-bash) `GIT_TRACE=1; GIT_CURL_VERBOSE=1 git clone --verbose http://github.com/rajasimon/yourproject.git` para debuggear y revisar cual es la fuente de fallas.

A lo mejor la falta de determinada carpeta podría ser la causa (si es que tmbn tienes problemas para clonar otros repos), como [se señala acá](https://github.com/gitextensions/gitextensions/issues/1189#issuecomment-362583440)

**Comment by sebastiangamerre** [comment]
Corri el codigo que mandaste, se pega en este paso 
![image](https://user-images.githubusercontent.com/80768609/123026069-9359c600-d3a9-11eb-8ede-41f3b7785587.png)
Y revise el segundo link, efectivamente esa carpeta no estaba en el lugar que correspondia pero aun sigue sin funcionar
*Al realizar el git fetch tambien se pega la consola

**Comment by MFMG99** [comment]
@KrishnaChaparro Hola! si sigues con el mismo problema, lo que le pasaba a @sebastiangamerre era que no podía clonar repos privados por no tener un token de github, este es el [link para crear uno](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) c:

**Comment by MFMG99** [comment]
@sebastiangamerre **[Importante]** No puedes olvidarte del access token porque nunca más podrás volver a verlo una vez generado, anótalo en algún lado xd

**Comment by sebastiangamerre** [comment]
si lo deje anotado jaja, muchas gracias son unos amores <3<3

**Comment by KrishnaChaparro** [comment]
@MFMG99  hola!! disculpa, esque me enfoque en hacer la tarea primero jeje, aún tengo el mismo problema, la verdad es que no entiendo bien eso de los token pero lo intentaré.

**Comment by KrishnaChaparro** [comment]
No me funciona, no me pide las credenciales, y apretó el link de abajo cuando no las pide pero me dice que la pagina no existe.

**Comment by KrishnaChaparro** [comment]
![3](https://user-images.githubusercontent.com/80900635/123347744-15232e00-d527-11eb-84a0-ad44807d0863.PNG)
Corrí el código que mandaron y para acá, no entiendo que significa.

**Comment by MFMG99** [comment]
Holaa @KrishnaChaparro 
Por lo que veo en tu consola te pasa lo mismo que a Sebastián, debes crear un access token, si no entendiste muy bien los pasos del [link anterior](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token), aquí hay un [video tutorial](https://www.youtube.com/watch?v=kHkQnuYzwoo) que puede servirte c:

**Comment by KrishnaChaparro** [comment]
ya lo hise pero no me funciona, se sigue quedando pegado y no me pide la contraseña

**Comment by KrishnaChaparro** [comment]
Lo desinstale y lo instale de nuevo y quedo con las credenciales guardadas no se si es normal:
![4](https://user-images.githubusercontent.com/80900635/123363599-de5a1180-d540-11eb-8fb9-7a1c3a450f35.PNG)
En todo caso lo hice de nuevo, pero aun se queda pegado y no me pide las credenciales:
![5](https://user-images.githubusercontent.com/80900635/123363637-f467d200-d540-11eb-8815-1ad77c1aeb5f.PNG)

**Comment by diegotmz** [comment]
Hola, yo creo haberlo solucionado. Git Bash no te deja clonar repositorios privados si no has iniciado sesión en GitHub. Para hacer esto el comando es git config --global github.user "usuario". Después de hacer esto te deja clonarlo de manera normal, quizás debas ingresar también tu token con git config --global github.token "token". Al hacer esto deberían poder clonarlo de manera normal y sin algún comando raro ingresando su clave.
