### ISSUE TITLE
TC3 Bonus

### ISSUE THREAD

**Issue by emiliaup** [Exploratorio-DCC-PUC/Syllabus#648]
Hola! En el bonus de la tarea,¿A que se refiere con eliminar el cuarto supuesto o el tercer supuesto? logre hacer todo el código en una cinta, pero no elimine nada :( estoy un poco confundida

**Comment by MFMG99** [comment]
Hola! En el enunciado pusimos una serie de supuestos a considerar:
![Captura de Pantalla 2021-06-22 a la(s) 11 57 38](https://user-images.githubusercontent.com/48294273/122960285-43e7ab80-d351-11eb-841d-f8e41e60accd.png)
Con eliminar el tercer supuesto se refiere a que ahora te entregaremos inputs de distinto largo (del tipo 100#11#10#1) y con eliminar el cuarto supuesto se refiere a que la máquina no puede tener más de 1 cinta.
Saludos c:

**Comment by emiliaup** [comment]
aaa perfecto gracias :)
