### ISSUE TITLE
Parte II 2. Peliculas que no se han comprado

### ISSUE THREAD

**Issue by jitorralba** [Exploratorio-DCC-PUC/Syllabus#65]
Hola, quería saber si el output debe incluir las peliculas que no se han comprado (y cuya recaudación por ende es 0). Ya que de ser así no se podrían igualar los id_user, ya que no están en la tabla PURCHASES.

**Comment by ValentinaAlvarezG** [comment]
Hola!
Las películas que no se han comprado no es necesario que aparezcan en el output. La idea es que sea la recaudación de sólo las que se han vendido (y que comiencen con la letra A)
