### ISSUE TITLE
TC3 - Segunda pregunta del informe

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#650]
Solo para estar seguros, ya que las letras de la tupla máquina de turing ya se definen formalmente en el enunciado, asumo que no debemos repetir esta información y simplemente enumerar esos elementos en nuestras máquinas?

**Comment by MFMG99** [comment]
Queremos que definas formalmente **tu** Máquina de Turing, en el enunciado definimos la máquina que está en el ejemplo, queremos que definas formalmente la tuya, con tus estados, tu alfabeto, etc.

**Comment by fernandosmither** [comment]
> Queremos que definas formalmente **tu** Máquina de Turing, en el enunciado definimos la máquina que está en el ejemplo, queremos que definas formalmente la tuya, con tus estados, tu alfabeto, tus funciones de transición, etc.

Súper!

**Comment by Gau04** [comment]
Hola! respecto a esta pregunta a mi me queda la duda si es necesario definir formalmente las funciones de transición, ya que en el enunciado se señala "Una definición formal para Q; q0; Γ; F"

**Comment by MFMG99** [comment]
Holaa @Gau04 !
No, no es necesario definir formalmente las funciones de transición. Siento la confusión c:
