### ISSUE TITLE
TC3 - Pregunta 1, consideraciones

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#651]
¿Qué tan específica tiene que ser la explicación 1 del informe?

Por ahora tengo una explicación de una plana que revisa abstractamente la idea, sin necesariamente hacer referencia a los estados mismos. Explico el porqué la máquina finaliza bien dado los supuestos de que el input sea correcto, y luego explico 2 formas en que el código podría caerse, pero quizás de una forma más teórica y matemática.

Está bien? o debo ser mucho más directo e ir como paso a paso, que estado llama a cual y detallarme más? (por ahora mi informe completo, considerando las otras preguntas tiene 4 planas)

**Comment by MFMG99** [comment]
En la parte 1 del informe debes explicar **paso a paso** (y de manera **completa, pero precisa**) lo que hace tu máquina y **cómo** lo hace, desde que recibe el input hasta que lo acepta o rechaza (es para evaluar que realmente saben lo que está pasando en la máquina). Si leemos la respuesta deberíamos entender lo que está haciendo tu máquina sin tener que leer el código. Si crees que cumple todo esto, debería estar bien.

Imagina que le das un input a tu máquina, ¿qué pasos realizará hasta aceptar/rechazar el input?, ¿qué decisiones tomará?, ¿cómo lo hará?, etc.

**Comment by fernandosmither** [comment]
> En la parte 1 del informe debes explicar **paso a paso** (y de manera **completa, pero precisa**) lo que hace tu máquina y **cómo** lo hace, desde que recibe el input hasta que lo acepta o rechaza (es para evaluar que realmente saben lo que está pasando en la máquina). Si leemos la respuesta deberíamos entender lo que está haciendo tu máquina sin tener que leer el código. Si crees que cumple todo esto, debería estar bien.
> 
> Imagina que le das un input a tu máquina, ¿qué pasos realizará hasta aceptar/rechazar el input?, ¿qué decisiones tomará?, ¿cómo lo hará?, etc.

Y puedo hacerlo a grandes razgos, detallando solo los estados más importantes, ya que en la tercera pregunta detallo todos?

**Comment by MFMG99** [comment]
> > En la parte 1 del informe debes explicar **paso a paso** (y de manera **completa, pero precisa**) lo que hace tu máquina y **cómo** lo hace, desde que recibe el input hasta que lo acepta o rechaza (es para evaluar que realmente saben lo que está pasando en la máquina). Si leemos la respuesta deberíamos entender lo que está haciendo tu máquina sin tener que leer el código. Si crees que cumple todo esto, debería estar bien.
> > Imagina que le das un input a tu máquina, ¿qué pasos realizará hasta aceptar/rechazar el input?, ¿qué decisiones tomará?, ¿cómo lo hará?, etc.
> 
> Y puedo hacerlo a grandes razgos, detallando solo los estados más importantes, ya que en la tercera pregunta detallo todos?

Sip, mientras se entienda qué esta haciendo la máquina todo bien c:
