### ISSUE TITLE
TC3 Pregunta 2 informe

### ISSUE THREAD

**Issue by SebaMartinezM** [Exploratorio-DCC-PUC/Syllabus#653]
Hola debemos definir todas las funciones de transición para todo los estados? pregunto ya que al menos en mi caso sería muy extenso realizar esto.

**Comment by mimadri** [comment]
Hola!

Como comentamos en la ayudantía, si cuentas con varios estados que cumplen una función similar, no es necesario definir cada uno por separado, puedes agruparlos mencionando cuáles son y qué función cumplen.

Espero haber aclarado tu duda :)
