### ISSUE TITLE
TC3 Entrega

### ISSUE THREAD

**Issue by SebaMartinezM** [Exploratorio-DCC-PUC/Syllabus#655]
Hola, debemos eliminar los archivos README.md y main.tex del repositorio?

**Comment by mimadri** [comment]
Hola!

El archivo readme.md debe quedar en el repo, y en cuanto al main.tex, este debe ser reemplazado por el archivo .tex que compila tu informe (si ocupas imágenes estas también deben incluirse en el repo).

Éxito con la tarea :)

**Comment by SebaMartinezM** [comment]
Gracias!

**Comment by emiliaup** [comment]
Hola! sobre la entrega, el archivo donde contiene el main.tex y las imagenes usadas en main.tex, tiene que estar en .zip?

**Comment by mimadri** [comment]
Hola!

No es necesario comprimirlos, basta con incluir todos los archivos necesarios para compilar su informe.

Éxito con la tarea :)

**Comment by sachondo7** [comment]
hola! cuando descargo el formato en.tex me crea una carpeta con el informe y las fotos que utilicé. 
Puedo subirlo así como carpeta o tengo que subir cada archivo por separado?

**Comment by mimadri** [comment]
Hola!

No hay problema con que lo subas en la carpeta que te crea.

Éxito :)
