### ISSUE TITLE
Descuentos TC3

### ISSUE THREAD

**Issue by CataLebe** [Exploratorio-DCC-PUC/Syllabus#656]
Hola, quería preguntar a qué se refiere el segundo descuento que aparece en el enunciado de la tarea "0.5 puntos por mantener los _ejemplos_ de la plantilla en su informe" ¿significa que no puedo usar el formato que ya está en la plantilla?
O más bien ¿qué son específicamente esos _ejemplos_ que no se pueden mantener en el informe?

**Comment by MFMG99** [comment]
Holaa! Nos referimos a **no** mantener el contenido del template, todos esos ejemplos que salen como "Comandos Básicos LaTex". La idea es que usen el formato del template, pero que cambien el contenido de este por su informe c:

**Comment by CataLebe** [comment]
Genial, muchas gracias.

**Comment by sachondo7** [comment]
hola, no me queda claro si tenemos que borrar el main.tex que viene por predeterminado en el repo o da lo mismo, siempre y cuando el informe.tex no tenga esos ejemplos que mencionas que hay que borrar. 

gracias

**Comment by MFMG99** [comment]
Hola! **El archivo `.tex` que debe estar en el repo es el tuyo, el que debe llamarse `informe.tex`.**
El `main.tex` del repo se lo damos para que lo usen como una plantilla para poder crear su `informe.tex`.
