### ISSUE TITLE
TC3 - Informe - Explicación de la máquina

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [Exploratorio-DCC-PUC/Syllabus#658]
Hola!
Al momento de realizar la explicación de nuestra máquina, ¿Qué tan especifica debe ser la explicación?. Por ejemplo, si realizo una resta en binario, ¿debo explicar como funciona la resta en binario?, ¿o basta con que diga que se realiza una resta en binario, y cite la fuente desde donde me inspiré para implementarla en la máquina?
También, en las instrucciones hablan del uso de diagramas. ¿Está incorrecto si no uso uno, en caso de que no lo considere necesario en la explicación?

**Comment by MFMG99** [comment]
> Al momento de realizar la explicación de nuestra máquina, ¿Qué tan especifica debe ser la explicación?. Por ejemplo, si realizo una resta en binario, ¿debo explicar como funciona la resta en binario?, ¿o basta con que diga que se realiza una resta en binario, y cite la fuente desde donde me inspiré para implementarla en la máquina?

Hola! Con la explicación nosotros debemos saber qué es lo que está haciendo tu máquina sin necesidad de ir a leer e interpretar tu código. En el caso de que te hayas inspirado en un código de otro lado, no basta con decir "usé la resta de esta página", debes explicarnos qué es lo que hace esta resta para saber que entendiste bien lo que encontraste en internet y no fue solo copy-paste.

> También, en las instrucciones hablan del uso de diagramas. ¿Está incorrecto si no uso uno, en caso de que no lo considere necesario en la explicación?

Si no encuentras que sea necesario el uso de diagramas para explicar tu código porque se entiende bien con palabras, todo bien :)

Saludos!

**Comment by ElTioAndresCabezas** [comment]
Dale. Igual destacar que mi fuente no tiene nada de codigo, sino que una explicación para humanos de como hacer la resta de numeros binarios
