### ISSUE TITLE
TC4 Poster

### ISSUE THREAD

**Issue by Jesusdelgad** [Exploratorio-DCC-PUC/Syllabus#659]
Hola tengo una consulta de la tarea chica 4 , cuando ponen realizar un poster que resuman los elementos básicos , a que se refieren con poster? , como un miniresumen de los elementos ( con iconos) que utilizamos junto a una pequeña descripción de este? , muchas gracias de antemano.

**Comment by sofiaolmedos** [comment]
Hola!

Lo único que deben entregar en esta tarea es un pdf con el diagrama, y con sus supuestos en el caso de que hagan alguno.

Asumo que tu pregunta es sobre el último punto del enunciado, con esto nos referimos a que en la carpeta de Tareas/TC4 del Syllabus nosotros les dejamos un poster con los elementos básicos de BPMN que les puede ser útil para la tarea.

Saludos😄
