### ISSUE TITLE
TC4 - Duda de enunciado

### ISSUE THREAD

**Issue by isufan** [Exploratorio-DCC-PUC/Syllabus#660]
Hola! Se debe asumir que el paciente nunca va a dejar el centro médico hasta que sea dado de alta? O puede volver a casa para realizar alguna indicación (como tomar un medicamento) y luego ir de nuevo al centro médico a un control?

Muchas gracias de antemano.

**Comment by sofiaolmedos** [comment]
Hola! 

Puedes asumir que el paciente no abandona el centro médico hasta que se le de permiso.

Saludos😊
