### ISSUE TITLE
TC4 - Gateways

### ISSUE THREAD

**Issue by cpschulz** [Exploratorio-DCC-PUC/Syllabus#661]
Un gateway puede llevar a otros gateways?

![image](https://user-images.githubusercontent.com/69017344/124340667-df182680-db84-11eb-83dd-d84168e13095.png)

Algo asi?

**Comment by fernandosmither** [comment]
Hola! No soy ayudante pero yo me he basado en lo que mostró el profesor en clases.

![image](https://user-images.githubusercontent.com/66154723/124370314-3b8e4b00-dc44-11eb-9154-f30d95027d9b.png)

Creo que lo importante es como los cierras y la lógica de lo que quieres hacer.

**Comment by cpschulz** [comment]
Ah, buena! Que clase es?

**Comment by fernandosmither** [comment]
> Ah, buena! Que clase es?

La segunda de bpmn

**Comment by sofiaolmedos** [comment]
Hola!
Como dice Fernando, si se pueden usar gateways dentro de otros, e incluso muchas veces es necesario. Eso si deben de tener cuidado con qué tipo de gateway deciden usar para qué cosa, y asegurarse de cumplir con el funcionamiento de cada uno.
Saludos😄
