### ISSUE TITLE
TC4 

### ISSUE THREAD

**Issue by fsazo** [Exploratorio-DCC-PUC/Syllabus#662]
Holaaa, se puede usar bpmn.io en vez draw.io para hacer la tarea?

Gracias de antemano

**Comment by fernandosmither** [comment]
> Holaaa, se puede usar bpmn.io en vez draw.io para hacer la tarea?
> 
> Gracias de antemano

Hola, no soy ayudante, pero yo he hecho todo en bpmn.io porque el profesor lo recomendó en la clase, de hecho no recuerdo que hayan dicho que usemos draw.io, aunque el enunciado no te obliga a usar ninguno 😅

**Comment by fsazo** [comment]
Buenaa, usaré bpmn.io entonces. Muchas gracias!!

**Comment by sofiaolmedos** [comment]
Holaa
Como dice Fernando, queda a decisión de ustedes que programa usar para hacer el diagrama.
Saludos 😊
