### ISSUE TITLE
TC4 - Subprocesos

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#663]
Es obligatorio (hay un punto en la pauta que lo pida) hacer uso de los subprocesos? O puedo evitar utilizarlos por simpleza?

**Comment by cpschulz** [comment]
Y como se detallan? Si tengo un subproceso que quiero decir lo que pasa

**Comment by sofiaolmedos** [comment]
Hola! @fernandosmither no te puedo decir si deben o no usar los subprocesos, eso lo deben decidir ustedes mismos al leer el enunciado. Pero para explicar un poco, los subprocesos se usan para facilitar el flujo principal del modelo. Si se tiene que modelar una tarea muy específica y se cree que al ponerla en el diagrama principal se obstaculiza un poco el flujo general, se debe hacer un subproceso. En la ayudantía pueden ver un ejemplo.

**Comment by sofiaolmedos** [comment]
@cpschulz para incorporar un subproceso,  se agrega un +, los programas que usen deberían tener como opción el cuadro de un subproceso. Dependiendo de qué tan relevante es la tarea, y de qué tanto detalle disponen de esta, pueden modelarla como un nuevo proceso con los mismos elementos ya conocidos (deben siempre cerrarla), también pueden no anexar el subproceso si no es necesario.

**Comment by fernandosmither** [comment]
> @cpschulz para incorporar un subproceso, se agrega un +, los programas que usen deberían tener como opción el cuadro de un subproceso. Dependiendo de qué tan relevante es la tarea, y de qué tanto detalle disponen de esta, pueden modelarla como un nuevo proceso con los mismos elementos ya conocidos (deben siempre cerrarla), también pueden no anexar el subproceso si no es necesario.

Para mi tarea yo consideré un subproceso como importante, y consideré otros 2 menos importantes o que no se detalllaban por completo. El "importante" lo hice como un subproceso expandido, el cual como mencionas le hice una secuencia de inicio hasta término, y los "menos importantes" los dejé simplemente como subprocesos colapsados. ¿Se aceptará ese formato?

**Comment by sofiaolmedos** [comment]
@fernandosmither el formato estaría correcto. Como consejo, ten cuidado con abusar de los subprocesos, si algo es muy relevante en el modelo es mejor dejarlo en el flujo principal.

**Comment by sofiaolmedos** [comment]
@cpschulz como la entrega es con un pdf, puedes simplemente ponerlo en otra página, la idea es que quede en otro diagrama.

**Comment by fernandosmither** [comment]
> @cpschulz como la entrega es con un pdf, puedes simplemente ponerlo en otra página, la idea es que quede en otro diagrama.

Ahh, y no puedo dejar el subproceso expandido en la misma lane? (creo que en mi caso no se ve muy feo)

**Comment by sofiaolmedos** [comment]
@fernandosmither lo mejor es ponerlo a parte, pero si no lo quieres hacer, el diagrama debe quedar fácil de entender y leer.
