### ISSUE TITLE
TC4 - Mensajes enviados

### ISSUE THREAD

**Issue by fernandosmither** [Exploratorio-DCC-PUC/Syllabus#664]
En clases vimos ejemplos donde las tasks enviaban mensajes, sin el ícono del mensajito, pero en la ayudantía sí se usaron.
![image](https://user-images.githubusercontent.com/66154723/124371240-d3446700-dc4d-11eb-8be3-69929f9397ac.png)

Nos pedirán el uso de ese símbolo en la evaluación para tasks mensajeras?

**Comment by sofiaolmedos** [comment]
Hola!!
Si no lo quieren agregar a las tareas, no se va a descontar. Ojo que para los eventos si es necesario ponerlo. 
Saludos 😊

**Comment by fernandosmither** [comment]
> Hola!!
> Si no lo quieren agregar a las tareas, no se va a descontar. Ojo que para los eventos si es necesario ponerlo.
> Saludos 😊

con "para los eventos si es necesario ponerlo." te refieres a lo siguiente? 😅 
![image](https://user-images.githubusercontent.com/66154723/124488837-51a02680-dd7e-11eb-9449-db983961d080.png)

**Comment by sofiaolmedos** [comment]
@fernandosmither eso mismo
