### ISSUE TITLE
TC4 - Procesos recurrentes

### ISSUE THREAD

**Issue by cpschulz** [Exploratorio-DCC-PUC/Syllabus#665]
Hola, estoy confundida en como funcionan los procesos recurrentes y como usarlos. 
![image](https://user-images.githubusercontent.com/69017344/124817866-56103f00-df38-11eb-8fdf-f43df34f7467.png)
Tengo esto para una parte de la tarea, pero no se como cerrarlo, pensaba que podia devolverlo al gateway, pero quedaría igual la opcion de que se quede dando vueltas infinitamente, y estaba tratando de interrumpirlo con un mensaje, pero bpmn.io no permite que el mensaje "llegue" a la tarea...
Alguna sugerencia?

**Comment by sofiaolmedos** [comment]
Hola!
Al poner un ciclo dentro de un gateway, lo que ocurre es que el ciclo se repite un número x de veces hasta que el resto de las tareas dentro del gateway se cumplan, dependiendo de qué tipo de gateway estás usando. Como dijiste, deberías "devolverlo" al gateway, y no se quedaría dando vueltas infinitamente. 
Suerte con lo que queda 😄
