### ISSUE TITLE
TC4- Evento señal y subprocesos

### ISSUE THREAD

**Issue by SCarcG1** [Exploratorio-DCC-PUC/Syllabus#666]
Se puede usar otro evento aparte de los de mensajes y de tiempo para esta tarea?
En especifico quiero usar el evento de señal para esta tarea
![Evento_Señal](https://user-images.githubusercontent.com/81240257/125012255-e5e8e280-e037-11eb-9dd3-e7df81703a01.PNG)

Además, si quiero tener un subproceso debo de presentarlo dentro del mismo lane? Y si realizo una actividad de llamada lo incluyo en un costado toda la actividad, por ejemplo en un pool aparte?

**Comment by sofiaolmedos** [comment]
Hola

Para esta tarea no son necesarios otro tipo de eventos, por eso no lo vimos en la ayudantía. Al hacer un subproceso, si lo quieres desarrollar de manera detallada, debes hacer un anexo donde esté el subproceso con todos los lanes y pools que use. Una actividad no puede ser descompuesta, solo los subprocesos.

**Comment by SCarcG1** [comment]
Lo lamento, no entendí la segunda respuesta. ¿ Si tengo un subproceso que lo realizo dos veces en situaciones separadas puedo utilizar una actividad de llamada (el rectangulito con líneas bien gruesas mas el simbolito mas de todo subproceso), al menos en este trabajo? pregunto debido a que leyendo el poster y la documentación me aparece que esta es reutilizable.

**Comment by SCarcG1** [comment]
> Hola
> 
> Para esta tarea no son necesarios otro tipo de eventos, por eso no lo vimos en la ayudantía. Al hacer un subproceso, si lo quieres desarrollar de manera detallada, debes hacer un anexo donde esté el subproceso con todos los lanes y pools que use. Una actividad no puede ser descompuesta, solo los subprocesos.

Lo lamento, no entendí la segunda respuesta. ¿ Si tengo un subproceso que lo realizo dos veces en situaciones separadas puedo utilizar una actividad de llamada (el rectangulito con líneas bien gruesas mas el simbolito mas de todo subproceso), al menos en este trabajo? pregunto debido a que leyendo el poster y la documentación me aparece que esta es reutilizable.

**Comment by sofiaolmedos** [comment]
Si puedes, aunque también podrías poner el subproceso dos veces
