### ISSUE TITLE
TC4- Duda sobre compuertas

### ISSUE THREAD

**Issue by SCarcG1** [Exploratorio-DCC-PUC/Syllabus#667]
¿las compuertas basadas en eventos en eventos, una vez que se quiera hacer el join, debo de utilizar una compuerta exclusiva, o inclusiva?

**Comment by sofiaolmedos** [comment]
Debes cerrarla con la misma compuerta con la que comenzó (una compuerta de eventos). En todo caso, no es necesario usar cosas tan complejas en esta tarea. Con lo visto en la ayudantía debería ser suficiente.

**Comment by sebacamposdavis** [comment]
En ese caso, luego de utilizar una compuerta exclusiva y realizar una actividad asociada, ¿debo volver a utilizar otra compuerta para continuar el flujo?

**Comment by sofiaolmedos** [comment]
@sebacamposdavis No necesariamente, en el caso de compuertas paralelas o inclusivas si. Les recuerdo que se **vean la ayudantía**.

**Comment by SCarcG1** [comment]
> Debes cerrarla con la misma compuerta con la que comenzó (una compuerta de eventos). En todo caso, no es necesario usar cosas tan complejas en esta tarea. Con lo visto en la ayudantía debería ser suficiente.

Es que es debido a que las compuertas por eventos no me permiten cerrar el gateway con una compuerta de eventos, al menos en bpmn.io.  ¿Seguro que no hay que usar una exclusiva, debido a que ambas lo son?

**Comment by SCarcG1** [comment]
Pregunto debido a que al menos, siguiendo la guía de usuario de BizAgi, [https://help.bizagi.com/bpm-suite/es/](url), menciona que una buena practica es que para cerrar el flujo dividido por la compuerta de eventos es no utilizar otra compuerta de eventos. (si se mete al sitio, puede encontrar lo que digo en la pestaña  Bizagi Studio>Asistente de Procesos> Mejores practicas en modelos de procesos. Luego Sección 2 de la pagina). Es importante debido a que después de cerrar el flujo tengo una tarea, y no un evento, por lo que como digo en bpmn.io no me deja juntar la flecha.

**Comment by sofiaolmedos** [comment]
@SCarcG1 comprendo, toda la razón. Debes cerrarla con la compuerta acorde a lo que estás intentando hacer, las exclusivas e inclusivas se usan en diferentes situaciones asi que debes analizar cual es el uso que le diste a la compuerta de evento.
