### ISSUE TITLE
TC4 - Uso compuerta exclusiva

### ISSUE THREAD

**Issue by sebacamposdavis** [Exploratorio-DCC-PUC/Syllabus#668]
Hola, tengo una duda sobre las compuertas exclusivas

Tengo entendido que es una buena práctica describir el flujo a través de la compuerta, específicando qué criterio se utiliza para seguir el flujo (Ejemplo: ¿Hecho? Sí/No -> "Tarea"). ¿Pero qué pasa si mi compuerta tiene varias acciones posibles y finalmente el flujo se determina por la acción que se quiera realizar? (Ejemplo: ¿Qué escoge X? -> Escogió Y -> X ejecuta Y) En este caso siento que es un poco redundante poner "Escogió Y" ya que se hace evidente al ver la acción que le sigue, ¿es necesario ponerlo igual?

Perdón si es muy confusa la pregunta

**Comment by sofiaolmedos** [comment]
Holaa
Si entendí bien tu duda, no es necesario poner la pregunta en la compuerta, eso se usa más que nada para facilitar la lectura del diagrama. Si crees que queda todo claro con solo ver la acción que le sigue a la compuerta, está bien si no lo pones.
