### ISSUE TITLE
Examen 2021-1

### ISSUE THREAD

**Issue by denisparra** [Exploratorio-DCC-PUC/Syllabus#669]
En este issue se agregarán preguntas y respuestas del examen 2021-1.
El examen estará abierto entre 8am y 13:30 del lunes 19 de julio de 2021.
El profesor estará disponible via zoom para preguntas en vivo entre 8:30am y 10am. El link a zoom está en canvas (no se pone acá por seguridad)

[p1] no sé si ya lo preguntaron, pero en la 1 se pide eliminar el archivo [minombre]_2.txt.txt, debo escribir .txt dos veces o es un error?

**Respuesta**: Es un error de tipeo en el enunciado, el archivo a eliminar es  [minombre]_2.txt

[p2] en la pregunta 1, ¿a qué se refiere el nombre de pila ?

**Respuesta**: se refiere a la parte de tu nombre que no es tu apellido, si te llamas Arturo Carlos Perez Pinares, tu nombre de pila es "Arturo".

[p3] hay un error en la pregunta final (18), la última oración aparece cortada. 

**Respuesta**: Esa oración se debe ignorar. La pregunta correcta es:

[Majors]  (18) ¿Cuál de 3 majors ofrecidos por el DCC UC le interesa más ? ¿por qué razón?Explique dando detalles de temas o clases del exploratorio que le interesaron y cursos que le gustaría tomar.

[p4] ¿cómo es la ponderación de las preguntas?

**Respuesta**: Todas las preguntas valen 1 punto, es decir, ponderación uniforme para las preguntas del examen.

[p5] ¿dónde encuentro la clase sobre Sistemas Operativos?

**Respuesta**:  Está en el módulo de "Arquitectura de Computadores y Sistemas Operativos" pero tiene un nombre extraño, el enlace directo a la clase se encuentra aquí: http://iic2333.ing.puc.cl/slides/exploratorio-os.html#/

[p6] ¿qué tipo de ejemplo se da en la pregunta (15) sobre TF-IDF?

**Respuesta**:  Se sugiere dar un ejemplo similar al entregado en clases, donde se crean 3 documentos y se calcula la tabla (o matriz) termino/documento donde los pesos TF-IDF van en las celdas. Se puede hacer algo similar pero mucho más pequeño, con 2 documentos y menos palabras, pero donde se vea claramente el uso de los fórmulas para calcular los pesos en la tabla (puede ser para algunos términos, no es necesario calcularlo para todos) (se pueden "simular" o inventar los valores de cantidad de documentos donde aparece cada término en el corpus)

**Comment by NicoJGutierrez** [comment]
La pregunta n°7 de visualización en clases fue vista en alrededor de 10 segundos https://drive.google.com/file/d/1YpxFnzsPkbLflXN8QuK39hkQljco_0GI/view entre los segundos 1:14:22 y 1:14:32 por lo que me queda la duda de si realmente resolver una pregunta de examen al respecto sería posible con esa información o se requiere buscar en una fuente externa.

**Comment by AstridESMJ** [comment]
> La pregunta n°7 de visualización en clases fue vista en alrededor de 10 segundos https://drive.google.com/file/d/1YpxFnzsPkbLflXN8QuK39hkQljco_0GI/view entre los segundos 1:14:22 y 1:14:32 por lo que me queda la duda de si realmente resolver una pregunta de examen al respecto sería posible con esa información o se requiere buscar en una fuente externa.

Hola,

En la pregunta se pide definiciones y generar un ejemplo, tú debes definir si esa información más las diapositivas de clases son suficiente información. Se esperan respuestas más bien cortas y que que vayan al tema, respuestas bien precisas.

Saludos,

Astrid,
Ayudante IIC1005
