### ISSUE TITLE
Fecha entrega tc2.

### ISSUE THREAD

**Issue by totichi** [Exploratorio-DCC-PUC/Syllabus#67]
Hola! queria preguntar cuando se entrega finalmente la tarea chica 2, dado que en el enunciado sale que se entrega el lunes a las 23:59 y en el mail enviado de la tarea chica sale que se entrega hoy a las 23:59.
Saludos!
PD: ( me imagino que se hace caso al enunciado no?, pero por si las moscas)

**Comment by Dalal15** [comment]
La fecha de entrega es para el Lunes a las 23:59. 

Saludos!
