### ISSUE TITLE
Pregunta 14 BPMN

### ISSUE THREAD

**Issue by NicoJGutierrez** [Exploratorio-DCC-PUC/Syllabus#671]
Hola, en la pregunta 14 se ve que se habla de 5 acciones que permite hacer el BPMN, estas 5 acciones están explícitas en algún power point (busqué en el de la clase 22/23) o deben ser buscadas de forma implícita en ellos?

**Comment by JupaOlivares** [comment]
Hola no te puedo responder esa pregunta porque es solo un hint y te podria estar soplando la respuesta,, pero, te recomiendo ignorarlo si no lo entendiste y fundamentar tu respuesta en algo de lo conversado en clases
