### ISSUE TITLE
Pregunta 15 Examen

### ISSUE THREAD

**Issue by fcontardo** [Exploratorio-DCC-PUC/Syllabus#672]
Hola, no entiendo algo sobre el calculo del tf-idf.
En general se hace con varios documentos, pero en el enunciado dice 2 palabras en **un** documento, creo dos documentos para mi ejemplo o lo calculo con 1 nomas?

**Comment by IchottMano** [comment]
Hola!

Esta pregunta está en #669 

Saludos
