### ISSUE TITLE
Versiones de Python

### ISSUE THREAD

**Issue by GonzaAlegria** [Exploratorio-DCC-PUC/Syllabus#674]
Hola!
El semestre pasado tomé programación avanzada, ramo en el cual se requería Python versión 3.7
En este ramo se pide la versión 3.9
Mi pregunta es si se pueden tener ambas versiones instaladas a la vez y como dar uso a cada una.
Muchas gracias!

**Comment by JupaOlivares** [comment]
Si, no hay problema. Puedes usar algo como pylauncher o definir las distintas versiones de python como variables de entorno para poder llamarlas desde el terminal (yo he usado este método y ningún problema), te recomiendo ver la siguiente pagina para implementar este método https://levelup.gitconnected.com/how-to-install-and-manage-multiple-python-versions-on-windows-10-c90098d7ba5a .
