### ISSUE TITLE
Duda de enunciado TC1

### ISSUE THREAD

**Issue by pipeaw** [Exploratorio-DCC-PUC/Syllabus#675]
En el archivo PrimerPaso.md donde dice _"...tendras que **mostrar** todos los archivos que contengan || (doble pipe). Esto se debe lograr **mostrando** todos los archivos al mismo tiempo y sin colocarlos manualmente."_ me queda la duda si pide abrir los archivos al mismo tiempo o mostrar/imprimir el contenido de los archivos.

**Comment by josemquinta15** [comment]
Hola!, lo que se pide es **imprimir** el contenido de los archivos que contengan || en consola.

**Comment by nicoz17** [comment]
Holaa! con respecto a la misma parte de la tarea, qué significa que no pueda hacerlo manualmente? Tengo que ocupar un comando que abra los que tienen || automáticamente sin mirarlos como desde documentos?

**Comment by josemquinta15** [comment]
Hola, se refiere a que mediante **un solo comando** se muestren/impriman en consola los contenidos de todos los archivos que contienen en ellos un ||.
