### ISSUE TITLE
Problema paso Final

### ISSUE THREAD

**Issue by JosepVargasf** [Exploratorio-DCC-PUC/Syllabus#677]
Al mover los archivos .bla a la carpeta que tenía mi nombre se eliminaron de las carpetas originales, por lo que en el paso que debía contar la cantidad de archivos el numero que me resultaba no correspondía con la ruta que debía seguir para encontrar el último paso. Me di cuenta y sumé la cantidad de archivos que habían en la carpeta con mi nombre y en la TareaChica1 y logré llegar, pero entiendo que esto puede ser un problema. 
Estaría bien especificar en el paso en que tenemos que mover los archivos .bla que estos no deben ser eliminados, pues son necesarios para pasos más adelante.

**Comment by JupaOlivares** [comment]
Hola! Como dice en la tarea deben moverse (esto significa que dejen de estar en una ubicacion y pasen a estar en la otra), resulta extraño que te haya dado de la otra forma.

**Comment by JosepVargasf** [comment]
Estuve pensando que quizás la carpeta con mi nombre debí crearla en la carpeta TareaChica1 y no en la carpeta del repositorio.
Durante la tarea siempre pensé que la carpeta padre era la carpeta que contenía el repositorio.
Si pudieras ayudarme a entender eso sería bacán 👯

**Comment by josemquinta15** [comment]
Hola, efectivamente es por eso, la carpeta con tu nombre debe ir dentro de la carpeta TareaChica1. Ya que cuando se menciona "en la carpeta padre de esta tarea", se esta haciendo referencia a la carpeta TareaChica1.
