### ISSUE TITLE
Problema al contar archivos

### ISSUE THREAD

**Issue by pepinofdz** [Exploratorio-DCC-PUC/Syllabus#678]
Pude realizar las instrucciones pedidas anteriormente, pero al ejecutar un comando que cuenta los archivos, me otorga un número que, al seguir el resto de las instrucciones, no me lleva a nada: quedo en una carpeta vacía.

Lo primero que pensé fue que el comando que utilicé no era el correcto, por lo que busqué otras alternativas de código abierto (que hubiese citado de funcionar), pero tampoco funcionaban. Después de esto verifiqué el comando en una carpeta de prueba, hecha por mí, y me funcionó a la perfección: agregaba archivos y aumentaba el número, agregaba carpetas vacías y no cambiaba, entre otros. Por esto, creo que el comando está bien, y que quizás tengo archivos de sobra o me falta alguno entre las carpetas del repositorio personal. ¿Cómo podría verificar esto? ¿O saber si mi comando es erróneo?

**Comment by josemquinta15** [comment]
Hola, creaste la carpeta con tu nombre dentro de TareaChica1?, si no es así te recomiendo ver la issue #677

**Comment by pepinofdz** [comment]
Hola! Sí, la carpeta esta dentro de TareaChica. Creí tener un problema parecido al de ese issue por lo que también intenté sumando aparte los archivos de ésta, pero no funcionó.

También tengo screenshots de los comandos que ejecuté en las otras partes, para ponerlos en el informe. Quizás en ellos se pueda visualizar el error.

**Comment by caramelnico** [comment]
Hola!, Yo tuve el mismo problema pero para resolverlo no conté los directorios y ahí llegue al resultado, no se si estaba contemplado de esa manera o no, espero te sirva.

**Comment by pepinofdz** [comment]
Lo solucioné! Lo que me pasó es que sin querer cree 2 archivos en vez de 1 en el paso anterior: busqué ese archivo (dado que fue el único que cree) y me salieron 2 direcciones. Después de eso, mi código funcionó sin problemas. Gracias por la ayuda!
