### ISSUE TITLE
Mover varios archivos a la vez

### ISSUE THREAD

**Issue by rodrigoogalde** [Exploratorio-DCC-PUC/Syllabus#679]
Necesito saber como mover varios archivos que tengan extensión .bla (que están en subcarpetas) a una carpeta
Entiendo que tengo que utilizar el comando mv, pero no me deja porque solo selecciona los archivos que están en la carpeta que se encuentra actualmente

**Comment by JupaOlivares** [comment]
Estas bien encaminado necesitas buscar que parámetro o que otro comando puedes combinar con mv para mover varios archivos  (no te podemos decir exactamente cual porque justamente ese es el objetivo de la tarea buscar y aprender), sitios como stackoverflow son de ayuda (por ahí dicen varias maneras como hacerlo si buscas bien).
