### ISSUE TITLE
dirección concierto

### ISSUE THREAD

**Issue by valeeeriquelme** [Exploratorio-DCC-PUC/Syllabus#68]
un concierto tiene asociado solo una direccion?
osea es que tengo una confusion por ejemplo el concierto believe de justin bieber que se hizo en santiago seria distinto al que se hizo en argentina?
 o es el mismo concierto realizado en distintos lugares?

**Comment by Dalal15** [comment]
En tu ejemplo sería: conciertos distintos, con el mismo nombre en lugares distintos.
Puedes hacer los supuestos que quieras ante estas confusiones, siempre y cuando quede bien modelado el problema y soporte las consultas planteadas.

Saludos!
