### ISSUE TITLE
Contar los Archivos [MacOs]

### ISSUE THREAD

**Issue by bxespinozar** [Exploratorio-DCC-PUC/Syllabus#681]
Hago este Issue para dejar registro de lo que me percaté. 

Al usar Finder (explorador de archivos del sistema) crea archivos ocultos que guardan información sobre la distribución de carpetas, si hay un error cuando se cuentan los archivos y se accede a la ruta erronea a través del finder, al contar nuevamente los archivos el número de los mismos aumentará por estos archivos ocultos que Finder crea. 

Por eso, no hay que usar el finder o usar comandos para descartar estos archivos.

Salu2

**Comment by JupaOlivares** [comment]
Efectivamente si tu computador crea archivos ocultos tienes que encontrar la forma de borrarlos o no considerarlos.
