### ISSUE TITLE
Problema al mover archivos

### ISSUE THREAD

**Issue by scavagnaro** [Exploratorio-DCC-PUC/Syllabus#683]
Hola! Al mover los archivos, no me di cuenta de que debía mover los archivos tareaChica.bla, así que en cambio movi todos los archivos de extensión *.bla. El problema me surge que ya no puedo retroceder y moverlos correctamente, ya que no están en los archivos iniciales. Que me recomiendan?

Las opciones que se me ocurren son: filtrar los archivos que no son tareaChica.bla, y moverlos a otra carpeta para que igual puedan ser contados en el paso 3, o crear de nuevo la carpeta.

**Comment by scavagnaro** [comment]
Me acabo de fijar que todos los archivos *.bla dentro de la carpeta inician con tareaChica, asi que asumo que el problema no tiene inportancia.

**Comment by josemquinta15** [comment]
Claro, en el caso de que todos empiecen con tareaChica y terminen en .bla se estarían moviendo los archivos correctos. Sin embargo, te recomiendo poner en el pdf un comando que cumpla lo solicitado, ya que en el caso de que se añadiesen nuevos archivos .bla tu comando dejaría de funcionar.
