### ISSUE TITLE
¿En el pdf de la tarea se deben incluir los comandos de git que se mostraron en la ayudantia?

### ISSUE THREAD

**Issue by LMD18** [Exploratorio-DCC-PUC/Syllabus#684]
Hola! queria saber si en el pdf de la tarea ¿se deben incluir los comandos de git que se enseñaron en la ayudantia 1 o solamente importan los comandos utilizados para resolver la tarea?

**Comment by josemquinta15** [comment]
Hola!, el archivo pdf debe contener solo los comandos utilizados en tu tarea, junto con un pantallazo de su ejecución en consola.
Los comandos básicos (git push, git pull, git commit, git add, cd, ls) no es necesario explicarlos.
