### ISSUE TITLE
Error al clonar el repositorio

### ISSUE THREAD

**Issue by renatoqueirolo** [Exploratorio-DCC-PUC/Syllabus#685]
Hola, seguí los pasos para crear la llave SSH y al intentar clonar el repositorio me aparece lo siguiente. Vi el video nuevamente para asegurarme de hacer todo igual pero sigue sin funcionar. 

<img width="717" alt="Screen Shot 2021-08-29 at 20 01 18" src="https://user-images.githubusercontent.com/89088195/131269778-fd876f9e-250e-48c7-af95-0880e480469f.png">

Leí en internet que podía ser un error en al archivo de texto, esto es lo que tengo. 

<img width="192" alt="Screen Shot 2021-08-29 at 20 06 22" src="https://user-images.githubusercontent.com/89088195/131269874-e012c315-dc2b-4f66-9e56-7ff0efff9eed.png">

Gracias!

**Comment by josemquinta15** [comment]
Hola! efectivamente el error es en la línea 4 del archivo de texto, ahí debiese decir `IdentityFile` en vez de `IdentifyFile` como tienes. Por lo tanto el archivo de texto debe quedar así:
<pre>
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
</pre>
