### ISSUE TITLE
Problema con 3.2. Generar carpeta de trabajo 

### ISSUE THREAD

**Issue by FVivess** [Exploratorio-DCC-PUC/Syllabus#686]
Hola, al seguir las instrucciones de la tarea, en el paso 3.2 al ejecutar los comandos que se indican me dice que no se puede abrir la carpeta .pyc

![3 2 problema](https://user-images.githubusercontent.com/80867403/131372948-a756b1ac-7a0e-43dc-9558-3981157ad7f1.png)

**Comment by JupaOlivares** [comment]
Hola que version de python tienes? y te aseguraste de haber agregado python al PATH?

**Comment by FVivess** [comment]
Tengo la versión 3.9.0. Lo instale denuevo para asegurarme de agregar el PATH.
