### ISSUE TITLE
Problema paso 3

### ISSUE THREAD

**Issue by LucianoDiazG** [Exploratorio-DCC-PUC/Syllabus#687]
Hola! Tengo un problema con el numero de archivos que tengo en tareachica1/, al obtener este numero me dirijo a las carpetas correspondientes a los 3 últimos dígitos, y no encuentro nada. Para corroborar que aquel numero no esté incorrecto revisé en propiedades el numero de archivos y me muestra el mismo numero que me lleva a una carpeta vacía. ¿Qué me recomiendan hacer? ¿Puedo comenzar todo de nuevo?

**Comment by josemquinta15** [comment]
Hola!, lo primero que te recomiendo comprobar es que la carpeta con tu nombre este dentro de tareachica1, ya que si no le esta justificaría la diferencia en la cuenta. Por otro lado, si la carpeta ya esta dentro de tareachica1, te recomiendo revisar los pasos anteriores que hiciste, ya que probablemente haya un error en alguno de ellos.
Si efectivamente hay un error en algún paso y no es reversible, tendrías que empezar todo desde cero.

**Comment by LucianoDiazG** [comment]
Hola! hace unos 10 minutos comencé todo de nuevo y me funcionó, tal vez borre algo sin querer por ahí. Gracias!!
