### ISSUE TITLE
Empezar todo de nuevo

### ISSUE THREAD

**Issue by juanfdezg** [Exploratorio-DCC-PUC/Syllabus#688]
Hola! quería saber si hay alguna forma de poder empezar todo de nuevo habiendo hecho varios commits ya y git push también. Lo que pasa es que me di cuenta que algo salió mal y volviendo a commits anteriores tampoco se soluciona. ¿Hay alguna forma de poder borrar todo lo que hice, descargar de nuevo el repositorio y empezar todo desde cero? Gracias!

**Comment by josemquinta15** [comment]
Hola!, te recomiendo utilizar git revert o git reset, [Acá lo explican bien](https://www.youtube.com/watch?v=HZ1c25OIX4o). Con eso deberías poder volver al commit inicial de tu repo y empezar a trabajar desde cero.

**Comment by Zarth912** [comment]
Hola! Me paso lo mismo, y luego de ver el video y utilizar git reset, logre trabajar desde 0 hasta que intente hacer push.
Aqui la terminal me enviava el siguiente mensaje
<img width="677" alt="Screen Shot 2021-09-01 at 17 23 59" src="https://user-images.githubusercontent.com/80773706/131747195-e4069a9d-d3fd-4891-b62f-86b586b97d70.png">

¿Que deberia hacer en este caso?

**Comment by juanfdezg** [comment]
Quizás podrías hacer git pull y después git push de nuevo.
