### ISSUE TITLE
Problema al clonar el repositorio

### ISSUE THREAD

**Issue by SofiaFigueroaa** [Exploratorio-DCC-PUC/Syllabus#690]
Hola!! 
Tengo un problema al clonar mi repositorio, me sale este error, he intentado clonando otros y no me pasa este error ni me pide clave (hice lo de la llave ssh). También use una personal access token y tampoco resulta.

Gracias de antemano!
![Captura de pantalla 2021-08-31 a la(s) 20 02 29](https://user-images.githubusercontent.com/89421658/131591533-f62bf9ed-4262-461e-ab9a-6585b0ed3c52.png)

**Comment by josemquinta15** [comment]
Hola!, el problema es que estas clonando el repositorio mediante el link https, debes seleccionar el link que dice SSH para que funcione.

<img width="393" alt="Screen Shot 2021-08-31 at 22 11 57" src="https://user-images.githubusercontent.com/54672128/131600645-6d688bd6-c46d-4c97-9657-6d48d5b4e09f.png">

**Comment by SofiaFigueroaa** [comment]
Super!! Graciaas
