### ISSUE TITLE
Problemas al subir archivo nuevo

### ISSUE THREAD

**Issue by JosefinaGuasch** [Exploratorio-DCC-PUC/Syllabus#691]
Hola!
Estoy teniendo problemas al subir el archivo progreso.txt de la tarea. En un momento cuando quize hacer el commit se fue a una página en que no podía hacer nada y lo cerré. Probablemente algo haya quedado dando vuelta, pero ahora no me deja seguir para subir el archivo. 
Cuando intento me aparece esto:
![Problema git](https://user-images.githubusercontent.com/89088279/131689733-2e36fe0b-8429-4ae6-a06c-e9579f797e4a.png)

**Comment by josemquinta15** [comment]
Hola!, estuve buscando y encontré [esta solución](https://stackoverflow.com/questions/7860751/git-fatal-unable-to-create-path-my-project-git-index-lock-file-exists). Prueba ejecutando el comando que se indica y trata subiéndolo de nuevo a GitHub, recuerda estar parada en el path de tu repo (tc1-2021-2-JosefinaGuasch) al ejecutar el comando.

**Comment by JosefinaGuasch** [comment]
Muchas gracias! Logré arreglarlo con ese código
