### ISSUE TITLE
pregunta sobre commits

### ISSUE THREAD

**Issue by juacob** [Exploratorio-DCC-PUC/Syllabus#693]
hola, he realizado 4 commits sin contar el inicial y los dos primeros que hice no llevaban el nombre descriptivo que se pedia en el PDF de la tarea (si tenian un mensaje pero no era descriptivo), ademas de que el PDF de los comandos tenia un error. Por lo que realice 2 commits mas que si tenian el nombre descriptivo y el segundo de estos contiene el PDF actualizado. Pero leyendo el PDF de la tarea veo que dice que todos los commits que hagamos deben llevar el nombre descriptivo, por lo que mi pregunta es: se ignoran todos los commits que no sean los ultimos 2? o seria mejor que eliminara los 2 primeros?
Muchas gracias!

**Comment by juacob** [comment]
agregando mas info: a la hora de ver los archivos en mi repositorio privado la carpeta de la tarea aparece con el mensaje del commit antiguo, aun cuando la volvi a subir con los 2 commits con los mensaje correctos. Queria saber si se me descontara por eso o no, tengo la opcion de hacer un force push para cambiarle el mensaje o hacer 2 commits nuevos eliminando la carpeta y volviendola a subir pero no quiero arriesgarme a algun problema innecesariamente. Gracias!

**Comment by josemquinta15** [comment]
Hola, acabo de revisar tu repo y se ve bien, ya que tiene dos commits descriptivos, así que no te preocupes

**Comment by juacob** [comment]
Gracias!
