### ISSUE TITLE
Versiones alternativas de python

### ISSUE THREAD

**Issue by pepinofdz** [Exploratorio-DCC-PUC/Syllabus#696]
Holaa! Quería saber si es que es posible tener 2 versiones distintas de python, cada una con sus respectivas librerías: digo esto porque este semestre también estoy cursando progra avanzada y me piden pyhton 3.8.10 con la librería PyQt5, que ya instalé.
Entonces, cómo puedo agregar python 3.9 y la librería Pandas sin eliminar python 3.8.10 como predeterminado?
O si es que no se puede, hay algún problema con que trabaje con python 3.8.10?

Muchas gracias de antemano

**Comment by ValentinaAlvarezG** [comment]
Hola! según yo no deberías tener problemas con la versión de python que tienes, así que úsala no más. Nos avisas si es que llegas a tener algún problema.

**Comment by pepinofdz** [comment]
Oka, muchas gracias
