### ISSUE TITLE
Referencias y Citas TG1

### ISSUE THREAD

**Issue by LMD18** [Exploratorio-DCC-PUC/Syllabus#698]
En el jupyter notebook de la TG1 debemos hacer un apartado para colocar las citas y referencias que utilizamos para realizar la Tarea?

**Comment by ValentinaAlvarezG** [comment]
Puedes hacerlo como prefieras en verdad, no hay una estructura definida para poner las referencias. Puedes hacer un apartado y ver como hacer la referencia o en el momento en que la usas puedes poner el link como comentario.
