### ISSUE TITLE
Valor variables

### ISSUE THREAD

**Issue by amparostevens** [Exploratorio-DCC-PUC/Syllabus#7]
Hola! 
1) No entiendo si es que tenemos que escribir los comandos en el informe utilizando los valores reales y para, por ejemplo, para cada uno de los jugadores (en un loop) como si el juego se estuviese ya jugando o sólo hacerlo como un caso general sin ir guardando el valor de las variables ni actualizándolas. 
2) Es posible utilizar scripts de bash?
Gracias :)

**Comment by Pyralspite** [comment]
Hola!

Pueden pensar cada situación que les piden en la tarea como un caso aislado, es decir, no es necesario que almacenen variables más allá de las modificaciones (teóricas) a los archivos de texto.
Para corregir la tarea **únicamente leeremos el informe**, no revisaremos las carpetas ni los archivos de texto. 
En esta tarea no les pedimos que programen un juego funcional, solo que logren resolver los casos puntuales que les pedimos mediante comandos y ponerlos en el informe. Por lo tanto, no es necesario crear scripts.
Para mostrar los comandos pueden escribirlos en el informe o pegar pantallazos. Estos comandos pueden contener tanto las variables que aparecen en el informe (i, j, etc) o valores reales que sean consistentes con las limitaciones del juego (no escribir una instrucción para el jugador 5, por ejemplo). 
Les recomiendo que prueben en consola que las instrucciones funcionan en el entorno del juego (para eso les dejamos las carpetas y archivos) y luego peguen el pantallazo. Así saben que la instrucción que están poniendo en el informe está buena c:

Espero haber resuelto tus dudas. Cualquier cosa me preguntas por aquí!
