### ISSUE TITLE
Problema con terminal

### ISSUE THREAD

**Issue by totichi** [Exploratorio-DCC-PUC/Syllabus#7]
Hola!
Estoy tratando de hacer la tarea, y al estar en git bash e intentar hacer el comando python start.py ..... me arroja devuelta " bash : python: command not found."
¿Qué hago? ¿Estoy haciendo algo mal?
Saludos y gracias de antemano

**Comment by clolate** [comment]
En otro comentario hablaron del path y esas cosas, pero a mí se me solucionó poniendo py en vez de Python

**Comment by totichi** [comment]
Efectivamente! es el mismo problema,y de hecho, no me funciona el comando en cmd de windows. ¿qué hago? pd: no me funciono el comando py, gracias de igual manera

**Comment by aaossa** [comment]
@totichi efectivamente tienes que agregar Python al PATH. Asumiendo que tienes Windows, deberías seguir las instrucciones para [Windows 7](https://stackoverflow.com/a/14973684/3281097) (obviamente tienes que poner la ruta a la carpeta de Python 3, no de 2.7 como en la pregunta) o para [Windows 10](https://anthonydebarros.com/2015/08/16/setting-up-python-in-windows-10/) (punto 5) según sea tu caso. Avísanos si te sirve 👌

**Comment by totichi** [comment]
Funciona en cmd sólo con el comando py. Ahora,a la hora de hacer la tarea con git bash, y poner git status cuando te recomienda hacerlo, me sale que el arbol está actualizado. Tendrá que ver algo? porque estoy bastante seguro de que hice todo bien.

**Comment by aaossa** [comment]
Entonces deberías poder seguir avanzando sin problemas
