### ISSUE TITLE
Parte 2 SUPUESTOS

### ISSUE THREAD

**Issue by Gorgola22** [Exploratorio-DCC-PUC/Syllabus#70]
Tengo preguntas relacionadas a como debería modelarse la parte dos:
¿Dirección o Calle y Ciudad (un concierto se hizo en un lugar de la ciudad y luego en otro)?
¿Cada concierto tiene solo una fecha asociada (más de un concierto en el día)?
¿La duración de un concierto es la suma de las canciones?

**Comment by Dalal15** [comment]
Debes realizar los supuestos necesarios.
Por ejemplo, puedes crear los atributos Calle y Ciudad en vez de tener un solo atributo Dirección.
Si puede haber más de un concierto en el día.
Todo depende de como quieras modelar el problema planteado.
