### ISSUE TITLE
Consultas ejemplo ayudantia 4

### ISSUE THREAD

**Issue by SFarfan** [Exploratorio-DCC-PUC/Syllabus#70]
Hola! estoy haciendo los ejemplos de consultas con example.db de la ayudantía 4 para aprender antes de hacerlo con lo de la tarea pero la pagina no me arroja nada. ¿A qué se debera? 
![ejemplo](https://user-images.githubusercontent.com/53883136/64914798-080cc480-d72f-11e9-9672-90663c2c8f99.png)

**Comment by ValentinaAlvarezG** [comment]
Hola!

Quizás sea porque te falta el ; al final de la consulta. Prueba con eso y dale run. Avisame si te funciona con eso.

**Comment by SFarfan** [comment]
también probé con eso y nada :(

**Comment by Jiruiz2** [comment]
Hola,

No te arroja nada porque las tablas que puse en la ayudantía son solo de ejemplo, aunque comparten el nombre con example.db, difieren en los datos. Por lo anterior, debes aplicar lo que aparece en la ayudantía a example.db.

Puedes utilizar la consulta 'SELECT * FROM tabla;' para ver que datos hay en las tablas.

Saludos
