### ISSUE TITLE
Problema Con Git Commit TG1

### ISSUE THREAD

**Issue by Gutierrovski** [Exploratorio-DCC-PUC/Syllabus#702]
Hola, 
Al momento de hacer un commit, accidentalmente hice git add .  en vez de git add *, y se subieron algunos archivos que estaban escondidos (".DS_Store" y ".gitignore"). ¿Cómo puedo solucionar esto? Gracias de antemano.

**Comment by mimadri** [comment]
Hola!

No hay problema con que se suba el .gitignore, para que no aparezca el .DS_Store lo que puedes hacer es agregar una nueva línea dentro de tu .gitignore con lo siguiente:

> .DS_Store 

Éxito con la tarea!
