### ISSUE TITLE
Fuentes para el html

### ISSUE THREAD

**Issue by maromero-21** [Exploratorio-DCC-PUC/Syllabus#703]
Hola, tengo una pequeña consulta, si encuentro la forma de agregar fuentes para la parte de la página web, ¿lo puedo hacer? o hay algún tipo de restricción en este tema?

**Comment by mimadri** [comment]
Hola :)

Te refieres al tipo de letra? Si es así, no hay problema, siempre y cuando estas se agreguen dentro del archivo .css

Saludos!
