### ISSUE TITLE
Ancho de imagen

### ISSUE THREAD

**Issue by matimurata** [Exploratorio-DCC-PUC/Syllabus#704]
Hola,
En el enunciado se pide que el contenedor de la imagen tenga un ancho auto, sin embargo mi grafico de la pregunta 3 al tener esa caracteristica se sale de la pagina.
¿Es posible usar un max-width, para establecer un limite del ancho, que permita que el grafico se mantenga dentro de los margenes de la pagina?

Muchas gracias, saludos

**Comment by mimadri** [comment]
Hola
No hay problema con que modifiques max o width si es que no te funciona con el ancho automático.
Éxito en la tarea :)
