### ISSUE TITLE
Archivos HTML, CSS y JS

### ISSUE THREAD

**Issue by cristobal-contreras** [Exploratorio-DCC-PUC/Syllabus#705]
¿Se puede crear un archivo HTML para cada parte de la página, y a través de estos, mediante JS, interactuar en la página, o se debe tener solo un archivo HTML que contenga todas las partes de la página? 

En ese caso, ¿Cómo se podría configurar todo en un solo archivo HTML?, dado que cada parte de la página tiene requerimientos distintos (gráficos y texto). 

Replico la pregunta también para CSS y JS, ¿Se puede subir más de un archivo para cada uno?

**Comment by mimadri** [comment]
Hola :)

No es necesario crear más de un archivo html, te recomiendo que para hacer lo solicitado incluyas todo en tu html principal (añadiendo distintos ids o clases a las imágenes y su texto correspondiente) y luego crees una función en tu archivo javascript que vaya interactuando a medida que sea necesario.

De la misma manera, también sólo son necesarios un archivo css y js.

Éxito con la tarea!
