### ISSUE TITLE
Harcoding y archivos json

### ISSUE THREAD

**Issue by scavagnaro** [Exploratorio-DCC-PUC/Syllabus#706]
Hola! Tengo entendido que no puedo hacer hardcoding, pero puedo sin embargo tener un archivo .json donde guardo las variables y extraerlo hacia el codigo?

**Comment by mimadri** [comment]
Hola :)

No habrán descuentos para esta tarea si es que hardcodean código. Si te acomoda más trabajar con un .json no hay ningún problema, de hecho, es una muy buena práctica 👌

Éxito con la tarea!

**Comment by scavagnaro** [comment]
Me encantaría si pudieran hacer una ayudantía sobre el tema. No tengo problemas con la extracción de archivos y importar modulos en python, pero no logre abrir el .json desde el archivo .js, solo desde el .HTML. Voy a tener que hacer hardcoding y variables globales ;(

**Comment by mimadri** [comment]
Lamentablemente ya no quedan más ayudantías para esta tarea, pero si te interesa el tema, en cursos como Tecnologías y Aplicaciones Web se enseña cómo consumir una API, que es casi lo mismo, también te recomiendo buscar tutoriales en internet!

Que tengas un buen fin de semana :)
