### ISSUE TITLE
Hardcoding en archivos HTML

### ISSUE THREAD

**Issue by Rolivares2** [Exploratorio-DCC-PUC/Syllabus#707]
Hola! 

En el caso de utilizar varios archivos html para los gráficos (como última instancia) habría descuento de puntaje?

Desde ya, muchas gracias :D

**Comment by mimadri** [comment]
Hola

Deben usar sólo un html, ya que la idea es que puedan trabajar esa parte con javascript.

Éxito con la tarea!
