### ISSUE TITLE
Aclaracion "cuerpo"

### ISSUE THREAD

**Issue by fachile** [Exploratorio-DCC-PUC/Syllabus#708]
Hola! Cuando nos piden que el cuerpo tenga un margen de 3% de la pantalla, se refiere a que la seccion del cuerpo de nuestra pagina tenga ese margen o que el tag body lo tenga. Lo mismo para cuando piden cambiar el fondo el el superhero mode.

Gracias

**Comment by mimadri** [comment]
Hola

Se refiere al tag body, la idea es que haya un margen para la página completa, que incluya todo el contenido de su página.

Éxito con la tarea :)
