### ISSUE TITLE
TC2: Atributos de relaciones, N como un número en particular

### ISSUE THREAD

**Issue by pepinofdz** [Exploratorio-DCC-PUC/Syllabus#709]
Holaa ¿Para la parte 1 de tarea chica 2 es necesario agregar atributos a las relaciones o es suficiente con la PK implícita? Pregunto porque en la ayudantía vimos un caso en que la relación tenía atributos que no eran la PK, pero en el diagrama más complejo que presentaron no había ninguno.

Y sobre esta misma parte, se puede asignar un valor específico a N? Digo esto porque en cada partido hay exactamente 2 equipos, pero en la ayudantía no se vieron casos de N específico.

Muchas gracias de antemano!

**Comment by clolate** [comment]
Hola, debes agregar los atributos que sean necesarios según el enunciado. Los atributos de la relación (que son los pk de las entidades que conecta) no se ponen porque no entregan información. Por definición la relación está compuesta mínimo por esas pk, así que solo se agregan los atributos adicionales si corresponden.
El diagrama de modelación compleja cambio _participación_ de relación a entidad, se quedó con sus atributos y las nuevas relaciones (que se crean para conectar las entidades) ya no muestran atributos porque solo estan los pk de las entidades.

Usa N no más, existe una notación uqe es más explícita en cuanto a las restricciones de cardinalidad, pero para esta tarea solo se consideran 1:N y N:M o N:N

**Comment by pepinofdz** [comment]
Okaa, muchas gracias!
