### ISSUE TITLE
Búsqueda de parejas TG2

### ISSUE THREAD

**Issue by diflores** [Exploratorio-DCC-PUC/Syllabus#71]
Estimados,

🔍  En esta _issue_ pueden postear sus anuncios de búsqueda de pareja para la **tarea grande 2**, así como leer los anuncios posteados por sus compañeros. Esperamos que esto les sirva para formar su equipo ideal, aprender mucho realizando la tarea y así sacarse una gran nota 💯.

⚠️  ¡Recuerden el plazo estipulado para inscribirse! Cuando este se acabe, los no-inscritos serán asignados a un compañero de forma arbitraria y sin derecho a reclamos.

**Nota/petición**: sería ideal que en la medida que vayan encontrando pareja, editen su comentario para informar al mundo al respecto. De esta forma no generarán falsas esperanzas en sus compañeros que aún buscan grupo.

**Comment by NicolasCastillo24** [comment]
Se busca pareja! Prometo que soy tela y trabajador. Igual me manejo con el ramo :(

**Comment by zaertis0** [comment]
Hola, de igual manera busco pareja, lamentablemente github no tiene un sistema de mensajes por lo que necesito que respondas aquí si es que quieres ser conmigo y si es que ya tienes pareja invito a cualquiera que no tenga a escribir para poder coordinarnos.

**Comment by NicolasCastillo24** [comment]
Apaño! Escribeme nicastillo@uc.cl plz

**Comment by JupaOlivares** [comment]
Estoy buscando pareja! interesados comentar aca o mail cualquier cosa jpolivares3@uc.cl

**Comment by jearaneda** [comment]
Hola! Busco pareja. Puedes ver una muestra de mi trabajo [aquí](https://jearaneda.github.io/) y también escribirme: jearaneda@uc.cl

**Comment by brayanmoreno** [comment]
Busco pareja! cualquier cosa mi correo es bbmoreno@uc.cl 😄

**Comment by jasanchez1** [comment]
Me falta pareja para la TG2!  jasanchez1@uc.cl

**Comment by jpcorread** [comment]
busco pareja para la tarea, mi correo es jpcorread@uc.cl

**Comment by diegonavarrovergara** [comment]
Hola, busco pareja para la tarea que tenga la meta de sacarse al menos un 7. Mi mail es dnavarro1@uc.cl

**Comment by tomasriverah** [comment]
hola, busco pareja para la tarea.... dejo mi correo tvrivera@uc.cl
