### ISSUE TITLE
TC2, P4: Problema con jerarquia

### ISSUE THREAD

**Issue by rodrigoogalde** [Exploratorio-DCC-PUC/Syllabus#710]
Hola!
Al momento de realizar un sort de mayor a menor y luego el limite de 5 en la cantidad de libros tengo el problema que dos autores tienen la misma cantidades de libros escritos (En este caso 2), por lo que no se si debo aplicar alguna condición extra para saber quien se queda dentro del Top 5 o simplemente lo dejo tal cual como quedo (Actualmente se queda dentro del top 5 el usuario que tiene el aid menor)

**Comment by ValentinaAlvarezG** [comment]
Hola! no debes aplicar ninguna condición extra, solo aplica limit 5 y los queden dentro no más serán el top 5.

**Comment by rodrigoogalde** [comment]
Gracias!
