### ISSUE TITLE
Pantallazo en pdf de consultas SQL

### ISSUE THREAD

**Issue by sawiiii** [Exploratorio-DCC-PUC/Syllabus#711]
Hola!, que sucede si el resultado de la consulta es más largo que un pantallazo que puedo hacer? (si el largo del la tabla resultante es mas largo a el largo de la pantalla)

**Comment by ValentinaAlvarezG** [comment]
Hola! pon más pantallazos. Pero **ojo** que los resultados de las consultas están pensados para que sean cortos, por lo que revisa bien lo que estás haciendo, para todas las consultas te debería alcanzar con un pantallazo.
