### ISSUE TITLE
Uso del README

### ISSUE THREAD

**Issue by scavagnaro** [Exploratorio-DCC-PUC/Syllabus#713]
Hola!

Los supuestos de las consultas SQL las puedo incluir en el mismo README.MD?

También inclui ahí el bonus del diagrama E/R.

**Comment by ValentinaAlvarezG** [comment]
Hola! :thinking: no sé si la parte de SQL daba para poner supuestos, pero si tienes algo que incluir ponlo en la misma parte donde va la consulta, porque yo voy a revisar solo ese archivo pdf para la parte II.

El bonus del diagrama ER si está bien que lo incluyas en el readme.
