### ISSUE TITLE
Cantidad Clasificadores

### ISSUE THREAD

**Issue by jalliende** [Exploratorio-DCC-PUC/Syllabus#715]
Hola, cuando se piden 10 clasificadores se pueden repetir dentro del mismo subtítulo de la documentación de sklearn? Por ejemplo utilizar más de uno lineal? Que sino no encuentro 10.

**Comment by IchottMano** [comment]
Hola!

Si, dos clasificadores pueden estar en el mismo subtítulo de la documentación de sklearn. Ojo que lo importante es que los clasificadores no sean los mismos, es decir puedes usar una regresión lineal y al mismo tiempo usar ridge, pero dos regresiones lineales con distintos hiperparámetros no cuentan como dos clasificadores distintos.

Saludos!
