### ISSUE TITLE
Duda sobre funcion "fit"

### ISSUE THREAD

**Issue by IgnacioHqz** [Exploratorio-DCC-PUC/Syllabus#716]
Buenas tardes. 
Con mi compañero estamos teniendo problemas con la TG2 en la parte de clasificadores. Sucede que a la hora de querer implementar un clasificador, nos arroja el siguiente error:  "ValueError: could not convert string to float: 'tulip' " tras la ejecución del código FIT, que contiene a "X" y a "y", donde X lo definimos como la columnas que tienen números, e "y" la definimos como la columna "label" que contienen el nombre de las flores. No sabemos a qué se deberá este error y al no entender este error no hemos podido avanzar. Quedamos atentos! Muchas Gracias.
Ignacio Henríquez N.

**Comment by IchottMano** [comment]
Hola!

No pueden entregarle valores categóricos (Categorías, como Tulip) a esta función, tienen que primero pasar estos valores a números. Les recomiendo buscar algun "encoder" en la docuemtación de sklearn que les podría ayudar.

Saludos!

**Comment by cperez20** [comment]
> Hola!
> 
> No pueden entregarle valores categóricos (Categorías, como Tulip) a esta función, tienen que primero pasar estos valores a números. Les recomiendo buscar algun "encoder" en la docuemtación de sklearn que les podría ayudar.
> 
> Saludos!

Hola, me surgio una duda respecto a esta issue, pues mis "y" de prueba es la columna de label con valores categóricos (es decir el nombre de las flores), y no tengo ningun problema al ejecutar el código fit en los clasificadores, incluso al realizar una matriz de confusión para evaluar el rendimiento, la sección de las filas efectivamente contiene el nombre de las flores, habre hecho algo mal?

**Comment by IchottMano** [comment]
@cperez20 Es perfectamente posible que algunos clasificadores no tengan problemas al trabajar con labels categóricas.

Saludos!
