### ISSUE TITLE
Parámetros de métricas de éxito 

### ISSUE THREAD

**Issue by FranciscoPinto1138** [Exploratorio-DCC-PUC/Syllabus#717]
Hola, tenía la duda sobre si al momento de calcular f1-score, recall y precision basta con asignarle los parámetros micro y macro o también weighted y samples (?)

De antemano muchas gracias.

**Comment by IchottMano** [comment]
Hola!

Con micro y macro basta.

Saludos!

**Comment by FranciscoPinto1138** [comment]
¡Muchas gracias!
