### ISSUE TITLE
Duda con agregar una columna al dataset por conveniencia

### ISSUE THREAD

**Issue by cperez20** [Exploratorio-DCC-PUC/Syllabus#718]
Hola, tengo una duda si es posible crear una columna adicional al dataset, especificamente busco replicar la columna que creo el profe de "numeric_label"  en la clase 16 pero ajustado para este dataset, la razón de esto es que me facilitaría el hecho de realizar los gráficos de distribución de los datos despúes, adicionalmente me gustaría preguntar si svc , nusvc y linearsvc cuentan como 3 clasificadores distintos o no, muchas gracias de antemano

**Comment by IchottMano** [comment]
Hola!

No hay problema con crear esa columna, sin embargo sería incorrecto usarla para entrenar el modelo. Mientras no hagas eso, está bien.
Por otro lado, efectivamente son 3 clasificadores distintos.

Saludos!
