### ISSUE TITLE
Problema con graficar en TG2

### ISSUE THREAD

**Issue by taefl** [Exploratorio-DCC-PUC/Syllabus#719]
Hola! Con mi compañero de tarea no logramos graficar con dispersión, boxplot o histogramas :( A pesar de tener separado en vector y matriz los datos.

**Comment by IchottMano** [comment]
Hola!

Que librería estan intentando usar? Que error en específico les arroja?
Recuerden no subir código, pero pueden mostrar el mensaje de error producido siempre que este no tenga su propio código.

Saludos!

**Comment by taefl** [comment]
> Hola!
> 
> Que librería estan intentando usar? Que error en específico les arroja? Recuerden no subir código, pero pueden mostrar el mensaje de error producido siempre que este no tenga su propio código.
> 
> Saludos!
Estamos usando pandas y sale el siguiente error:
*Creo que el problema es como se definen los ejes :(

KeyError                                  Traceback (most recent call last)
<ipython-input-41-cadec2da1be2> in <module>()
----> 1 df4.plot.scatter(vector, matriz, s=None, c=None)

7 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1296             if missing == len(indexer):
   1297                 axis_name = self.obj._get_axis_name(axis)
-> 1298                 raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   1299 
   1300             # We (temporarily) allow for some missing keys with .loc, except in

KeyError: "None of [Index(['tulip', 'tulip', 'daisy', 'dandelion', 'tulip', 'sunflower', 'daisy',\n       'dandelion', 'tulip', 'rose',\n       ...\n       'tulip', 'rose', 'tulip', 'tulip', 'daisy', 'tulip', 'rose',\n       'sunflower', 'tulip', 'sunflower'],\n      dtype='object', length=493)] are in the [columns]"

**Comment by IchottMano** [comment]
Emm en primer lugar, recomiendo usar gráficos de librerías como seaborn, mas que nada porque estan intentando utilizar pandas para esto. Si bien es posible no lo recomiendo para nada.
Veo que están intentando hacer un scatterplot, sin embargo para esto simplemente pueden usar una de muchas otras librerías especializadas en eso, las cuales además son mucho mas verbosas y útiles en errores de este tipo.
