### ISSUE TITLE
Parte I 

### ISSUE THREAD

**Issue by rosariodiez** [Exploratorio-DCC-PUC/Syllabus#72]
Para el diagrama puedo hacerlo a papel y poner una foto en el pdf? Esque en mi computador es muy difícil de hacer!

**Comment by ValentinaAlvarezG** [comment]
Hola!

Si, puedes hacerlo en papel, pero debe estar muy ordenado. Si es que no se entiende, puede haber descuento, a criterio de corrector.

**Comment by rosariodiez** [comment]
Y las relaciones pueden tener atributos?

**Comment by Jiruiz2** [comment]
Hola,

Puede darse el caso, pero esto solo ocurre cuando es una relación N a N.

Saludos

**Comment by rosariodiez** [comment]
Esque no entiendo si las tablas son las entidades con sus respectivos atributos o no necesariamente

**Comment by rosariodiez** [comment]
Las entidades tienen que aparecer explícitamente o pueden estar incluidas en una relación?

**Comment by Jiruiz2** [comment]
> Las entidades tienen que aparecer explícitamente o pueden estar incluidas en una relación?

¿A que te refieres con eso?

**Comment by rosariodiez** [comment]
Por ejemplo si me dan una tabla de muñecas, otra de dueños y otra de muñecas de cada dueño, puedo hacer que la tabla muñecas de cada dueño sea una relación?
