### ISSUE TITLE
Preprocesamiento de datos incorrectos? Que hacer con ellos?

### ISSUE THREAD

**Issue by naquiroz** [Exploratorio-DCC-PUC/Syllabus#72]
Hola! Nos dimos cuenta (como bien se explicita en el enunciado) que hay columnas que tienen datos que están fuera de contexto con el tipo de dato esperado en esa columna. La pregunta es, que debemos hacer con ellos?

Ejemplo: en una variable binaria, que debemos hacer un con -1?

**Comment by aaossa** [comment]
Todo es parte del preprocesamiento. Sin embargo, la descripción de datos  debería reflejar  el estado actual  de la  base de datos.  ¿A cuál columna te refieres con el ejemplo?

**Comment by naquiroz** [comment]
Me refiero a la columna `URL_anchor`

**Comment by aaossa** [comment]
Cierto, es ternaria, lamento la confusión. Será arreglado en una próxima versión del enunciado 👌

**Comment by clolate** [comment]
Y que significa el -1, 0 y 1 en URL_anchor entonces?

**Comment by aaossa** [comment]
> `URL_of_Anchor`: Variable ternaria. Indica si los *links* en la página apuntan a un dominio distinto del tipeado en la *address bar* en un porcentaje bajo (1), intermedio (0) o alto (-1).
