### ISSUE TITLE
Duda reducción de dimensionalidad

### ISSUE THREAD

**Issue by cristobal-contreras** [Exploratorio-DCC-PUC/Syllabus#720]
Con mi compañero queríamos saber si en esta parte de la tarea solo se debe hacer la reducción de dimensionalidad, usando, por ej, PCA, o si además de esto, se debe también intentar formar clusters con la data reducida, por ej, a través del algoritmo de aprendizaje no supervisado KMeans.

Preguntamos esto último dado que en el enunciado se habla sobre la formación de clusters de interés.

Saludos

**Comment by IchottMano** [comment]
Hola!

A priori no es obligación usar algoritmos no supervisados para poder buscar clusters, pueden hacerlo visualmente. Sin embargo, estos algoritmos pueden facilitarles el trabajo.

Saludos!
