### ISSUE TITLE
Visualización de datos parte 3

### ISSUE THREAD

**Issue by caramelnico** [Exploratorio-DCC-PUC/Syllabus#721]
Con mi compañero nos surgió la duda de si para la visualización de los datos en la parte 3 debemos usar el DF completo o usar los datos separados (X_train, y_train, X_test, y_test).

**Comment by IchottMano** [comment]
Hola!

Para la parte 3 completa se usan todos los datos. La separación en train y test es únicamente para la parte 2.

Saludos!
