### ISSUE TITLE
Hiperparámetros de cada clasificador

### ISSUE THREAD

**Issue by gore26** [Exploratorio-DCC-PUC/Syllabus#722]
Hola, no me quedó claro si es que cada clasificador debiese tener 3 combinaciones de hiperparámetros distintos, de ser así, pongo todas esas combinaciones en el código (serían 30 en total)? o cuales debiesen ir en el jupyter?
Saludos!

**Comment by IchottMano** [comment]
Hola!

Efectivamente, deben probar cada uno de los 10 clasificadores con por lo menos 3 combinaciones de hiperparámetros distintas, las cuales se deben evidenciar todas en su código.

Saludos!
