### ISSUE TITLE
Lectura Control 2

### ISSUE THREAD

**Issue by pepinofdz** [Exploratorio-DCC-PUC/Syllabus#723]
Holaa, tengo una duda con respecto a la lectura para el control 2.
Lo que pasa es que la prueba estuvo calendarizada para el 18 de noviembre, pero la corrieron para que calce con la planificación original del curso, quedando así para el 25. Sin embargo, la fecha del avance en perusall sigue siendo para la semana del 18 (en especial para hoydía 16 de nov). Esto corresponde a un error o efectivamente hay que poner los comentarios la semana anterior a la prueba?

Muchas gracias de antemano!

**Comment by denisparra** [comment]
Hola, es un error efectivamente, debe quedar la fecha para el 24 de noviembre. Gracias por avisar, la corregiré.

Saludos
