### ISSUE TITLE
Formato entrega TC3

### ISSUE THREAD

**Issue by gore26** [Exploratorio-DCC-PUC/Syllabus#726]
Hola, a que se refieren cuando dicen esto en la sección de entrega del enunciado?

además del archivo .tex que lo compila con el nombre informe.tex.

Gracias!

**Comment by MFMG99** [comment]
Hola! Significa que debes tener un archivo llamado `informe.tex` que compile tu informe (en donde escribes el código que, al compilarlo, se transforma en tu `informe.pdf`)
