### ISSUE TITLE
Grupos Tarea Grande 2

### ISSUE THREAD

**Issue by Mdelaf** [Exploratorio-DCC-PUC/Syllabus#73]
Creo esta _issue_ para quienes necesiten buscar compañero para su tarea. 

Recuerden dejar su correo para que los interesados puedan contactarlos y actualicen su comentario cuando ya hayan encontrado pareja.

Saludos.

**Comment by Crespy98** [comment]
Hola busco pareja dejo mi mail tasoto@uc.cl

**Comment by Coolgatty** [comment]
aperez18@uc.cl

**Comment by bawas** [comment]
tvharris@uc.cl

**Comment by inmadariaga** [comment]
Inmadariaga@uc.cl aún no tengo pareja 😅

**Comment by Coolgatty** [comment]
aperez18@uc.cl

**Comment by bmurtagh01** [comment]
Hola alguien todavia no tiene pareja?? 
bmurtagh@uc.cl
