### ISSUE TITLE
Curiosidad respetuosa.

### ISSUE THREAD

**Issue by Malopez22** [Exploratorio-DCC-PUC/Syllabus#73]
¿Hay alguna posibilidad de modificar nuestra foto de grupo de trabajo?, pues creo que sería entretenido tener un identificador más además del nombre para tener una experiencia más grata a lo largo de la tarea.
Tengo entendido (por comentarios de gente x)  que es posible sólo para quién creó el repositorio... por lo que si le mando la imagen (sana) al ayudante que creó el repositorio por correo no le veo el lado malo... con respeto. 
Nota: La imagen puede aclarar el por qué nuestro repositorio se llama como tal... con respeto.

**Comment by VicenteVicenteVicenteVicenteVicente** [comment]
Apoyo la idea.

**Comment by aaossa** [comment]
Las solicitudes de asignación de foto solo serán aceptadas si son justificadas mediante un documento ordenado de entre 15 y 30 páginas, escrito a mano, donde se describan al menos 42 razones para cambiar la foto del *team*. El documento debe ser entregado en la oficina del ayudante Vicente Domínguez (@NevadaStreets )

**Comment by aaossa** [comment]
También podemos hacer el cambio si envían la foto (y un meme apropiado) a mi correo con copia a todos los ayudantes del curso (solo quieren el meme)

**Comment by Malopez22** [comment]
Revise el correo estimado... mi compañero aceleró el proceso y envió la solicitud a mano escaneada.

**Comment by clolate** [comment]
Estimados, 
Queremos ver el meme 
atte. todos

**Comment by Malopez22** [comment]
E...
