### ISSUE TITLE
Trabajo en parejas

### ISSUE THREAD

**Issue by ncasassus** [Exploratorio-DCC-PUC/Syllabus#75]
Uno al trabajar en parejas tiene que ir subiendo y bajando el archivo para que cuando se meta tu compañero le llega lo que has avanzado en el trabajo. Ahora, qué pasa si los dos están trabajando al mismo tiempo en un mismo archivo, uno sube lo que ha avanzado y luego el otro sube lo que avanzó (sin el trabajo que había avanzado tu otro compañero)? Git hub entiende que están trabajando dos personas y mantiene el trabajo de ambos? O borra la parte trabajada por la primera persona que haya actualizado el   ##repositorio, dejando solamente el trabajo del último que lo haya subido?
Ojalá se haya entendido. Muchas gracias!

**Comment by fvr1** [comment]
En github, estos casos se llaman "conflictos", que es cuando reconoce que hay un mismo archivo con modificaciones diferentes. Lo que hace es que te avisa al momento de hacer `git pull ` o `git push `, indicando cuál es el archivo que tiene un conflicto. Te va a pedir que vayas a ese archivo y que veas las modificaciones hechas y con cuál cambio quedarte. Luego tendrás que hacer `git add` del archivo y luego un `git commit` para que se solucione el conflicto. En esta página lo explican: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
