### ISSUE TITLE
Manejar atributos de tipo string

### ISSUE THREAD

**Issue by fmartint** [Exploratorio-DCC-PUC/Syllabus#75]
Hola, llevo mucho rato tratando de encontrar una forma eficiente de hacer el cambio de string a int pero no he encontrado nada, se hace con pandas?

**Comment by IchottMano** [comment]
Hola!
Se espera que esta parte la hagan tanto con Pandas como con la librería scikit-learn.
Te recomiendo que busques en la parte de [preprocessing](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing).

Espero te sirva.
Saludos!
