### ISSUE TITLE
Ayudantía TG2

### ISSUE THREAD

**Issue by absoto4** [Exploratorio-DCC-PUC/Syllabus#76]
Hola, pueden subir los archivos de la ayudantía de esta semana por favor?
Muchas gracias! 😄

**Comment by Mdelaf** [comment]
Hola,

Acabo de subir [la ayudantía de esta semana](https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Ayudant%C3%ADas/Ayudant%C3%ADa%205/Ayudant%C3%ADa%20ML.pdf).

Saludos.
