### ISSUE TITLE
Duda datos TG2

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [Exploratorio-DCC-PUC/Syllabus#77]
Hola!

Para la TG2,  hay que usar los 1250 datos para el modelo 1, después los 1250 para el modelo 2 y los 1250 para el 3? o hay que dividir los datos totales en 3 y usarlos por separado para cada modelo?

**Comment by aaossa** [comment]
Pueden usar todos los datos para cada modelo, pero recuerda que se recomienda dividir los datos antes de trabajar con ellos en conjuntos de *training*, *test* y *validation*.
