### ISSUE TITLE
TG2 - Cargar archivos .csv en Google Colab

### ISSUE THREAD

**Issue by AndresFaure** [Exploratorio-DCC-PUC/Syllabus#77]
Hola, buscando en Google he visto que hay varias formas de cargar archivos .csv en Google Colab. ¿Cuál es la que recomiendan usar? 

Gracias!

**Comment by Mdelaf** [comment]
Hola Andrés,

Perdón por demorarme en responder, no me di cuenta de esta issue.

En Colab se pueden ejecutar comandos de consola directamente usando el símbolo `!`. Esto nos permite, por ejemplo, usar `wget` o `curl` para descargar archivos desde una URL:

```
import pandas as pd

!wget https://raw.githubusercontent.com/Exploratorio-DCC-PUC/Syllabus/master/Tareas/TG2/adult_dataset.csv
df = pd.read_csv("adult_dataset.csv")
```

Notar que el dataset lo está descargando directamente de la URL de este repositorio.

Saludos.

**Comment by AndresFaure** [comment]
Muchas gracias!

**Comment by Mdelaf** [comment]
Por favor no cerrar las issues. Nosotros lo haremos oportunamente.
