### ISSUE TITLE
Cargar dataset

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#78]
Al cargar el archivo adult_dataset.csv usando el comando (!wget ...) - la cual vimos en la ayudantía para la TG1 - con el link de github (http://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Tareas/TG2/adult_dataset.csv) y luego usar "pd.read_csv" para leer el archivo, nos tira el siguiente error:

ParserError: Error tokenizing data.

Me gustaría saber a qué se debe ese error para así poder solucionarlo a la brevedad.

**Comment by Mdelaf** [comment]
Hola Felipe,

La URL que estás escribiendo lleva al archivo dentro de Github, pero no lleva al archivo en sí. Por eso tu código falla, pues no estás descargando el archivo realmente, sino que estás descargando la página de Github donde se muestra el archivo. Es una diferencia sutil.

Para que funcione correctamente debes usar el código que puse en la issue #77, donde la URL está modificada para que sí lleve directamente al archivo (fíjate que comienza con https://raw.githubusercontent.com.. y no https://github.com...).

Saludos.
