### ISSUE TITLE
Scale y fit

### ISSUE THREAD

**Issue by absoto4** [Exploratorio-DCC-PUC/Syllabus#79]
Hola! Para normalizar los datos, estamos usando scale como en el ejemplo que vimos en clase, pero esto nos deja los datos como float y luego, cuando quiero hacer fit con el grupo de entrenamiento en el árbol de desiciones, me sale error ValueError: Unknown label type: 'continuous'. creo que tiene que ver con que no soporta floats, saben cómo podría solucionarlo? o si hay otra forma de normalizar los valores? Muchas gracias!

**Comment by Mdelaf** [comment]
Hola,

El árbol de decisión de sklearn si puede trabajar con características de tipo float. Lo que no puede trabajar son clases continuas, porque eso significa que habrían infinitas predicciones posibles y no puede manejar eso.

¿Segura que no normalizaste el vector de clases erradamente?

Saludos.

**Comment by absoto4** [comment]
Creo lo solucioné. Cambié la forma de normalizar, en vez de usar scale, uso normalize. También lo consideran bueno?

**Comment by Mdelaf** [comment]
Cualquier forma de normalizar debiera estar bien mientras estén normalizando cada característica individualmente.
