### ISSUE TITLE
problema con tildes en la visualización en git-bash

### ISSUE THREAD

**Issue by jitorralba** [Exploratorio-DCC-PUC/Syllabus#8]
Hola! Al momento de ver el contenido del archivo en git-bash, las letras con tildes de las palabras créditos y posición no aparecen bien. ¿Hay una forma de arreglar esto? ¿Baja la nota? Ya que en el pdf de la tarea muestra como deberían quedar.
![Captura](https://user-images.githubusercontent.com/53885967/63181995-6d31a500-c01f-11e9-8ba4-fc47c7eabe68.PNG)

**Comment by IchottMano** [comment]
Hola!
Eso ocurre normalmente por algo llamado _encoding_, que es lo que se encarga de traducir los _bytes_ (unos y ceros) a letras que uno pueda entender. Sucede que el encoding de lo que uses para ver tu programa es distinto al que usas para escribirlo, causando que veas esas palabras de manera errónea.
Lo que podrías hacer para arreglar esto es intentar correr tu programa usando alguna otra línea de comandos o simplemente no poner tildes en tu código.
Sin embargo, **no bajaremos** por estos errores (siempre y cuando las palabras sean entendibles), asi que no te preocupes 😄 
Saludos!
