### ISSUE TITLE
[Piso 3] - Doble git push

### ISSUE THREAD

**Issue by VicenteVicenteVicenteVicenteVicente** [Exploratorio-DCC-PUC/Syllabus#8]
Dado que al hacer el primer **git push** edité el archivo pero no lo guardé, tuve que hacer un segundo para que se actualice el archivo **README.md** con el hash agregado. ¿Qué **hash** debo poner en mi hoja de respuestas?, ¿El primero o el segundo? 😓

**Comment by figarrido** [comment]
Deja el último. :+1:
