### ISSUE TITLE
Librería numpy

### ISSUE THREAD

**Issue by Margarita-Paz** [Exploratorio-DCC-PUC/Syllabus#80]
Hola! 
se puede utilizar la librería numpy en la parte I de la tarea??

**Comment by AndresFaure** [comment]
Pregunto lo mismo por la librería `seaborn`.

**Comment by IchottMano** [comment]
@Margarita-Paz hola! si puedes usar la librería numpy.

@AndresFaure no puedes utilizar seaborne.
