### ISSUE TITLE
problemas con random_state

### ISSUE THREAD

**Issue by mathiasvaldebenito** [Exploratorio-DCC-PUC/Syllabus#81]
Hola, mi problema es que intenté fijar el random_state usando el comando np.random.seed( ), pero no me fija random_state como debería entonces no puedo dejar mis outputs fijos. ¿Cómo puedo fijarlos usando este método u otro?

**Comment by aaossa** [comment]
Hola, según el [FAQ de scikit-learn](http://scikit-learn.org/stable/faq.html#how-do-i-set-a-random-state-for-an-entire-execution) la única forma de asegurarse de obtener los mismos resultados es definir el `RandomState` siempre que se pueda:

> Thus, the only way to ensure replicability is to pass RandomState instances everywhere and ensure that both estimators and cross-validation splitters have their random_state parameter set.

**Comment by MarceloAguila** [comment]
Significa que tengo que darle un valor cualquiera?

**Comment by aaossa** [comment]
Significa que tienes que darle siempre el mismo valor
