### ISSUE TITLE
Valores NaN

### ISSUE THREAD

**Issue by ghost** [Exploratorio-DCC-PUC/Syllabus#81]
Hola, tengo una consulta respecto a la parte de análisis de las características: ¿Los valores "NaN" solo aparecen en el caso de las variables numéricas (como edad, peso, etc.), o también aparecen en variables tipo strings (como nombre, país de origen, etc.)?

**Comment by Mdelaf** [comment]
Hola Felipe,

Pueden aparecer en cualquiera de las dos. 

Usando pandas, es fácil examinar tu dataset y ver dónde hay valores nulos. Por ejemplo, puedes hacer lo que se menciona en [esta pregunta](https://stackoverflow.com/questions/26266362/how-to-count-the-nan-values-in-a-column-in-pandas-dataframe) para saber cuántos valores nulos hay en cada columna.

Saludos.
