### ISSUE TITLE
Duda atributo en dataset

### ISSUE THREAD

**Issue by Karla1304** [Exploratorio-DCC-PUC/Syllabus#82]
En el atributo Request_URL a qué se refiere con que un alto porcentaje de los links son de otros dominios?. El ( 1 ) permite identificar si es mas confiable o menos confiable?

**Comment by aaossa** [comment]
Normalmente, el 1 es un "sí", así que si tiene el 1 es porque un alto porcentaje son de otros dominios (eso aparece en el enunciado explícitamente). El si esta *feature* te permite identificar si es confiable o menos confiable es lo que tienen que responder con el preprocesamiento (sirve o no) y luego utilizar en el entrenamiento (los modelos aprenderán en qué proporción respecto a las demás *features* esta aporta para inferir la respuesta)
