### ISSUE TITLE
Pasar strings a int

### ISSUE THREAD

**Issue by vvelasco150** [Exploratorio-DCC-PUC/Syllabus#82]
Hola! se puede realizar la parte de pasar los strings a int solo ocupando pandas o es necesario hacerlo también con sklearn?

**Comment by IchottMano** [comment]
@vvelasco150 hola! puedes hacerlo con cualquiera de las dos librerías.

saludos!

**Comment by MariaBarias** [comment]
holaa :)
estoy ocupando One Hot Encoder para hacer la transformación de los strings...
Mi pregunta va a si es necesario usar get_dummies en todas las columnas que transforme? O simplemente no ocupo One Hot Encoder? 

help

**Comment by Mdelaf** [comment]
Hola María,

Cuando trabajamos con modelos de ML, lo más correcto a la hora de convertir una característica nominal de tipo string es usar una codificación _one hot encoding_ o _dummy encoding_. Sin embargo, para simplificar la tarea nosotros decidimos pedirles que hagan una transformación más simple, y que a cada valor posible dentro de la característica le asignen un número entero. Esto se puede hacer de manera sencilla usando numpy o pandas, y no necesitarás usar One Hot Encoder.

Saludos.

**Comment by MariaBarias** [comment]
sirve ocupar Label Encoder??

**Comment by Mdelaf** [comment]
Sí, puedes ocupar Label Encoder.
