### ISSUE TITLE
Labels Gráficos parte 3

### ISSUE THREAD

**Issue by jitorralba** [Exploratorio-DCC-PUC/Syllabus#83]
Hola! Cuando intento hacer el primer gráfico de la parte 3, al insertar la columna label (de la misma forma que en la ayudantía), las primeras filas no presentan problema, es decir, se le asignan las letras correspondientes. Pero a partir de la fila 1797 hasta la ultima los valores de la columna labels es NaN, por lo que en el gráfico me aparecen casi todos los puntos del mismo color (por ser valor null). Como puedo arreglar esto? A que se debe el problema?
De antemano muchas gracias.

**Comment by Mdelaf** [comment]
Hola,

Tienes que tener cuidado cuando insertas columnas en un Dataframe. En Pandas, los Dataframes tienen un índice asociado a cada fila. Eso significa que si tu tienes un Dataframe e insertas una nueva columna, si los índices del Dataframe con los índices de la columna no coinciden, entonces vas a tener problemas de ese tipo.

Lo que puedes hacer para evitar este problema, es resetear los índices del Dataframe antes de insertar la columna. Esto lo puedes hacer con el método `df.reset_index(drop=True)`.
