### ISSUE TITLE
Código para la entrega

### ISSUE THREAD

**Issue by Nacho111** [Exploratorio-DCC-PUC/Syllabus#83]
Para el código que será entregado en el jupyter notebook, ¿es necesario dejar muestra de las distintas pruebas utilizadas para los distintos modelos? o basta con dejar el modelo con el mejor resultado, y sus respectivas métricas de validación, borrando todo el código de "ensayo y error".

Saludos,/n
Ejecutivo_de_banca_de_www.bancodechile.tk

**Comment by aaossa** [comment]
En lo personal, creo que basta con que entregues uno solo, bien ordenado y con el informe y las métricas que justifican tu análisis y respuestas. Pero, además de este, puedes dejar un *notebook* con todo lo que denominaste "ensayo y error", no hay problema.
