### ISSUE TITLE
matriz de confusion

### ISSUE THREAD

**Issue by clementesepulveda** [Exploratorio-DCC-PUC/Syllabus#84]
Cuando pongo el codigo de 

data = pd.DataFrame({'x': x.ravel(),
                     'y': y.ravel(),
                     'z': z.ravel()})

me tira un ValueError: arrays must all be same length. Como puedo solucionar este problema>

**Comment by Mdelaf** [comment]
Hola Clemente,

El error es bastante claro. Estás creando un Dataframe con tres columnas `x`, `y` y `z`. Dado que los Dataframes son matrices, las tres columnas tienen que tener la misma cantidad de elementos, pero eso no se está cumpliendo en tu caso y por eso te da error.

Te recomiendo que intentes entender bien cada línea de tu código, ver qué son tus variables `x`, `y`, `z`, ver qué hace el método `.ravel()`, etc. Si copias y pegas sin entender difícilmente te funcione.

Saludos.

**Comment by sebaelsaca** [comment]
En mi caso hice una matriz de 2x2 pero en la ayudantía vi que la matriz era de hartas columnas por hartas columnas. Está bien eso?

**Comment by Mdelaf** [comment]
Hola,

Una de las preguntas del enunciado es cuál es el tamaño de su matriz y por qué. Si te respondo te estaría respondiendo a esa pregunta también. 

Ustedes deberían saber qué es la matriz de confusión, qué representa y con eso debería estar muy clara la respuesta.

Saludos.
