### ISSUE TITLE
Duda con el bonus

### ISSUE THREAD

**Issue by mathiasvaldebenito** [Exploratorio-DCC-PUC/Syllabus#85]
En el enunciado dice  _Su respuesta solo será válida si dicho notebook es autocontenido y es capaz de generar el mismo archivo de predicciones entregado_ , esto se refiere a que debe generar todas las columnas con las que venía el dataset del bonus más la columna con las predicciones hechas por mi modelo?

**Comment by aaossa** [comment]
Se refiere a que si tu entregas un archivo con tus predicciones y el ayudante vuelve a ejecutar el *notebook*, el archivo con las predicciones debe ser el mismo

**Comment by Nacho111** [comment]
Yo tengo otra duda para el bonus, aunque creo que es un poco obvia.
Para entrenar el modelo a utilizar en el bonus usamos el primer dataset (data.csv)? y luego cargamos el data-bonus.csv para entregar nuestra predicción, cierto? 

También en el enunciado se decía que se habilitaría una issue para el bonus, cual es esa issue?
