### ISSUE TITLE
Altair grafico

### ISSUE THREAD

**Issue by sebastianferrer** [Exploratorio-DCC-PUC/Syllabus#88]
Hola! Cuando corro el código de la parte 3 para visualizar los datos me dice que el programa aguanta hasta 5000 datos, mientras que el dataframe tiene mucho más que eso. Estoy cometiendo un error o debería ocupar menos datos?

**Comment by IchottMano** [comment]
Hola!

Intenta poniendo la siguiente línea en tu código:

```python 
alt.data_transformers.disable_max_rows()
```

Saludos!

**Comment by sebastianferrer** [comment]
Funcionó, muchas gracias!
