### ISSUE TITLE
Consulta multiples archivos

### ISSUE THREAD

**Issue by tatanpoker09** [Exploratorio-DCC-PUC/Syllabus#9]
Buenas! Queria preguntar si podemos separar las funciones en distintos scripts y llamarlos desde el script principal, asi manteniendo un poco mejor el orden, o tenemos que subir todo en un solo .sh

Muchas gracias

**Comment by tatanpoker09** [comment]
Update: Leí la parte del informe en PDF, sin embargo, deben estos tomar en cuenta "Error Handling"? Podemos asumir que los archivos estarán? Hay que incluir leer por consola el input del usuario con respecto a las variables?

**Comment by ValentinaAlvarezG** [comment]
Hola!

Si, puedes asumir que los archivos estarán. 
No debes leer ningún input del usuario, en este caso todo es más o menos manual.
