### ISSUE TITLE
[Piso 1] python start.py

### ISSUE THREAD

**Issue by NicolasCastillo24** [Exploratorio-DCC-PUC/Syllabus#9]
Hola, tengo Mac y cuando pongo < python start.py numeroalumno usuario > me sale este error:

<img width="703" alt="screen shot 2018-03-22 at 21 06 58" src="https://user-images.githubusercontent.com/37150130/37804951-decec10e-2e15-11e8-9ebd-89897a61bf15.png">

help?

**Comment by benjastraub** [comment]
Al usar `python`, por defecto ejecuta python 2, que viene por defecto en mac. Intenta usando `python3 start.py 17638836 NicolasCastillo24` para que se ejecute con python 3

**Comment by NicolasCastillo24** [comment]
Thank you very much, eso era
