### ISSUE TITLE
Mover de Head a branch master

### ISSUE THREAD

**Issue by AgustinZalaquett** [Exploratorio-DCC-PUC/Syllabus#91]
Mientras trabajaba, quise subir el repositorio para que mi compañera trabaje desde su PC, cuando hice el git push me salio un error de que habia un problema:
 hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

busque en internet la solucion pero al creer solucionarlo como que borre todo el avance de mi archivo de jupyter. 
tratnado de recuperarlo, logre acceder a mi commits anteriores desde la terminal y logre rescatarlo pero ahora estoy en otro branch, en el HEAD, creo.
si pongo git status sale esto
![image](https://user-images.githubusercontent.com/53916764/66728610-47a4fa00-ee1c-11e9-9284-2ca5f83ca4dc.png)
y nose como subirlo ahora

**Comment by IchottMano** [comment]
Hola!

Esto ocurre porque intentaste subir cambios al repositorio, mientras tu no tenías la version mas actualizada de tu repo.
Antes de pushear tu repo, es importante saber si tienes la versión actualizada, haciendo
```git
git pull
```

Antes de tu push, lo cual probablemente te diga que tienes el repo mas actualizado o, en el peor de los casos, entres a un estado de merge donde tengas que modificar tu codigo para actualizar tu código local e incorporarle tus cambios.

Para arreglar el estado detached, puedes intentar lo que sale en [esta guía](https://www.loekvandenouweland.com/content/head-detached-from-origin-master.html#targetText=HEAD%20detached%20from%20origin%2Fmaster,not%20belong%20to%20a%20branch.)

Por favor dime si esto te funciona.

Saludos!

**Comment by AgustinZalaquett** [comment]
Hola, logre volver a la carpeta master pero me sale el error de que al
hacer push me dice que haga pull, y al hacerlo me dice error:
Auto-merging TG2.ipynb
CONFLICT (content): Merge conflict in TG2.ipynb
Automatic merge failed; fix conflicts and then commit the result.
y me cambia de master a (master/MERGING)

**Comment by AgustinZalaquett** [comment]
![image](https://user-images.githubusercontent.com/53916764/66761067-aa78ae80-ee79-11e9-9892-80858bdad674.png)

**Comment by Mdelaf** [comment]
Hola Agustín,

Se ve que ya alteraste demasiado tu repositorio y explicarte por aquí cómo salir de ese estado y volver al estado normal va a ser muy complicado. 

La solución más directa que se me ocurre es que vuelvas a clonar tu repositorio siguiendo los siguientes pasos:

1. Respalda tu archivo .ipynb en una carpeta fuera de tu repositorio
2. Elimina tu repositorio completamente
3. Clona tu repositorio de nuevo con `git clone`
4. Abre el archivo .ipynb que está en el tu repositorio recién clonado y abre en otra ventana tu .ipynb que habías respaldado. Compáralos y mueve todo el código que corresponda hacia el .ipynb de tu repositorio. Guarda los cambios.
5. Sube los cambios al repositorio remoto.
