### ISSUE TITLE
Duda github

### ISSUE THREAD

**Issue by Afro27** [Exploratorio-DCC-PUC/Syllabus#92]
Subi el archivo de la tg2 al repositorio correspondientepero al tratar de visualizar el archivo ipynb directamente en github, no lo visualiza, hice algo mal al subirlo?

**Comment by IchottMano** [comment]
Hola!

Probablemente es por que el archivo es muy grande, personalmente he tenido problemas similares, si embargo mientras ustedes suban los notebooks con los gráficas no hay problema.

Saludos!

**Comment by Mdelaf** [comment]
Hola,

Antes de subir el notebook a tu repositorio debes eliminar el output de todas las celdas. No hacerlo tendrá descuento en tu nota.

Con respecto a la primera pregunta, si tu abres tu ipynb usando Jupyter o Colab desde tu computador y se visualiza sin problemas, entonces está todo bien. De todas formas, si eliminas el output de todas las celdas, Github debería mostrar un preview, es extraño que no lo haga.
