### ISSUE TITLE
Hora de Entrega [TG2]

### ISSUE THREAD

**Issue by francisca0308** [Exploratorio-DCC-PUC/Syllabus#93]
Hola! En el enunciado no sale a qué hora se entrega hoy día! Muchas gracias

**Comment by sebastianferrer** [comment]
Se entrega a las 20:00 de hoy

**Comment by Mdelaf** [comment]
Hola,

Efectivamente se dijo en un aviso que la entrega era a las 20:00, sin embargo, como no está explícito en el enunciado, decidimos permitir entregas hasta las 23:59.

Saludos.

**Comment by francisca0308** [comment]
Graciaas!!
