### ISSUE TITLE
Presicion score

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#94]
Un parametro que recibe presicion score es average. Y como se puede ver en la documentacion de presicion score:
average : string, [None, ‘binary’ (default), ‘micro’, ‘macro’, ‘samples’, ‘weighted’]
This parameter is required for multiclass/multilabel targets. If None, the scores for each class are returned. Otherwise, this determines the type of averaging performed on the data:

'binary':
Only report results for the class specified by pos_label. This is applicable only if targets (y_{true,pred}) are binary.

'micro':
Calculate metrics globally by counting the total true positives, false negatives and false positives.

'macro':
Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

'weighted':
Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label). This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.

'samples':
Calculate metrics for each instance, and find their average (only meaningful for multilabel classification where this differs from accuracy_score).

Este cambia su valor dependiendo el parametro que reciba. Use binary pero nose si esta bien?

**Comment by Mdelaf** [comment]
Ese parámetro se usa cuando quieres calcular el _precision_ de un dataset que tiene varias clases (más de dos). Como nuestro dataset tiene dos clases, entonces no debes modificarlo. Dejar el parámetro por defecto (i.e `binary`) es lo correcto.

Saludos.
