### ISSUE TITLE
Tarea chica 4 repo vacio?

### ISSUE THREAD

**Issue by naquiroz** [Exploratorio-DCC-PUC/Syllabus#95]
Hola, nose si hubo un error en la creación de mi repo para la tc4, pero está vacío, esta bien eso?

**Comment by diflores** [comment]
Hola,

Está bien. No hay archivos base para esta tarea.

¡Saludos!

**Comment by naquiroz** [comment]
Y el enunciado?

**Comment by diflores** [comment]
En el SIDING. Acabo de subir una copia al [Syllabus](https://github.com/Exploratorio-DCC-PUC/Syllabus/blob/master/Tareas/TC4/TC4.pdf).
