### ISSUE TITLE
Strings a int

### ISSUE THREAD

**Issue by vvelasco150** [Exploratorio-DCC-PUC/Syllabus#95]
Hola! al pasar los strings a int por medio de pandas (cat.code) si corro el código una vez asigna valores a partir desde el -1, pero si vuelvo a correr el codigo (desde la segunda vez ) le asigna valores a partir del cero.
Saben si hay alguna forma de especificar desde que valor quiero que parta?, de no ser asi existen problemas con que se asignen valores negativos?
Muchas gracias

**Comment by Mdelaf** [comment]
Hola,

Buscando información encontré [esto](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#missing-data).

Al parecer ese método de Pandas asigna valor -1 a los valores nulos. En la primera parte de la tarea ustedes deben manejar los valores nulos y dejar el dataset sin valores nulos. No hacerlo te traerá problemas de este tipo.

Saludos.
