### ISSUE TITLE
Commit de mi compañero

### ISSUE THREAD

**Issue by sebastianferrer** [Exploratorio-DCC-PUC/Syllabus#96]
Hola! A mi compañero se le olvidó unirse a mi repositorio y ahora no lo deja unirse, cómo puedo hacer para que se pueda meter y realizar commits?

**Comment by Mdelaf** [comment]
Hola Sebastián,

¿Cuál es el nombre de usuario de Github de tu compañero?

**Comment by sebaelsaca** [comment]
sebaelsaca

**Comment by Mdelaf** [comment]
Te debería haber llegado una invitación para unirte al grupo, ¿la recibiste? @sebaelsaca

**Comment by sebaelsaca** [comment]
Si, gracias! Te pasaste
