### ISSUE TITLE
Matrix de confusion ACLARACION 

### ISSUE THREAD

**Issue by perezpefaur** [Exploratorio-DCC-PUC/Syllabus#97]
![image](https://user-images.githubusercontent.com/48262438/66778197-6dc0ad80-eea1-11e9-998d-83c441250e6a.png)
![image](https://user-images.githubusercontent.com/48262438/66778219-79ac6f80-eea1-11e9-8c88-42f4d109439f.png)
En internet dice que las filas siempre son lo predicho, y las columnas son el actual. Pero esto difiere con la matrix de la ayudantia, entonces estoy confundido

**Comment by Mdelaf** [comment]
Hola,

La verdad es que puedes usar cualquiera de los dos formatos. **Lo importante es que esté correctamente señalado qué representa cada eje**. Al final es la misma información pero "dada vuelta".

Saludos.
