### ISSUE TITLE
Eliminar outputs del Jupyter Notebook

### ISSUE THREAD

**Issue by francisca0308** [Exploratorio-DCC-PUC/Syllabus#98]
Hola!
A qué se refiere esto? Que no tengo que correrlo?

**Comment by Mdelaf** [comment]
Cuando estas haciendo la tarea, obviamente debes correr las celdas de código para ver que todo funcione bien.

Lo que se pide en el enunciado es que antes de subirlo a Github, eliminen todo el output de las celdas. Después nosotros ejecutaremos sus notebooks celda por celda e iremos revisando sus resultados. Adjunto imagen para que veas cómo se hace:

![image](https://user-images.githubusercontent.com/11620077/66783548-7b306480-eeae-11e9-9cd4-547eebfbc0ca.png)

Saludos.
