### ISSUE TITLE
Formato de entrega Tarea Chica 4

### ISSUE THREAD

**Issue by tfflores** [Exploratorio-DCC-PUC/Syllabus#98]
Hola, respecto a esta tarea:
¿El archivo que se entrega es un .bpm que se pueda abrir con editores, o una captura .jpg/.png del diagrama BPMN?
¿Es necesario añadir algún tipo de explicación escrita (en readme por ejemplo) del diagrama o sólo basta con el diagrama en sí?

**Comment by Dalal15** [comment]
Se debe entregar un archivo .pdf de tu modelo, y además entregar el .bpm.

Respecto a la explicación, si te fijas en el enunciado en la sección **Consideraciones**  , se señala que los supuestos deben ser claramente mencionados y explicados, por lo que estos deben ir incluidos en tu readme.

**Comment by ncasassus** [comment]
En el README debe estar explicado el modelo o solo van los supuestos aplicados en la tarea?

**Comment by Dalal15** [comment]
Solo los supuestos.
