### ISSUE TITLE
Orden de procesos TC4

### ISSUE THREAD

**Issue by migil1005** [Exploratorio-DCC-PUC/Syllabus#99]
Hola no entiendo muy bien el orden de los procesos ya que en la etapa de análisis de riesgo e impacto termina con una aprobación o rechazo y no se si los cambios aprobados pasan a la siguiente etapa, o están en desorden las etapas?

**Comment by Dalal15** [comment]
Hola,

Primero que todo una aclaración conceptual:  en la tarea solo se modela **un** proceso, por lo que sería más correcto hablar de orden de actividades o de subprocesos, según como abordes tu tarea. (Utilizar subprocesos es opcional).

Respecto al orden, en el enunciado en la parte de **etapa de autorización**, el párrafo comienza diciendo: **A continuación**, según el tipo  de ... 

Entonces se desprende que es la continuación de la etapa anterior. 

Saludos!
