### ISSUE TITLE
Entrega tarea 2

### ISSUE THREAD

**Issue by raimundoburgos** [Exploratorio-DCC-PUC/Syllabus#99]
Hola, no será posible entregar la tarea a las 24 horas? Muchos tenemos interrogación ahora y en el caso de mi grupo nos falta un poco para terminar, y como no aparece en el enunciado la hora supusimos que era para las 24 horas

**Comment by Mdelaf** [comment]
Hola Raimundo,

Como ya mencionamos [en otra issue](https://github.com/Exploratorio-DCC-PUC/Syllabus/issues/93), se permitirá entregar la tarea hasta las 23:59.

Saludos.
